/**
 * Fotobibliotheek van de boerderij (Scaleway, map `bibliotheek/`).
 * Gegenereerd uit de opgeschoonde en uitgesneden foto's; per thema geordend.
 */
import type { Lang } from "@/lib/routes-i18n";
import { isLowQuality } from "@/lib/photo-focus";


export type LibPhoto = { src: string; alt: Record<Lang, string> };

export const MEDIA_BASE = "https://maximilien-media.s3.fr-par.scw.cloud";
const U = (p: string) => `${MEDIA_BASE}/bibliotheek/${p}`;
const P = (p: string, nl: string, fr: string, en: string): LibPhoto => ({ src: U(p), alt: { nl, fr, en } });

/** Alle foto's per map in de opslag. */
export const LIBRARY: Record<string, LibPhoto[]> = {
  "dieren/alpacas": [
    P("dieren/alpacas/alpacas-01.webp", "Alpaca kijkt nieuwsgierig in de lens", "Un alpaga regarde l'objectif avec curiosité", "An alpaca looks curiously into the lens"),
    P("dieren/alpacas/alpacas-02.webp", "Alpaca's in de weide van de boerderij", "Des alpagas dans le pré de la ferme", "Alpacas in the farm meadow"),
    P("dieren/alpacas/alpacas-03.webp", "Twee alpaca's naast elkaar", "Deux alpagas côte à côte", "Two alpacas side by side"),
    P("dieren/alpacas/alpacas-04.webp", "Alpaca rust in de schaduw", "Un alpaga se repose à l'ombre", "An alpaca resting in the shade"),
    P("dieren/alpacas/alpacas-05.webp", "Witte alpaca op het erf", "Un alpaga blanc dans la cour", "A white alpaca in the yard"),
    P("dieren/alpacas/alpacas-06.webp", "Alpaca graast in het gras", "Un alpaga broute dans l'herbe", "An alpaca grazing in the grass"),
    P("dieren/alpacas/alpacas-07.webp", "Alpaca's bij de omheining", "Des alpagas près de la clôture", "Alpacas by the fence"),
    P("dieren/alpacas/alpacas-08.webp", "Portret van een alpaca", "Portrait d'un alpaga", "Portrait of an alpaca"),
    P("dieren/alpacas/alpacas-09.webp", "Alpaca kijkt nieuwsgierig in de lens", "Un alpaga regarde l'objectif avec curiosité", "An alpaca looks curiously into the lens"),
    P("dieren/alpacas/alpacas-10.webp", "Alpaca's in de weide van de boerderij", "Des alpagas dans le pré de la ferme", "Alpacas in the farm meadow"),
    P("dieren/alpacas/alpacas-11.webp", "Twee alpaca's naast elkaar", "Deux alpagas côte à côte", "Two alpacas side by side"),
    P("dieren/alpacas/alpacas-12.webp", "Alpaca rust in de schaduw", "Un alpaga se repose à l'ombre", "An alpaca resting in the shade"),
    P("dieren/alpacas/alpacas-13.webp", "Witte alpaca op het erf", "Un alpaga blanc dans la cour", "A white alpaca in the yard"),
    P("dieren/alpacas/alpacas-14.webp", "Alpaca graast in het gras", "Un alpaga broute dans l'herbe", "An alpaca grazing in the grass"),
    P("dieren/alpacas/alpacas-15.webp", "Alpaca's bij de omheining", "Des alpagas près de la clôture", "Alpacas by the fence"),
    P("dieren/alpacas/alpacas-16.webp", "Portret van een alpaca", "Portrait d'un alpaga", "Portrait of an alpaca"),
    P("dieren/alpacas/alpacas-17.webp", "Alpaca kijkt nieuwsgierig in de lens", "Un alpaga regarde l'objectif avec curiosité", "An alpaca looks curiously into the lens"),
    P("dieren/alpacas/alpacas-18.webp", "Alpaca's in de weide van de boerderij", "Des alpagas dans le pré de la ferme", "Alpacas in the farm meadow"),
    P("dieren/alpacas/alpacas-19.webp", "Twee alpaca's naast elkaar", "Deux alpagas côte à côte", "Two alpacas side by side"),
    P("dieren/alpacas/alpacas-20.webp", "Alpaca rust in de schaduw", "Un alpaga se repose à l'ombre", "An alpaca resting in the shade"),
    P("dieren/alpacas/alpacas-21.webp", "Witte alpaca op het erf", "Un alpaga blanc dans la cour", "A white alpaca in the yard"),
    P("dieren/alpacas/alpacas-22.webp", "Alpaca graast in het gras", "Un alpaga broute dans l'herbe", "An alpaca grazing in the grass"),
    P("dieren/alpacas/alpacas-23.webp", "Alpaca's bij de omheining", "Des alpagas près de la clôture", "Alpacas by the fence"),
    P("dieren/alpacas/alpacas-24.webp", "Portret van een alpaca", "Portrait d'un alpaga", "Portrait of an alpaca"),
    P("dieren/alpacas/alpacas-25.webp", "Alpaca kijkt nieuwsgierig in de lens", "Un alpaga regarde l'objectif avec curiosité", "An alpaca looks curiously into the lens"),
    P("dieren/alpacas/alpacas-26.webp", "Alpaca's in de weide van de boerderij", "Des alpagas dans le pré de la ferme", "Alpacas in the farm meadow"),
    P("dieren/alpacas/alpacas-27.webp", "Twee alpaca's naast elkaar", "Deux alpagas côte à côte", "Two alpacas side by side"),
    P("dieren/alpacas/alpacas-28.webp", "Alpaca rust in de schaduw", "Un alpaga se repose à l'ombre", "An alpaca resting in the shade"),
    P("dieren/alpacas/alpacas-29.webp", "Witte alpaca op het erf", "Un alpaga blanc dans la cour", "A white alpaca in the yard"),
    P("dieren/alpacas/alpacas-30.webp", "Alpaca graast in het gras", "Un alpaga broute dans l'herbe", "An alpaca grazing in the grass"),
    P("dieren/alpacas/alpacas-31.webp", "Alpaca's bij de omheining", "Des alpagas près de la clôture", "Alpacas by the fence"),
  ],
  "dieren/geiten": [
    P("dieren/geiten/geiten-01.webp", "Geit kijkt over het hek", "Une chèvre regarde par-dessus la barrière", "A goat looking over the gate"),
    P("dieren/geiten/geiten-02.webp", "De geiten bij hun schuilhok", "Les chèvres près de leur abri", "The goats by their shelter"),
    P("dieren/geiten/geiten-03.webp", "Bonte geit in de weide", "Chèvre tachetée au pré", "Spotted goat in the meadow"),
    P("dieren/geiten/geiten-04.webp", "Zwarte geit met grote horens", "Chèvre noire aux grandes cornes", "Black goat with big horns"),
    P("dieren/geiten/geiten-05.webp", "Geiten in het gras", "Des chèvres dans l'herbe", "Goats in the grass"),
    P("dieren/geiten/geiten-06.webp", "Jonge geitjes spelen", "De jeunes chevreaux jouent", "Young goats playing"),
    P("dieren/geiten/geiten-07.webp", "Geit tussen de bloemen", "Chèvre parmi les fleurs", "Goat among the flowers"),
    P("dieren/geiten/geiten-08.webp", "Geit kijkt over het hek", "Une chèvre regarde par-dessus la barrière", "A goat looking over the gate"),
    P("dieren/geiten/geiten-09.webp", "De geiten bij hun schuilhok", "Les chèvres près de leur abri", "The goats by their shelter"),
    P("dieren/geiten/geiten-10.webp", "Bonte geit in de weide", "Chèvre tachetée au pré", "Spotted goat in the meadow"),
    P("dieren/geiten/geiten-11.webp", "Zwarte geit met grote horens", "Chèvre noire aux grandes cornes", "Black goat with big horns"),
    P("dieren/geiten/geiten-12.webp", "Geiten in het gras", "Des chèvres dans l'herbe", "Goats in the grass"),
    P("dieren/geiten/geiten-13.webp", "Jonge geitjes spelen", "De jeunes chevreaux jouent", "Young goats playing"),
    P("dieren/geiten/geiten-14.webp", "Geit tussen de bloemen", "Chèvre parmi les fleurs", "Goat among the flowers"),
    P("dieren/geiten/geiten-15.webp", "Geit kijkt over het hek", "Une chèvre regarde par-dessus la barrière", "A goat looking over the gate"),
  ],
  "dieren/schapen": [
    P("dieren/schapen/schapen-01.webp", "Schaap graast in de weide", "Un mouton broute au pré", "A sheep grazing in the meadow"),
    P("dieren/schapen/schapen-02.webp", "De schaapskudde bij elkaar", "Le troupeau de moutons rassemblé", "The flock of sheep together"),
    P("dieren/schapen/schapen-03.webp", "Schapen rusten in het gras", "Des moutons se reposent dans l'herbe", "Sheep resting in the grass"),
    P("dieren/schapen/schapen-04.webp", "Schapen in het avondlicht", "Des moutons dans la lumière du soir", "Sheep in the evening light"),
    P("dieren/schapen/schapen-05.webp", "Wollig schaap van dichtbij", "Mouton laineux de près", "Woolly sheep up close"),
    P("dieren/schapen/schapen-06.webp", "Schapen in de grote weide", "Des moutons dans le grand pré", "Sheep in the large meadow"),
    P("dieren/schapen/schapen-07.webp", "Schaap graast in de weide", "Un mouton broute au pré", "A sheep grazing in the meadow"),
    P("dieren/schapen/schapen-08.webp", "De schaapskudde bij elkaar", "Le troupeau de moutons rassemblé", "The flock of sheep together"),
    P("dieren/schapen/schapen-09.webp", "Schapen rusten in het gras", "Des moutons se reposent dans l'herbe", "Sheep resting in the grass"),
    P("dieren/schapen/schapen-10.webp", "Schapen in het avondlicht", "Des moutons dans la lumière du soir", "Sheep in the evening light"),
    P("dieren/schapen/schapen-11.webp", "Wollig schaap van dichtbij", "Mouton laineux de près", "Woolly sheep up close"),
    P("dieren/schapen/schapen-12.webp", "Schapen in de grote weide", "Des moutons dans le grand pré", "Sheep in the large meadow"),
    P("dieren/schapen/schapen-13.webp", "Schaap graast in de weide", "Un mouton broute au pré", "A sheep grazing in the meadow"),
  ],
  "dieren/ezels": [
    P("dieren/ezels/ezels-01.webp", "Onze ezel op het erf", "Notre âne dans la cour", "Our donkey in the yard"),
    P("dieren/ezels/ezels-02.webp", "Ezel met grote oren van dichtbij", "Un âne aux grandes oreilles, de près", "A long-eared donkey up close"),
    P("dieren/ezels/ezels-03.webp", "De verzorger bij de ezels", "Le soigneur avec les ânes", "The keeper with the donkeys"),
    P("dieren/ezels/ezels-04.webp", "Ezel kijkt over de staldeur", "Un âne regarde par-dessus la porte de l'étable", "A donkey looking over the stable door"),
  ],
  "dieren/ponys": [
    P("dieren/ponys/ponys-01.webp", "De pony onder de grote boom", "Le poney sous le grand arbre", "The pony under the big tree"),
    P("dieren/ponys/ponys-02.webp", "Pony's op het erf", "Des poneys dans la cour", "Ponies in the yard"),
    P("dieren/ponys/ponys-03.webp", "Pony tussen de herfstbladeren", "Un poney parmi les feuilles d'automne", "A pony among autumn leaves"),
    P("dieren/ponys/ponys-04.webp", "Bruine pony in de zon", "Un poney brun au soleil", "A brown pony in the sun"),
    P("dieren/ponys/ponys-05.webp", "Pony graast rustig", "Un poney broute tranquillement", "A pony grazing quietly"),
    P("dieren/ponys/ponys-06.webp", "De pony onder de grote boom", "Le poney sous le grand arbre", "The pony under the big tree"),
    P("dieren/ponys/ponys-07.webp", "Pony's op het erf", "Des poneys dans la cour", "Ponies in the yard"),
    P("dieren/ponys/ponys-08.webp", "Pony tussen de herfstbladeren", "Un poney parmi les feuilles d'automne", "A pony among autumn leaves"),
    P("dieren/ponys/ponys-09.webp", "Bruine pony in de zon", "Un poney brun au soleil", "A brown pony in the sun"),
  ],
  "dieren/pauwen": [
    P("dieren/pauwen/pauwen-01.webp", "Pauw die pronkt met zijn staart", "Un paon fait la roue", "A peacock displaying its tail"),
    P("dieren/pauwen/pauwen-02.webp", "Pauw op het erf", "Un paon dans la cour", "A peacock in the yard"),
    P("dieren/pauwen/pauwen-03.webp", "Blauwe pauw van dichtbij", "Un paon bleu de près", "A blue peacock up close"),
    P("dieren/pauwen/pauwen-04.webp", "Pauw wandelt over het pad", "Un paon marche sur le chemin", "A peacock walking on the path"),
    P("dieren/pauwen/pauwen-05.webp", "Pauw op het dak van het hok", "Un paon sur le toit de l'abri", "A peacock on the shelter roof"),
    P("dieren/pauwen/pauwen-06.webp", "Pauw die pronkt met zijn staart", "Un paon fait la roue", "A peacock displaying its tail"),
    P("dieren/pauwen/pauwen-07.webp", "Pauw op het erf", "Un paon dans la cour", "A peacock in the yard"),
    P("dieren/pauwen/pauwen-08.webp", "Blauwe pauw van dichtbij", "Un paon bleu de près", "A blue peacock up close"),
    P("dieren/pauwen/pauwen-09.webp", "Pauw wandelt over het pad", "Un paon marche sur le chemin", "A peacock walking on the path"),
    P("dieren/pauwen/pauwen-10.webp", "Pauw op het dak van het hok", "Un paon sur le toit de l'abri", "A peacock on the shelter roof"),
  ],
  "dieren/kippen": [
    P("dieren/kippen/kippen-01.webp", "Kippen scharrelen in de ren", "Les poules grattent dans l'enclos", "Chickens scratching in the run"),
    P("dieren/kippen/kippen-02.webp", "Haan met rode kam", "Un coq à la crête rouge", "A rooster with a red comb"),
    P("dieren/kippen/kippen-03.webp", "Witte kip tussen het groen", "Une poule blanche dans la verdure", "A white hen in the greenery"),
    P("dieren/kippen/kippen-04.webp", "Parelhoenders in het gras", "Des pintades dans l'herbe", "Guinea fowl in the grass"),
    P("dieren/kippen/kippen-05.webp", "Kippen bij het kippenhok", "Des poules près du poulailler", "Hens by the henhouse"),
    P("dieren/kippen/kippen-06.webp", "Kippen scharrelen in de ren", "Les poules grattent dans l'enclos", "Chickens scratching in the run"),
  ],
  "dieren/eenden-ganzen": [
    P("dieren/eenden-ganzen/eenden-ganzen-01.webp", "Ganzen op het erf", "Des oies dans la cour", "Geese in the yard"),
    P("dieren/eenden-ganzen/eenden-ganzen-02.webp", "Eend op de vijver", "Un canard sur la mare", "A duck on the pond"),
    P("dieren/eenden-ganzen/eenden-ganzen-03.webp", "Witte gans rust in het gras", "Une oie blanche se repose dans l'herbe", "A white goose resting in the grass"),
    P("dieren/eenden-ganzen/eenden-ganzen-04.webp", "Veren van dichtbij", "Plumes en gros plan", "Feathers up close"),
    P("dieren/eenden-ganzen/eenden-ganzen-05.webp", "Watervogels bij het water", "Oiseaux d'eau au bord de l'eau", "Waterfowl by the water"),
    P("dieren/eenden-ganzen/eenden-ganzen-06.webp", "Ganzen op het erf", "Des oies dans la cour", "Geese in the yard"),
  ],
  "dieren/konijnen": [
    P("dieren/konijnen/konijnen-01.webp", "Konijn knabbelt aan een blad", "Un lapin grignote une feuille", "A rabbit nibbling a leaf"),
    P("dieren/konijnen/konijnen-02.webp", "Konijn in de ren", "Un lapin dans l'enclos", "A rabbit in the run"),
    P("dieren/konijnen/konijnen-03.webp", "Konijnen tussen de herfstbladeren", "Des lapins parmi les feuilles d'automne", "Rabbits among autumn leaves"),
  ],
  "dieren/knaagdieren": [
    P("dieren/knaagdieren/knaagdieren-01.webp", "Cavia's in hun buitenverblijf", "Des cochons d'Inde dans leur enclos", "Guinea pigs in their outdoor pen"),
    P("dieren/knaagdieren/knaagdieren-02.webp", "Cavia's in het hok", "Des cochons d'Inde dans la cage", "Guinea pigs in the hutch"),
  ],
  "tuin/moestuin": [
    P("tuin/moestuin/moestuin-01.webp", "De moestuinbakken in de zomer", "Les bacs du potager en été", "The vegetable beds in summer"),
    P("tuin/moestuin/moestuin-02.webp", "Groenten groeien in de moestuin", "Des légumes poussent au potager", "Vegetables growing in the kitchen garden"),
    P("tuin/moestuin/moestuin-03.webp", "Zonnebloemen boven de moestuin", "Des tournesols au-dessus du potager", "Sunflowers above the garden"),
    P("tuin/moestuin/moestuin-04.webp", "Bloemenborder bij de moestuin", "Massif de fleurs près du potager", "Flower border by the garden"),
    P("tuin/moestuin/moestuin-05.webp", "Werken tussen de plantenbakken", "Travail entre les bacs de culture", "Working between the planting beds"),
    P("tuin/moestuin/moestuin-06.webp", "De tuin in volle groei", "Le jardin en pleine croissance", "The garden in full growth"),
    P("tuin/moestuin/moestuin-07.webp", "De moestuinbakken in de zomer", "Les bacs du potager en été", "The vegetable beds in summer"),
    P("tuin/moestuin/moestuin-08.webp", "Groenten groeien in de moestuin", "Des légumes poussent au potager", "Vegetables growing in the kitchen garden"),
    P("tuin/moestuin/moestuin-09.webp", "Zonnebloemen boven de moestuin", "Des tournesols au-dessus du potager", "Sunflowers above the garden"),
    P("tuin/moestuin/moestuin-10.webp", "Bloemenborder bij de moestuin", "Massif de fleurs près du potager", "Flower border by the garden"),
  ],
  "tuin/boomgaard": [
    P("tuin/boomgaard/boomgaard-01.webp", "Rijpende peren in de boomgaard", "Poires mûrissantes au verger", "Ripening pears in the orchard"),
    P("tuin/boomgaard/boomgaard-02.webp", "Fruit aan de tak", "Des fruits sur la branche", "Fruit on the branch"),
    P("tuin/boomgaard/boomgaard-03.webp", "De boomgaard in de zomer", "Le verger en été", "The orchard in summer"),
  ],
  "natuur/vijver": [
    P("natuur/vijver/vijver-01.webp", "De vijver met waterplanten", "La mare et ses plantes aquatiques", "The pond with water plants"),
    P("natuur/vijver/vijver-02.webp", "Rustig water tussen het groen", "Eau calme entre la verdure", "Still water among the greenery"),
    P("natuur/vijver/vijver-03.webp", "Vlonderpad langs het water", "Passerelle en bois le long de l'eau", "Boardwalk along the water"),
    P("natuur/vijver/vijver-04.webp", "De vijver in de herfst", "La mare en automne", "The pond in autumn"),
    P("natuur/vijver/vijver-05.webp", "Natuurzone bij het water", "Zone naturelle au bord de l'eau", "Nature area by the water"),
    P("natuur/vijver/vijver-06.webp", "De vijver met waterplanten", "La mare et ses plantes aquatiques", "The pond with water plants"),
    P("natuur/vijver/vijver-07.webp", "Rustig water tussen het groen", "Eau calme entre la verdure", "Still water among the greenery"),
    P("natuur/vijver/vijver-08.webp", "Vlonderpad langs het water", "Passerelle en bois le long de l'eau", "Boardwalk along the water"),
    P("natuur/vijver/vijver-09.webp", "De vijver in de herfst", "La mare en automne", "The pond in autumn"),
  ],
  "natuur/paden": [
    P("natuur/paden/paden-01.webp", "Het wandelpad door het groen", "Le sentier à travers la verdure", "The path through the greenery"),
    P("natuur/paden/paden-02.webp", "Schaduwrijk pad langs de weide", "Chemin ombragé le long du pré", "Shady path along the meadow"),
    P("natuur/paden/paden-03.webp", "Kasseipad op het domein", "Chemin pavé du domaine", "Cobbled path on the grounds"),
    P("natuur/paden/paden-04.webp", "Groene doorkijk op de boerderij", "Perspective verte sur la ferme", "Green view across the farm"),
    P("natuur/paden/paden-05.webp", "Bomen en struiken langs het pad", "Arbres et buissons le long du chemin", "Trees and shrubs along the path"),
    P("natuur/paden/paden-06.webp", "Het wandelpad door het groen", "Le sentier à travers la verdure", "The path through the greenery"),
    P("natuur/paden/paden-07.webp", "Schaduwrijk pad langs de weide", "Chemin ombragé le long du pré", "Shady path along the meadow"),
    P("natuur/paden/paden-08.webp", "Kasseipad op het domein", "Chemin pavé du domaine", "Cobbled path on the grounds"),
    P("natuur/paden/paden-09.webp", "Groene doorkijk op de boerderij", "Perspective verte sur la ferme", "Green view across the farm"),
    P("natuur/paden/paden-10.webp", "Bomen en struiken langs het pad", "Arbres et buissons le long du chemin", "Trees and shrubs along the path"),
    P("natuur/paden/paden-11.webp", "Het wandelpad door het groen", "Le sentier à travers la verdure", "The path through the greenery"),
    P("natuur/paden/paden-12.webp", "Schaduwrijk pad langs de weide", "Chemin ombragé le long du pré", "Shady path along the meadow"),
  ],
  "erf/gebouwen": [
    P("erf/gebouwen/gebouwen-01.webp", "De hoevegebouwen op het erf", "Les bâtiments de la ferme", "The farm buildings in the yard"),
    P("erf/gebouwen/gebouwen-02.webp", "Het erf met de stallen", "La cour et les étables", "The yard with the stables"),
    P("erf/gebouwen/gebouwen-03.webp", "Bakstenen hoeve met zonnepanelen", "Ferme en briques avec panneaux solaires", "Brick farmhouse with solar panels"),
    P("erf/gebouwen/gebouwen-04.webp", "De ingang van de boerderij", "L'entrée de la ferme", "The farm entrance"),
    P("erf/gebouwen/gebouwen-05.webp", "Schuilhokken langs de weide", "Abris le long du pré", "Shelters along the meadow"),
    P("erf/gebouwen/gebouwen-06.webp", "Serre en tuinhuis", "Serre et cabane de jardin", "Greenhouse and garden shed"),
    P("erf/gebouwen/gebouwen-07.webp", "De hoevegebouwen op het erf", "Les bâtiments de la ferme", "The farm buildings in the yard"),
    P("erf/gebouwen/gebouwen-08.webp", "Het erf met de stallen", "La cour et les étables", "The yard with the stables"),
    P("erf/gebouwen/gebouwen-09.webp", "Bakstenen hoeve met zonnepanelen", "Ferme en briques avec panneaux solaires", "Brick farmhouse with solar panels"),
    P("erf/gebouwen/gebouwen-10.webp", "De ingang van de boerderij", "L'entrée de la ferme", "The farm entrance"),
    P("erf/gebouwen/gebouwen-11.webp", "Schuilhokken langs de weide", "Abris le long du pré", "Shelters along the meadow"),
    P("erf/gebouwen/gebouwen-12.webp", "Serre en tuinhuis", "Serre et cabane de jardin", "Greenhouse and garden shed"),
    P("erf/gebouwen/gebouwen-13.webp", "De hoevegebouwen op het erf", "Les bâtiments de la ferme", "The farm buildings in the yard"),
  ],
  "erf/trojaans-paard": [
    P("erf/trojaans-paard/trojaans-paard-01.webp", "Het houten paard op het erf", "Le cheval en bois dans la cour", "The wooden horse in the yard"),
    P("erf/trojaans-paard/trojaans-paard-02.webp", "Het grote houten paard tegen de blauwe lucht", "Le grand cheval en bois sous le ciel bleu", "The big wooden horse against a blue sky"),
    P("erf/trojaans-paard/trojaans-paard-03.webp", "Het houten paard tussen de weiden", "Le cheval en bois entre les prés", "The wooden horse between the meadows"),
    P("erf/trojaans-paard/trojaans-paard-04.webp", "Blikvanger van de boerderij", "L'emblème de la ferme", "The farm's landmark"),
    P("erf/trojaans-paard/trojaans-paard-05.webp", "Het houten paard op het erf", "Le cheval en bois dans la cour", "The wooden horse in the yard"),
    P("erf/trojaans-paard/trojaans-paard-06.webp", "Het grote houten paard tegen de blauwe lucht", "Le grand cheval en bois sous le ciel bleu", "The big wooden horse against a blue sky"),
    P("erf/trojaans-paard/trojaans-paard-07.webp", "Het houten paard tussen de weiden", "Le cheval en bois entre les prés", "The wooden horse between the meadows"),
    P("erf/trojaans-paard/trojaans-paard-08.webp", "Blikvanger van de boerderij", "L'emblème de la ferme", "The farm's landmark"),
  ],
  "bezoek/kinderen": [
    P("bezoek/kinderen/kinderen-01.webp", "Kinderen ontdekken de dieren", "Des enfants découvrent les animaux", "Children discovering the animals"),
    P("bezoek/kinderen/kinderen-02.webp", "Bezoekers bij de weide", "Des visiteurs au bord du pré", "Visitors by the meadow"),
    P("bezoek/kinderen/kinderen-03.webp", "Een kind aait een dier", "Un enfant caresse un animal", "A child petting an animal"),
    P("bezoek/kinderen/kinderen-04.webp", "Samen op stap over de boerderij", "En balade ensemble à la ferme", "Exploring the farm together"),
    P("bezoek/kinderen/kinderen-05.webp", "Kinderen bij de gele koe", "Des enfants près de la vache jaune", "Children by the yellow cow"),
    P("bezoek/kinderen/kinderen-06.webp", "Kinderen ontdekken de dieren", "Des enfants découvrent les animaux", "Children discovering the animals"),
    P("bezoek/kinderen/kinderen-07.webp", "Bezoekers bij de weide", "Des visiteurs au bord du pré", "Visitors by the meadow"),
    P("bezoek/kinderen/kinderen-08.webp", "Een kind aait een dier", "Un enfant caresse un animal", "A child petting an animal"),
  ],
  "bezoek/speeltuin": [
    P("bezoek/speeltuin/speeltuin-01.webp", "De speelzone met zandbak", "L'aire de jeux avec bac à sable", "The play area with sandpit"),
    P("bezoek/speeltuin/speeltuin-02.webp", "Spelen op het erf", "Jouer dans la cour", "Playing in the yard"),
  ],
  "educatie/borden-en-workshops": [
    P("educatie/borden-en-workshops/borden-en-workshops-01.webp", "Educatief bord over de boerderij", "Panneau pédagogique de la ferme", "Educational sign about the farm"),
    P("educatie/borden-en-workshops/borden-en-workshops-02.webp", "Het bijenhotel met uitleg", "L'hôtel à insectes et ses explications", "The bee hotel with explanations"),
    P("educatie/borden-en-workshops/borden-en-workshops-03.webp", "Workshop aan de grote tafel", "Atelier à la grande table", "Workshop at the big table"),
    P("educatie/borden-en-workshops/borden-en-workshops-04.webp", "Samen leren op de boerderij", "Apprendre ensemble à la ferme", "Learning together at the farm"),
    P("educatie/borden-en-workshops/borden-en-workshops-05.webp", "Infobord aan de ingang", "Panneau d'information à l'entrée", "Information board at the entrance"),
    P("educatie/borden-en-workshops/borden-en-workshops-06.webp", "Educatief bord over de boerderij", "Panneau pédagogique de la ferme", "Educational sign about the farm"),
    P("educatie/borden-en-workshops/borden-en-workshops-07.webp", "Het bijenhotel met uitleg", "L'hôtel à insectes et ses explications", "The bee hotel with explanations"),
  ],
};

export function lib(folder: string): LibPhoto[] {
  // Te kleine of slecht belichte foto's laten we niet zien.
  return (LIBRARY[folder] ?? []).filter((p) => !isLowQuality(p.src));
}

