import type { Booking, LocationInfo, Service, StaffMember } from "./portal-types";

export const iso = (d: Date) => d.toISOString().slice(0, 10);

export const shift = (days: number) => {
  const d = new Date();
  d.setHours(12, 0, 0, 0);
  d.setDate(d.getDate() + days);
  return iso(d);
};

export const LOCATIONS: LocationInfo[] = [
  { id: "chalet", name: "Chalet", capacity: 40, base_price: 150, color: "chalet" },
  { id: "zaal", name: "Zaal", capacity: 80, base_price: 260, color: "zaal" },
  { id: "prairie", name: "Prairie", capacity: 150, base_price: 200, color: "prairie" },
  {
    id: "boerderij",
    name: "Volledige boerderij",
    capacity: 250,
    base_price: 950,
    color: "boerderij",
  },
];

export const locationName = (id: string) => LOCATIONS.find((l) => l.id === id)?.name ?? id;

let seq = 100;
const id = () => `BK-${++seq}`;

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: id(),
    type: "teambuilding",
    status: "gereserveerd",
    client_name: "Sofie Vermeulen",
    client_org: "Brussels Health Lab",
    client_email: "sofie@bhl.be",
    client_phone: "+32 478 22 11 09",
    date: shift(0),
    start_time: "09:30",
    end_time: "16:00",
    location_id: "prairie",
    guests_count: 24,
    options: ["Lunch boerderij", "Begeleide moestuinworkshop"],
    internal_notes: ["Catering komt om 11:30", "Extra tafels klaarzetten"],
    price: 1180,
    day_status: "verwacht",
    created_at: shift(-21),
  },
  {
    id: id(),
    type: "zaalverhuur",
    status: "gereserveerd",
    client_name: "Karim Belhaj",
    client_org: "Buurtcomité Laken",
    client_email: "karim.belhaj@laken.brussels",
    client_phone: "+32 495 61 40 77",
    date: shift(0),
    start_time: "18:00",
    end_time: "22:30",
    location_id: "zaal",
    guests_count: 55,
    options: ["Geluidsinstallatie"],
    internal_notes: ["Sleutel afhalen aan het onthaal", "Zaal om 17:00 vrij maken"],
    price: 420,
    day_status: "verwacht",
    created_at: shift(-12),
  },
  {
    id: id(),
    type: "zaalverhuur",
    status: "gereserveerd",
    client_name: "Émilie Dubois",
    client_org: "Atelier Céramique",
    client_email: "emilie@atelierceramique.be",
    client_phone: "+32 470 88 12 30",
    date: shift(0),
    start_time: "13:00",
    end_time: "17:00",
    location_id: "chalet",
    guests_count: 12,
    options: ["Koffiepauze"],
    internal_notes: ["Klant brengt eigen materiaal mee"],
    price: 180,
    day_status: "aangekomen",
    created_at: shift(-30),
  },
  {
    id: id(),
    type: "privatisering",
    status: "offerte_verzonden",
    client_name: "Nathalie Peeters",
    client_org: "Fondation Verte",
    client_email: "n.peeters@fondationverte.org",
    client_phone: "+32 486 33 90 12",
    date: shift(9),
    start_time: "10:00",
    end_time: "23:00",
    location_id: "boerderij",
    guests_count: 180,
    options: ["Volledige privatisering", "Foodtrucks", "Avondverlichting"],
    internal_notes: ["Offerte v2 verzonden op vraag van klant"],
    price: 4200,
    day_status: "verwacht",
    created_at: shift(-6),
  },
  {
    id: id(),
    type: "teambuilding",
    status: "nieuw",
    client_name: "Tom Claes",
    client_org: "Nordic Software",
    client_email: "tom.claes@nordicsw.eu",
    client_phone: "+32 472 10 55 41",
    date: shift(24),
    start_time: "09:00",
    end_time: "17:00",
    location_id: "prairie",
    guests_count: 35,
    options: ["Teambuilding à la ferme", "BBQ"],
    internal_notes: [],
    price: 1750,
    day_status: "verwacht",
    created_at: shift(-1),
  },
  {
    id: id(),
    type: "zaalverhuur",
    status: "nieuw",
    client_name: "Fatima Ouahbi",
    client_email: "fatima.ouahbi@gmail.com",
    client_phone: "+32 493 77 21 08",
    date: shift(17),
    start_time: "14:00",
    end_time: "19:00",
    location_id: "zaal",
    guests_count: 60,
    options: ["Verjaardagsfeest"],
    internal_notes: [],
    price: 380,
    day_status: "verwacht",
    created_at: shift(0),
  },
  {
    id: id(),
    type: "teambuilding",
    status: "in_behandeling",
    client_name: "Pierre Lemaire",
    client_org: "Cabinet Lemaire",
    client_email: "p.lemaire@cablem.be",
    client_phone: "+32 477 45 62 19",
    date: shift(12),
    start_time: "13:30",
    end_time: "18:00",
    location_id: "chalet",
    guests_count: 18,
    options: ["Workshop kaasmaken"],
    internal_notes: ["Wacht op bevestiging aantal deelnemers"],
    price: 890,
    day_status: "verwacht",
    created_at: shift(-3),
  },
  {
    id: id(),
    type: "privatisering",
    status: "afgerond",
    client_name: "Lucas Martin",
    client_org: "Coop Bruxelles",
    client_email: "lucas@coopbxl.be",
    client_phone: "+32 484 12 76 03",
    date: shift(-14),
    start_time: "11:00",
    end_time: "20:00",
    location_id: "boerderij",
    guests_count: 120,
    options: ["Privatisering namiddag"],
    internal_notes: ["Alles vlot verlopen, factuur betaald"],
    price: 3100,
    day_status: "aangekomen",
    created_at: shift(-60),
  },
  {
    id: id(),
    type: "zaalverhuur",
    status: "geannuleerd",
    client_name: "Anouk De Wit",
    client_email: "anouk.dewit@outlook.com",
    client_phone: "+32 468 90 34 55",
    date: shift(-4),
    start_time: "15:00",
    end_time: "20:00",
    location_id: "zaal",
    guests_count: 40,
    options: [],
    internal_notes: ["Geannuleerd door klant, geen voorschot betaald"],
    price: 0,
    day_status: "verwacht",
    created_at: shift(-25),
  },
  {
    id: id(),
    type: "geblokkeerd",
    status: "gereserveerd",
    client_name: "Onderhoud terrein",
    client_email: "-",
    client_phone: "-",
    date: shift(5),
    start_time: "08:00",
    end_time: "18:00",
    location_id: "prairie",
    guests_count: 0,
    options: [],
    internal_notes: ["Maaiwerken en herstel omheining"],
    price: 0,
    day_status: "verwacht",
    created_at: shift(-2),
  },
  {
    id: id(),
    type: "teambuilding",
    status: "gereserveerd",
    client_name: "Ines Rossi",
    client_org: "Studio Nord",
    client_email: "ines@studionord.be",
    client_phone: "+32 471 09 88 24",
    date: shift(2),
    start_time: "09:00",
    end_time: "15:30",
    location_id: "chalet",
    guests_count: 16,
    options: ["Lunch boerderij"],
    internal_notes: ["Vegetarische lunch voor 6 personen"],
    price: 760,
    day_status: "verwacht",
    created_at: shift(-8),
  },
];

export const INITIAL_SERVICES: Service[] = [
  {
    id: "svc-1",
    title_fr: "Chalet — Demi-journée",
    title_nl: "Chalet — Halve dag",
    title_en: "Chalet — Half day",
    desc_fr: "Location du chalet pour 4 heures, jusqu'à 40 personnes.",
    desc_nl: "Verhuur van het chalet voor 4 uur, tot 40 personen.",
    desc_en: "Chalet rental for 4 hours, up to 40 people.",
    price: 150,
    location_id: "chalet",
    active: true,
  },
  {
    id: "svc-2",
    title_fr: "Chalet — Journée complète",
    title_nl: "Chalet — Volledige dag",
    title_en: "Chalet — Full day",
    desc_fr: "Location du chalet de 9h à 22h.",
    desc_nl: "Verhuur van het chalet van 9u tot 22u.",
    desc_en: "Chalet rental from 9am to 10pm.",
    price: 260,
    location_id: "chalet",
    active: true,
  },
  {
    id: "svc-3",
    title_fr: "Teambuilding à la ferme",
    title_nl: "Teambuilding op de boerderij",
    title_en: "Teambuilding at the farm",
    desc_fr: "Programme d'une journée avec ateliers potager et animaux.",
    desc_nl: "Dagprogramma met moestuin- en dierenworkshops.",
    desc_en: "Full-day programme with vegetable garden and animal workshops.",
    price: 48,
    location_id: "prairie",
    active: true,
  },
  {
    id: "svc-4",
    title_fr: "Location de salle — Soirée",
    title_nl: "Zaalverhuur — Avond",
    title_en: "Hall rental — Evening",
    desc_fr: "Salle polyvalente de 18h à 23h, 80 personnes.",
    desc_nl: "Polyvalente zaal van 18u tot 23u, 80 personen.",
    desc_en: "Multipurpose hall from 6pm to 11pm, 80 people.",
    price: 420,
    location_id: "zaal",
    active: true,
  },
  {
    id: "svc-5",
    title_fr: "Privatisation complète",
    title_nl: "Volledige privatisering",
    title_en: "Full privatisation",
    desc_fr: "Toute la ferme réservée pour votre événement.",
    desc_nl: "De volledige boerderij gereserveerd voor uw evenement.",
    desc_en: "The entire farm reserved for your event.",
    price: 2400,
    location_id: "boerderij",
    active: true,
  },
  {
    id: "svc-6",
    title_fr: "Atelier fromage",
    title_nl: "Workshop kaasmaken",
    title_en: "Cheese-making workshop",
    desc_fr: "Atelier de 2h avec dégustation.",
    desc_nl: "Workshop van 2u met degustatie.",
    desc_en: "Two-hour workshop including tasting.",
    price: 32,
    location_id: "chalet",
    active: false,
  },
];

export const INITIAL_STAFF: StaffMember[] = [
  {
    id: "u-1",
    name: "Marie Dubois",
    email: "marie@fermeduparc.be",
    role: "admin",
    active: true,
  },
  {
    id: "u-2",
    name: "Youssef Amrani",
    email: "youssef@fermeduparc.be",
    role: "team",
    active: true,
  },
  { id: "u-3", name: "Lotte Janssens", email: "lotte@fermeduparc.be", role: "team", active: true },
  { id: "u-4", name: "Bram Wouters", email: "bram@fermeduparc.be", role: "team", active: false },
];
