-- Basismigratie: volledige structuur van de kern-tabellen, idempotent.
-- Draait vóór alle andere migraties (bestandsnaam sorteert eerst) zodat een
-- lege Neon-databank van nul opgebouwd kan worden.

-- ---------- Enums ----------
do $$
begin
  if not exists (select 1 from pg_type where typname = 'booking_type') then
    create type public.booking_type as enum ('zaalverhuur', 'workshop', 'schoolbezoek', 'evenement', 'teambuilding', 'kamp');
  end if;
  if not exists (select 1 from pg_type where typname = 'booking_status') then
    create type public.booking_status as enum ('nieuw', 'bevestigd', 'geannuleerd', 'afgerond');
  end if;
  if not exists (select 1 from pg_type where typname = 'day_status') then
    create type public.day_status as enum ('verwacht', 'aanwezig', 'afwezig');
  end if;
end $$;

-- ---------- Basisreferenties ----------
create table if not exists public.organisations (
  id serial primary key,
  name text not null,
  slug text unique,
  created_at timestamptz not null default now()
);

create table if not exists public.locations (
  id text primary key,
  name text not null default '',
  created_at timestamptz not null default now()
);

-- Oudere databanken hebben `name` zonder default: vul altijd een naam in.
alter table public.locations add column if not exists name text not null default '';

insert into public.locations (id, name)
values ('chalet', 'Chalet'), ('zaal', 'Zaal'), ('prairie', 'Prairie'), ('boerderij', 'Boerderij')
on conflict (id) do nothing;


-- ---------- Site-instellingen ----------
create table if not exists public.site_settings (
  key text primary key,
  value_nl text not null default '',
  value_fr text not null default '',
  value jsonb not null default '{}'::jsonb,
  updated_by text,
  updated_at timestamptz not null default now()
);

-- ---------- Diensten (prijzen & locaties) ----------
create table if not exists public.services (
  id uuid primary key default gen_random_uuid(),
  title_nl text not null,
  title_fr text not null,
  title_en text not null,
  desc_nl text not null default '',
  desc_fr text not null default '',
  desc_en text not null default '',
  price numeric(10, 2) not null default 0,
  location_id text not null references public.locations (id),
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  constraint services_location_check check (location_id in ('chalet', 'zaal', 'prairie', 'boerderij'))
);

create index if not exists services_active_idx on public.services (active, sort_order);

-- ---------- Webshop: producten ----------
create table if not exists public.products (
  id serial primary key,
  organisation_id integer not null references public.organisations (id) on delete cascade,
  title varchar(255) not null,
  description text,
  image_url varchar(1024),
  price_cents integer not null,
  stock_quantity integer not null default 0,
  is_packaging_free boolean not null default true,
  c2c_eligible boolean not null default false,
  c2c_refund_value_cents integer not null default 0,
  title_nl text,
  title_fr text,
  title_en text,
  desc_nl text,
  desc_fr text,
  desc_en text,
  is_catalog boolean not null default true,
  availability text not null default 'available',
  required_level smallint,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  constraint products_availability_check check (availability in ('available', 'coming_soon', 'out_of_stock'))
);

create index if not exists products_org_idx on public.products (organisation_id);

create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products (id) on delete cascade,
  media_id text,
  url text,
  alt text,
  position integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists product_images_product_idx on public.product_images (product_id, position);

-- ---------- Boekingen ----------
create table if not exists public.bookings (
  id uuid primary key default gen_random_uuid(),
  reference text not null default ('BK-' || upper(substr(md5(random()::text), 1, 6))),
  type public.booking_type not null default 'zaalverhuur',
  status public.booking_status not null default 'nieuw',
  client_name text not null,
  client_org text,
  client_email text not null default '',
  client_phone text not null default '',
  event_date date not null,
  start_time time not null default '09:00',
  end_time time not null default '17:00',
  location_id text not null references public.locations (id),
  guests_count integer not null default 0,
  options text[] not null default '{}'::text[],
  price numeric(10, 2) not null default 0,
  day_status public.day_status not null default 'verwacht',
  lang text not null default 'nl',
  amount_cent integer not null default 0,
  payment_status text not null default 'PENDING',
  stripe_payment_intent_id text,
  payment_id uuid,
  paid_at timestamptz,
  confirmation_sent_at timestamptz,
  notes text,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint bookings_lang_check check (lang in ('nl', 'fr', 'en')),
  constraint bookings_payment_status_check check (payment_status in ('PENDING', 'PAID', 'FAILED', 'CANCELLED'))
);

create index if not exists bookings_event_date_idx on public.bookings (event_date);
create index if not exists bookings_status_idx on public.bookings (status);
create index if not exists bookings_client_email_idx on public.bookings (client_email);
create index if not exists bookings_deleted_idx on public.bookings (deleted_at);
create unique index if not exists bookings_pi_idx
  on public.bookings (stripe_payment_intent_id)
  where stripe_payment_intent_id is not null;

-- ---------- Bestellingen ----------
create table if not exists public.orders (
  id serial primary key,
  organisation_id integer not null references public.organisations (id) on delete cascade,
  structured_communication varchar(64) not null unique,
  total_price_cents integer not null,
  pickup_slot timestamptz not null,
  payment_status varchar(32) not null default 'pending',
  payment_method varchar(32),
  customer_email varchar(255),
  customer_name text,
  stripe_payment_intent_id text,
  lang text not null default 'nl',
  paid_at timestamptz,
  reference text,
  order_reference text,
  invoice_url text,
  invoice_number text,
  created_at timestamptz not null default now()
);

create index if not exists orders_created_idx on public.orders (created_at desc);
create index if not exists orders_email_idx on public.orders (customer_email);

create table if not exists public.order_items (
  id serial primary key,
  order_id integer not null references public.orders (id) on delete cascade,
  product_id integer references public.products (id),
  quantity integer not null,
  price_at_purchase_cents integer not null
);

create index if not exists order_items_order_idx on public.order_items (order_id);
