WITH a AS (
  INSERT INTO public.academies (diersoort_naam, diersoort_naam_fr, diersoort_naam_en, slug, badge_icon, vragen_per_test, slaag_grens, beschrijving, beschrijving_fr, beschrijving_en, categorie, prioriteit)
  VALUES ('Cavia','Cochon d''Inde','Guinea Pig','cavia','cavia',12,9,'Ontdek hoe je een cavia een gezond, sociaal en comfortabel leven geeft.','Découvrez comment offrir au cochon d''Inde une vie saine, sociale et confortable.','Discover how to give a guinea pig a healthy, social and comfortable life.','knaagdieren',10)
  RETURNING id
)
INSERT INTO public.academy_vragen (academy_id, module, vraag_type, vraag_tekst, vraag_tekst_fr, vraag_tekst_en, opties, opties_fr, opties_en, correcte_optie_index, wist_je_dat, wist_je_dat_fr, wist_je_dat_en)
SELECT a.id, v.module, v.vraag_type, v.nl, v.fr, v.en, v.onl, v.ofr, v.oen, v.ci, v.wnl, v.wfr, v.wen
FROM a, (VALUES
(1,'tekst','Hoeveel vloeroppervlakte heeft een cavia minimaal nodig?','De quelle surface au sol minimale un cochon d''Inde a-t-il besoin ?','How much floor space does a guinea pig need at minimum?',
 '["0,5 m² per dier","2 m² per dier","0,1 m² per dier","Geen vaste norm nodig"]'::jsonb,
 '["0,5 m² par animal","2 m² par animal","0,1 m² par animal","Aucune norme fixe nécessaire"]'::jsonb,
 '["0.5 m² per animal","2 m² per animal","0.1 m² per animal","No fixed standard needed"]'::jsonb,
 0,'Cavia''s hebben minstens 0,5 m² per dier nodig om te kunnen rennen, verstoppen en exploreren.','Les cochons d''Inde ont besoin d''au moins 0,5 m² par animal pour courir, se cacher et explorer.','Guinea pigs need at least 0.5 m² per animal to run, hide and explore.'),
(1,'tekst','Wat hoort altijd in een caviaverblijf aanwezig te zijn?','Qu''est-ce qui doit toujours se trouver dans l''enclos d''un cochon d''Inde ?','What should always be present in a guinea pig enclosure?',
 '["Een loopwiel","Schuilplaatsen zoals hutjes of buizen","Een waterbad","Niets, een kale bodem is best"]'::jsonb,
 '["Une roue d''exercice","Des cachettes comme des huttes ou tubes","Un bain d''eau","Rien, un sol nu est préférable"]'::jsonb,
 '["An exercise wheel","Hiding spots like huts or tubes","A water bath","Nothing, a bare floor is best"]'::jsonb,
 1,'Cavia''s zijn prooidieren en hebben schuilplaatsen nodig om zich veilig te voelen en stress te vermijden.','Les cochons d''Inde sont des proies et ont besoin de cachettes pour se sentir en sécurité.','Guinea pigs are prey animals and need hiding spots to feel safe and avoid stress.'),
(1,'tekst','Bij welke temperatuur voelt een cavia zich het best?','À quelle température un cochon d''Inde se sent-il le mieux ?','At what temperature does a guinea pig feel best?',
 '["Tussen 5 en 10°C","Tussen 30 en 35°C","Tussen 18 en 22°C","Temperatuur maakt niet uit"]'::jsonb,
 '["Entre 5 et 10°C","Entre 30 et 35°C","Entre 18 et 22°C","La température n''a pas d''importance"]'::jsonb,
 '["Between 5 and 10°C","Between 30 and 35°C","Between 18 and 22°C","Temperature doesn''t matter"]'::jsonb,
 2,'Cavia''s zijn gevoelig aan tocht en extreme temperaturen; 18-22°C is ideaal voor hun welzijn.','Les cochons d''Inde sont sensibles aux courants d''air et aux températures extrêmes ; 18-22°C est idéal.','Guinea pigs are sensitive to drafts and extreme temperatures; 18-22°C is ideal for their wellbeing.'),
(1,'tekst','Waarom is een loopwiel ongeschikt voor cavia''s?','Pourquoi une roue d''exercice est-elle inadaptée aux cochons d''Inde ?','Why is an exercise wheel unsuitable for guinea pigs?',
 '["Ze houden niet van bewegen","Hun rug kan zich niet krommen zoals bij muizen, dit is schadelijk","Wielen zijn te duur","Ze passen er niet in"]'::jsonb,
 '["Ils n''aiment pas bouger","Leur dos ne peut pas se courber comme celui d''une souris, c''est nocif","Les roues coûtent trop cher","Ils n''y tiennent pas"]'::jsonb,
 '["They don''t like moving","Their spine can''t curve like a mouse''s, which is harmful","Wheels are too expensive","They don''t fit in them"]'::jsonb,
 1,'De wervelkolom van een cavia is niet gebouwd om te krommen in een wiel, wat rugletsel kan veroorzaken.','La colonne vertébrale d''un cochon d''Inde n''est pas faite pour se courber dans une roue, ce qui peut blesser le dos.','A guinea pig''s spine isn''t built to curve in a wheel, which can cause back injury.'),
(2,'tekst','Waarom hebben cavia''s dagelijks vitamine C nodig via hun voeding?','Pourquoi les cochons d''Inde ont-ils besoin de vitamine C chaque jour dans leur alimentation ?','Why do guinea pigs need daily vitamin C in their diet?',
 '["Ze kunnen dit zelf aanmaken, dus het is niet nodig","Ze kunnen geen vitamine C aanmaken en worden anders ziek","Het maakt hun vacht glanzender","Vitamine C is giftig voor hen"]'::jsonb,
 '["Ils le produisent eux-mêmes, donc inutile","Ils ne peuvent pas produire de vitamine C et tombent malades sinon","Cela rend leur pelage plus brillant","La vitamine C leur est toxique"]'::jsonb,
 '["They can produce it themselves, so it''s unnecessary","They cannot produce vitamin C and get sick without it","It makes their coat shinier","Vitamin C is toxic to them"]'::jsonb,
 1,'Cavia''s missen, net als mensen, het enzym om vitamine C aan te maken en hebben het dus via voeding nodig, anders krijgen ze scheurbuik.','Comme les humains, les cochons d''Inde manquent de l''enzyme pour produire de la vitamine C et doivent l''obtenir par l''alimentation, sinon ils développent le scorbut.','Like humans, guinea pigs lack the enzyme to make vitamin C and must get it from food, or they develop scurvy.'),
(2,'tekst','Wat vormt de basis van een gezond caviadieet?','Quelle est la base d''une alimentation saine pour le cochon d''Inde ?','What forms the basis of a healthy guinea pig diet?',
 '["Onbeperkt hooi","Vooral pellets","Vooral fruit","Voornamelijk brood en granen"]'::jsonb,
 '["Du foin à volonté","Surtout des granulés","Surtout des fruits","Principalement du pain et des céréales"]'::jsonb,
 '["Unlimited hay","Mostly pellets","Mostly fruit","Mainly bread and grains"]'::jsonb,
 0,'Hooi moet altijd onbeperkt beschikbaar zijn: het houdt de darmen en tanden van de cavia gezond.','Le foin doit toujours être disponible à volonté : il maintient les intestins et les dents du cochon d''Inde en bonne santé.','Hay should always be available unlimited: it keeps a guinea pig''s gut and teeth healthy.'),
(2,'tekst','Waarom groeien de tanden van een cavia levenslang door?','Pourquoi les dents du cochon d''Inde poussent-elles toute sa vie ?','Why do a guinea pig''s teeth grow continuously throughout its life?',
 '["Dit is een ziekte","Om voldoende ruwvoer te kunnen afslijten en kauwen","Ze verliezen tanden vaak","Alleen bij oude dieren"]'::jsonb,
 '["C''est une maladie","Pour pouvoir user les dents grâce aux fibres et mâcher","Ils perdent souvent des dents","Seulement chez les animaux âgés"]'::jsonb,
 '["It''s a disease","So they can wear them down chewing fibrous food","They often lose teeth","Only in old animals"]'::jsonb,
 1,'De tanden groeien continu door en worden afgesleten door het kauwen op hooi; te weinig ruwvoer leidt tot gebitsproblemen.','Les dents poussent en continu et s''usent en mâchant du foin ; trop peu de fibres cause des problèmes dentaires.','Teeth grow continuously and are worn down by chewing hay; too little fibre causes dental problems.'),
(2,'tekst','Wat is een teken van ziekte bij een cavia waarbij je snel een dierenarts moet raadplegen?','Quel signe de maladie chez un cochon d''Inde nécessite de consulter rapidement un vétérinaire ?','What sign of illness in a guinea pig should prompt a quick vet visit?',
 '["Normale eetlust","Stoppen met eten gedurende enkele uren","Rustig slapen overdag","Regelmatig knagen op hooi"]'::jsonb,
 '["Appétit normal","Arrêt de l''alimentation pendant quelques heures","Dormir tranquillement le jour","Ronger régulièrement du foin"]'::jsonb,
 '["Normal appetite","Stopping eating for a few hours","Sleeping calmly during the day","Regularly gnawing on hay"]'::jsonb,
 1,'Cavia''s hebben een snelle darmpassage nodig; stoppen met eten kan al na enkele uren levensbedreigend zijn.','Les cochons d''Inde ont besoin d''un transit rapide ; arrêter de manger peut devenir dangereux en quelques heures.','Guinea pigs need constant gut movement; stopping eating can become life-threatening within hours.'),
(3,'tekst','Waarom mag een cavia nooit alleen gehouden worden?','Pourquoi un cochon d''Inde ne doit-il jamais être détenu seul ?','Why should a guinea pig never be kept alone?',
 '["Ze zijn van nature solitair","Het zijn sociale dieren die soortgenoten nodig hebben","Ze vechten altijd met elkaar","Alleen wijfjes hebben gezelschap nodig"]'::jsonb,
 '["Ils sont naturellement solitaires","Ce sont des animaux sociaux ayant besoin de congénères","Ils se battent toujours entre eux","Seules les femelles ont besoin de compagnie"]'::jsonb,
 '["They are naturally solitary","They are social animals needing companions","They always fight with each other","Only females need companionship"]'::jsonb,
 1,'Cavia''s leven in het wild in groepen en hebben soortgenoten nodig om zich veilig en gelukkig te voelen.','À l''état sauvage, les cochons d''Inde vivent en groupes et ont besoin de congénères pour se sentir en sécurité et heureux.','In the wild guinea pigs live in groups and need companions to feel safe and happy.'),
(3,'tekst','Hoe til je een cavia het beste correct op?','Comment soulever correctement un cochon d''Inde ?','How should you correctly pick up a guinea pig?',
 '["Aan de oren","Met beide handen, één onder de borst en één onder het achterwerk","Aan de nekvel","Aan de pootjes"]'::jsonb,
 '["Par les oreilles","Avec les deux mains, une sous la poitrine et une sous l''arrière-train","Par la peau du cou","Par les pattes"]'::jsonb,
 '["By the ears","With both hands, one under the chest and one under the rear","By the scruff of the neck","By the legs"]'::jsonb,
 1,'Een cavia moet met beide handen ondersteund worden zodat het lichaam volledig gedragen wordt en niet kan wegglijden.','Un cochon d''Inde doit être soutenu à deux mains pour que tout le corps soit porté sans risque de chute.','A guinea pig should be supported with both hands so the whole body is held and can''t slip.'),
(3,'tekst','Wat betekent het geluid "wheeking" (een luid piepje) meestal bij een cavia?','Que signifie généralement le "wheek" (cri aigu) chez le cochon d''Inde ?','What does a guinea pig''s loud "wheeking" sound usually mean?',
 '["Pijn","Opwinding, vaak in verwachting van eten","Agressie","Ze zijn ziek"]'::jsonb,
 '["Douleur","Excitation, souvent en attendant la nourriture","Agressivité","Ils sont malades"]'::jsonb,
 '["Pain","Excitement, often in anticipation of food","Aggression","They are ill"]'::jsonb,
 1,'Wheeken is een herkenbaar geluid dat cavia''s maken wanneer ze eten verwachten of enthousiast zijn.','Le "wheek" est un son reconnaissable que les cochons d''Inde émettent en anticipant la nourriture ou par enthousiasme.','Wheeking is a recognisable sound guinea pigs make when anticipating food or feeling excited.'),
(3,'tekst','Hoe reageert een cavia meestal wanneer die schrikt?','Comment un cochon d''Inde réagit-il généralement lorsqu''il a peur ?','How does a guinea pig usually react when startled?',
 '["Het verstijft en blijft doodstil zitten (freeze)","Het gaat meteen slapen","Het klimt hoog omhoog","Het maakt luid keelgeschraap"]'::jsonb,
 '["Il se fige et reste immobile (freeze)","Il s''endort immédiatement","Il grimpe très haut","Il émet un raclement de gorge fort"]'::jsonb,
 '["It freezes and stays completely still","It goes to sleep immediately","It climbs up high","It makes a loud throat rasp"]'::jsonb,
 0,'Cavia''s zijn prooidieren die bij schrik vaak bevriezen (freeze) in plaats van te vluchten, als overlevingsstrategie.','Les cochons d''Inde, proies dans la nature, se figent souvent (freeze) plutôt que de fuir, comme stratégie de survie.','Guinea pigs are prey animals that often freeze when startled rather than flee, as a survival strategy.')
) AS v(module,vraag_type,nl,fr,en,onl,ofr,oen,ci,wnl,wfr,wen);

WITH a AS (
  INSERT INTO public.academies (diersoort_naam, diersoort_naam_fr, diersoort_naam_en, slug, badge_icon, vragen_per_test, slaag_grens, beschrijving, beschrijving_fr, beschrijving_en, categorie, prioriteit)
  VALUES ('Hamster','Hamster','Hamster','hamster','hamster',12,9,'Leer alles over de behoeften van een hamster op het vlak van kooi, voeding en gedrag.','Apprenez tout sur les besoins du hamster en matière de cage, d''alimentation et de comportement.','Learn all about a hamster''s needs in terms of housing, diet and behaviour.','knaagdieren',11)
  RETURNING id
)
INSERT INTO public.academy_vragen (academy_id, module, vraag_type, vraag_tekst, vraag_tekst_fr, vraag_tekst_en, opties, opties_fr, opties_en, correcte_optie_index, wist_je_dat, wist_je_dat_fr, wist_je_dat_en)
SELECT a.id, v.module, v.vraag_type, v.nl, v.fr, v.en, v.onl, v.ofr, v.oen, v.ci, v.wnl, v.wfr, v.wen
FROM a, (VALUES
(1,'tekst','Hoeveel oppervlakte heeft een goudhamster minimaal nodig?','De quelle surface minimale un hamster doré a-t-il besoin ?','How much floor space does a golden hamster need at minimum?',
 '["Ongeveer 800 cm²","Minstens 100 x 50 cm bodemoppervlak","Een schoenendoos volstaat","10 cm²"]'::jsonb,
 '["Environ 800 cm²","Au moins 100 x 50 cm de surface au sol","Une boîte à chaussures suffit","10 cm²"]'::jsonb,
 '["About 800 cm²","At least 100 x 50 cm of floor space","A shoebox is enough","10 cm²"]'::jsonb,
 1,'Hamsters leggen in het wild kilometers af; een groot kooioppervlak van minstens 100x50 cm is nodig om normaal gedrag te vertonen.','Dans la nature, les hamsters parcourent des kilomètres ; une cage d''au moins 100x50 cm est nécessaire pour un comportement normal.','In the wild hamsters roam kilometres; a cage of at least 100x50 cm is needed for normal behaviour.'),
(1,'tekst','Hoe diep moet de strooisellaag minstens zijn zodat een hamster kan graven?','Quelle doit être l''épaisseur minimale de litière pour que le hamster puisse creuser ?','How deep should the bedding layer be at minimum so a hamster can dig?',
 '["2 cm","20-30 cm","Graven is niet nodig","1 cm volstaat"]'::jsonb,
 '["2 cm","20-30 cm","Creuser n''est pas nécessaire","1 cm suffit"]'::jsonb,
 '["2 cm","20-30 cm","Digging isn''t necessary","1 cm is enough"]'::jsonb,
 1,'Hamsters zijn gravers die in de natuur tunnels graven; 20-30 cm strooisel maakt dit natuurlijk gedrag mogelijk.','Les hamsters sont des fouisseurs qui creusent des tunnels dans la nature ; 20-30 cm de litière permet ce comportement naturel.','Hamsters are diggers that build tunnels in the wild; 20-30 cm of bedding allows this natural behaviour.'),
(1,'tekst','Waarom is een loopwiel met een gesloten (niet-ladder) rijvlak belangrijk voor een hamster?','Pourquoi une roue d''exercice à surface pleine (sans barreaux) est-elle importante pour un hamster ?','Why is a solid-surface (non-rung) exercise wheel important for a hamster?',
 '["Om esthetische redenen","Om rugletsels en beknelde pootjes te voorkomen","Om de kooi te versieren","Ladders zijn net beter"]'::jsonb,
 '["Pour des raisons esthétiques","Pour éviter les blessures au dos et les pattes coincées","Pour décorer la cage","Les barreaux sont en fait préférables"]'::jsonb,
 '["For aesthetic reasons","To prevent back injuries and trapped feet","To decorate the cage","Rungs are actually better"]'::jsonb,
 1,'Een wiel met spijlen kan pootjes bekneld raken; een gesloten loopvlak van minstens 20-28 cm diameter is veiliger.','Une roue à barreaux peut coincer les pattes ; une surface pleine d''au moins 20-28 cm de diamètre est plus sûre.','A rung wheel can trap feet; a solid running surface of at least 20-28 cm diameter is safer.'),
(1,'tekst','Op welk tijdstip is een hamster het meest actief?','À quel moment de la journée un hamster est-il le plus actif ?','At what time of day is a hamster most active?',
 '["''s Ochtends vroeg","Overdag","''s Nachts (nocturnaal)","Nooit, ze slapen bijna altijd"]'::jsonb,
 '["Tôt le matin","Pendant la journée","La nuit (nocturne)","Jamais, ils dorment presque tout le temps"]'::jsonb,
 '["Early in the morning","During the day","At night (nocturnal)","Never, they sleep almost all the time"]'::jsonb,
 2,'Hamsters zijn nachtdieren en worden overdag best niet gestoord, zodat ze voldoende rust krijgen.','Les hamsters sont nocturnes et il vaut mieux ne pas les déranger la journée pour qu''ils se reposent suffisamment.','Hamsters are nocturnal and should ideally not be disturbed during the day so they get enough rest.'),
(2,'tekst','Waarom stoppen hamsters voedsel in hun wangzakken?','Pourquoi les hamsters stockent-ils de la nourriture dans leurs bajoues ?','Why do hamsters store food in their cheek pouches?',
 '["Om indruk te maken op soortgenoten","Om voedsel te verzamelen en op te slaan als voorraad","Omdat ze niet kunnen kauwen","Uit verveling"]'::jsonb,
 '["Pour impressionner leurs congénères","Pour rassembler et stocker de la nourriture en réserve","Parce qu''ils ne peuvent pas mâcher","Par ennui"]'::jsonb,
 '["To impress other hamsters","To gather and store food as a reserve","Because they can''t chew","Out of boredom"]'::jsonb,
 1,'Wangzakken laten hamsters toe voedsel te verzamelen en later terug te trekken naar hun nest als voorraad.','Les bajoues permettent aux hamsters de rassembler de la nourriture et de la rapporter à leur nid comme réserve.','Cheek pouches let hamsters gather food and carry it back to their nest as a reserve.'),
(2,'tekst','Welk voedsel is gevaarlijk voor hamsters?','Quel aliment est dangereux pour les hamsters ?','Which food is dangerous for hamsters?',
 '["Speciaal hamsterkorrelvoer","Verse groenten in kleine hoeveelheid","Citrusvruchten en te veel vochtige snacks","Hooi"]'::jsonb,
 '["Granulés spéciaux pour hamster","Légumes frais en petite quantité","Agrumes et trop de collations humides","Foin"]'::jsonb,
 '["Special hamster pellet food","Fresh vegetables in small amounts","Citrus fruit and too many moist snacks","Hay"]'::jsonb,
 2,'Citrusvruchten en te vochtige snacks kunnen diarree veroorzaken bij hamsters, wat snel gevaarlijk wordt door hun kleine formaat.','Les agrumes et les collations trop humides peuvent causer des diarrhées, dangereuses vu leur petite taille.','Citrus fruit and overly moist snacks can cause diarrhoea, which is dangerous given a hamster''s small size.'),
(2,'tekst','Waarom is het belangrijk dat een hamster kan knagen op hard voedsel of takken?','Pourquoi est-il important qu''un hamster puisse ronger des aliments durs ou des branches ?','Why is it important for a hamster to be able to gnaw on hard food or branches?',
 '["Om verveling te uiten","Om de doorgroeiende tanden af te slijten","Puur voor de smaak","Het is niet belangrijk"]'::jsonb,
 '["Pour exprimer l''ennui","Pour user les dents qui poussent en continu","Uniquement pour le goût","Ce n''est pas important"]'::jsonb,
 '["To express boredom","To wear down their continuously growing teeth","Purely for taste","It isn''t important"]'::jsonb,
 1,'De tanden van een hamster groeien levenslang door; knagen op hard materiaal houdt ze op de juiste lengte.','Les dents d''un hamster poussent toute sa vie ; ronger des matériaux durs les maintient à la bonne longueur.','A hamster''s teeth grow continuously; gnawing on hard material keeps them at the right length.'),
(2,'tekst','Wat is een teken van gezondheidsproblemen bij een hamster?','Quel est un signe de problème de santé chez un hamster ?','What is a sign of health problems in a hamster?',
 '["Actief graven ''s nachts","Natte, plakkerige staart of vacht","Wangzakken gebruiken","Normale slaap overdag"]'::jsonb,
 '["Creuser activement la nuit","Queue ou pelage humide et collant","Utiliser ses bajoues","Sommeil normal le jour"]'::jsonb,
 '["Actively digging at night","Wet, sticky tail or fur","Using cheek pouches","Normal daytime sleep"]'::jsonb,
 1,'Een natte staart ("wet tail") wijst vaak op een ernstige darminfectie en vereist dringend dierenartsbezoek.','Une "queue mouillée" indique souvent une infection intestinale grave nécessitant une visite vétérinaire urgente.','A "wet tail" often indicates a serious intestinal infection requiring urgent veterinary care.'),
(3,'tekst','Kunnen de meeste hamstersoorten samen met soortgenoten gehuisvest worden?','La plupart des espèces de hamsters peuvent-elles être hébergées avec des congénères ?','Can most hamster species be housed together with others?',
 '["Ja, altijd in groep","Nee, Syrische hamsters zijn solitair en moeten alleen gehouden worden","Alleen mannetjes kunnen samen","Ja, in grote kolonies zoals cavia''s"]'::jsonb,
 '["Oui, toujours en groupe","Non, les hamsters syriens sont solitaires et doivent vivre seuls","Seuls les mâles peuvent cohabiter","Oui, en grandes colonies comme les cochons d''Inde"]'::jsonb,
 '["Yes, always in a group","No, Syrian hamsters are solitary and must live alone","Only males can live together","Yes, in large colonies like guinea pigs"]'::jsonb,
 1,'Syrische hamsters zijn territoriaal en solitair; samen huisvesten leidt vaak tot hevige gevechten.','Les hamsters syriens sont territoriaux et solitaires ; les héberger ensemble mène souvent à de violents combats.','Syrian hamsters are territorial and solitary; housing them together often leads to serious fighting.'),
(3,'tekst','Hoe til je een hamster het best op?','Comment soulever un hamster correctement ?','How should you best pick up a hamster?',
 '["Aan de staart","Rustig met beide handen als een kommetje, van onderaf","Nooit, je mag ze niet aanraken","Aan de nekvel vastgrijpen"]'::jsonb,
 '["Par la queue","Doucement à deux mains en forme de coupe, par-dessous","Jamais, on ne doit pas les toucher","En le saisissant par la peau du cou"]'::jsonb,
 '["By the tail","Gently with both hands cupped, scooping from below","Never, they shouldn''t be touched","By grabbing the scruff of the neck"]'::jsonb,
 1,'Hamsters voelen zich veiliger wanneer ze met beide handen als een kommetje worden opgetild in plaats van van bovenaf gegrepen.','Les hamsters se sentent plus en sécurité lorsqu''ils sont soulevés à deux mains en coupe plutôt qu''attrapés par le dessus.','Hamsters feel safer when scooped up with both hands cupped rather than grabbed from above.'),
(3,'tekst','Waarom moet je een hamster nooit plots wakker maken overdag?','Pourquoi ne faut-il jamais réveiller brusquement un hamster le jour ?','Why should you never suddenly wake a hamster during the day?',
 '["Het kan schrikken en bijten uit zelfverdediging","Hamsters worden er blij van","Het heeft geen effect","Hamsters slapen nooit overdag"]'::jsonb,
 '["Il peut avoir peur et mordre par autodéfense","Cela rend le hamster heureux","Cela n''a aucun effet","Les hamsters ne dorment jamais le jour"]'::jsonb,
 '["It can startle them into biting out of self-defence","It makes hamsters happy","It has no effect","Hamsters never sleep during the day"]'::jsonb,
 0,'Een plots gewekte hamster kan schrikken en instinctief bijten omdat hij zich bedreigd voelt, laat hem rustig wakker worden.','Un hamster réveillé brusquement peut mordre par instinct de survie, mieux vaut le laisser se réveiller tranquillement.','A suddenly woken hamster may bite instinctively out of fear; let it wake up calmly.'),
(3,'tekst','Wat betekent het wanneer een hamster rechtop staat met de pootjes omhoog?','Que signifie un hamster debout, les pattes avant levées ?','What does it mean when a hamster stands upright with paws raised?',
 '["Het is aan het spelen","Het voelt zich bedreigd en waarschuwt of verdedigt zich","Het vraagt om eten","Het heeft honger naar water"]'::jsonb,
 '["Il joue","Il se sent menacé et avertit ou se défend","Il demande à manger","Il a soif"]'::jsonb,
 '["It is playing","It feels threatened and is warning or defending itself","It is asking for food","It is thirsty"]'::jsonb,
 1,'Deze houding is een verdedigingshouding waarbij de hamster groter probeert te lijken uit angst of bedreiging.','Cette posture est une position défensive où le hamster tente de paraître plus grand par peur ou menace.','This posture is a defensive stance where the hamster tries to look bigger out of fear or threat.')
) AS v(module,vraag_type,nl,fr,en,onl,ofr,oen,ci,wnl,wfr,wen);

WITH a AS (
  INSERT INTO public.academies (diersoort_naam, diersoort_naam_fr, diersoort_naam_en, slug, badge_icon, vragen_per_test, slaag_grens, beschrijving, beschrijving_fr, beschrijving_en, categorie, prioriteit)
  VALUES ('Konijn','Lapin','Rabbit','konijn','konijn',12,9,'Ontdek de basisbehoeften van konijnen op vlak van huisvesting, voeding en gedrag.','Découvrez les besoins essentiels des lapins en matière d''hébergement, d''alimentation et de comportement.','Discover the essential needs of rabbits regarding housing, diet and behaviour.','knaagdieren',12)
  RETURNING id
)
INSERT INTO public.academy_vragen (academy_id, module, vraag_type, vraag_tekst, vraag_tekst_fr, vraag_tekst_en, opties, opties_fr, opties_en, correcte_optie_index, wist_je_dat, wist_je_dat_fr, wist_je_dat_en)
SELECT a.id, v.module, v.vraag_type, v.nl, v.fr, v.en, v.onl, v.ofr, v.oen, v.ci, v.wnl, v.wfr, v.wen
FROM a, (VALUES
(1,'tekst','Hoeveel ruimte heeft een konijn minstens nodig om te kunnen huppelen en rennen?','De combien d''espace un lapin a-t-il au minimum besoin pour sautiller et courir ?','How much space does a rabbit need at minimum to hop and run?',
 '["Een kooi van 60x40 cm volstaat","Minstens 3 tot 6 m² vrije ruimte","Konijnen hebben geen ruimte nodig","1 m² is voldoende"]'::jsonb,
 '["Une cage de 60x40 cm suffit","Au moins 3 à 6 m² d''espace libre","Les lapins n''ont pas besoin d''espace","1 m² suffit"]'::jsonb,
 '["A 60x40 cm cage is enough","At least 3 to 6 m² of free space","Rabbits don''t need space","1 m² is enough"]'::jsonb,
 1,'Konijnen hebben dagelijks veel bewegingsruimte nodig om te springen en rennen; minstens 3 à 6 m² is aanbevolen.','Les lapins ont besoin de beaucoup d''espace quotidien pour sauter et courir ; au moins 3 à 6 m² sont recommandés.','Rabbits need lots of daily movement space to hop and run; at least 3 to 6 m² is recommended.'),
(1,'tekst','Waarom moeten konijnen altijd met minstens twee gehouden worden?','Pourquoi les lapins doivent-ils toujours être détenus à deux minimum ?','Why should rabbits always be kept in pairs at minimum?',
 '["Het zijn sociale kuddedieren die gezelschap nodig hebben","Ze vervelen zich anders van elkaar","Het is wettelijk verplicht overal","Ze eten anders niet"]'::jsonb,
 '["Ce sont des animaux sociaux ayant besoin de compagnie","Sinon ils s''ennuient l''un de l''autre","C''est obligatoire partout par la loi","Sinon ils ne mangent pas"]'::jsonb,
 '["They are social herd animals needing companionship","Otherwise they get bored of each other","It''s legally required everywhere","Otherwise they won''t eat"]'::jsonb,
 0,'Konijnen zijn van nature sociale dieren die in het wild in groepen leven en gezelschap van soortgenoten nodig hebben.','Les lapins sont des animaux naturellement sociaux qui vivent en groupe à l''état sauvage et ont besoin de compagnie.','Rabbits are naturally social animals that live in groups in the wild and need companionship.'),
(1,'tekst','Wat is essentieel in een konijnenverblijf om gravend gedrag mogelijk te maken?','Qu''est-ce qui est essentiel dans un enclos de lapin pour permettre le comportement de fouissage ?','What is essential in a rabbit enclosure to allow digging behaviour?',
 '["Een gladde plastic bodem","Een graafbak of dikke laag stro/grond","Een loopwiel","Niets speciaals nodig"]'::jsonb,
 '["Un sol en plastique lisse","Un bac à creuser ou une épaisse couche de paille/terre","Une roue d''exercice","Rien de spécial n''est nécessaire"]'::jsonb,
 '["A smooth plastic floor","A digging box or thick layer of straw/soil","An exercise wheel","Nothing special is needed"]'::jsonb,
 1,'Konijnen graven van nature holen; een graafbak biedt hen de kans op dit natuurlijke gedrag zonder schade te veroorzaken.','Les lapins creusent naturellement des terriers ; un bac à creuser leur permet ce comportement sans causer de dégâts.','Rabbits naturally dig burrows; a digging box lets them express this natural behaviour without causing damage.'),
(1,'tekst','Waarom is schaduw en beschutting tegen hitte cruciaal voor buitenkonijnen?','Pourquoi l''ombre et la protection contre la chaleur sont-elles cruciales pour les lapins d''extérieur ?','Why is shade and heat protection crucial for outdoor rabbits?',
 '["Konijnen kunnen niet goed zweten en oververhitten snel","Ze houden niet van zonlicht","Het is enkel esthetisch","Konijnen slapen liever in de zon"]'::jsonb,
 '["Les lapins ne transpirent pas bien et surchauffent vite","Ils n''aiment pas la lumière du soleil","C''est purement esthétique","Les lapins préfèrent dormir au soleil"]'::jsonb,
 '["Rabbits cannot sweat well and overheat quickly","They dislike sunlight","It''s purely aesthetic","Rabbits prefer sleeping in the sun"]'::jsonb,
 0,'Konijnen kunnen nauwelijks zweten en lopen snel risico op hitteslag; schaduw en ventilatie zijn levensnoodzakelijk bij warm weer.','Les lapins transpirent à peine et risquent vite un coup de chaleur ; l''ombre et la ventilation sont vitales par temps chaud.','Rabbits can barely sweat and risk heatstroke quickly; shade and ventilation are vital in hot weather.'),
(2,'tekst','Wat moet het grootste deel van het konijnendieet uitmaken?','Quelle doit être la principale composante de l''alimentation du lapin ?','What should make up the largest part of a rabbit''s diet?',
 '["Pellets/korrels","Hooi (ongeveer 80%)","Wortelen","Brood en granen"]'::jsonb,
 '["Granulés","Le foin (environ 80%)","Les carottes","Le pain et les céréales"]'::jsonb,
 '["Pellets","Hay (about 80%)","Carrots","Bread and grains"]'::jsonb,
 1,'Hooi moet ongeveer 80% van het dieet vormen; het is essentieel voor de spijsvertering en het gebit van konijnen.','Le foin doit représenter environ 80% du régime ; il est essentiel pour la digestion et les dents des lapins.','Hay should make up about 80% of the diet; it is essential for a rabbit''s digestion and teeth.'),
(2,'tekst','Waarom zijn wortelen en fruit slechts als kleine traktatie geschikt voor konijnen?','Pourquoi les carottes et fruits ne conviennent-ils qu''en petite friandise pour les lapins ?','Why are carrots and fruit only suitable as small treats for rabbits?',
 '["Ze zijn giftig","Ze bevatten veel suiker en kunnen obesitas of gebitsproblemen veroorzaken","Konijnen lusten ze niet","Ze bevatten geen voedingswaarde"]'::jsonb,
 '["Ils sont toxiques","Ils contiennent beaucoup de sucre et peuvent causer obésité ou problèmes dentaires","Les lapins ne les aiment pas","Ils n''ont aucune valeur nutritive"]'::jsonb,
 '["They are toxic","They are high in sugar and can cause obesity or dental issues","Rabbits dislike them","They have no nutritional value"]'::jsonb,
 1,'Wortelen en fruit zijn suikerrijk; te veel kan leiden tot overgewicht en tandproblemen bij konijnen.','Les carottes et fruits sont riches en sucre ; un excès peut causer surpoids et problèmes dentaires chez le lapin.','Carrots and fruit are high in sugar; too much can lead to obesity and dental problems in rabbits.'),
(2,'tekst','Wat is een teken van een ernstig gezondheidsprobleem bij konijnen dat spoedeisende zorg vereist?','Quel signe chez le lapin nécessite une intervention vétérinaire urgente ?','What sign in rabbits requires urgent veterinary care?',
 '["Normaal keutelen","Volledig stoppen met eten (gastro-intestinale stase)","Actief hooi eten","Rustig zitten in de schaduw"]'::jsonb,
 '["Crottes normales","Arrêt total de l''alimentation (stase gastro-intestinale)","Manger activement du foin","Rester tranquille à l''ombre"]'::jsonb,
 '["Normal droppings","Complete stop in eating (gastrointestinal stasis)","Actively eating hay","Sitting calmly in the shade"]'::jsonb,
 1,'Konijnen hebben een continu werkend spijsverteringsstelsel; wanneer ze stoppen met eten kan dit binnen uren levensgevaarlijk worden.','Le système digestif du lapin doit fonctionner en continu ; un arrêt de l''alimentation peut devenir mortel en quelques heures.','A rabbit''s digestive system must work continuously; stopping eating can become life-threatening within hours.'),
(2,'tekst','Waarom moeten de tanden van een konijn regelmatig gecontroleerd worden?','Pourquoi les dents d''un lapin doivent-elles être vérifiées régulièrement ?','Why should a rabbit''s teeth be checked regularly?',
 '["Ze groeien levenslang door en kunnen te lang worden","Ze vallen vaak uit","Konijnen hebben maar 2 tanden","Dit is niet nodig"]'::jsonb,
 '["Elles poussent toute la vie et peuvent devenir trop longues","Elles tombent souvent","Les lapins n''ont que 2 dents","Ce n''est pas nécessaire"]'::jsonb,
 '["They grow continuously and can become too long","They often fall out","Rabbits only have 2 teeth","It isn''t necessary"]'::jsonb,
 0,'Zonder voldoende hooi om op te kauwen kunnen de doorgroeiende tanden te lang worden en pijnlijke gebitsproblemen veroorzaken.','Sans assez de foin à mâcher, les dents qui poussent en continu peuvent devenir trop longues et douloureuses.','Without enough hay to chew, continuously growing teeth can become too long and cause painful problems.'),
(3,'tekst','Hoe til je een konijn correct op om letsel te vermijden?','Comment soulever correctement un lapin pour éviter les blessures ?','How should you correctly lift a rabbit to avoid injury?',
 '["Aan de oren","Met één hand onder de borst en één onder het achterwerk, rug ondersteund","Aan de nekvel alleen","Aan de pootjes optillen"]'::jsonb,
 '["Par les oreilles","Une main sous la poitrine et une sous l''arrière-train, dos soutenu","Uniquement par la peau du cou","Par les pattes"]'::jsonb,
 '["By the ears","One hand under the chest and one under the rear, back supported","Only by the scruff","By the legs"]'::jsonb,
 1,'De rug van een konijn moet altijd ondersteund worden; verkeerd optillen kan tot ernstig ruggenmergletsel leiden.','Le dos d''un lapin doit toujours être soutenu ; un mauvais soulèvement peut causer de graves blessures à la colonne.','A rabbit''s back must always be supported; incorrect lifting can cause serious spinal injury.'),
(3,'tekst','Wat betekent het wanneer een konijn met zijn achterpoot op de grond stampt?','Que signifie un lapin qui tape du pied arrière sur le sol ?','What does it mean when a rabbit thumps its hind foot on the ground?',
 '["Het is blij en speels","Het waarschuwt voor gevaar of is gestrest","Het vraagt om eten","Het wil slapen"]'::jsonb,
 '["Il est heureux et joueur","Il avertit d''un danger ou est stressé","Il demande à manger","Il veut dormir"]'::jsonb,
 '["It is happy and playful","It is warning of danger or is stressed","It is asking for food","It wants to sleep"]'::jsonb,
 1,'Stampen is een alarmsignaal waarmee konijnen soortgenoten waarschuwen voor gevaar, of het toont stress of onrust.','Le tapement est un signal d''alarme par lequel les lapins avertissent leurs congénères d''un danger, ou montre du stress.','Thumping is an alarm signal rabbits use to warn others of danger, or it shows stress.'),
(3,'tekst','Waarom mag je een konijn nooit plots achteropkomen of vastgrijpen?','Pourquoi ne faut-il jamais surprendre ou saisir brusquement un lapin par derrière ?','Why should you never suddenly approach or grab a rabbit from behind?',
 '["Konijnen zijn prooidieren en schrikken hierdoor hevig","Konijnen vinden het net leuk","Het heeft geen effect op hen","Konijnen zien niets aankomen sowieso"]'::jsonb,
 '["Les lapins sont des proies et sont fortement effrayés","Les lapins adorent ça","Cela n''a aucun effet sur eux","Les lapins ne voient rien venir de toute façon"]'::jsonb,
 '["Rabbits are prey animals and get badly frightened","Rabbits actually enjoy it","It has no effect on them","Rabbits can''t see anything coming anyway"]'::jsonb,
 0,'Konijnen zijn prooidieren met een sterk vluchtinstinct; plotse bewegingen van achteren kunnen paniek en letsel veroorzaken.','Les lapins sont des proies avec un fort instinct de fuite ; des mouvements soudains par derrière peuvent causer panique et blessures.','Rabbits are prey animals with a strong flight instinct; sudden movements from behind can cause panic and injury.')
) AS v(module,vraag_type,nl,fr,en,onl,ofr,oen,ci,wnl,wfr,wen);
