-- Aquarium & goudvis
WITH a AS (
  INSERT INTO public.academies (diersoort_naam, diersoort_naam_fr, diersoort_naam_en, slug, badge_icon, vragen_per_test, slaag_grens, beschrijving, beschrijving_fr, beschrijving_en, categorie, prioriteit)
  VALUES ('Aquarium & goudvis','Aquarium & poisson rouge','Aquarium & goldfish','aquarium-goudvis','aquarium-goudvis',15,12,'Leer alles over een gezond aquarium, de stikstofcyclus en goede zorg voor goudvissen.','Découvrez tout sur un aquarium sain, le cycle de l''azote et les bons soins pour les poissons rouges.','Learn everything about a healthy aquarium, the nitrogen cycle and good goldfish care.','huisdieren',50)
  RETURNING id
)
INSERT INTO public.academy_vragen (academy_id, module, vraag_type, vraag_tekst, vraag_tekst_fr, vraag_tekst_en, opties, opties_fr, opties_en, correcte_optie_index, wist_je_dat, wist_je_dat_fr, wist_je_dat_en)
SELECT a.id, v.module, v.vraag_type, v.nl, v.fr, v.en, v.onl, v.ofr, v.oen, v.ci, v.wnl, v.wfr, v.wen
FROM a, (VALUES
(1,'tekst','Waarom is een ronde goudviskom dieronvriendelijk?','Pourquoi un bocal rond est-il néfaste pour un poisson rouge ?','Why is a round goldfish bowl bad for the fish?',
 '["Te weinig water en oppervlak voor voldoende zuurstof en filtering","Het is te groot voor de vis","Goudvissen houden van weinig water","Er is geen enkel nadeel"]'::jsonb,
 '["Trop peu d''eau et de surface pour l''oxygène et la filtration","C''est trop grand pour le poisson","Les poissons rouges aiment peu d''eau","Il n''y a aucun inconvénient"]'::jsonb,
 '["Too little water and surface area for oxygen and filtration","It is too large for the fish","Goldfish prefer little water","There is no downside at all"]'::jsonb,
 0,'Goudvissen kunnen tot wel 30 cm groeien en hebben minstens 100 liter nodig voor een volwassen leven.','Les poissons rouges peuvent atteindre 30 cm et ont besoin d''au moins 100 litres à l''âge adulte.','Goldfish can grow up to 30 cm and need at least 100 litres as adults.'),
(1,'tekst','Wat is de stikstofcyclus in een aquarium?','Qu''est-ce que le cycle de l''azote dans un aquarium ?','What is the nitrogen cycle in an aquarium?',
 '["Het proces waarbij bacteriën ammoniak omzetten via nitriet naar nitraat","Het proces waarbij vissen zuurstof maken","De cyclus van waterverdamping","Het proces waarbij planten afsterven"]'::jsonb,
 '["Le processus par lequel des bactéries transforment l''ammoniac en nitrite puis nitrate","Le processus par lequel les poissons produisent de l''oxygène","Le cycle d''évaporation de l''eau","Le processus par lequel les plantes meurent"]'::jsonb,
 '["The process where bacteria convert ammonia via nitrite into nitrate","The process where fish produce oxygen","The cycle of water evaporation","The process where plants die off"]'::jsonb,
 0,'Zonder een ingelopen stikstofcyclus is ammoniak dodelijk giftig voor vissen.','Sans cycle de l''azote établi, l''ammoniac est mortellement toxique pour les poissons.','Without an established nitrogen cycle, ammonia is lethally toxic to fish.'),
(1,'tekst','Waarom is een filter noodzakelijk in een aquarium?','Pourquoi un filtre est-il indispensable dans un aquarium ?','Why is a filter necessary in an aquarium?',
 '["Om schadelijke afvalstoffen af te breken en water te zuiveren","Om het water warmer te maken","Enkel voor decoratie","Vissen hebben geen filter nodig"]'::jsonb,
 '["Pour décomposer les déchets nocifs et purifier l''eau","Pour réchauffer l''eau","Uniquement pour la décoration","Les poissons n''ont pas besoin de filtre"]'::jsonb,
 '["To break down harmful waste and purify the water","To make the water warmer","Only for decoration","Fish do not need a filter"]'::jsonb,
 0,'Filters bevatten goede bacteriën die ammoniak en nitriet omzetten naar minder schadelijk nitraat.','Les filtres contiennent de bonnes bactéries qui transforment l''ammoniac et le nitrite en nitrate moins nocif.','Filters contain beneficial bacteria that convert ammonia and nitrite into less harmful nitrate.'),
(1,'tekst','Hoe vaak moet je gedeeltelijk water verversen in een aquarium?','À quelle fréquence faut-il changer partiellement l''eau ?','How often should you do a partial water change?',
 '["Wekelijks ongeveer 10 tot 20 procent van het water","Nooit, water blijft altijd goed","Enkel als het water groen wordt","Eén keer per jaar volledig"]'::jsonb,
 '["Chaque semaine, environ 10 à 20 % de l''eau","Jamais, l''eau reste toujours bonne","Seulement quand l''eau devient verte","Une fois par an, complètement"]'::jsonb,
 '["Weekly, around 10 to 20 percent of the water","Never, water always stays fine","Only when the water turns green","Once a year, completely"]'::jsonb,
 0,'Regelmatige waterverversing houdt nitraatniveaus laag en het water gezond.','Des changements d''eau réguliers maintiennent les nitrates bas et l''eau saine.','Regular water changes keep nitrate levels low and the water healthy.'),
(1,'tekst','Waarom moet je goudvissen niet met tropische vissoorten combineren?','Pourquoi ne pas combiner poissons rouges et poissons tropicaux ?','Why should you not combine goldfish with tropical species?',
 '["Goudvissen hebben koeler water nodig dan de meeste tropische vissen","Ze combineren altijd perfect","Tropische vissen eten geen voedsel","Goudvissen hebben warmer water nodig dan tropische vissen"]'::jsonb,
 '["Les poissons rouges ont besoin d''une eau plus fraîche que la plupart des poissons tropicaux","Ils se combinent toujours parfaitement","Les poissons tropicaux ne mangent pas","Les poissons rouges ont besoin d''une eau plus chaude"]'::jsonb,
 '["Goldfish need cooler water than most tropical fish","They always combine perfectly","Tropical fish do not eat food","Goldfish need warmer water than tropical fish"]'::jsonb,
 0,'Goudvissen zijn koudwatervissen, terwijl de meeste tropische soorten verwarmd water rond 24-26°C nodig hebben.','Les poissons rouges sont des poissons d''eau froide, alors que les tropicaux ont besoin d''eau chauffée à 24-26°C.','Goldfish are coldwater fish, while most tropical species need heated water around 24-26°C.'),
(2,'tekst','Hoe groot kan een goudvis worden bij goede verzorging?','Quelle taille un poisson rouge peut-il atteindre avec de bons soins ?','How large can a goldfish grow with good care?',
 '["Tot wel 30 centimeter of meer","Maximaal 3 centimeter","Ze groeien nooit verder dan de kom","Tot 1 meter"]'::jsonb,
 '["Jusqu''à 30 centimètres ou plus","Maximum 3 centimètres","Ils ne grandissent jamais plus que le bocal","Jusqu''à 1 mètre"]'::jsonb,
 '["Up to 30 centimetres or more","A maximum of 3 centimetres","They never grow beyond the size of the bowl","Up to 1 metre"]'::jsonb,
 0,'Goudvissen worden vaak veel groter dan verwacht, wat een groot aquarium noodzakelijk maakt.','Les poissons rouges deviennent souvent bien plus grands que prévu, d''où la nécessité d''un grand aquarium.','Goldfish often grow much larger than expected, which is why a large tank is essential.'),
(2,'tekst','Hoe lang kan een goudvis leven bij goede zorg?','Combien de temps un poisson rouge peut-il vivre avec de bons soins ?','How long can a goldfish live with good care?',
 '["10 tot 20 jaar of langer","Slechts enkele weken","Maximaal 1 jaar","Ongeveer 2 maanden"]'::jsonb,
 '["10 à 20 ans ou plus","Seulement quelques semaines","Maximum 1 an","Environ 2 mois"]'::jsonb,
 '["10 to 20 years or longer","Only a few weeks","A maximum of 1 year","About 2 months"]'::jsonb,
 0,'Bij goede verzorging kunnen goudvissen tientallen jaren leven, veel langer dan vaak wordt gedacht.','Avec de bons soins, les poissons rouges peuvent vivre des dizaines d''années, bien plus qu''on ne le pense.','With good care, goldfish can live for decades, much longer than often assumed.'),
(2,'tekst','Wat gebeurt er als een goudvis in te weinig water leeft?','Que se passe-t-il si un poisson rouge vit dans trop peu d''eau ?','What happens if a goldfish lives in too little water?',
 '["De vis blijft klein en ongezond, en kan ziek worden of vroegtijdig sterven","De vis groeit precies normaal","Er is geen enkel effect","De vis wordt automatisch groter"]'::jsonb,
 '["Le poisson reste petit et malsain, peut tomber malade ou mourir prématurément","Le poisson grandit normalement","Il n''y a aucun effet","Le poisson devient automatiquement plus grand"]'::jsonb,
 '["The fish stays stunted and unhealthy, and may fall ill or die prematurely","The fish grows completely normally","There is no effect at all","The fish automatically becomes larger"]'::jsonb,
 0,'Onvoldoende ruimte en slechte waterkwaliteit remmen de groei en verkorten de levensduur van goudvissen.','Un espace insuffisant et une mauvaise qualité de l''eau freinent la croissance et réduisent la durée de vie.','Insufficient space and poor water quality stunt growth and shorten a goldfish''s lifespan.'),
(2,'tekst','Wat is een teken van slechte waterkwaliteit in een aquarium?','Quel est un signe de mauvaise qualité de l''eau ?','What is a sign of poor water quality in a tank?',
 '["Vissen happen naar lucht aan het oppervlak","Vissen zwemmen actief rond","Het water ruikt naar niets","De planten groeien goed"]'::jsonb,
 '["Les poissons cherchent de l''air à la surface","Les poissons nagent activement","L''eau ne sent rien","Les plantes poussent bien"]'::jsonb,
 '["Fish gasping for air at the surface","Fish swimming around actively","The water has no smell","The plants are growing well"]'::jsonb,
 0,'Happen naar lucht wijst vaak op te weinig opgeloste zuurstof of hoge ammoniak- en nitrietwaarden.','Chercher de l''air indique souvent un manque d''oxygène dissous ou des niveaux élevés d''ammoniac et de nitrite.','Gasping for air often indicates too little dissolved oxygen or high ammonia and nitrite levels.'),
(2,'tekst','Wat moet je doen voor je een nieuw aquarium met vissen bevolkt?','Que faut-il faire avant de peupler un nouvel aquarium ?','What should you do before stocking a new aquarium?',
 '["Het aquarium eerst laten inlopen zodat de stikstofcyclus op gang komt","Meteen vissen toevoegen zonder wachten","Het water dagelijks volledig vervangen","Geen filter gebruiken"]'::jsonb,
 '["Faire d''abord cycler l''aquarium pour démarrer le cycle de l''azote","Ajouter les poissons immédiatement sans attendre","Remplacer complètement l''eau chaque jour","Ne pas utiliser de filtre"]'::jsonb,
 '["Cycle the aquarium first so the nitrogen cycle gets established","Add fish immediately without waiting","Completely replace the water every day","Not use a filter at all"]'::jsonb,
 0,'Een nieuw aquarium inlopen duurt meestal enkele weken en voorkomt gevaarlijke ammoniekpieken.','Le cyclage d''un nouvel aquarium prend généralement plusieurs semaines et évite des pics d''ammoniac dangereux.','Cycling a new tank usually takes a few weeks and prevents dangerous ammonia spikes.'),
(3,'tekst','Waar moet je op letten bij het combineren van vissoorten in één aquarium?','À quoi faire attention en combinant des espèces dans un aquarium ?','What should you consider when combining fish species in one tank?',
 '["Vergelijkbare temperatuur- en waterbehoeften en verenigbaar temperament","Enkel de kleur van de vissen","Of ze allemaal even oud zijn","Niets, alle vissen kunnen altijd samen"]'::jsonb,
 '["Des besoins similaires en température et en eau, et un tempérament compatible","Uniquement la couleur des poissons","S''ils ont tous le même âge","Rien, tous les poissons peuvent toujours être ensemble"]'::jsonb,
 '["Similar temperature and water needs, and compatible temperament","Only the colour of the fish","Whether they are all the same age","Nothing, all fish can always live together"]'::jsonb,
 0,'Vissen met verschillende watertemperaturen of agressief gedrag kunnen elkaar stress bezorgen of verwonden.','Des poissons avec des besoins en température différents ou un comportement agressif peuvent se stresser ou se blesser.','Fish with differing temperature needs or aggressive behaviour can stress or injure each other.'),
(3,'tekst','Waarom kan het gevaarlijk zijn om te veel vissen in één aquarium te houden?','Pourquoi est-il dangereux de mettre trop de poissons dans un aquarium ?','Why can overstocking an aquarium be dangerous?',
 '["Overbevolking verhoogt afvalproductie en verlaagt zuurstofgehalte","Meer vissen betekent altijd een gezonder aquarium","Vissen delen dan automatisch al hun voedsel eerlijk","Er is geen enkel risico"]'::jsonb,
 '["La surpopulation augmente les déchets et réduit l''oxygène","Plus de poissons signifie toujours un aquarium plus sain","Les poissons partagent alors automatiquement leur nourriture équitablement","Il n''y a aucun risque"]'::jsonb,
 '["Overstocking increases waste production and lowers oxygen levels","More fish always means a healthier tank","Fish then automatically share food fairly","There is no risk at all"]'::jsonb,
 0,'Overbevolking kan leiden tot snelle ammoniakopbouw, stress en ziekte-uitbraken.','La surpopulation peut entraîner une accumulation rapide d''ammoniac, du stress et des épidémies.','Overstocking can lead to rapid ammonia build-up, stress and disease outbreaks.'),
(3,'tekst','Wat is de vuistregel om overvoeding van vissen te vermijden?','Quelle est la règle de base pour éviter de suralimenter les poissons ?','What is the rule of thumb to avoid overfeeding fish?',
 '["Geef enkel wat ze in 2 tot 3 minuten volledig kunnen opeten","Geef altijd zoveel mogelijk voedsel","Voer nooit vissen","Voer enkel eenmaal per maand"]'::jsonb,
 '["Donnez seulement ce qu''ils peuvent manger entièrement en 2 à 3 minutes","Donnez toujours le plus de nourriture possible","Ne nourrissez jamais les poissons","Nourrissez seulement une fois par mois"]'::jsonb,
 '["Only give what they can fully eat within 2 to 3 minutes","Always give as much food as possible","Never feed fish at all","Feed only once a month"]'::jsonb,
 0,'Overvoeding leidt tot resten die water vervuilen en de ammoniakwaarden snel doen stijgen.','Suralimenter laisse des restes qui polluent l''eau et font grimper rapidement l''ammoniac.','Overfeeding leaves leftovers that pollute the water and cause ammonia levels to rise quickly.'),
(3,'tekst','Waarom is een goede waterthermometer belangrijk bij een aquarium?','Pourquoi un bon thermomètre est-il important pour un aquarium ?','Why is a good thermometer important for an aquarium?',
 '["Om schommelingen in temperatuur te vermijden die vissen stress geven","Enkel voor de esthetiek van het aquarium","Vissen voelen temperatuur niet","Het is nooit nodig"]'::jsonb,
 '["Pour éviter des variations de température qui stressent les poissons","Uniquement pour l''esthétique de l''aquarium","Les poissons ne ressentent pas la température","Ce n''est jamais nécessaire"]'::jsonb,
 '["To avoid temperature fluctuations that stress fish","Only for the aesthetics of the tank","Fish do not sense temperature","It is never necessary"]'::jsonb,
 0,'Plotse temperatuurschommelingen kunnen het immuunsysteem van vissen verzwakken.','Des changements brusques de température peuvent affaiblir le système immunitaire des poissons.','Sudden temperature swings can weaken a fish''s immune system.'),
(3,'tekst','Wat is een goede reden om aquariumplanten toe te voegen?','Quelle est une bonne raison d''ajouter des plantes à l''aquarium ?','What is a good reason to add live plants to an aquarium?',
 '["Ze helpen nitraat opnemen en geven zuurstof en schuilplaatsen","Ze zijn enkel decoratief en hebben geen functie","Ze verhogen de ammoniak in het water","Vissen mogen nooit bij planten in de buurt komen"]'::jsonb,
 '["Elles aident à absorber le nitrate et fournissent oxygène et cachettes","Elles sont purement décoratives sans fonction","Elles augmentent l''ammoniac dans l''eau","Les poissons ne doivent jamais s''approcher des plantes"]'::jsonb,
 '["They help absorb nitrate and provide oxygen and hiding spots","They are purely decorative with no function","They increase ammonia in the water","Fish should never be near plants"]'::jsonb,
 0,'Levende planten verbeteren de waterkwaliteit en bieden vissen natuurlijke schuilplaatsen.','Les plantes vivantes améliorent la qualité de l''eau et offrent des cachettes naturelles aux poissons.','Live plants improve water quality and give fish natural hiding places.')
) AS v(module,vraag_type,nl,fr,en,onl,ofr,oen,ci,wnl,wfr,wen);

-- Chinchilla & degoe
WITH a AS (
  INSERT INTO public.academies (diersoort_naam, diersoort_naam_fr, diersoort_naam_en, slug, badge_icon, vragen_per_test, slaag_grens, beschrijving, beschrijving_fr, beschrijving_en, categorie, prioriteit)
  VALUES ('Chinchilla & degoe','Chinchilla & dègue','Chinchilla & degu','chinchilla','chinchilla',15,12,'Leer over zandbaden, dieet, knaagbehoeften en huisvesting van chinchilla''s en degoes.','Découvrez les bains de sable, l''alimentation, les besoins de rongement et le logement des chinchillas et dègues.','Learn about dust baths, diet, gnawing needs and housing for chinchillas and degus.','knaagdieren',50)
  RETURNING id
)
INSERT INTO public.academy_vragen (academy_id, module, vraag_type, vraag_tekst, vraag_tekst_fr, vraag_tekst_en, opties, opties_fr, opties_en, correcte_optie_index, wist_je_dat, wist_je_dat_fr, wist_je_dat_en)
SELECT a.id, v.module, v.vraag_type, v.nl, v.fr, v.en, v.onl, v.ofr, v.oen, v.ci, v.wnl, v.wfr, v.wen
FROM a, (VALUES
(1,'tekst','Waarom hebben chinchilla''s een zandbad nodig?','Pourquoi les chinchillas ont-ils besoin d''un bain de sable ?','Why do chinchillas need a dust bath?',
 '["Om hun dichte vacht schoon en vetvrij te houden","Om te drinken","Om te slapen","Chinchilla''s hebben dit niet nodig"]'::jsonb,
 '["Pour garder leur pelage dense propre et sans excès de graisse","Pour boire","Pour dormir","Les chinchillas n''en ont pas besoin"]'::jsonb,
 '["To keep their dense fur clean and free of excess oil","To drink","To sleep","Chinchillas do not need this"]'::jsonb,
 0,'Chinchilla''s hebben zo''n dichte vacht dat water er niet goed in droogt, daarom gebruiken ze speciaal stofzand.','Le pelage des chinchillas est si dense que l''eau y sèche mal, d''où l''utilisation de sable spécial.','Chinchilla fur is so dense that water does not dry well in it, so they use special dust sand instead.'),
(1,'tekst','Hoe vaak moet een chinchilla een zandbad krijgen?','À quelle fréquence un chinchilla doit-il avoir un bain de sable ?','How often should a chinchilla get a dust bath?',
 '["Enkele keren per week, kort aangeboden","Elke dag de hele dag laten staan","Nooit, dat is gevaarlijk","Slechts één keer per jaar"]'::jsonb,
 '["Plusieurs fois par semaine, offert brièvement","Le laisser en permanence chaque jour","Jamais, c''est dangereux","Seulement une fois par an"]'::jsonb,
 '["A few times a week, offered briefly","Left available all day every day","Never, it is dangerous","Only once a year"]'::jsonb,
 0,'Te lang zandbad laten staan kan huidirritatie geven, kort aanbieden is voldoende voor een schone vacht.','Laisser le bain de sable trop longtemps peut irriter la peau, une courte durée suffit pour un pelage propre.','Leaving the dust bath out too long can irritate the skin; a short session is enough for a clean coat.'),
(1,'tekst','Waarom mag je een chinchilla geen vers fruit geven?','Pourquoi ne pas donner de fruits frais à un chinchilla ?','Why should you not give a chinchilla fresh fruit?',
 '["Hun spijsvertering verdraagt geen suikers goed en het kan diarree veroorzaken","Fruit is hun hoofdvoeding","Chinchilla''s houden niet van de smaak","Fruit is altijd verplicht in hun dieet"]'::jsonb,
 '["Leur digestion tolère mal le sucre et cela peut causer des diarrhées","Les fruits sont leur alimentation principale","Les chinchillas n''aiment pas le goût","Les fruits sont toujours obligatoires dans leur régime"]'::jsonb,
 '["Their digestion tolerates sugar poorly and it can cause diarrhoea","Fruit is their main food source","Chinchillas dislike the taste","Fruit is always required in their diet"]'::jsonb,
 0,'Chinchilla''s hebben een gevoelig spijsverteringsstelsel dat is aangepast aan vezelrijk, suikerarm voedsel zoals hooi.','Les chinchillas ont un système digestif sensible adapté à une alimentation riche en fibres et pauvre en sucre comme le foin.','Chinchillas have a sensitive digestive system adapted to high-fibre, low-sugar food like hay.'),
(1,'tekst','Waarom moeten chinchilla''s en degoes veel knagen?','Pourquoi les chinchillas et dègues doivent-ils beaucoup ronger ?','Why do chinchillas and degus need to gnaw a lot?',
 '["Hun tanden groeien continu en moeten worden afgesleten","Ze knagen enkel uit verveling","Knagen is niet nodig voor hen","Hun tanden stoppen met groeien na een jaar"]'::jsonb,
 '["Leurs dents poussent continuellement et doivent être usées","Ils rongent seulement par ennui","Ronger n''est pas nécessaire pour eux","Leurs dents arrêtent de pousser après un an"]'::jsonb,
 '["Their teeth grow continuously and need to be worn down","They only gnaw out of boredom","Gnawing is not necessary for them","Their teeth stop growing after a year"]'::jsonb,
 0,'Zonder voldoende knaagmateriaal kunnen de tanden te lang worden en eetproblemen veroorzaken.','Sans matériel à ronger suffisant, les dents peuvent devenir trop longues et causer des problèmes alimentaires.','Without enough gnawing material, teeth can grow too long and cause feeding problems.'),
(1,'tekst','Waarom hebben chinchilla''s een hoge volière of kooi nodig?','Pourquoi les chinchillas ont-ils besoin d''une grande volière verticale ?','Why do chinchillas need a tall aviary-style cage?',
 '["Ze springen graag en hebben verticale ruimte nodig om actief te zijn","Ze bewegen zich nooit veel","Een lage kooi is altijd beter","Hoogte is enkel decoratief"]'::jsonb,
 '["Ils aiment sauter et ont besoin d''espace vertical pour être actifs","Ils bougent très peu","Une cage basse est toujours préférable","La hauteur est purement décorative"]'::jsonb,
 '["They love jumping and need vertical space to stay active","They rarely move much","A low cage is always better","Height is purely decorative"]'::jsonb,
 0,'In het wild leven chinchilla''s in rotsachtige gebieden en springen ze graag van hoogte tot hoogte.','Dans la nature, les chinchillas vivent en zones rocheuses et aiment sauter d''un niveau à l''autre.','In the wild, chinchillas live in rocky areas and love jumping between different heights.'),
(2,'tekst','Waarom zijn chinchilla''s gevoelig voor warmte?','Pourquoi les chinchillas sont-ils sensibles à la chaleur ?','Why are chinchillas sensitive to heat?',
 '["Hun dichte vacht houdt warmte vast en ze kunnen snel oververhit raken","Ze hebben geen vacht","Ze houden juist van hoge temperaturen","Warmte heeft geen effect op hen"]'::jsonb,
 '["Leur pelage dense retient la chaleur et ils surchauffent rapidement","Ils n''ont pas de pelage","Ils aiment justement les températures élevées","La chaleur n''a aucun effet sur eux"]'::jsonb,
 '["Their dense fur traps heat and they can overheat quickly","They have no fur at all","They actually prefer high temperatures","Heat has no effect on them"]'::jsonb,
 0,'Chinchilla''s kunnen al bij temperaturen boven 25°C een hitteberoerte krijgen door hun dikke vacht.','Les chinchillas peuvent subir un coup de chaleur dès 25°C à cause de leur pelage épais.','Chinchillas can suffer heatstroke at temperatures above 25°C due to their thick fur.'),
(2,'tekst','Wat is de ideale voeding voor een chinchilla?','Quelle est l''alimentation idéale d''un chinchilla ?','What is the ideal diet for a chinchilla?',
 '["Voornamelijk hooi, aangevuld met speciale korrels","Voornamelijk vers fruit en groenten","Voornamelijk vlees en eiwitten","Enkel water en zaden"]'::jsonb,
 '["Principalement du foin, complété de granulés spéciaux","Principalement des fruits et légumes frais","Principalement de la viande et des protéines","Uniquement de l''eau et des graines"]'::jsonb,
 '["Mainly hay, supplemented with special pellets","Mainly fresh fruit and vegetables","Mainly meat and protein","Only water and seeds"]'::jsonb,
 0,'Hooi moet altijd onbeperkt beschikbaar zijn en vormt de basis van een gezond chinchilladieet.','Le foin doit toujours être disponible à volonté et constitue la base d''une alimentation saine.','Hay should always be available unlimited and forms the basis of a healthy chinchilla diet.'),
(2,'tekst','Waarom is een degoe ook gevoelig voor suiker in het dieet?','Pourquoi le dègue est-il aussi sensible au sucre dans son régime ?','Why is a degu also sensitive to sugar in its diet?',
 '["Degoes kunnen makkelijk diabetes ontwikkelen bij te veel suiker","Degoes hebben juist veel suiker nodig","Suiker heeft geen effect op degoes","Degoes eten enkel suiker"]'::jsonb,
 '["Les dègues peuvent facilement développer un diabète avec trop de sucre","Les dègues ont justement besoin de beaucoup de sucre","Le sucre n''a aucun effet sur les dègues","Les dègues ne mangent que du sucre"]'::jsonb,
 '["Degus can easily develop diabetes with too much sugar","Degus actually need a lot of sugar","Sugar has no effect on degus","Degus only eat sugar"]'::jsonb,
 0,'Degoes zijn zeer gevoelig voor suikers en kunnen net als mensen diabetes type 2 ontwikkelen.','Les dègues sont très sensibles au sucre et peuvent développer un diabète de type 2 comme les humains.','Degus are highly sensitive to sugar and can develop type 2 diabetes just like humans.'),
(2,'tekst','Waarom moet je chinchilla''s en degoes niet alleen houden?','Pourquoi ne pas garder chinchillas et dègues seuls ?','Why should you not keep chinchillas and degus alone?',
 '["Het zijn sociale dieren die het gezelschap van soortgenoten nodig hebben","Ze zijn van nature solitair en haten gezelschap","Groepen zorgen altijd voor stress","Ze kunnen niet samenleven met andere dieren"]'::jsonb,
 '["Ce sont des animaux sociaux qui ont besoin de la compagnie de congénères","Ils sont naturellement solitaires et détestent la compagnie","Les groupes causent toujours du stress","Ils ne peuvent jamais vivre ensemble"]'::jsonb,
 '["They are social animals that need the company of others of their species","They are naturally solitary and hate company","Groups always cause stress","They can never live together with others"]'::jsonb,
 0,'Zowel chinchilla''s als degoes leven in het wild in groepen en gedijen beter met soortgenoten.','Les chinchillas et dègues vivent en groupe dans la nature et s''épanouissent mieux avec des congénères.','Both chinchillas and degus live in groups in the wild and thrive better with companions.'),
(2,'tekst','Wat is een teken dat een chinchilla stress ervaart?','Quel est un signe de stress chez un chinchilla ?','What is a sign that a chinchilla is stressed?',
 '["Overmatig vachtplukken of verminderde eetlust","Normaal actief springgedrag","Rustig en tevreden slapen","Gezonde ontlasting"]'::jsonb,
 '["Arrachage excessif du pelage ou perte d''appétit","Comportement de saut normal et actif","Sommeil calme et satisfait","Selles saines"]'::jsonb,
 '["Excessive fur-chewing or reduced appetite","Normal active jumping behaviour","Calm, contented sleeping","Healthy droppings"]'::jsonb,
 0,'Vachtplukken bij chinchilla''s wijst vaak op stress, verveling of een medisch probleem.','L''arrachage du pelage chez les chinchillas indique souvent un stress, de l''ennui ou un problème médical.','Fur-chewing in chinchillas often points to stress, boredom or a medical issue.'),
(3,'tekst','Hoe voorkom je oververhitting bij een chinchilla in de zomer?','Comment éviter la surchauffe d''un chinchilla en été ?','How do you prevent a chinchilla from overheating in summer?',
 '["Zorg voor een koele kamer onder 21°C en voldoende schaduw","Zet de kooi in direct zonlicht","Geef enkel meer water zonder verder aan te passen","Verhoog juist de kamertemperatuur"]'::jsonb,
 '["Assurez une pièce fraîche sous 21°C et beaucoup d''ombre","Placez la cage en plein soleil direct","Donnez juste plus d''eau sans autre adaptation","Augmentez plutôt la température ambiante"]'::jsonb,
 '["Keep the room cool below 21°C and provide plenty of shade","Place the cage in direct sunlight","Just give more water without other adjustments","Actually increase the room temperature"]'::jsonb,
 0,'Chinchilla''s voelen zich het best bij temperaturen tussen 15 en 21°C dankzij hun dikke vacht.','Les chinchillas se sentent le mieux entre 15 et 21°C grâce à leur pelage épais.','Chinchillas do best at temperatures between 15 and 21°C due to their thick fur.'),
(3,'tekst','Wat moet je doen als een degoe agressief speelgedrag vertoont in de groep?','Que faire si un dègue montre un comportement de jeu agressif en groupe ?','What should you do if a degu shows aggressive play behaviour in the group?',
 '["De groepsdynamiek observeren en indien nodig dieren scheiden","Meteen alle dieren apart houden voor altijd","Niets doen, dit is normaal en onschadelijk","Enkel het voedsel verminderen"]'::jsonb,
 '["Observer la dynamique de groupe et séparer si nécessaire","Séparer immédiatement tous les animaux pour toujours","Ne rien faire, c''est normal et inoffensif","Réduire seulement la nourriture"]'::jsonb,
 '["Observe the group dynamics and separate animals if necessary","Immediately keep all animals apart forever","Do nothing, this is normal and harmless","Only reduce the food amount"]'::jsonb,
 0,'Aanhoudende agressie kan wijzen op rangorde-conflicten en moet opgevolgd worden om verwondingen te voorkomen.','Une agressivité persistante peut indiquer des conflits de hiérarchie et doit être surveillée pour éviter des blessures.','Persistent aggression can indicate hierarchy conflicts and should be monitored to prevent injuries.'),
(3,'tekst','Wat is belangrijk bij het aanbieden van knaaghout aan chinchilla''s?','Qu''est-ce qui est important en offrant du bois à ronger aux chinchillas ?','What is important when offering gnawing wood to chinchillas?',
 '["Gebruik onbehandeld, veilig hout zoals wilg of hazelaar","Gebruik behandeld geverfd hout voor kleur","Elk soort hout is altijd veilig","Chinchilla''s hebben geen hout nodig"]'::jsonb,
 '["Utilisez du bois non traité et sûr comme le saule ou le noisetier","Utilisez du bois traité et peint pour la couleur","Tout type de bois est toujours sûr","Les chinchillas n''ont pas besoin de bois"]'::jsonb,
 '["Use untreated, safe wood such as willow or hazel","Use treated, painted wood for colour","Any type of wood is always safe","Chinchillas do not need wood at all"]'::jsonb,
 0,'Behandeld of giftig hout kan schadelijke stoffen bevatten die gevaarlijk zijn bij inname.','Le bois traité ou toxique peut contenir des substances nocives dangereuses en cas d''ingestion.','Treated or toxic wood can contain harmful substances that are dangerous if ingested.'),
(3,'tekst','Wat moet je controleren als een chinchilla plots minder eet?','Que faut-il vérifier si un chinchilla mange soudainement moins ?','What should you check if a chinchilla suddenly eats less?',
 '["Raadpleeg snel een dierenarts, want dit kan wijzen op een ernstig probleem","Wacht enkele weken af zonder actie","Geef meteen meer suiker als stimulans","Dit is altijd volkomen normaal"]'::jsonb,
 '["Consultez rapidement un vétérinaire, cela peut indiquer un problème grave","Attendez plusieurs semaines sans agir","Donnez immédiatement plus de sucre comme stimulant","C''est toujours parfaitement normal"]'::jsonb,
 '["Consult a vet quickly, as this can indicate a serious problem","Wait several weeks without taking action","Immediately give more sugar as a stimulant","This is always completely normal"]'::jsonb,
 0,'Verminderde eetlust bij chinchilla''s kan snel leiden tot levensbedreigende darmproblemen (GI stasis).','Une baisse d''appétit chez les chinchillas peut rapidement mener à une stase digestive potentiellement mortelle.','Reduced appetite in chinchillas can quickly lead to life-threatening gut stasis (GI stasis).')
) AS v(module,vraag_type,nl,fr,en,onl,ofr,oen,ci,wnl,wfr,wen);

-- Fret
WITH a AS (
  INSERT INTO public.academies (diersoort_naam, diersoort_naam_fr, diersoort_naam_en, slug, badge_icon, vragen_per_test, slaag_grens, beschrijving, beschrijving_fr, beschrijving_en, categorie, prioriteit)
  VALUES ('Fret','Furet','Ferret','fret','fret',15,12,'Ontdek de eigenheden van fretten: geur, dieet, vrije uitloop en fretproof wonen.','Découvrez les particularités des furets : odeur, alimentation, temps libre et sécurisation du logement.','Discover the quirks of ferrets: scent, diet, free-roam time and ferret-proofing your home.','valkuilen',50)
  RETURNING id
)
INSERT INTO public.academy_vragen (academy_id, module, vraag_type, vraag_tekst, vraag_tekst_fr, vraag_tekst_en, opties, opties_fr, opties_en, correcte_optie_index, wist_je_dat, wist_je_dat_fr, wist_je_dat_en)
SELECT a.id, v.module, v.vraag_type, v.nl, v.fr, v.en, v.onl, v.ofr, v.oen, v.ci, v.wnl, v.wfr, v.wen
FROM a, (VALUES
(1,'tekst','Waarom hebben fretten een sterke, kenmerkende lichaamsgeur?','Pourquoi les furets ont-ils une odeur corporelle forte et caractéristique ?','Why do ferrets have a strong, distinctive body odour?',
 '["Ze hebben actieve talgklieren die musk-achtige geurstoffen produceren","Ze wassen zich nooit","Ze eten enkel visvoer","Alle fretten zijn geurloos"]'::jsonb,
 '["Ils ont des glandes sébacées actives produisant des substances musquées","Ils ne se lavent jamais","Ils mangent uniquement du poisson","Tous les furets sont inodores"]'::jsonb,
 '["They have active sebaceous glands producing musky scent compounds","They never wash themselves","They only eat fish-based food","All ferrets are odourless"]'::jsonb,
 0,'De geur van fretten wordt vaak sterker als ze niet gesteriliseerd of gecastreerd zijn.','L''odeur des furets est souvent plus forte s''ils ne sont pas stérilisés ou castrés.','Ferret odour is often stronger if they are not spayed or neutered.'),
(1,'tekst','Hoeveel vrije rondlooptijd buiten de kooi heeft een fret minimaal nodig per dag?','De combien de temps hors cage un furet a-t-il minimalement besoin par jour ?','How much free roaming time outside the cage does a ferret need minimally per day?',
 '["3 tot 4 uur","5 minuten","1 uur per week","Fretten hebben geen vrije tijd nodig"]'::jsonb,
 '["3 à 4 heures","5 minutes","1 heure par semaine","Les furets n''ont pas besoin de temps libre"]'::jsonb,
 '["3 to 4 hours","5 minutes","1 hour per week","Ferrets do not need free time at all"]'::jsonb,
 0,'Fretten zijn zeer actief en nieuwsgierig, en hebben dagelijks veel beweging en verkenning nodig.','Les furets sont très actifs et curieux, et ont besoin de beaucoup de mouvement et d''exploration chaque jour.','Ferrets are highly active and curious, needing plenty of movement and exploration daily.'),
(1,'tekst','Wat voor dieet heeft een fret nodig?','Quel type de régime un furet a-t-il besoin ?','What kind of diet does a ferret need?',
 '["Een 100 procent vleeseiwitrijk, carnivoor dieet","Voornamelijk groenten en fruit","Een vegetarisch dieet zonder vlees","Voornamelijk granen en zaden"]'::jsonb,
 '["Un régime carnivore, riche à 100 % en protéines animales","Principalement des légumes et fruits","Un régime végétarien sans viande","Principalement des céréales et graines"]'::jsonb,
 '["A 100 percent meat-protein-rich, carnivorous diet","Mainly vegetables and fruit","A vegetarian diet without meat","Mainly grains and seeds"]'::jsonb,
 0,'Fretten zijn strikte carnivoren en kunnen plantaardige koolhydraten en vezels slecht verteren.','Les furets sont des carnivores stricts et digèrent mal les glucides et fibres végétales.','Ferrets are strict carnivores and digest plant carbohydrates and fibre poorly.'),
(1,'tekst','Waarom moet je een huis fretproof maken?','Pourquoi faut-il sécuriser une maison pour un furet ?','Why do you need to ferret-proof a house?',
 '["Fretten kruipen in kleine spleten en kunnen vast komen te zitten of iets inslikken","Fretten blijven altijd op één plek zitten","Fretten kunnen niet klimmen of kruipen","Het is enkel voor de netheid van het huis"]'::jsonb,
 '["Les furets se faufilent dans de petits espaces et peuvent rester coincés ou avaler des objets","Les furets restent toujours au même endroit","Les furets ne peuvent ni grimper ni ramper","C''est uniquement pour la propreté de la maison"]'::jsonb,
 '["Ferrets squeeze into small gaps and can get stuck or swallow objects","Ferrets always stay in one place","Ferrets cannot climb or crawl","It is only for keeping the house tidy"]'::jsonb,
 0,'Fretten zijn berucht om het inslikken van rubber en schuim, wat een darmobstructie kan veroorzaken.','Les furets sont connus pour avaler du caoutchouc et de la mousse, causant des occlusions intestinales.','Ferrets are notorious for swallowing rubber and foam, which can cause intestinal blockages.'),
(1,'tekst','Hoeveel uur per dag slaapt een fret gemiddeld?','Combien d''heures par jour un furet dort-il en moyenne ?','How many hours a day does a ferret sleep on average?',
 '["Ongeveer 14 tot 18 uur","Slechts 2 uur","24 uur zonder onderbreking","Fretten slapen nooit"]'::jsonb,
 '["Environ 14 à 18 heures","Seulement 2 heures","24 heures sans interruption","Les furets ne dorment jamais"]'::jsonb,
 '["Around 14 to 18 hours","Only 2 hours","24 hours without a break","Ferrets never sleep"]'::jsonb,
 0,'Fretten slapen erg veel, maar zijn tijdens hun wakkere uren juist extreem energiek.','Les furets dorment énormément, mais sont extrêmement énergiques pendant leurs heures d''éveil.','Ferrets sleep a lot, but are extremely energetic during their waking hours.'),
(2,'tekst','Tegen welke ziekte moet een fret gevaccineerd worden, net zoals honden?','Contre quelle maladie un furet doit-il être vacciné, comme les chiens ?','Against which disease should a ferret be vaccinated, just like dogs?',
 '["Hondenziekte (canine distemper)","Vogelgriep","Salmonella","Botulisme"]'::jsonb,
 '["La maladie de Carré (distemper canin)","La grippe aviaire","La salmonelle","Le botulisme"]'::jsonb,
 '["Canine distemper","Avian flu","Salmonella","Botulism"]'::jsonb,
 0,'Hondenziekte is bijna altijd dodelijk voor fretten, daarom is vaccinatie erg belangrijk.','La maladie de Carré est presque toujours mortelle pour les furets, d''où l''importance de la vaccination.','Canine distemper is almost always fatal for ferrets, which is why vaccination is very important.'),
(2,'tekst','Waarom is castratie of sterilisatie vaak aangeraden bij fretten?','Pourquoi la castration ou la stérilisation est-elle souvent recommandée chez les furets ?','Why is neutering or spaying often recommended for ferrets?',
 '["Het vermindert geur en voorkomt gezondheidsrisico''s van een aanhoudende bronst","Het heeft geen enkel effect op fretten","Het is verplicht voor alle knaagdieren","Het maakt de vacht dikker"]'::jsonb,
 '["Cela réduit l''odeur et prévient les risques de santé liés aux chaleurs prolongées","Cela n''a aucun effet sur les furets","C''est obligatoire pour tous les rongeurs","Cela épaissit le pelage"]'::jsonb,
 '["It reduces odour and prevents health risks from prolonged heat","It has no effect on ferrets at all","It is mandatory for all rodents","It thickens the fur"]'::jsonb,
 0,'Onbehandelde vrouwelijke fretten kunnen ernstig ziek worden als hun bronstperiode te lang aanhoudt.','Les furettes non traitées peuvent tomber gravement malades si leurs chaleurs durent trop longtemps.','Untreated female ferrets can become severely ill if their heat cycle lasts too long.'),
(2,'tekst','Waarom moet je fretten geen hondenvoer geven?','Pourquoi ne pas donner de nourriture pour chien aux furets ?','Why should you not feed ferrets dog food?',
 '["Hondenvoer bevat te veel plantaardige vezels en te weinig dierlijk eiwit","Hondenvoer is perfect geschikt voor fretten","Fretten kunnen enkel hondenvoer verteren","Hondenvoer bevat geen calorieën"]'::jsonb,
 '["La nourriture pour chien contient trop de fibres végétales et trop peu de protéines animales","La nourriture pour chien convient parfaitement aux furets","Les furets ne peuvent digérer que la nourriture pour chien","La nourriture pour chien ne contient aucune calorie"]'::jsonb,
 '["Dog food contains too much plant fibre and too little animal protein","Dog food is perfectly suitable for ferrets","Ferrets can only digest dog food","Dog food contains no calories"]'::jsonb,
 0,'Fretten hebben speciaal frettenvoer of hoogwaardig kattenvoer nodig met veel dierlijk eiwit en vet.','Les furets ont besoin d''une nourriture spéciale pour furets ou de croquettes pour chat riches en protéines et graisses animales.','Ferrets need special ferret food or high-quality cat food rich in animal protein and fat.'),
(2,'tekst','Wat is een teken dat een fret gezondheidsproblemen kan hebben?','Quel est un signe que le furet pourrait avoir des problèmes de santé ?','What is a sign that a ferret may have health problems?',
 '["Plotse lusteloosheid, haaruitval of gewichtsverlies","Actief spelen en graven","Een glanzende, dichte vacht","Normale eetlust"]'::jsonb,
 '["Léthargie soudaine, perte de poils ou de poids","Jouer et creuser activement","Un pelage brillant et dense","Un appétit normal"]'::jsonb,
 '["Sudden lethargy, hair loss or weight loss","Actively playing and digging","A shiny, dense coat","Normal appetite"]'::jsonb,
 0,'Fretten kunnen gevoelig zijn voor bijnierziekte en insulinoom, die vaak beginnen met subtiele signalen.','Les furets peuvent être sensibles à la maladie surrénalienne et à l''insulinome, qui débutent souvent par des signes subtils.','Ferrets can be prone to adrenal disease and insulinoma, which often start with subtle signs.'),
(2,'tekst','Waarom moeten fretten regelmatig hun nagels laten knippen?','Pourquoi les furets doivent-ils se faire couper les griffes régulièrement ?','Why should ferrets have their nails trimmed regularly?',
 '["Te lange nagels kunnen breken of het lopen bemoeilijken","Nagels groeien nooit bij fretten","Het is enkel voor esthetische redenen","Fretten hebben geen nagels"]'::jsonb,
 '["Des griffes trop longues peuvent se casser ou gêner la marche","Les griffes ne poussent jamais chez les furets","C''est uniquement pour des raisons esthétiques","Les furets n''ont pas de griffes"]'::jsonb,
 '["Overly long nails can break or make walking difficult","Nails never grow in ferrets","It is only for aesthetic reasons","Ferrets do not have nails"]'::jsonb,
 0,'Fretten graven van nature veel, wat normaal helpt de nagels af te slijten, maar binnenshuis is bijknippen vaak nodig.','Les furets creusent naturellement beaucoup, ce qui use les griffes, mais à l''intérieur, une coupe régulière reste souvent nécessaire.','Ferrets naturally dig a lot, which helps wear nails down, but indoors regular trimming is often still needed.'),
(3,'tekst','Wat is een veilige manier om een fretkooi in te richten?','Comment aménager une cage à furet en toute sécurité ?','What is a safe way to set up a ferret cage?',
 '["Met meerdere niveaus, een hangmat en veilig speelgoed zonder kleine onderdelen","Met enkel een kale bodem zonder verrijking","Met kleine speeltjes die makkelijk ingeslikt kunnen worden","Zonder enige slaapplaats"]'::jsonb,
 '["Avec plusieurs niveaux, un hamac et des jouets sûrs sans petites pièces","Avec seulement un sol nu sans enrichissement","Avec de petits jouets facilement avalables","Sans aucun endroit pour dormir"]'::jsonb,
 '["With multiple levels, a hammock and safe toys without small parts","With just a bare floor and no enrichment","With small toys that are easy to swallow","Without any sleeping area"]'::jsonb,
 0,'Fretten houden van klimmen en nestelen, dus een verrijkte, veilige kooi bevordert hun welzijn.','Les furets aiment grimper et nicher, une cage enrichie et sûre favorise leur bien-être.','Ferrets love to climb and nest, so an enriched, safe cage promotes their wellbeing.'),
(3,'tekst','Wat moet je doen voor je een fret vrij door het huis laat lopen?','Que faire avant de laisser un furet se promener librement dans la maison ?','What should you do before letting a ferret roam freely in the house?',
 '["Alle kleine gaten, giftige planten en gevaarlijke voorwerpen wegnemen of afsluiten","Niets, fretten zijn altijd veilig overal","Enkel de deuren op slot doen","De verwarming uitzetten"]'::jsonb,
 '["Retirer ou fermer tous les petits trous, plantes toxiques et objets dangereux","Rien, les furets sont toujours en sécurité partout","Uniquement verrouiller les portes","Éteindre le chauffage"]'::jsonb,
 '["Remove or block all small gaps, toxic plants and dangerous objects","Nothing, ferrets are always safe everywhere","Only lock the doors","Turn off the heating"]'::jsonb,
 0,'Fretten zijn extreem nieuwsgierig en kunnen zichzelf in gevaar brengen zonder een fretproof omgeving.','Les furets sont extrêmement curieux et peuvent se mettre en danger sans un environnement sécurisé.','Ferrets are extremely curious and can put themselves in danger without a ferret-proofed environment.'),
(3,'tekst','Waarom is spelen met andere fretten sociaal belangrijk?','Pourquoi jouer avec d''autres furets est-il socialement important ?','Why is playing with other ferrets socially important?',
 '["Fretten zijn sociale dieren die vaak beter gedijen met soortgenoten","Fretten haten altijd gezelschap van andere fretten","Sociaal contact is nooit nodig","Fretten spelen enkel alleen"]'::jsonb,
 '["Les furets sont des animaux sociaux qui s''épanouissent souvent mieux avec des congénères","Les furets détestent toujours la compagnie d''autres furets","Le contact social n''est jamais nécessaire","Les furets ne jouent que seuls"]'::jsonb,
 '["Ferrets are social animals that often thrive better with companions","Ferrets always hate the company of other ferrets","Social contact is never necessary","Ferrets only play alone"]'::jsonb,
 0,'Fretten leven van nature vaak in groepen en spelen graag stoeigevechten met soortgenoten.','Les furets vivent souvent naturellement en groupe et aiment les jeux de bagarre avec leurs congénères.','Ferrets often naturally live in groups and enjoy rough-and-tumble play with each other.'),
(3,'tekst','Wat moet je doen als een fret plots iets kleins heeft ingeslikt?','Que faire si un furet vient d''avaler un petit objet ?','What should you do if a ferret has just swallowed a small object?',
 '["Onmiddellijk een dierenarts raadplegen wegens risico op darmobstructie","Afwachten en niets doen","Enkel meer water geven","Het voedsel verminderen voor een week"]'::jsonb,
 '["Consulter immédiatement un vétérinaire à cause du risque d''occlusion intestinale","Attendre et ne rien faire","Donner seulement plus d''eau","Réduire la nourriture pendant une semaine"]'::jsonb,
 '["Consult a vet immediately due to the risk of intestinal blockage","Wait and do nothing","Just give more water","Reduce food for a week"]'::jsonb,
 0,'Fretten kunnen snel een levensbedreigende darmobstructie ontwikkelen na het inslikken van vreemde voorwerpen.','Les furets peuvent rapidement développer une occlusion intestinale mortelle après avoir avalé un corps étranger.','Ferrets can quickly develop a life-threatening intestinal blockage after swallowing foreign objects.')
) AS v(module,vraag_type,nl,fr,en,onl,ofr,oen,ci,wnl,wfr,wen);

-- Agapornis (dwergpapegaai)
WITH a AS (
  INSERT INTO public.academies (diersoort_naam, diersoort_naam_fr, diersoort_naam_en, slug, badge_icon, vragen_per_test, slaag_grens, beschrijving, beschrijving_fr, beschrijving_en, categorie, prioriteit)
  VALUES ('Agapornis (dwergpapegaai)','Inséparable','Lovebird','agapornis','agapornis',15,12,'Leer over geluid, gedrag, sloopneiging en verzorging van agapornissen (dwergpapegaaien).','Découvrez le bruit, le comportement, la tendance à détruire et les soins des inséparables.','Learn about the noise, behaviour, destructive tendencies and care of lovebirds.','valkuilen',50)
  RETURNING id
)
INSERT INTO public.academy_vragen (academy_id, module, vraag_type, vraag_tekst, vraag_tekst_fr, vraag_tekst_en, opties, opties_fr, opties_en, correcte_optie_index, wist_je_dat, wist_je_dat_fr, wist_je_dat_en)
SELECT a.id, v.module, v.vraag_type, v.nl, v.fr, v.en, v.onl, v.ofr, v.oen, v.ci, v.wnl, v.wfr, v.wen
FROM a, (VALUES
(1,'tekst','Waarom kunnen agapornissen problematisch zijn in een appartement?','Pourquoi les inséparables peuvent-ils poser problème en appartement ?','Why can lovebirds be problematic in an apartment?',
 '["Ze kunnen extreem hard en doordringend krijsen","Ze maken nooit enig geluid","Ze zijn te groot voor een appartement","Ze hebben speciale vergunningen nodig"]'::jsonb,
 '["Ils peuvent crier de façon extrêmement forte et perçante","Ils ne font jamais aucun bruit","Ils sont trop grands pour un appartement","Ils nécessitent des permis spéciaux"]'::jsonb,
 '["They can screech extremely loudly and piercingly","They never make any noise at all","They are too large for an apartment","They require special permits"]'::jsonb,
 0,'Ondanks hun kleine formaat kunnen agapornissen geluidsniveaus produceren die buren kunnen storen.','Malgré leur petite taille, les inséparables peuvent produire des niveaux sonores qui dérangent les voisins.','Despite their small size, lovebirds can produce sound levels that can disturb neighbours.'),
(1,'tekst','Waarom bijten agapornissen soms behoorlijk hard?','Pourquoi les inséparables mordent-ils parfois assez fort ?','Why do lovebirds sometimes bite quite hard?',
 '["Ze hebben een sterke snavel en kunnen territoriaal of gestrest gedrag vertonen","Ze hebben geen snavelkracht","Ze bijten nooit onder enige omstandigheid","Bijten komt enkel voor bij zieke vogels"]'::jsonb,
 '["Ils ont un bec puissant et peuvent montrer un comportement territorial ou stressé","Ils n''ont aucune force au bec","Ils ne mordent jamais en aucune circonstance","Mordre n''arrive que chez les oiseaux malades"]'::jsonb,
 '["They have a strong beak and can show territorial or stressed behaviour","They have no beak strength at all","They never bite under any circumstance","Biting only happens in sick birds"]'::jsonb,
 0,'Agapornissen kunnen ondanks hun kleine formaat verrassend pijnlijk bijten wanneer ze zich bedreigd voelen.','Malgré leur petite taille, les inséparables peuvent mordre étonnamment fort quand ils se sentent menacés.','Despite their small size, lovebirds can bite surprisingly hard when they feel threatened.'),
(1,'tekst','Waarom kunnen agapornissen veel schade aanrichten aan meubels en kabels?','Pourquoi les inséparables peuvent-ils beaucoup abîmer meubles et câbles ?','Why can lovebirds cause a lot of damage to furniture and cables?',
 '["Ze hebben een natuurlijke drang om te knagen en te ontdekken met hun snavel","Ze doen dit enkel als ze honger hebben","Agapornissen knagen nooit aan iets","Het is enkel gedrag bij jonge vogels"]'::jsonb,
 '["Ils ont un besoin naturel de ronger et d''explorer avec leur bec","Ils ne font cela que lorsqu''ils ont faim","Les inséparables ne rongent jamais rien","C''est un comportement uniquement chez les jeunes"]'::jsonb,
 '["They have a natural urge to gnaw and explore with their beak","They only do this when hungry","Lovebirds never gnaw on anything","It is behaviour only seen in young birds"]'::jsonb,
 0,'Onbewaakte agapornissen kunnen snel houtwerk, boeken en elektriciteitskabels beschadigen door hun sterke snavel.','Sans surveillance, les inséparables peuvent rapidement endommager le bois, les livres et les câbles électriques avec leur bec puissant.','Unsupervised lovebirds can quickly damage woodwork, books and electrical cables with their strong beak.'),
(1,'tekst','Hoe oud kan een agapornis worden bij goede verzorging?','Quel âge un inséparable peut-il atteindre avec de bons soins ?','How old can a lovebird get with good care?',
 '["Tot wel 15 jaar of meer","Slechts 1 tot 2 jaar","Enkele maanden","Meer dan 50 jaar"]'::jsonb,
 '["Jusqu''à 15 ans ou plus","Seulement 1 à 2 ans","Quelques mois","Plus de 50 ans"]'::jsonb,
 '["Up to 15 years or more","Only 1 to 2 years","A few months","More than 50 years"]'::jsonb,
 0,'Agapornissen worden vaak onderschat qua levensduur en vragen een langdurige zorgverbintenis.','La durée de vie des inséparables est souvent sous-estimée et exige un engagement de soins à long terme.','Lovebird lifespans are often underestimated and require a long-term care commitment.'),
(1,'tekst','Waarom hebben agapornissen dagelijks vliegruimte buiten de kooi nodig?','Pourquoi les inséparables ont-ils besoin d''espace de vol quotidien hors de la cage ?','Why do lovebirds need daily flying space outside the cage?',
 '["Vliegen is essentieel gedrag voor hun fysieke en mentale gezondheid","Agapornissen kunnen niet vliegen","Ze hebben nooit ruimte buiten de kooi nodig","Vliegen is enkel nodig bij jonge vogels"]'::jsonb,
 '["Voler est un comportement essentiel pour leur santé physique et mentale","Les inséparables ne peuvent pas voler","Ils n''ont jamais besoin d''espace hors de la cage","Voler n''est nécessaire que chez les jeunes"]'::jsonb,
 '["Flying is essential behaviour for their physical and mental health","Lovebirds cannot fly at all","They never need space outside the cage","Flying is only needed in young birds"]'::jsonb,
 0,'Zonder voldoende vliegruimte kunnen agapornissen last krijgen van obesitas en gedragsproblemen.','Sans espace de vol suffisant, les inséparables peuvent souffrir d''obésité et de problèmes de comportement.','Without enough flying space, lovebirds can suffer from obesity and behavioural problems.'),
(2,'tekst','Wat is een gebalanceerd dieet voor een agapornis?','Quelle est une alimentation équilibrée pour un inséparable ?','What is a balanced diet for a lovebird?',
 '["Een basis van pellets aangevuld met groenten en beperkt zaad","Enkel zonnebloemzaad de hele dag","Enkel suikerhoudend fruit","Enkel water zonder vast voedsel"]'::jsonb,
 '["Une base de granulés complétée de légumes et peu de graines","Uniquement des graines de tournesol toute la journée","Uniquement des fruits sucrés","Uniquement de l''eau sans nourriture solide"]'::jsonb,
 '["A base of pellets supplemented with vegetables and limited seed","Only sunflower seeds all day","Only sugary fruit","Only water with no solid food"]'::jsonb,
 0,'Een zaaddieet alleen is te vet en te eenzijdig, pellets bieden een completer voedingspatroon.','Un régime uniquement de graines est trop gras et unilatéral, les granulés offrent une alimentation plus complète.','A seed-only diet is too fatty and one-sided; pellets provide a more complete nutritional pattern.'),
(2,'tekst','Waarom is pure zaadvoeding minder geschikt als hoofdvoeding?','Pourquoi une alimentation uniquement de graines est-elle moins adaptée comme régime principal ?','Why is a pure seed diet less suitable as the main food?',
 '["Zaad is te vetrijk en mist essentiële vitamines en mineralen","Zaad bevat alle voedingsstoffen die een vogel nodig heeft","Zaad is giftig voor agapornissen","Vogels kunnen zaad niet verteren"]'::jsonb,
 '["Les graines sont trop grasses et manquent de vitamines et minéraux essentiels","Les graines contiennent tous les nutriments dont l''oiseau a besoin","Les graines sont toxiques pour les inséparables","Les oiseaux ne peuvent pas digérer les graines"]'::jsonb,
 '["Seed is too high in fat and lacks essential vitamins and minerals","Seed contains all the nutrients a bird needs","Seed is toxic to lovebirds","Birds cannot digest seed at all"]'::jsonb,
 0,'Vogels op een zuiver zaaddieet kunnen tekorten ontwikkelen aan vitamine A en calcium.','Les oiseaux nourris exclusivement de graines peuvent développer des carences en vitamine A et calcium.','Birds on a pure seed diet can develop deficiencies in vitamin A and calcium.'),
(2,'tekst','Wat is een teken van verveling of stress bij een agapornis?','Quel est un signe d''ennui ou de stress chez un inséparable ?','What is a sign of boredom or stress in a lovebird?',
 '["Overmatig veren plukken of luid, aanhoudend krijsen","Rustig en tevreden op de stok zitten","Normaal eetgedrag en glanzend verenkleed","Actief spelen met speeltjes"]'::jsonb,
 '["Arrachage excessif des plumes ou cris forts et persistants","Rester calme et satisfait sur le perchoir","Comportement alimentaire normal et plumage brillant","Jouer activement avec des jouets"]'::jsonb,
 '["Excessive feather-plucking or loud, persistent screeching","Sitting calmly and content on the perch","Normal eating behaviour and glossy plumage","Actively playing with toys"]'::jsonb,
 0,'Verveling door te weinig stimulatie is een veelvoorkomende oorzaak van veren plukken bij papegaaiachtigen.','L''ennui dû à un manque de stimulation est une cause fréquente d''arrachage de plumes chez les perroquets.','Boredom from lack of stimulation is a common cause of feather-plucking in parrot species.'),
(2,'tekst','Waarom is speelgoed en verrijking belangrijk voor agapornissen?','Pourquoi jouets et enrichissement sont-ils importants pour les inséparables ?','Why are toys and enrichment important for lovebirds?',
 '["Ze zijn intelligent en hebben mentale stimulatie nodig om gezond gedrag te behouden","Agapornissen hebben geen enkele interesse in speelgoed","Speelgoed is enkel decoratief voor de kooi","Ze hebben geen intelligentie nodig te stimuleren"]'::jsonb,
 '["Ils sont intelligents et ont besoin de stimulation mentale pour un comportement sain","Les inséparables n''ont aucun intérêt pour les jouets","Les jouets sont purement décoratifs pour la cage","Ils n''ont pas besoin de stimulation intellectuelle"]'::jsonb,
 '["They are intelligent and need mental stimulation to maintain healthy behaviour","Lovebirds have no interest in toys at all","Toys are purely decorative for the cage","They do not need any intellectual stimulation"]'::jsonb,
 0,'Zonder verrijking kunnen agapornissen destructief, luidruchtig of zelfs zelfbeschadigend gedrag ontwikkelen.','Sans enrichissement, les inséparables peuvent développer un comportement destructeur, bruyant voire autodestructeur.','Without enrichment, lovebirds can develop destructive, noisy or even self-harming behaviour.'),
(2,'tekst','Waarom houden agapornissen best in paren of groepen?','Pourquoi vaut-il mieux garder les inséparables en paires ou en groupes ?','Why is it best to keep lovebirds in pairs or groups?',
 '["Ze zijn zeer sociale vogels die eenzaamheid slecht verdragen","Agapornissen zijn strikt solitaire dieren","Groepen veroorzaken altijd meer stress","Ze kunnen niet samenleven met andere agapornissen"]'::jsonb,
 '["Ce sont des oiseaux très sociaux qui supportent mal la solitude","Les inséparables sont des animaux strictement solitaires","Les groupes causent toujours plus de stress","Ils ne peuvent pas cohabiter avec d''autres inséparables"]'::jsonb,
 '["They are highly social birds that tolerate loneliness poorly","Lovebirds are strictly solitary animals","Groups always cause more stress","They cannot live together with other lovebirds"]'::jsonb,
 0,'De naam "agapornis" (onafscheidelijken) verwijst naar hun sterke sociale binding met een partner of groep.','Le nom « inséparable » fait référence à leur fort lien social avec un partenaire ou un groupe.','The name "lovebird" refers to their strong social bond with a partner or group.'),
(3,'tekst','Wat moet je doen om schade aan meubels en kabels te voorkomen?','Que faire pour éviter les dégâts aux meubles et câbles ?','What should you do to prevent damage to furniture and cables?',
 '["Toezicht houden tijdens vrije vliegtijd en veilig knaagspeelgoed aanbieden","Niets, agapornissen richten nooit schade aan","Kabels altijd onbedekt laten liggen","De vogel de hele dag alleen laten rondvliegen zonder toezicht"]'::jsonb,
 '["Superviser pendant le temps de vol libre et offrir des jouets à ronger sûrs","Rien, les inséparables ne causent jamais de dégâts","Toujours laisser les câbles à découvert","Laisser l''oiseau voler seul toute la journée sans surveillance"]'::jsonb,
 '["Supervise during free-flight time and offer safe gnawing toys","Nothing, lovebirds never cause any damage","Always leave cables uncovered","Let the bird fly around alone all day unsupervised"]'::jsonb,
 0,'Toezicht en afleiding met veilig speelgoed voorkomen dat agapornissen zich richten op gevaarlijke voorwerpen.','La surveillance et des jouets sûrs évitent que les inséparables ne s''attaquent à des objets dangereux.','Supervision and distraction with safe toys prevent lovebirds from targeting dangerous objects.'),
(3,'tekst','Hoe kun je overmatig krijsen bij een agapornis verminderen?','Comment réduire les cris excessifs d''un inséparable ?','How can you reduce excessive screeching in a lovebird?',
 '["Voldoende sociale interactie, uitdaging en een regelmatig dagritme bieden","De vogel volledig negeren de hele dag","De kooi permanent afdekken","Enkel meer zaad geven"]'::jsonb,
 '["Offrir suffisamment d''interaction sociale, de défis et un rythme quotidien régulier","Ignorer complètement l''oiseau toute la journée","Couvrir la cage en permanence","Donner uniquement plus de graines"]'::jsonb,
 '["Providing enough social interaction, challenge and a regular daily routine","Completely ignoring the bird all day","Permanently covering the cage","Only giving more seed"]'::jsonb,
 0,'Overmatig krijsen wordt vaak veroorzaakt door verveling, aandacht zoeken of een onregelmatig ritme.','Les cris excessifs sont souvent causés par l''ennui, la recherche d''attention ou un rythme irrégulier.','Excessive screeching is often caused by boredom, attention-seeking or an irregular routine.'),
(3,'tekst','Wat is belangrijk bij het introduceren van een nieuwe agapornis in een bestaande groep?','Qu''est-ce qui est important lors de l''introduction d''un nouvel inséparable dans un groupe ?','What is important when introducing a new lovebird into an existing group?',
 '["Geleidelijke, gecontroleerde kennismaking om agressie te vermijden","Meteen samen in dezelfde kooi zetten zonder observatie","Nooit nieuwe vogels toevoegen aan een groep","Agapornissen accepteren altijd direct elkaar"]'::jsonb,
 '["Une présentation graduelle et contrôlée pour éviter l''agressivité","Les mettre immédiatement ensemble dans la même cage sans observation","Ne jamais ajouter de nouveaux oiseaux à un groupe","Les inséparables s''acceptent toujours immédiatement"]'::jsonb,
 '["A gradual, controlled introduction to avoid aggression","Immediately putting them together in the same cage without observation","Never adding new birds to a group","Lovebirds always accept each other immediately"]'::jsonb,
 0,'Agapornissen kunnen territoriaal en zelfs agressief zijn tegenover onbekende soortgenoten bij te snelle introductie.','Les inséparables peuvent être territoriaux voire agressifs envers des congénères inconnus si l''introduction est trop rapide.','Lovebirds can be territorial and even aggressive towards unfamiliar peers if introduced too quickly.'),
(3,'tekst','Waarom is een vaste dag- en nachtcyclus belangrijk voor agapornissen?','Pourquoi un cycle jour-nuit régulier est-il important pour les inséparables ?','Why is a consistent day-night cycle important for lovebirds?',
 '["Onregelmatige slaap kan stress, gedragsproblemen en gezondheidsklachten veroorzaken","Agapornissen hebben geen slaapschema nodig","Licht heeft geen invloed op hun gedrag","Ze slapen best de hele dag door met het licht aan"]'::jsonb,
 '["Un sommeil irrégulier peut causer stress, problèmes de comportement et de santé","Les inséparables n''ont pas besoin d''horaire de sommeil","La lumière n''a aucune influence sur leur comportement","Ils dorment mieux avec la lumière allumée toute la journée"]'::jsonb,
 '["Irregular sleep can cause stress, behavioural problems and health issues","Lovebirds do not need a sleep schedule at all","Light has no influence on their behaviour","They sleep best with the light on all day"]'::jsonb,
 0,'Agapornissen hebben idealiter 10 tot 12 uur ononderbroken duisternis en rust nodig per nacht.','Les inséparables ont idéalement besoin de 10 à 12 heures d''obscurité et de repos ininterrompus par nuit.','Lovebirds ideally need 10 to 12 hours of uninterrupted darkness and rest per night.')
) AS v(module,vraag_type,nl,fr,en,onl,ofr,oen,ci,wnl,wfr,wen);
