-- Minivarken
WITH a AS (
  INSERT INTO public.academies (diersoort_naam, diersoort_naam_fr, diersoort_naam_en, slug, badge_icon, vragen_per_test, slaag_grens, beschrijving, beschrijving_fr, beschrijving_en, categorie, prioriteit)
  VALUES ('Minivarken','Mini-cochon','Mini pig','minivarken','minivarken',15,12,'Ontdek de waarheid achter de ''teacup pig''-mythe en leer wat een minivarken echt nodig heeft.','Découvrez la vérité derrière le mythe du ''mini-cochon miniature'' et ce dont il a vraiment besoin.','Discover the truth behind the ''teacup pig'' myth and what a mini pig really needs.','valkuilen',50)
  RETURNING id
)
INSERT INTO public.academy_vragen (academy_id, module, vraag_type, vraag_tekst, vraag_tekst_fr, vraag_tekst_en, opties, opties_fr, opties_en, correcte_optie_index, wist_je_dat, wist_je_dat_fr, wist_je_dat_en)
SELECT a.id, v.module, v.vraag_type, v.nl, v.fr, v.en, v.onl, v.ofr, v.oen, v.ci, v.wnl, v.wfr, v.wen
FROM a, (VALUES
(1,'tekst','Wat klopt er niet aan de term ''teacup pig''?','Qu''est-ce qui est faux dans le terme ''mini-cochon miniature'' ?','What is wrong with the term ''teacup pig''?',
 '["Elk varken groeit uiteindelijk veel groter dan een kopje suggereert","Het is een officiële, erkende rasnaam","Teacup pigs blijven levenslang zo klein","Er bestaat een gecertificeerd mini-ras"]'::jsonb,
 '["Chaque cochon grandit bien plus qu''une tasse ne le suggère","C''est un nom de race officiel et reconnu","Les mini-cochons restent petits toute leur vie","Il existe une race miniature certifiée"]'::jsonb,
 '["Every pig grows far larger than a teacup suggests","It is an official, recognised breed name","Teacup pigs stay that small for life","There is a certified miniature breed"]'::jsonb,
 0,'''Teacup pig'' is een verkoopterm, geen ras; jonge biggetjes worden vaak ondervoed getoond om klein te lijken.','''Mini-cochon miniature'' est un terme marketing, pas une race; les porcelets sont souvent sous-alimentés pour paraître petits.','''Teacup pig'' is a marketing term, not a breed; piglets are often shown underfed to look small.'),
(1,'tekst','Hoeveel weegt een volwassen zogenaamd ''miniatuur''varken doorgaans?','Combien pèse en général un ''mini-cochon'' adulte ?','How much does an adult so-called ''mini'' pig typically weigh?',
 '["Meestal 50 tot meer dan 100 kg","Altijd minder dan 5 kg","Nooit meer dan 10 kg","Precies 2 kg, zoals een kat"]'::jsonb,
 '["Généralement entre 50 et plus de 100 kg","Toujours moins de 5 kg","Jamais plus de 10 kg","Exactement 2 kg, comme un chat"]'::jsonb,
 '["Usually 50 to over 100 kg","Always less than 5 kg","Never more than 10 kg","Exactly 2 kg, like a cat"]'::jsonb,
 0,'Zelfs ''mini''-rassen zoals de Vietnamese buikvarkens wegen als volwassene vaak 50-100 kg of meer.','Même les races ''mini'' comme le cochon ventru vietnamien pèsent souvent 50-100 kg adultes, voire plus.','Even ''mini'' breeds like the Vietnamese potbellied pig often weigh 50-100 kg or more as adults.'),
(1,'tekst','Waarom worden verkopers soms oneerlijk over de eindgrootte van minivarkens?','Pourquoi certains vendeurs sont-ils malhonnêtes sur la taille finale des mini-cochons ?','Why are some sellers dishonest about the final size of mini pigs?',
 '["Om de verkoop te bevorderen ten koste van het dierenwelzijn","Omdat wetenschappers dat aanbevelen","Omdat het altijd waar is wat ze zeggen","Om het varken te beschermen"]'::jsonb,
 '["Pour favoriser la vente au détriment du bien-être animal","Parce que les scientifiques le recommandent","Parce que c''est toujours vrai","Pour protéger le cochon"]'::jsonb,
 '["To boost sales at the expense of animal welfare","Because scientists recommend it","Because what they say is always true","To protect the pig"]'::jsonb,
 0,'Veel ''mini''varkens belanden in asielen zodra eigenaars beseffen hoe groot en zwaar ze worden.','De nombreux ''mini-cochons'' finissent en refuge quand les propriétaires réalisent leur taille réelle.','Many ''mini'' pigs end up in shelters once owners realise how large and heavy they become.'),
(1,'tekst','Hoe oud kan een minivarken worden?','Quel âge un mini-cochon peut-il atteindre ?','How old can a mini pig get?',
 '["12 tot 20 jaar of meer","Slechts 2 tot 3 jaar","Nooit ouder dan 1 jaar","Altijd exact 5 jaar"]'::jsonb,
 '["12 à 20 ans ou plus","Seulement 2 à 3 ans","Jamais plus d''un an","Toujours exactement 5 ans"]'::jsonb,
 '["12 to 20 years or more","Only 2 to 3 years","Never older than 1 year","Always exactly 5 years"]'::jsonb,
 0,'Minivarkens kunnen wel 15 tot 20 jaar leven, dit is dus een langdurige verantwoordelijkheid.','Les mini-cochons peuvent vivre 15 à 20 ans, c''est donc un engagement de longue durée.','Mini pigs can live 15 to 20 years, making this a long-term commitment.'),
(1,'tekst','Waarom is impulsaankoop van een minivarken riskant?','Pourquoi l''achat impulsif d''un mini-cochon est-il risqué ?','Why is impulse-buying a mini pig risky?',
 '["Omdat de werkelijke grootte, levensduur en behoeften vaak onderschat worden","Omdat minivarkens goedkoop in onderhoud zijn","Omdat ze nooit ziek worden","Omdat ze zichzelf verzorgen"]'::jsonb,
 '["Car la taille réelle, la durée de vie et les besoins sont souvent sous-estimés","Car les mini-cochons coûtent peu d''entretien","Car ils ne tombent jamais malades","Car ils s''occupent d''eux-mêmes"]'::jsonb,
 '["Because real size, lifespan and needs are often underestimated","Because mini pigs are cheap to keep","Because they never get sick","Because they take care of themselves"]'::jsonb,
 0,'Grondig onderzoek vooraf voorkomt dat eigenaars overweldigd raken door de realiteit van varkenshouderij.','Une recherche approfondie évite d''être dépassé par la réalité de l''élevage porcin.','Thorough research beforehand prevents owners being overwhelmed by the reality of pig keeping.'),
(2,'tekst','Waarom hebben varkens wroetruimte nodig?','Pourquoi les cochons ont-ils besoin d''un espace pour fouiller ?','Why do pigs need rooting space?',
 '["Wroeten is natuurlijk gedrag om voedsel te zoeken en stress te verminderen","Varkens wroeten nooit","Het is enkel destructief zonder functie","Ze doen dit alleen als ze ziek zijn"]'::jsonb,
 '["Fouiller est un comportement naturel pour chercher de la nourriture et réduire le stress","Les cochons ne fouillent jamais","C''est juste destructeur sans fonction","Ils ne font cela que lorsqu''ils sont malades"]'::jsonb,
 '["Rooting is natural behaviour to find food and reduce stress","Pigs never root","It is purely destructive with no purpose","They only do this when ill"]'::jsonb,
 0,'Varkens gebruiken hun snuit om de grond om te woelen, dit is essentieel natuurlijk gedrag.','Les cochons utilisent leur groin pour fouiller le sol, un comportement naturel essentiel.','Pigs use their snout to dig up the ground; this is essential natural behaviour.'),
(2,'tekst','Hoeveel buitenruimte heeft een minivarken minimaal nodig?','Quel espace extérieur minimum un mini-cochon nécessite-t-il ?','How much outdoor space does a mini pig minimally need?',
 '["Een ruime, afgesloten tuin met wroetgrond, geen appartement","Geen enkele, een varken kan altijd binnen blijven","Een klein balkon volstaat ruimschoots","Een kattenbak is voldoende"]'::jsonb,
 '["Un grand jardin clôturé avec zone à fouiller, pas un appartement","Aucun, un cochon peut toujours rester à l''intérieur","Un petit balcon suffit largement","Une litière suffit"]'::jsonb,
 '["A spacious, fenced garden with rooting ground, not an apartment","None, a pig can always stay indoors","A small balcony is more than enough","A litter box is sufficient"]'::jsonb,
 0,'Een varken zonder tuin en wroetgrond ontwikkelt vaak stressgedrag en frustratie.','Un cochon sans jardin ni zone à fouiller développe souvent du stress et de la frustration.','A pig without a garden and rooting ground often develops stress and frustration.'),
(2,'tekst','Wat hoort bij een gezond dieet voor een minivarken?','Qu''est-ce qui compose une alimentation saine pour un mini-cochon ?','What belongs in a healthy mini pig diet?',
 '["Speciaal varkensvoer, groenten en beperkt fruit, geen overvoeren","Enkel snoep en chips","Onbeperkt brood elke dag","Onbeperkt hondenvoer"]'::jsonb,
 '["Aliment spécial cochon, légumes et fruits limités, pas de suralimentation","Uniquement des bonbons et chips","Du pain illimité chaque jour","De la nourriture pour chien à volonté"]'::jsonb,
 '["Special pig feed, vegetables and limited fruit, no overfeeding","Only candy and chips","Unlimited bread every day","Unlimited dog food"]'::jsonb,
 0,'Overvoeren leidt snel tot obesitas, wat gewrichten en gezondheid van varkens ernstig belast.','La suralimentation cause rapidement l''obésité, nuisant gravement aux articulations et à la santé.','Overfeeding quickly leads to obesity, seriously straining a pig''s joints and health.'),
(2,'tekst','Wat is verplicht bij het houden van een varken in veel Europese landen?','Qu''est-ce qui est obligatoire pour détenir un cochon dans de nombreux pays européens ?','What is required when keeping a pig in many European countries?',
 '["Registratie bij de bevoegde overheid en identificatie van het dier","Niets, varkens zijn volledig vrij van regels","Enkel een naam kiezen","Een jaarlijkse foto insturen"]'::jsonb,
 '["Enregistrement auprès des autorités compétentes et identification de l''animal","Rien, les cochons ne sont soumis à aucune règle","Choisir simplement un nom","Envoyer une photo chaque année"]'::jsonb,
 '["Registration with the competent authority and identification of the animal","Nothing, pigs are free of all rules","Only choosing a name","Sending an annual photo"]'::jsonb,
 0,'Varkens vallen onder veeteeltwetgeving; niet-naleving kan leiden tot boetes of inbeslagname.','Les cochons relèvent de la législation sur l''élevage; le non-respect peut entraîner amendes ou saisie.','Pigs fall under livestock legislation; non-compliance can lead to fines or confiscation.'),
(2,'tekst','Waarom is sociaal contact met soortgenoten belangrijk voor varkens?','Pourquoi le contact social avec des congénères est-il important pour les cochons ?','Why is social contact with other pigs important for pigs?',
 '["Varkens zijn kuddedieren en kunnen eenzaam en gestrest raken alleen","Varkens leven van nature volledig solitair","Ze hebben nooit behoefte aan gezelschap","Contact met andere varkens is gevaarlijk"]'::jsonb,
 '["Les cochons sont des animaux grégaires et peuvent devenir solitaires et stressés seuls","Les cochons vivent naturellement en solitaire","Ils n''ont jamais besoin de compagnie","Le contact avec d''autres cochons est dangereux"]'::jsonb,
 '["Pigs are herd animals and can become lonely and stressed alone","Pigs naturally live entirely solitary lives","They never need company","Contact with other pigs is dangerous"]'::jsonb,
 0,'Varkens zijn intelligente kuddedieren; isolatie kan leiden tot gedragsproblemen en apathie.','Les cochons sont des animaux grégaires intelligents; l''isolement peut causer troubles du comportement et apathie.','Pigs are intelligent herd animals; isolation can cause behavioural problems and apathy.'),
(3,'tekst','Waarom kunnen minivarkens binnenshuis destructief gedrag vertonen?','Pourquoi les mini-cochons peuvent-ils être destructeurs à l''intérieur ?','Why can mini pigs show destructive behaviour indoors?',
 '["Omdat hun natuurlijke wroet- en graafdrang niet uitgeleefd kan worden","Omdat ze dat expres doen uit wraak","Omdat ze niet slim genoeg zijn","Ze zijn nooit destructief binnenshuis"]'::jsonb,
 '["Car leur besoin naturel de fouiller ne peut pas s''exprimer","Car ils le font exprès par vengeance","Car ils ne sont pas assez intelligents","Ils ne sont jamais destructeurs à l''intérieur"]'::jsonb,
 '["Because their natural rooting instinct cannot be expressed indoors","Because they do it deliberately out of revenge","Because they are not intelligent enough","They are never destructive indoors"]'::jsonb,
 0,'Zonder uitlaatklep voor wroetgedrag richten varkens hun energie vaak op meubels en vloeren.','Sans exutoire pour fouiller, les cochons dirigent souvent leur énergie vers meubles et sols.','Without an outlet for rooting, pigs often direct their energy at furniture and floors.'),
(3,'tekst','Hoe intelligent zijn varkens in vergelijking met andere huisdieren?','Quelle est l''intelligence des cochons comparée aux autres animaux ?','How intelligent are pigs compared to other pets?',
 '["Zeer intelligent, vergelijkbaar met of slimmer dan honden","Minder intelligent dan een goudvis","Ze kunnen helemaal niets leren","Intelligentie is niet meetbaar bij varkens"]'::jsonb,
 '["Très intelligents, comparables voire plus intelligents que les chiens","Moins intelligents qu''un poisson rouge","Ils ne peuvent rien apprendre","L''intelligence n''est pas mesurable chez les cochons"]'::jsonb,
 '["Very intelligent, comparable to or smarter than dogs","Less intelligent than a goldfish","They cannot learn anything at all","Intelligence is not measurable in pigs"]'::jsonb,
 0,'Studies tonen dat varkens puzzels kunnen oplossen en trucjes leren zoals slimme hondenrassen.','Des études montrent que les cochons résolvent des puzzles et apprennent des tours comme des chiens intelligents.','Studies show pigs can solve puzzles and learn tricks similar to intelligent dog breeds.'),
(3,'tekst','Wat gebeurt er vaak met minivarkens die te groot worden voor het huis?','Que devient souvent un mini-cochon devenu trop grand pour la maison ?','What often happens to mini pigs that outgrow the home?',
 '["Ze worden afgestaan aan asielen of opvangcentra","Ze passen zich automatisch aan de ruimte aan","Ze stoppen met groeien vanzelf","Niets, dit probleem komt nooit voor"]'::jsonb,
 '["Ils sont abandonnés dans des refuges ou centres d''accueil","Ils s''adaptent automatiquement à l''espace","Ils arrêtent de grandir spontanément","Rien, ce problème n''arrive jamais"]'::jsonb,
 '["They are surrendered to shelters or rescue centres","They automatically adapt to the space","They naturally stop growing","Nothing, this problem never occurs"]'::jsonb,
 0,'Varkensopvangcentra melden een toename van afgestane ''minivarkens'' die te groot werden.','Les refuges pour cochons signalent une hausse des ''mini-cochons'' abandonnés devenus trop grands.','Pig sanctuaries report an increase in surrendered ''mini pigs'' that grew too large.'),
(3,'tekst','Wat is een belangrijke voorbereiding voordat men een minivarken aanschaft?','Quelle préparation importante faut-il avant d''acquérir un mini-cochon ?','What is important preparation before acquiring a mini pig?',
 '["Navragen bij de gemeente en voldoende ruimte en tijd voorzien","Enkel een leuk hokje kopen","Niets, het regelt zichzelf wel","Wachten tot het varken volwassen is om te beslissen"]'::jsonb,
 '["Se renseigner auprès de la commune et prévoir assez d''espace et de temps","Acheter juste un joli enclos","Rien, cela se règle tout seul","Attendre que le cochon soit adulte pour décider"]'::jsonb,
 '["Checking with local authorities and ensuring enough space and time","Just buying a nice pen","Nothing, it will sort itself out","Waiting until the pig is an adult to decide"]'::jsonb,
 0,'Goede voorbereiding en realistische verwachtingen voorkomen latere problemen en afstand.','Une bonne préparation et des attentes réalistes évitent les problèmes et abandons ultérieurs.','Good preparation and realistic expectations prevent later problems and surrender.'),
(3,'tekst','Wat is een teken dat een minivarken zich verveelt of gestrest is?','Quel est un signe qu''un mini-cochon s''ennuie ou est stressé ?','What is a sign a mini pig is bored or stressed?',
 '["Overmatig knagen, wroeten in verboden plekken of agressief gedrag","Rustig slapen na een wandeling","Normaal eetgedrag","Spelen met speeltjes"]'::jsonb,
 '["Rongement excessif, fouiller aux mauvais endroits ou agressivité","Dormir calmement après une promenade","Comportement alimentaire normal","Jouer avec des jouets"]'::jsonb,
 '["Excessive chewing, rooting in forbidden spots or aggressive behaviour","Sleeping calmly after a walk","Normal eating behaviour","Playing with toys"]'::jsonb,
 0,'Gedragsproblemen bij varkens wijzen vaak op onvoldoende mentale en fysieke verrijking.','Les troubles du comportement chez les cochons indiquent souvent un manque d''enrichissement mental et physique.','Behavioural problems in pigs often indicate insufficient mental and physical enrichment.')
) AS v(module,vraag_type,nl,fr,en,onl,ofr,oen,ci,wnl,wfr,wen);

-- Waterschildpad
WITH a AS (
  INSERT INTO public.academies (diersoort_naam, diersoort_naam_fr, diersoort_naam_en, slug, badge_icon, vragen_per_test, slaag_grens, beschrijving, beschrijving_fr, beschrijving_en, categorie, prioriteit)
  VALUES ('Geelwang- en roodwangschildpad','Tortue de Floride','Slider turtle','waterschildpad','waterschildpad',15,12,'Ontdek waarom deze schattige kleine schildpad uitgroeit tot een groot, langlevend dier met veel verzorging nodig.','Découvrez pourquoi cette petite tortue mignonne devient un grand animal qui vit très longtemps.','Discover why this cute little turtle grows into a large, long-living animal needing much care.','valkuilen',50)
  RETURNING id
)
INSERT INTO public.academy_vragen (academy_id, module, vraag_type, vraag_tekst, vraag_tekst_fr, vraag_tekst_en, opties, opties_fr, opties_en, correcte_optie_index, wist_je_dat, wist_je_dat_fr, wist_je_dat_en)
SELECT a.id, v.module, v.vraag_type, v.nl, v.fr, v.en, v.onl, v.ofr, v.oen, v.ci, v.wnl, v.wfr, v.wen
FROM a, (VALUES
(1,'tekst','Hoe groot kan een geelwang- of roodwangschildpad worden?','Quelle taille peut atteindre une tortue de Floride ?','How large can a slider turtle grow?',
 '["Tot wel 25-30 cm, ongeveer soepbordformaat","Nooit groter dan een muntstuk","Maximaal 3 cm als volwassene","Ze groeien helemaal niet"]'::jsonb,
 '["Jusqu''à 25-30 cm, environ la taille d''une assiette","Jamais plus grand qu''une pièce de monnaie","Maximum 3 cm à l''âge adulte","Elles ne grandissent pas du tout"]'::jsonb,
 '["Up to 25-30 cm, about the size of a soup plate","Never larger than a coin","Maximum 3 cm as an adult","They do not grow at all"]'::jsonb,
 0,'Het schattige babyschildpadje van enkele centimeters groeit uit tot een fors dier van soepbordformaat.','Le mignon bébé tortue de quelques centimètres grandit jusqu''à la taille d''une assiette.','The cute baby turtle of a few centimetres grows into a sizeable, plate-sized animal.'),
(1,'tekst','Hoe oud kan deze schildpadsoort worden?','Quel âge peut atteindre cette espèce de tortue ?','How old can this turtle species get?',
 '["30 tot 40 jaar of ouder","Slechts 2 tot 3 jaar","Nooit langer dan 1 jaar","Precies 10 jaar, niet meer"]'::jsonb,
 '["30 à 40 ans ou plus","Seulement 2 à 3 ans","Jamais plus d''un an","Exactement 10 ans, pas plus"]'::jsonb,
 '["30 to 40 years or older","Only 2 to 3 years","Never longer than 1 year","Exactly 10 years, no more"]'::jsonb,
 0,'Met goede zorg kunnen deze schildpadden gemakkelijk 30 tot 40 jaar leven, soms langer.','Avec de bons soins, ces tortues peuvent facilement vivre 30 à 40 ans, parfois plus.','With good care, these turtles can easily live 30 to 40 years, sometimes longer.'),
(1,'tekst','Waarom worden deze schildpadjes vaak impulsief gekocht?','Pourquoi ces tortues sont-elles souvent achetées de façon impulsive ?','Why are these turtles often bought on impulse?',
 '["Omdat ze als baby klein, goedkoop en schattig lijken","Omdat ze wettelijk verplicht zijn per gezin","Omdat ze nooit groeien","Omdat verkopers de zorgvereisten altijd volledig uitleggen"]'::jsonb,
 '["Car bébé, elles paraissent petites, bon marché et mignonnes","Car elles sont obligatoires par foyer","Car elles ne grandissent jamais","Car les vendeurs expliquent toujours tous les besoins"]'::jsonb,
 '["Because as babies they look small, cheap and cute","Because they are legally required per household","Because they never grow","Because sellers always fully explain care requirements"]'::jsonb,
 0,'De lage aanschafprijs en kleine baby-omvang verbergen vaak de werkelijke lange termijn zorgvereisten.','Le faible prix d''achat et la petite taille du bébé masquent souvent les besoins réels à long terme.','The low purchase price and small baby size often hide the real long-term care requirements.'),
(1,'tekst','Waarom is deze schildpad een invasieve exoot in Europa?','Pourquoi cette tortue est-elle une espèce exotique envahissante en Europe ?','Why is this turtle an invasive species in Europe?',
 '["Ze is oorspronkelijk uit Noord-Amerika en verdringt inheemse soorten","Ze is van nature al Europees","Ze kan niet overleven buiten een aquarium","Ze heeft geen enkele impact op ecosystemen"]'::jsonb,
 '["Elle est originaire d''Amérique du Nord et évince les espèces locales","Elle est naturellement déjà européenne","Elle ne peut pas survivre hors d''un aquarium","Elle n''a aucun impact sur les écosystèmes"]'::jsonb,
 '["It originates from North America and outcompetes native species","It is naturally already European","It cannot survive outside an aquarium","It has no impact on ecosystems at all"]'::jsonb,
 0,'Uitgezette schildpadden concurreren met de inheemse Europese moerasschildpad om voedsel en zonplekken.','Les tortues relâchées concurrencent la cistude d''Europe pour la nourriture et les zones d''insolation.','Released turtles compete with the native European pond turtle for food and basking spots.'),
(1,'tekst','Wat is het gevolg van het onderschatten van de volwassen grootte?','Quelle est la conséquence de sous-estimer la taille adulte ?','What is the consequence of underestimating the adult size?',
 '["Het aquarium wordt te klein en moet vervangen worden","Er verandert niets aan de huisvesting","De schildpad past zich vanzelf aan een klein bakje aan","Dit is nooit een probleem"]'::jsonb,
 '["L''aquarium devient trop petit et doit être remplacé","Rien ne change pour l''hébergement","La tortue s''adapte naturellement à un petit bac","Ce n''est jamais un problème"]'::jsonb,
 '["The aquarium becomes too small and must be replaced","Nothing changes about the housing","The turtle naturally adapts to a small tank","This is never a problem"]'::jsonb,
 0,'Veel eigenaars moeten binnen enkele jaren investeren in een veel groter bak of vijver.','De nombreux propriétaires doivent investir dans un bac ou bassin bien plus grand en quelques années.','Many owners must invest in a much larger tank or pond within a few years.'),
(2,'tekst','Hoe groot moet het aquarium minimaal zijn voor een volwassen schildpad?','Quelle taille minimale doit avoir l''aquarium pour une tortue adulte ?','How large must the aquarium minimally be for an adult turtle?',
 '["Minstens enkele honderden liters, met veel zwemruimte","Een kom van 5 liter volstaat","Een emmer is voldoende","Grootte maakt niet uit"]'::jsonb,
 '["Au moins plusieurs centaines de litres, avec beaucoup d''espace pour nager","Un bol de 5 litres suffit","Un seau suffit","La taille n''a pas d''importance"]'::jsonb,
 '["At least several hundred litres, with plenty of swimming space","A 5-litre bowl is enough","A bucket is sufficient","Size does not matter"]'::jsonb,
 0,'Een volwassen schildpad heeft een groot bassin nodig, vaak 300-500 liter of meer.','Une tortue adulte a besoin d''un grand bassin, souvent 300-500 litres ou plus.','An adult turtle needs a large tank, often 300-500 litres or more.'),
(2,'tekst','Waarom is een sterke filter essentieel in het schildpadaquarium?','Pourquoi un filtre puissant est-il essentiel dans l''aquarium de la tortue ?','Why is a strong filter essential in the turtle aquarium?',
 '["Schildpadden produceren veel afval en vervuilen het water snel","Schildpadden hebben geen invloed op waterkwaliteit","Filters zijn enkel decoratief","Water hoeft nooit gefilterd te worden"]'::jsonb,
 '["Les tortues produisent beaucoup de déchets et polluent vite l''eau","Les tortues n''ont aucun effet sur la qualité de l''eau","Les filtres sont juste décoratifs","L''eau n''a jamais besoin d''être filtrée"]'::jsonb,
 '["Turtles produce a lot of waste and pollute the water quickly","Turtles have no effect on water quality","Filters are purely decorative","Water never needs filtering"]'::jsonb,
 0,'Schildpadden eten en poepen in het water, waardoor krachtige filtering nodig is om ziektes te voorkomen.','Les tortues mangent et défèquent dans l''eau, une filtration puissante est nécessaire pour éviter les maladies.','Turtles eat and defecate in the water, so powerful filtration is needed to prevent illness.'),
(2,'tekst','Waarom heeft een schildpad een basking-plek nodig?','Pourquoi une tortue a-t-elle besoin d''une zone d''insolation ?','Why does a turtle need a basking spot?',
 '["Om volledig droog te kunnen liggen en op te warmen onder een lamp","Schildpadden hoeven nooit uit het water te komen","Enkel voor decoratie in het aquarium","Om te kunnen slapen onder water"]'::jsonb,
 '["Pour pouvoir sécher complètement et se réchauffer sous une lampe","Les tortues n''ont jamais besoin de sortir de l''eau","Juste pour décorer l''aquarium","Pour dormir sous l''eau"]'::jsonb,
 '["To be able to dry off completely and warm up under a lamp","Turtles never need to leave the water","Purely for decoration in the tank","To sleep underwater"]'::jsonb,
 0,'Basken helpt schildpadden hun lichaamstemperatuur regelen en voorkomt schimmel- en huidproblemen.','L''insolation aide les tortues à réguler leur température et prévient les problèmes de peau et champignons.','Basking helps turtles regulate body temperature and prevents shell fungus and skin problems.'),
(2,'tekst','Waarom is UV-B verlichting noodzakelijk?','Pourquoi un éclairage UV-B est-il nécessaire ?','Why is UV-B lighting necessary?',
 '["Het helpt de schildpad vitamine D3 aanmaken voor sterke botten en schild","UV-B is enkel voor sfeerverlichting","Schildpadden hebben geen vitamine D3 nodig","Gewoon daglicht door een raam volstaat altijd"]'::jsonb,
 '["Il aide la tortue à produire de la vitamine D3 pour des os et une carapace solides","L''UV-B est juste pour l''ambiance","Les tortues n''ont pas besoin de vitamine D3","La lumière du jour par une fenêtre suffit toujours"]'::jsonb,
 '["It helps the turtle produce vitamin D3 for strong bones and shell","UV-B is only for mood lighting","Turtles do not need vitamin D3","Ordinary daylight through a window is always enough"]'::jsonb,
 0,'Zonder UV-B kunnen schildpadden metabole botziekte en een zacht, misvormd schild ontwikkelen.','Sans UV-B, les tortues peuvent développer une maladie osseuse métabolique et une carapace molle.','Without UV-B, turtles can develop metabolic bone disease and a soft, deformed shell.'),
(2,'tekst','Welke watertemperatuur is geschikt voor deze schildpadsoort?','Quelle température de l''eau convient à cette espèce de tortue ?','What water temperature suits this turtle species?',
 '["Ongeveer 22-26°C, met een warmere basking-zone erboven","Altijd onder 5°C","Kokend heet water van 60°C","Temperatuur is volledig onbelangrijk"]'::jsonb,
 '["Environ 22-26°C, avec une zone d''insolation plus chaude au-dessus","Toujours en dessous de 5°C","De l''eau bouillante à 60°C","La température n''a aucune importance"]'::jsonb,
 '["Around 22-26°C, with a warmer basking zone above","Always below 5°C","Boiling hot water at 60°C","Temperature is completely unimportant"]'::jsonb,
 0,'Een stabiele watertemperatuur voorkomt stress en ondersteunt een goede spijsvertering en immuunsysteem.','Une température de l''eau stable évite le stress et favorise une bonne digestion et immunité.','A stable water temperature prevents stress and supports good digestion and immune function.'),
(3,'tekst','Waarom mag je een schildpad nooit uitzetten in de natuur?','Pourquoi ne faut-il jamais relâcher une tortue dans la nature ?','Why should you never release a turtle into the wild?',
 '["Ze is een invasieve exoot die het ecosysteem en inheemse soorten schaadt","Ze kan perfect overleven en hoort daar thuis","Het is wettelijk altijd toegestaan en aangemoedigd","Uitzetten helpt de schildpad altijd gelukkiger worden"]'::jsonb,
 '["C''est une espèce exotique envahissante nuisant à l''écosystème et aux espèces locales","Elle peut parfaitement survivre et y a sa place","C''est toujours légal et encouragé","Le relâcher la rend toujours plus heureuse"]'::jsonb,
 '["It is an invasive exotic species that harms the ecosystem and native species","It can survive perfectly and belongs there","It is always legal and encouraged","Releasing it always makes the turtle happier"]'::jsonb,
 0,'In veel landen is het uitzetten van uitheemse schildpadden bij wet verboden vanwege ecologische schade.','Dans de nombreux pays, relâcher des tortues exotiques est interdit par la loi en raison des dommages écologiques.','In many countries, releasing non-native turtles is prohibited by law due to ecological harm.'),
(3,'tekst','Wat moet je doen als je een schildpad niet meer kunt verzorgen?','Que faire si vous ne pouvez plus vous occuper d''une tortue ?','What should you do if you can no longer care for a turtle?',
 '["Contact opnemen met een gespecialiseerd opvangcentrum of reptielenvereniging","Ze in een vijver of rivier loslaten","Ze gewoon buiten achterlaten","Ze weggeven aan een willekeurige vreemde zonder controle"]'::jsonb,
 '["Contacter un centre d''accueil spécialisé ou une association de reptiles","La relâcher dans un étang ou une rivière","La laisser simplement dehors","La donner à un inconnu sans vérification"]'::jsonb,
 '["Contact a specialised rescue centre or reptile association","Release it into a pond or river","Just leave it outside","Give it away to a random stranger without checks"]'::jsonb,
 0,'Reptielenopvangcentra zijn gespecialiseerd in herplaatsing en voorkomen ecologische schade door uitzetten.','Les centres d''accueil pour reptiles sont spécialisés dans le replacement et évitent les dégâts écologiques.','Reptile rescue centres specialise in rehoming and prevent ecological damage from release.'),
(3,'tekst','Wat is een risico van salmonella bij waterschildpadden?','Quel est un risque de salmonelle chez les tortues aquatiques ?','What is a salmonella risk with water turtles?',
 '["Schildpadden kunnen salmonella dragen, dus handen wassen na contact is belangrijk","Schildpadden dragen nooit bacteriën","Salmonella is enkel gevaarlijk voor vissen","Contact met schildpadden is altijd volledig steriel"]'::jsonb,
 '["Les tortues peuvent porter la salmonelle, il faut se laver les mains après contact","Les tortues ne portent jamais de bactéries","La salmonelle n''affecte que les poissons","Le contact avec les tortues est toujours parfaitement stérile"]'::jsonb,
 '["Turtles can carry salmonella, so washing hands after contact is important","Turtles never carry bacteria","Salmonella only affects fish","Contact with turtles is always perfectly sterile"]'::jsonb,
 0,'Goede hygiëne na het aanraken van schildpadden of hun water voorkomt salmonella-infecties bij mensen.','Une bonne hygiène après avoir touché les tortues ou leur eau évite les infections à salmonelle chez l''homme.','Good hygiene after touching turtles or their water prevents salmonella infections in people.'),
(3,'tekst','Waarom moeten kinderen begeleid worden bij de zorg voor deze schildpad?','Pourquoi les enfants doivent-ils être encadrés dans les soins de cette tortue ?','Why should children be supervised in caring for this turtle?',
 '["De verzorging is complex en de schildpad kan bijten of hygiënerisico''s geven","Kinderen kunnen dit volledig zelfstandig zonder enige kennis","Schildpadden vergen geen enkele zorg","Het is wettelijk verboden dat kinderen ze zien"]'::jsonb,
 '["Les soins sont complexes et la tortue peut mordre ou présenter des risques d''hygiène","Les enfants peuvent le faire seuls sans aucune connaissance","Les tortues ne nécessitent aucun soin","Il est interdit par la loi que les enfants les voient"]'::jsonb,
 '["Care is complex and the turtle can bite or pose hygiene risks","Children can do this fully independently without any knowledge","Turtles need no care at all","It is legally forbidden for children to see them"]'::jsonb,
 0,'Volwassen begeleiding zorgt voor correcte verzorging en vermindert hygiëne- en verwondingsrisico''s.','L''encadrement d''un adulte assure des soins corrects et réduit les risques d''hygiène et de blessure.','Adult supervision ensures correct care and reduces hygiene and injury risks.')
) AS v(module,vraag_type,nl,fr,en,onl,ofr,oen,ci,wnl,wfr,wen);

-- Bettavis
WITH a AS (
  INSERT INTO public.academies (diersoort_naam, diersoort_naam_fr, diersoort_naam_en, slug, badge_icon, vragen_per_test, slaag_grens, beschrijving, beschrijving_fr, beschrijving_en, categorie, prioriteit)
  VALUES ('Bèttavis','Poisson combattant','Betta fish','bettavis','bettavis',15,12,'Ontkracht de vaas-mythe en leer wat een bèttavis echt nodig heeft om gezond te leven.','Démystifiez le mythe du vase et découvrez ce dont un poisson combattant a vraiment besoin.','Debunk the vase myth and learn what a betta fish really needs to live healthily.','valkuilen',50)
  RETURNING id
)
INSERT INTO public.academy_vragen (academy_id, module, vraag_type, vraag_tekst, vraag_tekst_fr, vraag_tekst_en, opties, opties_fr, opties_en, correcte_optie_index, wist_je_dat, wist_je_dat_fr, wist_je_dat_en)
SELECT a.id, v.module, v.vraag_type, v.nl, v.fr, v.en, v.onl, v.ofr, v.oen, v.ci, v.wnl, v.wfr, v.wen
FROM a, (VALUES
(1,'tekst','Klopt het dat een bèttavis gelukkig leeft in een kleine vaas?','Est-il vrai qu''un poisson combattant vit heureux dans un petit vase ?','Is it true that a betta fish lives happily in a small vase?',
 '["Nee, dit is een mythe die tot stress en vroegtijdige sterfte leidt","Ja, vazen zijn hun natuurlijke habitat","Ja, hoe kleiner hoe beter voor bèttavissen","Ja, ze hebben geen filter of verwarming nodig"]'::jsonb,
 '["Non, c''est un mythe qui cause stress et mort prématurée","Oui, les vases sont leur habitat naturel","Oui, plus petit est toujours mieux","Oui, ils n''ont besoin ni de filtre ni de chauffage"]'::jsonb,
 '["No, this is a myth that leads to stress and premature death","Yes, vases are their natural habitat","Yes, the smaller the better for bettas","Yes, they need no filter or heater"]'::jsonb,
 0,'De vaas-mythe komt van het feit dat bètta''s lucht kunnen ademen, maar dat betekent niet dat ze weinig ruimte nodig hebben.','Le mythe du vase vient du fait que les bettas respirent l''air, mais cela ne signifie pas qu''ils ont besoin de peu d''espace.','The vase myth comes from the fact that bettas can breathe air, but that does not mean they need little space.'),
(1,'tekst','Waar komt het misverstand over bèttavissen in vazen vandaan?','D''où vient le malentendu sur les poissons combattants en vase ?','Where does the misunderstanding about bettas in vases come from?',
 '["Ze hebben een labyrintorgaan waarmee ze lucht kunnen ademen","Ze kunnen niet zwemmen dus hebben ze geen ruimte nodig","Ze zijn van nature vaasdieren","Ze hebben geen kieuwen"]'::jsonb,
 '["Ils ont un organe labyrinthique leur permettant de respirer l''air","Ils ne savent pas nager donc n''ont pas besoin d''espace","Ils sont naturellement des animaux de vase","Ils n''ont pas de branchies"]'::jsonb,
 '["They have a labyrinth organ allowing them to breathe air","They cannot swim so do not need space","They are naturally vase-dwelling animals","They have no gills"]'::jsonb,
 0,'Het labyrintorgaan laat bètta''s overleven in zuurstofarm water, maar zegt niets over hun ruimtebehoefte.','L''organe labyrinthique permet aux bettas de survivre en eau pauvre en oxygène, mais ne dit rien sur leur besoin d''espace.','The labyrinth organ lets bettas survive in low-oxygen water, but says nothing about their space needs.'),
(1,'tekst','Wat is het minimale aquariumvolume dat wordt aanbevolen voor een bèttavis?','Quel volume minimal d''aquarium est recommandé pour un poisson combattant ?','What is the minimum recommended aquarium volume for a betta fish?',
 '["10 tot 20 liter, met filter en verwarming","1 liter volstaat ruimschoots","Een kopje van 0,5 liter is ideaal","Volume maakt geen enkel verschil"]'::jsonb,
 '["10 à 20 litres, avec filtre et chauffage","1 litre suffit largement","Une tasse de 0,5 litre est idéale","Le volume ne fait aucune différence"]'::jsonb,
 '["10 to 20 litres, with filter and heater","1 litre is more than enough","A 0.5-litre cup is ideal","Volume makes no difference at all"]'::jsonb,
 0,'Grotere aquaria houden de watertemperatuur en -kwaliteit veel stabieler, wat cruciaal is voor bètta''s.','Un aquarium plus grand garde la température et la qualité de l''eau bien plus stables, essentiel pour les bettas.','Larger tanks keep water temperature and quality much more stable, which is crucial for bettas.'),
(1,'tekst','Waarom verkopen sommige winkels bèttavissen in kleine bakjes zonder uitleg?','Pourquoi certains magasins vendent-ils des bettas dans de petits bocaux sans explication ?','Why do some shops sell bettas in small cups without explanation?',
 '["Uit gemak en kostenbesparing, niet omdat het goed is voor de vis","Omdat dit wetenschappelijk de beste huisvesting is","Omdat bèttavissen daar het gelukkigst zijn","Omdat het wettelijk verplicht is"]'::jsonb,
 '["Par commodité et économie, pas parce que c''est bon pour le poisson","Car c''est scientifiquement le meilleur hébergement","Car les bettas y sont les plus heureux","Car c''est légalement obligatoire"]'::jsonb,
 '["Out of convenience and cost-saving, not because it is good for the fish","Because it is scientifically the best housing","Because bettas are happiest there","Because it is legally required"]'::jsonb,
 0,'Kleine bakjes zijn goedkoop voor winkels om aan te bieden, maar zijn geen goede permanente huisvesting.','Les petits bocaux sont bon marché pour les magasins, mais ne constituent pas un bon logement permanent.','Small cups are cheap for shops to offer, but are not good permanent housing.'),
(1,'tekst','Wat kan een te klein en onverwarmd bakje veroorzaken bij een bèttavis?','Que peut causer un bocal trop petit et non chauffé chez un betta ?','What can a too-small, unheated cup cause in a betta fish?',
 '["Stress, verzwakt immuunsysteem en een kortere levensduur","Een langer en gelukkiger leven","Snellere groei en meer kleur","Geen enkel effect op de vis"]'::jsonb,
 '["Stress, système immunitaire affaibli et durée de vie réduite","Une vie plus longue et plus heureuse","Une croissance plus rapide et plus de couleur","Aucun effet sur le poisson"]'::jsonb,
 '["Stress, a weakened immune system and a shorter lifespan","A longer and happier life","Faster growth and more colour","No effect on the fish at all"]'::jsonb,
 0,'Bèttavissen in kleine, koude bakjes leven vaak slechts enkele maanden in plaats van meerdere jaren.','Les bettas dans de petits bocaux froids ne vivent souvent que quelques mois au lieu de plusieurs années.','Bettas in small, cold cups often live only a few months instead of several years.'),
(2,'tekst','Welke watertemperatuur heeft een bèttavis nodig?','Quelle température d''eau nécessite un poisson combattant ?','What water temperature does a betta fish need?',
 '["Rond de 24-27°C, verwarmd en stabiel","Kamertemperatuur zonder verwarming volstaat altijd","Ijskoud water onder 10°C","Temperatuur speelt geen rol"]'::jsonb,
 '["Environ 24-27°C, chauffée et stable","La température ambiante sans chauffage suffit toujours","De l''eau glacée sous 10°C","La température ne joue aucun rôle"]'::jsonb,
 '["Around 24-27°C, heated and stable","Room temperature without a heater is always enough","Ice-cold water below 10°C","Temperature plays no role"]'::jsonb,
 0,'Bèttavissen zijn tropische vissen en hebben een verwarmer nodig om een stabiele, warme temperatuur te behouden.','Les bettas sont des poissons tropicaux et ont besoin d''un chauffage pour maintenir une température stable et chaude.','Bettas are tropical fish and need a heater to maintain a stable, warm temperature.'),
(2,'tekst','Waarom is een filter nodig, ondanks dat bètta''s lucht kunnen ademen?','Pourquoi un filtre est-il nécessaire malgré la capacité des bettas à respirer l''air ?','Why is a filter needed despite bettas being able to breathe air?',
 '["Om afvalstoffen en ammoniak uit het water te verwijderen","Filters zijn overbodig voor bètta''s","Enkel om het water te laten bewegen voor de show","Bètta''s hebben geen vervuild water nodig te vermijden"]'::jsonb,
 '["Pour éliminer les déchets et l''ammoniac de l''eau","Les filtres sont inutiles pour les bettas","Juste pour faire bouger l''eau pour le spectacle","Les bettas n''ont pas besoin d''éviter l''eau polluée"]'::jsonb,
 '["To remove waste and ammonia from the water","Filters are unnecessary for bettas","Only to move the water for show","Bettas do not need to avoid polluted water"]'::jsonb,
 0,'Zonder filtratie hopen ammoniak en nitriet zich snel op, wat giftig is voor vissen, ook bètta''s.','Sans filtration, l''ammoniac et les nitrites s''accumulent vite, ce qui est toxique même pour les bettas.','Without filtration, ammonia and nitrite build up quickly, which is toxic even to bettas.'),
(2,'tekst','Waarom is beplanting of decoratie belangrijk in een bèttavis-aquarium?','Pourquoi les plantes ou décorations sont-elles importantes dans l''aquarium d''un betta ?','Why is planting or decoration important in a betta aquarium?',
 '["Het biedt schuilplaatsen en verrijking, vermindert stress","Bètta''s houden niet van enige decoratie","Planten zijn giftig voor alle vissen","Decoratie heeft geen functie"]'::jsonb,
 '["Cela offre des cachettes et de l''enrichissement, réduit le stress","Les bettas n''aiment aucune décoration","Les plantes sont toxiques pour tous les poissons","La décoration n''a aucune fonction"]'::jsonb,
 '["It provides hiding spots and enrichment, reducing stress","Bettas dislike any decoration","Plants are toxic to all fish","Decoration has no function"]'::jsonb,
 0,'Levende of zachte kunstplanten geven een bètta een gevoel van veiligheid en verminderen verveling.','Des plantes vivantes ou artificielles douces donnent un sentiment de sécurité au betta et réduisent l''ennui.','Live or soft artificial plants give a betta a sense of security and reduce boredom.'),
(2,'tekst','Hoe vaak moet je het water in een klein bèttavis-aquarium verversen?','À quelle fréquence faut-il changer l''eau d''un petit aquarium à betta ?','How often should you change the water in a small betta aquarium?',
 '["Regelmatig gedeeltelijk, meestal wekelijks, afhankelijk van filtercapaciteit","Nooit, water hoeft nooit ververst te worden","Om de vijf jaar is voldoende","Enkel wanneer de vis overlijdt"]'::jsonb,
 '["Partiellement et régulièrement, souvent chaque semaine, selon le filtre","Jamais, l''eau n''a jamais besoin d''être changée","Tous les cinq ans suffit","Uniquement quand le poisson meurt"]'::jsonb,
 '["Regular partial changes, usually weekly, depending on filter capacity","Never, water never needs changing","Once every five years is enough","Only when the fish dies"]'::jsonb,
 0,'Regelmatige waterverversingen houden ammoniak- en nitraatniveaus laag en het water gezond.','Des changements d''eau réguliers maintiennent des niveaux d''ammoniac et de nitrate bas et une eau saine.','Regular water changes keep ammonia and nitrate levels low and the water healthy.'),
(3,'tekst','Waarom mag je geen twee mannetjesbèttavissen samen houden?','Pourquoi ne faut-il pas garder deux bettas mâles ensemble ?','Why should you not keep two male betta fish together?',
 '["Ze zijn extreem territoriaal en zullen elkaar aanvallen, vaak fataal","Ze worden altijd beste vrienden","Mannetjes zijn nooit agressief tegenover elkaar","Ze moeten juist altijd in paren gehouden worden"]'::jsonb,
 '["Ils sont extrêmement territoriaux et s''attaqueront, souvent fatalement","Ils deviennent toujours les meilleurs amis","Les mâles ne sont jamais agressifs entre eux","Ils doivent au contraire toujours être gardés en paires"]'::jsonb,
 '["They are extremely territorial and will attack each other, often fatally","They always become best friends","Males are never aggressive toward each other","They must actually always be kept in pairs"]'::jsonb,
 0,'De naam ''fighting fish'' komt van hevige gevechten tussen mannetjes, die tot ernstig letsel of dood leiden.','Le nom ''poisson combattant'' vient des combats féroces entre mâles, causant blessures graves ou mort.','The name ''fighting fish'' comes from fierce fights between males, leading to severe injury or death.'),
(3,'tekst','Wat is het labyrintorgaan van een bèttavis?','Qu''est-ce que l''organe labyrinthique d''un poisson combattant ?','What is the labyrinth organ of a betta fish?',
 '["Een orgaan waarmee ze aan het wateroppervlak lucht kunnen ademen","Een orgaan om op het droge te lopen","Een spierorgaan voor snel zwemmen","Een orgaan dat kleuren produceert"]'::jsonb,
 '["Un organe leur permettant de respirer l''air à la surface de l''eau","Un organe pour marcher sur terre","Un organe musculaire pour nager vite","Un organe qui produit les couleurs"]'::jsonb,
 '["An organ allowing them to breathe air at the water surface","An organ for walking on land","A muscular organ for fast swimming","An organ that produces colours"]'::jsonb,
 0,'Dankzij het labyrintorgaan kunnen bètta''s overleven in zuurstofarm water door rechtstreeks lucht te happen.','Grâce à l''organe labyrinthique, les bettas survivent en eau pauvre en oxygène en respirant l''air directement.','Thanks to the labyrinth organ, bettas can survive in low-oxygen water by gulping air directly.'),
(3,'tekst','Kunnen mannetjes- en vrouwtjesbèttavissen altijd samen gehouden worden?','Peut-on toujours garder ensemble des bettas mâles et femelles ?','Can male and female betta fish always be kept together?',
 '["Niet altijd, dit vereist zorgvuldige introductie en voldoende ruimte","Ja, altijd zonder enig risico","Nee, mannetjes en vrouwtjes verdragen elkaar nooit","Enkel als ze uit dezelfde nest komen"]'::jsonb,
 '["Pas toujours, cela nécessite une introduction prudente et assez d''espace","Oui, toujours sans aucun risque","Non, mâles et femelles ne se tolèrent jamais","Uniquement s''ils viennent de la même portée"]'::jsonb,
 '["Not always, this requires careful introduction and enough space","Yes, always without any risk","No, males and females never tolerate each other","Only if they come from the same brood"]'::jsonb,
 0,'Zelfs mannetjes en vrouwtjes kunnen agressief zijn zonder voldoende ruimte, schuilplaatsen en voorzichtig samenbrengen.','Même mâles et femelles peuvent être agressifs sans assez d''espace, de cachettes et une introduction prudente.','Even males and females can be aggressive without enough space, hiding spots and careful introduction.'),
(3,'tekst','Wat is een teken van stress of ziekte bij een bèttavis?','Quel est un signe de stress ou de maladie chez un betta ?','What is a sign of stress or illness in a betta fish?',
 '["Vervaagde kleuren, gescheurde vinnen of lethargisch gedrag","Actief zwemmen met heldere kleuren","Normaal eetgedrag en felle kleuren","Regelmatig naar het oppervlak zwemmen om lucht te happen"]'::jsonb,
 '["Couleurs ternes, nageoires déchirées ou léthargie","Nage active avec des couleurs vives","Comportement alimentaire normal et couleurs vives","Nager régulièrement en surface pour respirer"]'::jsonb,
 '["Faded colours, torn fins or lethargic behaviour","Active swimming with bright colours","Normal eating behaviour and vivid colours","Regularly swimming to the surface to gulp air"]'::jsonb,
 0,'Vervaagde kleuren en lethargie wijzen vaak op slechte waterkwaliteit of ziekte en vereisen actie.','Des couleurs ternes et de la léthargie indiquent souvent une mauvaise qualité de l''eau ou une maladie.','Faded colours and lethargy often indicate poor water quality or illness and require action.')
) AS v(module,vraag_type,nl,fr,en,onl,ofr,oen,ci,wnl,wfr,wen);
