-- Kip
WITH a AS (
  INSERT INTO public.academies (diersoort_naam, diersoort_naam_fr, diersoort_naam_en, slug, badge_icon, vragen_per_test, slaag_grens, beschrijving, beschrijving_fr, beschrijving_en, categorie, prioriteit)
  VALUES ('Kip','Poule','Chicken','kip','kip',12,9,'Leer hoe je kippen een veilig hok, gezond voer en een fijne leefomgeving geeft op de kinderboerderij.','Découvrez comment offrir aux poules un poulailler sûr, une bonne alimentation et un environnement agréable à la ferme urbaine.','Learn how to give chickens a safe coop, healthy food and a good environment at the city farm.','boerderij',60)
  RETURNING id
)
INSERT INTO public.academy_vragen (academy_id, module, vraag_type, vraag_tekst, vraag_tekst_fr, vraag_tekst_en, opties, opties_fr, opties_en, correcte_optie_index, wist_je_dat, wist_je_dat_fr, wist_je_dat_en)
SELECT a.id, v.module, v.vraag_type, v.nl, v.fr, v.en, v.onl, v.ofr, v.oen, v.ci, v.wnl, v.wfr, v.wen
FROM a, (VALUES
(1,'tekst','Waarom moet een kippenhok goed geventileerd zijn?','Pourquoi le poulailler doit-il être bien ventilé ?','Why should a chicken coop be well ventilated?',
 '["Om vochtige, ammoniakrijke lucht af te voeren","Om het hok kouder te maken","Om de kippen wakker te houden","Ventilatie is niet belangrijk"]'::jsonb,
 '["Pour évacuer l''air humide chargé d''ammoniac","Pour refroidir le poulailler","Pour garder les poules éveillées","La ventilation n''est pas importante"]'::jsonb,
 '["To remove damp, ammonia-rich air","To make the coop colder","To keep the chickens awake","Ventilation is not important"]'::jsonb,
 0,'Slechte ventilatie leidt tot ademhalingsproblemen bij kippen door opgebouwde ammoniak uit mest.','Une mauvaise ventilation cause des problèmes respiratoires à cause de l''ammoniac accumulé dans les fientes.','Poor ventilation causes breathing problems from ammonia build-up in droppings.'),
(1,'tekst','Waarom moeten kippen ''s nachts opgesloten worden?','Pourquoi les poules doivent-elles être enfermées la nuit ?','Why should chickens be locked up at night?',
 '["Om ze te beschermen tegen roofdieren zoals vossen","Om ze te laten vliegen","Om het hok te reinigen","Kippen slapen nooit"]'::jsonb,
 '["Pour les protéger des prédateurs comme les renards","Pour les laisser voler","Pour nettoyer le poulailler","Les poules ne dorment jamais"]'::jsonb,
 '["To protect them from predators like foxes","To let them fly","To clean the coop","Chickens never sleep"]'::jsonb,
 0,'Vossen en marters jagen vaak ''s nachts, dus een stevig afgesloten hok is levensbelangrijk.','Les renards et fouines chassent souvent la nuit, un poulailler bien fermé est vital.','Foxes and martens often hunt at night, so a securely locked coop is vital.'),
(1,'tekst','Wat hoort er in een kippenhok voor een goede nachtrust?','Que faut-il dans un poulailler pour un bon repos ?','What should a coop have for good rest?',
 '["Zitstokken op verschillende hoogtes","Enkel een betonnen vloer","Fel licht de hele nacht","Geen stro of nestmateriaal"]'::jsonb,
 '["Des perchoirs à différentes hauteurs","Uniquement un sol en béton","Une lumière vive toute la nuit","Aucune paille ni matériel de nid"]'::jsonb,
 '["Perches at different heights","Only a concrete floor","Bright light all night","No straw or nesting material"]'::jsonb,
 0,'Kippen slapen van nature graag hoog op stokken, weg van grondroofdieren.','Les poules aiment naturellement dormir en hauteur, loin des prédateurs terrestres.','Chickens naturally prefer to sleep up high, away from ground predators.'),
(1,'tekst','Waarom is een zandbad belangrijk voor kippen?','Pourquoi un bain de sable est-il important pour les poules ?','Why is a dust bath important for chickens?',
 '["Het houdt hun veren en huid schoon en vrij van parasieten","Het is enkel om te spelen","Kippen hebben dit niet nodig","Het maakt ze moe"]'::jsonb,
 '["Cela garde leurs plumes et leur peau propres et sans parasites","C''est juste pour jouer","Les poules n''en ont pas besoin","Cela les fatigue"]'::jsonb,
 '["It keeps their feathers and skin clean and parasite-free","It is only for play","Chickens do not need this","It makes them tired"]'::jsonb,
 0,'Stofbaden helpen kippen om luizen en mijten van hun veren te verwijderen.','Les bains de poussière aident les poules à se débarrasser des poux et acariens.','Dust bathing helps chickens remove lice and mites from their feathers.'),
(2,'tekst','Waarom hebben leghennen extra calcium nodig?','Pourquoi les poules pondeuses ont-elles besoin de calcium supplémentaire ?','Why do laying hens need extra calcium?',
 '["Voor sterke eierschalen","Om sneller te groeien","Om beter te vliegen","Calcium is niet nodig"]'::jsonb,
 '["Pour des coquilles d''œufs solides","Pour grandir plus vite","Pour mieux voler","Le calcium n''est pas nécessaire"]'::jsonb,
 '["For strong eggshells","To grow faster","To fly better","Calcium is not needed"]'::jsonb,
 0,'Zonder voldoende calcium, bijvoorbeeld uit oesterschelpgrit, leggen kippen broze of zachte eieren.','Sans calcium suffisant, par exemple des coquilles d''huîtres, les poules pondent des œufs fragiles.','Without enough calcium, such as from oyster shell grit, hens lay brittle or soft eggs.'),
(2,'tekst','Waarvoor dient grit in het voer van kippen?','À quoi sert le gravier dans l''alimentation des poules ?','What is grit for in a chicken''s diet?',
 '["Het helpt hen voedsel te vermalen in de krop","Het is enkel decoratie","Het vervangt water","Kippen eten geen grit"]'::jsonb,
 '["Cela aide à broyer la nourriture dans le jabot","C''est juste décoratif","Cela remplace l''eau","Les poules ne mangent pas de gravier"]'::jsonb,
 '["It helps grind food in the gizzard","It is only decorative","It replaces water","Chickens do not eat grit"]'::jsonb,
 0,'Kippen hebben geen tanden, dus grit in de spiermaag helpt om graan fijn te malen.','Les poules n''ont pas de dents, le gravier dans le gésier aide à broyer les grains.','Chickens have no teeth, so grit in the gizzard helps grind grains.'),
(2,'tekst','Wat is een teken dat een kip ziek kan zijn?','Quel est un signe que la poule pourrait être malade ?','What is a sign a chicken may be ill?',
 '["Ze zit stil met opgezette veren en eet weinig","Ze scharrelt actief rond","Ze legt elke dag een ei","Ze drinkt normaal water"]'::jsonb,
 '["Elle reste immobile, plumes ébouriffées, mange peu","Elle picore activement","Elle pond un œuf chaque jour","Elle boit normalement de l''eau"]'::jsonb,
 '["It sits still with fluffed feathers and eats little","It actively forages","It lays an egg every day","It drinks water normally"]'::jsonb,
 0,'Kippen verbergen ziekte goed, dus stille, opgezette kippen moeten snel worden nagekeken.','Les poules cachent bien la maladie, une poule immobile et ébouriffée doit être examinée vite.','Chickens hide illness well, so a still, fluffed-up hen should be checked quickly.'),
(2,'tekst','Hoe vaak moet vers water beschikbaar zijn voor kippen?','À quelle fréquence l''eau fraîche doit-elle être disponible pour les poules ?','How often should fresh water be available to chickens?',
 '["Altijd, de hele dag door","Enkel ''s ochtends","Eenmaal per week","Kippen hebben geen water nodig"]'::jsonb,
 '["Toujours, toute la journée","Seulement le matin","Une fois par semaine","Les poules n''ont pas besoin d''eau"]'::jsonb,
 '["Always, throughout the day","Only in the morning","Once a week","Chickens do not need water"]'::jsonb,
 0,'Kippen drinken vaak kleine hoeveelheden, dus continu toegang tot schoon water is essentieel.','Les poules boivent souvent de petites quantités, un accès continu à l''eau propre est essentiel.','Chickens drink small amounts often, so continuous access to clean water is essential.'),
(3,'tekst','Wat betekent de pikorde bij kippen?','Que signifie l''ordre hiérarchique chez les poules ?','What does the pecking order mean in chickens?',
 '["Een sociale rangorde in de groep","Een manier van vliegen","Een soort ziekte","Het legpatroon van eieren"]'::jsonb,
 '["Une hiérarchie sociale dans le groupe","Une façon de voler","Un type de maladie","Le rythme de ponte des œufs"]'::jsonb,
 '["A social ranking within the group","A way of flying","A type of disease","The egg-laying pattern"]'::jsonb,
 0,'De pikorde bepaalt wie als eerste eet en waar elke kip mag zitten in het hok.','L''ordre hiérarchique détermine qui mange en premier et où chaque poule peut se percher.','The pecking order determines who eats first and where each hen may perch.'),
(3,'tekst','Hoe til je een kip best op?','Comment soulever une poule correctement ?','How should you best pick up a chicken?',
 '["Ondersteun het lichaam met beide handen, vleugels tegen het lijf","Trek aan één poot","Grijp enkel de nek","Til op aan de veren"]'::jsonb,
 '["Soutenez le corps avec les deux mains, ailes contre le corps","Tirez sur une patte","Attrapez seulement le cou","Soulevez par les plumes"]'::jsonb,
 '["Support the body with both hands, wings held in","Pull one leg","Grab only the neck","Lift by the feathers"]'::jsonb,
 0,'Correct optillen voorkomt stress en verwondingen, houd vleugels zachtjes tegen het lichaam.','Un bon maintien évite stress et blessures, gardez les ailes doucement contre le corps.','Proper handling prevents stress and injury; hold the wings gently against the body.'),
(3,'tekst','Waarom pikken kippen soms naar de grond en elkaar?','Pourquoi les poules picorent-elles parfois le sol et entre elles ?','Why do chickens sometimes peck the ground and each other?',
 '["Om voedsel te zoeken en sociale rangorde te bepalen","Uit verveling zonder reden","Ze zijn altijd agressief","Ze zoeken water"]'::jsonb,
 '["Pour chercher de la nourriture et établir la hiérarchie","Par ennui sans raison","Elles sont toujours agressives","Elles cherchent de l''eau"]'::jsonb,
 '["To forage for food and establish social rank","Out of boredom for no reason","They are always aggressive","They are searching for water"]'::jsonb,
 0,'Natuurlijk scharrelgedrag en sociale pikjes horen bij normaal kippengedrag, mits niet overdreven.','Le picorage naturel et les coups de bec sociaux font partie du comportement normal, sans excès.','Natural foraging pecks and social pecks are normal chicken behaviour, unless excessive.'),
(3,'tekst','Wat kan overmatig verenpikken bij kippen aanduiden?','Que peut indiquer un picage excessif des plumes chez les poules ?','What can excessive feather pecking indicate in chickens?',
 '["Stress, verveling of te weinig ruimte","Dat de kip heel gezond is","Dat het gewoon speelgedrag is","Niets, het is altijd normaal"]'::jsonb,
 '["Du stress, de l''ennui ou un manque d''espace","Que la poule est en pleine forme","Que c''est juste un jeu","Rien, c''est toujours normal"]'::jsonb,
 '["Stress, boredom or too little space","That the hen is very healthy","That it is just play behaviour","Nothing, it is always normal"]'::jsonb,
 0,'Overmatig pikken wijst vaak op onvoldoende verrijking of te veel kippen op te weinig ruimte.','Le picage excessif indique souvent un manque d''enrichissement ou trop de poules sur peu d''espace.','Excessive pecking often signals insufficient enrichment or too many hens in too little space.')
) AS v(module,vraag_type,nl,fr,en,onl,ofr,oen,ci,wnl,wfr,wen);

-- Bijen
WITH a AS (
  INSERT INTO public.academies (diersoort_naam, diersoort_naam_fr, diersoort_naam_en, slug, badge_icon, vragen_per_test, slaag_grens, beschrijving, beschrijving_fr, beschrijving_en, categorie, prioriteit)
  VALUES ('Bijen','Abeilles','Bees','bijen','bijen',12,9,'Ontdek hoe een bijenkast, gezonde voeding en veilig gedrag rond de kast bijen helpen gedijen.','Découvrez comment une ruche bien placée, une bonne alimentation et un comportement sûr aident les abeilles.','Discover how a good hive, healthy food and safe behaviour around the hive help bees thrive.','boerderij',61)
  RETURNING id
)
INSERT INTO public.academy_vragen (academy_id, module, vraag_type, vraag_tekst, vraag_tekst_fr, vraag_tekst_en, opties, opties_fr, opties_en, correcte_optie_index, wist_je_dat, wist_je_dat_fr, wist_je_dat_en)
SELECT a.id, v.module, v.vraag_type, v.nl, v.fr, v.en, v.onl, v.ofr, v.oen, v.ci, v.wnl, v.wfr, v.wen
FROM a, (VALUES
(1,'tekst','Waar moet een bijenkast bij voorkeur staan?','Où une ruche doit-elle de préférence être placée ?','Where should a beehive preferably be placed?',
 '["Op een rustige, beschutte plek met ochtendzon","Midden op een druk speelplein","In volledige schaduw de hele dag","Op een plek zonder bloemen in de buurt"]'::jsonb,
 '["Dans un endroit calme et abrité, au soleil du matin","Au milieu d''une cour de jeu animée","À l''ombre complète toute la journée","Dans un endroit sans fleurs à proximité"]'::jsonb,
 '["In a calm, sheltered spot with morning sun","In the middle of a busy playground","In full shade all day","Somewhere with no flowers nearby"]'::jsonb,
 0,'Ochtendzon warmt de kast op en helpt bijen vroeg te beginnen met foerageren.','Le soleil du matin réchauffe la ruche et aide les abeilles à butiner tôt.','Morning sun warms the hive and helps bees start foraging early.'),
(1,'tekst','Waarom is een windluwe plek belangrijk voor een bijenkast?','Pourquoi un endroit protégé du vent est-il important pour une ruche ?','Why is a wind-sheltered spot important for a hive?',
 '["Wind kan de kast afkoelen en bijen bemoeilijken bij het vliegen","Wind maakt de bijen sneller","Bijen houden van harde wind","Het maakt geen verschil"]'::jsonb,
 '["Le vent peut refroidir la ruche et gêner le vol des abeilles","Le vent rend les abeilles plus rapides","Les abeilles aiment le vent fort","Cela ne fait aucune différence"]'::jsonb,
 '["Wind can cool the hive and make flying harder for bees","Wind makes bees faster","Bees like strong wind","It makes no difference"]'::jsonb,
 0,'Sterke wind verstoort de vliegroutes van bijen en laat de kast sneller afkoelen.','Un vent fort perturbe les trajectoires de vol des abeilles et refroidit la ruche plus vite.','Strong wind disrupts bees'' flight paths and cools the hive faster.'),
(1,'tekst','Waarom moet de kast op een verhoging staan?','Pourquoi la ruche doit-elle être surélevée ?','Why should the hive stand raised off the ground?',
 '["Om vocht en ongedierte van onderaf te vermijden","Om de kast zichtbaarder te maken","Het is enkel decoratief","Bijen houden niet van hoogte"]'::jsonb,
 '["Pour éviter l''humidité et les nuisibles venant du sol","Pour rendre la ruche plus visible","C''est juste décoratif","Les abeilles n''aiment pas la hauteur"]'::jsonb,
 '["To avoid moisture and pests from below","To make the hive more visible","It is only decorative","Bees dislike height"]'::jsonb,
 0,'Een verhoogde kast blijft droger en is moeilijker te bereiken voor mieren en muizen.','Une ruche surélevée reste plus sèche et est plus difficile d''accès pour fourmis et souris.','A raised hive stays drier and is harder for ants and mice to reach.'),
(1,'tekst','Waarom hebben bijen een nabijgelegen waterbron nodig?','Pourquoi les abeilles ont-elles besoin d''un point d''eau proche ?','Why do bees need a nearby water source?',
 '["Om de kast te koelen en larven te voeden","Bijen drinken nooit water","Enkel om te baden","Water trekt enkel roofdieren aan"]'::jsonb,
 '["Pour refroidir la ruche et nourrir les larves","Les abeilles ne boivent jamais d''eau","Seulement pour se baigner","L''eau n''attire que des prédateurs"]'::jsonb,
 '["To cool the hive and feed larvae","Bees never drink water","Only to bathe","Water only attracts predators"]'::jsonb,
 0,'Bijen gebruiken water om de kast te koelen via verdamping en om voedsel voor larven te bereiden.','Les abeilles utilisent l''eau pour refroidir la ruche par évaporation et préparer la nourriture des larves.','Bees use water to cool the hive by evaporation and to prepare larval food.'),
(2,'tekst','Waar halen bijen hun belangrijkste voedsel vandaan?','D''où les abeilles tirent-elles leur principale nourriture ?','Where do bees get their main food from?',
 '["Nectar en stuifmeel van bloemen","Enkel suikerwater van imkers","Vlees van andere insecten","Regenwater"]'::jsonb,
 '["Le nectar et le pollen des fleurs","Uniquement l''eau sucrée des apiculteurs","La viande d''autres insectes","L''eau de pluie"]'::jsonb,
 '["Nectar and pollen from flowers","Only sugar water from beekeepers","Meat from other insects","Rainwater"]'::jsonb,
 0,'Nectar geeft energie en stuifmeel levert eiwitten, essentieel voor het bijenvolk en broed.','Le nectar apporte de l''énergie et le pollen des protéines, essentiels pour la colonie et le couvain.','Nectar provides energy and pollen provides protein, essential for the colony and brood.'),
(2,'tekst','Wanneer geven imkers bijen extra suikerwater?','Quand les apiculteurs donnent-ils de l''eau sucrée aux abeilles ?','When do beekeepers give bees extra sugar water?',
 '["Bij voedseltekort, bijvoorbeeld in vroege lente of winter","Elke dag het hele jaar","Nooit, dat is verboden","Enkel in de zomer bij overvloed"]'::jsonb,
 '["En cas de pénurie, par exemple au printemps ou en hiver","Chaque jour toute l''année","Jamais, c''est interdit","Uniquement en été en cas d''abondance"]'::jsonb,
 '["During food shortage, such as early spring or winter","Every day all year round","Never, it is forbidden","Only in summer when food is abundant"]'::jsonb,
 0,'Bijvoeren helpt een volk overleven wanneer er te weinig bloemen bloeien voor voldoende nectar.','Le nourrissage aide la colonie à survivre quand trop peu de fleurs sont en fleur.','Supplemental feeding helps a colony survive when too few flowers are blooming.'),
(2,'tekst','Wat is een teken van een gezond bijenvolk?','Quel est un signe d''une colonie d''abeilles en bonne santé ?','What is a sign of a healthy bee colony?',
 '["Actieve in- en uitvliegende bijen en broed in de raten","Volledige stilte aan de kastingang","Veel dode bijen voor de kast","Geen enkele bij zichtbaar overdag"]'::jsonb,
 '["Des abeilles actives entrant et sortant, du couvain dans les rayons","Un silence total à l''entrée de la ruche","Beaucoup d''abeilles mortes devant la ruche","Aucune abeille visible en journée"]'::jsonb,
 '["Active bees flying in and out, brood present in the comb","Complete silence at the hive entrance","Many dead bees in front of the hive","No bees visible during the day"]'::jsonb,
 0,'Regelmatige vliegactiviteit en gezond broed wijzen op een sterk, goed functionerend bijenvolk.','Une activité de vol régulière et un couvain sain indiquent une colonie forte et bien portante.','Regular flight activity and healthy brood indicate a strong, well-functioning colony.'),
(2,'tekst','Waarom is het belangrijk om bijenkasten te controleren op ziektes?','Pourquoi est-il important de vérifier les maladies des ruches ?','Why is it important to check hives for diseases?',
 '["Om ziektes zoals varroamijt vroeg te herkennen en te behandelen","Ziektes bij bijen bestaan niet","Het is verplicht maar nutteloos","Enkel voor de statistiek"]'::jsonb,
 '["Pour détecter et traiter tôt des maladies comme le varroa","Les maladies des abeilles n''existent pas","C''est obligatoire mais inutile","Uniquement pour les statistiques"]'::jsonb,
 '["To detect and treat diseases like varroa mite early","Bee diseases do not exist","It is mandatory but useless","Only for statistics"]'::jsonb,
 0,'De varroamijt is wereldwijd een belangrijke bedreiging en vroege opsporing redt bijenvolken.','L''acarien varroa est une menace majeure dans le monde, la détection précoce sauve les colonies.','The varroa mite is a major worldwide threat, and early detection saves colonies.'),
(3,'tekst','Waarom mag je nooit zomaar een bijenkast openen zonder imker?','Pourquoi ne faut-il jamais ouvrir une ruche sans apiculteur ?','Why should you never open a hive without a beekeeper?',
 '["Het kan gevaarlijk zijn en de bijen ernstig verstoren","Het is altijd volledig veilig","Bijen merken het niet op","Het is enkel voor de show"]'::jsonb,
 '["Cela peut être dangereux et perturber gravement les abeilles","C''est toujours totalement sûr","Les abeilles ne le remarquent pas","C''est juste pour le spectacle"]'::jsonb,
 '["It can be dangerous and seriously disturb the bees","It is always completely safe","Bees do not notice it","It is only for show"]'::jsonb,
 0,'Een imker gebruikt rook en beschermende kleding om de bijen kalm te houden en zichzelf te beschermen.','Un apiculteur utilise fumée et vêtements protecteurs pour calmer les abeilles et se protéger.','A beekeeper uses smoke and protective clothing to keep bees calm and stay safe.'),
(3,'tekst','Hoe kan je bijen het best observeren op een kinderboerderij?','Comment observer les abeilles au mieux à la ferme urbaine ?','How can you best observe bees at a city farm?',
 '["Op veilige afstand, rustig en zonder plotse bewegingen","Door vlak bij de kastingang te staan zwaaien","Door de kast aan te raken","Door luid te roepen"]'::jsonb,
 '["À distance sûre, calmement et sans mouvements brusques","En agitant les bras près de l''entrée de la ruche","En touchant la ruche","En criant fort"]'::jsonb,
 '["From a safe distance, calmly and without sudden movements","By waving your arms near the hive entrance","By touching the hive","By shouting loudly"]'::jsonb,
 0,'Bijen reageren op snelle bewegingen en trillingen, dus rustig observeren voorkomt stress bij mens en dier.','Les abeilles réagissent aux mouvements brusques et vibrations, observer calmement évite le stress.','Bees react to sudden movements and vibrations, so calm observation avoids stress for everyone.'),
(3,'tekst','Wat betekent het als bijen luid zoemen en druk rondvliegen bij de kast?','Que signifie un bourdonnement fort et une agitation près de la ruche ?','What does loud buzzing and busy flying near the hive mean?',
 '["Het volk kan gestrest of verstoord zijn","Bijen zijn dan altijd aan het slapen","Het betekent niets bijzonders","De bijen willen enkel spelen"]'::jsonb,
 '["La colonie peut être stressée ou dérangée","Les abeilles dorment toujours dans ce cas","Cela ne signifie rien de particulier","Les abeilles veulent juste jouer"]'::jsonb,
 '["The colony may be stressed or disturbed","Bees are then always sleeping","It means nothing special","The bees just want to play"]'::jsonb,
 0,'Verhoogde activiteit en zoemen kunnen wijzen op verstoring, dus geef de kast dan ruimte.','Une activité et un bourdonnement accrus peuvent indiquer un dérangement, il faut alors laisser de l''espace.','Increased activity and buzzing can indicate disturbance, so give the hive space.'),
(3,'tekst','Waarom steken bijen meestal niet zomaar zonder reden?','Pourquoi les abeilles ne piquent-elles généralement pas sans raison ?','Why do bees usually not sting without reason?',
 '["Een bij sterft na het steken, dus ze doet dit enkel ter verdediging","Bijen steken willekeurig en vaak","Ze steken enkel voor plezier","Bijen kunnen niet steken"]'::jsonb,
 '["Une abeille meurt après avoir piqué, elle ne le fait donc que pour se défendre","Les abeilles piquent au hasard et souvent","Elles piquent juste pour le plaisir","Les abeilles ne peuvent pas piquer"]'::jsonb,
 '["A bee dies after stinging, so it only does so in self-defence","Bees sting randomly and often","They sting just for fun","Bees cannot sting"]'::jsonb,
 0,'Omdat een steek de bij zelf het leven kost, steekt ze enkel wanneer ze zich bedreigd voelt.','Comme piquer coûte la vie à l''abeille, elle ne le fait que si elle se sent menacée.','Because stinging costs the bee its life, it only stings when it feels threatened.')
) AS v(module,vraag_type,nl,fr,en,onl,ofr,oen,ci,wnl,wfr,wen);

-- Geit
WITH a AS (
  INSERT INTO public.academies (diersoort_naam, diersoort_naam_fr, diersoort_naam_en, slug, badge_icon, vragen_per_test, slaag_grens, beschrijving, beschrijving_fr, beschrijving_en, categorie, prioriteit)
  VALUES ('Geit','Chèvre','Goat','geit','geit',12,9,'Leer over huisvesting, voeding en gedrag van geiten voor een fijn leven op de kinderboerderij.','Découvrez le logement, l''alimentation et le comportement des chèvres pour une belle vie à la ferme.','Learn about housing, food and behaviour of goats for a good life at the city farm.','boerderij',62)
  RETURNING id
)
INSERT INTO public.academy_vragen (academy_id, module, vraag_type, vraag_tekst, vraag_tekst_fr, vraag_tekst_en, opties, opties_fr, opties_en, correcte_optie_index, wist_je_dat, wist_je_dat_fr, wist_je_dat_en)
SELECT a.id, v.module, v.vraag_type, v.nl, v.fr, v.en, v.onl, v.ofr, v.oen, v.ci, v.wnl, v.wfr, v.wen
FROM a, (VALUES
(1,'tekst','Wat hebben geiten nodig in hun stal?','De quoi les chèvres ont-elles besoin dans leur abri ?','What do goats need in their shelter?',
 '["Een droge, tochtvrije ligplaats met stro","Enkel een betonnen vloer zonder stro","Continu fel licht","Een volledig kale ruimte"]'::jsonb,
 '["Un couchage sec et sans courants d''air, avec de la paille","Uniquement un sol en béton sans paille","Une lumière vive en continu","Un espace totalement vide"]'::jsonb,
 '["A dry, draught-free bedded area with straw","Only a concrete floor without straw","Continuous bright light","A completely bare space"]'::jsonb,
 0,'Geiten zijn gevoelig voor vocht en tocht, droog stro voorkomt longproblemen.','Les chèvres sont sensibles à l''humidité, la paille sèche prévient les problèmes pulmonaires.','Goats are sensitive to damp; dry straw helps prevent lung problems.'),
(1,'tekst','Waarom hebben geiten graag verhogingen om op te klimmen?','Pourquoi les chèvres aiment-elles grimper sur des surélévations ?','Why do goats like elevated platforms to climb on?',
 '["Klimmen is natuurlijk gedrag en verrijkt hun omgeving","Geiten klimmen nooit","Het is enkel gevaarlijk","Ze doen dit om te ontsnappen"]'::jsonb,
 '["Grimper est un comportement naturel qui enrichit leur environnement","Les chèvres ne grimpent jamais","C''est uniquement dangereux","Elles le font pour s''échapper"]'::jsonb,
 '["Climbing is natural behaviour that enriches their environment","Goats never climb","It is only dangerous","They do it to escape"]'::jsonb,
 0,'In het wild leven geiten op rotsachtig terrein, klimstructuren stimuleren hun natuurlijk gedrag.','À l''état sauvage, les chèvres vivent en terrain rocheux, les structures stimulent ce comportement naturel.','In the wild, goats live on rocky terrain; climbing structures encourage this natural behaviour.'),
(1,'tekst','Hoeveel ruimte hebben geiten minstens nodig om zich normaal te gedragen?','De combien d''espace minimum les chèvres ont-elles besoin ?','How much space do goats need at minimum to behave normally?',
 '["Voldoende ruimte om te bewegen, spelen en elkaar te ontwijken","Amper genoeg om te blijven staan","Geiten hebben geen ruimte nodig","Enkel een klein hok van 1m²"]'::jsonb,
 '["Assez d''espace pour bouger, jouer et s''éviter","À peine assez pour rester debout","Les chèvres n''ont pas besoin d''espace","Un enclos d''à peine 1 m²"]'::jsonb,
 '["Enough space to move, play and avoid each other","Barely enough to stand","Goats do not need space","A tiny 1m² pen"]'::jsonb,
 0,'Te weinig ruimte leidt tot stress en conflicten binnen de groep.','Un espace insuffisant entraîne stress et conflits au sein du groupe.','Too little space leads to stress and conflict within the group.'),
(1,'tekst','Waarom moeten geiten nooit alleen gehouden worden?','Pourquoi les chèvres ne doivent-elles jamais être seules ?','Why should goats never be kept alone?',
 '["Het zijn kuddedieren die gezelschap nodig hebben","Geiten verkiezen eenzaamheid","Het maakt geen verschil","Ze worden agressiever in een groep"]'::jsonb,
 '["Ce sont des animaux grégaires qui ont besoin de compagnie","Les chèvres préfèrent la solitude","Cela ne fait aucune différence","Elles deviennent plus agressives en groupe"]'::jsonb,
 '["They are herd animals that need companionship","Goats prefer solitude","It makes no difference","They become more aggressive in groups"]'::jsonb,
 0,'Een geit alleen houden veroorzaakt ernstige stress omdat ze van nature in een kudde leven.','Garder une chèvre seule cause un stress sévère car elle vit naturellement en troupeau.','Keeping a single goat causes severe stress because they naturally live in herds.'),
(2,'tekst','Wat vormt het grootste deel van het dieet van een geit?','Quelle est la base principale de l''alimentation d''une chèvre ?','What forms the main part of a goat''s diet?',
 '["Hooi, gras en bladeren van struiken","Enkel brood en koekjes","Vlees en vis","Uitsluitend krachtvoer"]'::jsonb,
 '["Foin, herbe et feuilles d''arbustes","Uniquement du pain et des biscuits","Viande et poisson","Uniquement des aliments concentrés"]'::jsonb,
 '["Hay, grass and shrub leaves","Only bread and biscuits","Meat and fish","Exclusively concentrated feed"]'::jsonb,
 0,'Geiten zijn browsers die van nature bladeren en struiken eten, niet enkel gras zoals schapen.','Les chèvres sont des broutardes qui mangent feuilles et arbustes, pas seulement de l''herbe comme les moutons.','Goats are browsers that naturally eat leaves and shrubs, not just grass like sheep.'),
(2,'tekst','Waarom is het gevaarlijk om geiten brood of koekjes te voeren?','Pourquoi est-il dangereux de nourrir les chèvres avec du pain ou des biscuits ?','Why is it dangerous to feed goats bread or biscuits?',
 '["Het kan hun spijsvertering verstoren en tot gezondheidsproblemen leiden","Geiten hebben dit net nodig","Het is hun favoriete en gezondste voer","Het heeft geen enkel effect"]'::jsonb,
 '["Cela peut perturber leur digestion et causer des problèmes de santé","Les chèvres en ont justement besoin","C''est leur nourriture préférée et la plus saine","Cela n''a aucun effet"]'::jsonb,
 '["It can upset their digestion and cause health problems","Goats actually need this","It is their favourite and healthiest food","It has no effect at all"]'::jsonb,
 0,'Suikerrijk en bewerkt voedsel kan pensproblemen en zwaarlijvigheid veroorzaken bij geiten.','Les aliments sucrés et transformés peuvent causer des troubles ruminaux et l''obésité chez les chèvres.','Sugary, processed food can cause rumen problems and obesity in goats.'),
(2,'tekst','Waarom moeten geitenhoeven regelmatig bijgesneden worden?','Pourquoi les sabots des chèvres doivent-ils être taillés régulièrement ?','Why do goat hooves need regular trimming?',
 '["Om overgroei, kreupelheid en infecties te voorkomen","Hoeven groeien niet bij geiten","Het is enkel esthetisch","Het is nooit nodig"]'::jsonb,
 '["Pour éviter la surcroissance, la boiterie et les infections","Les sabots des chèvres ne poussent pas","C''est purement esthétique","Ce n''est jamais nécessaire"]'::jsonb,
 '["To prevent overgrowth, lameness and infections","Goat hooves do not grow","It is purely cosmetic","It is never necessary"]'::jsonb,
 0,'Onverzorgde hoeven kunnen misvormen en pijnlijke infecties veroorzaken, geregeld bijsnijden is nodig.','Des sabots non entretenus peuvent se déformer et provoquer des infections douloureuses.','Untrimmed hooves can deform and cause painful infections; regular trimming is needed.'),
(2,'tekst','Wat is een teken van goede gezondheid bij een geit?','Quel est un signe de bonne santé chez une chèvre ?','What is a sign of good health in a goat?',
 '["Heldere ogen, actieve houding en goede eetlust","Doffe vacht en volledige lusteloosheid","Constant hoesten","Weigeren van alle voedsel"]'::jsonb,
 '["Des yeux clairs, une attitude active et un bon appétit","Un pelage terne et une léthargie totale","Une toux constante","Refuser toute nourriture"]'::jsonb,
 '["Bright eyes, an active posture and good appetite","Dull coat and complete lethargy","Constant coughing","Refusing all food"]'::jsonb,
 0,'Een gezonde geit is alert en nieuwsgierig, met een glanzende vacht en goede eetlust.','Une chèvre en bonne santé est alerte et curieuse, avec un pelage brillant et un bon appétit.','A healthy goat is alert and curious, with a shiny coat and good appetite.'),
(3,'tekst','Waarom vormen geiten een strikte rangorde binnen de kudde?','Pourquoi les chèvres établissent-elles une hiérarchie stricte dans le troupeau ?','Why do goats form a strict hierarchy within the herd?',
 '["Het regelt toegang tot voedsel en rustplekken en vermindert conflicten","Geiten hebben geen sociale structuur","Het is enkel toeval","Rangorde bestaat niet bij geiten"]'::jsonb,
 '["Cela règle l''accès à la nourriture et aux zones de repos, réduisant les conflits","Les chèvres n''ont pas de structure sociale","C''est purement aléatoire","La hiérarchie n''existe pas chez les chèvres"]'::jsonb,
 '["It regulates access to food and resting spots and reduces conflict","Goats have no social structure","It is purely random","Hierarchy does not exist in goats"]'::jsonb,
 0,'Een duidelijke rangorde vermindert agressie doordat elke geit haar plaats in de groep kent.','Une hiérarchie claire réduit l''agressivité car chaque chèvre connaît sa place dans le groupe.','A clear hierarchy reduces aggression because each goat knows its place in the group.'),
(3,'tekst','Hoe reageer je best als een geit tegen je opdringt om aandacht?','Comment réagir si une chèvre s''appuie sur vous pour attirer l''attention ?','How should you react if a goat pushes against you for attention?',
 '["Rustig blijven en grenzen stellen zonder te straffen","Onmiddellijk wegrennen","De geit hard wegduwen","Haar altijd meteen voeren als beloning"]'::jsonb,
 '["Rester calme et poser des limites sans punir","Fuir immédiatement","Repousser violemment la chèvre","Toujours la nourrir immédiatement en récompense"]'::jsonb,
 '["Stay calm and set boundaries without punishing","Run away immediately","Push the goat away hard","Always feed her immediately as a reward"]'::jsonb,
 0,'Duidelijke, kalme grenzen leren geiten respectvol gedrag zonder angst te veroorzaken.','Des limites claires et calmes apprennent aux chèvres un comportement respectueux sans provoquer de peur.','Clear, calm boundaries teach goats respectful behaviour without causing fear.'),
(3,'tekst','Wat betekent het als een geit met de horens stampt of duwt tegen soortgenoten?','Que signifie une chèvre qui donne des coups de cornes à ses congénères ?','What does it mean when a goat headbutts other goats?',
 '["Het is vaak een teken van rangordebepaling of spel","Het gebeurt nooit bij geiten","Het betekent altijd ernstige ziekte","Het is puur toeval zonder betekenis"]'::jsonb,
 '["C''est souvent un signe d''établissement de hiérarchie ou de jeu","Cela n''arrive jamais chez les chèvres","Cela signifie toujours une maladie grave","C''est purement aléatoire sans signification"]'::jsonb,
 '["It is often a sign of establishing rank or play","It never happens with goats","It always means serious illness","It is purely random and meaningless"]'::jsonb,
 0,'Koppen stoten is normaal sociaal gedrag bij geiten om rang te bepalen of te spelen.','Le heurtement des têtes est un comportement social normal pour établir un rang ou jouer.','Headbutting is normal social behaviour in goats to establish rank or play.'),
(3,'tekst','Waarom is het belangrijk om kinderen te leren hoe ze veilig met geiten omgaan op de kinderboerderij?','Pourquoi est-il important d''apprendre aux enfants à interagir en sécurité avec les chèvres ?','Why is it important to teach children safe interaction with goats?',
 '["Om stress bij dieren en ongelukken bij kinderen te voorkomen","Geiten zijn nooit gevaarlijk voor kinderen","Kinderen weten dit vanzelf","Het is niet nodig op een kinderboerderij"]'::jsonb,
 '["Pour éviter le stress chez les animaux et les accidents chez les enfants","Les chèvres ne sont jamais dangereuses pour les enfants","Les enfants le savent naturellement","Ce n''est pas nécessaire à la ferme urbaine"]'::jsonb,
 '["To prevent animal stress and accidents involving children","Goats are never dangerous to children","Children know this naturally","It is unnecessary at a city farm"]'::jsonb,
 0,'Rustig en respectvol gedrag zorgt voor een veilige, positieve ervaring voor kind en dier.','Un comportement calme et respectueux garantit une expérience sûre et positive pour l''enfant et l''animal.','Calm, respectful behaviour ensures a safe, positive experience for both child and animal.')
) AS v(module,vraag_type,nl,fr,en,onl,ofr,oen,ci,wnl,wfr,wen);
