-- Extra vragenpool: vergroot de vijver zodat niet iedereen dezelfde test krijgt.
-- Idempotent: bestaande vragen met dezelfde NL-tekst worden overgeslagen.

INSERT INTO public.academy_vragen
  (academy_id, module, vraag_type, vraag_tekst, vraag_tekst_fr, vraag_tekst_en,
   opties, opties_fr, opties_en, correcte_optie_index, wist_je_dat, wist_je_dat_fr, wist_je_dat_en)
SELECT a.id, v.module, 'tekst', v.nl, v.fr, v.en, v.onl::jsonb, v.ofr::jsonb, v.oen::jsonb, v.ci, v.wnl, v.wfr, v.wen
FROM (VALUES

-- ============================ KIP ============================
('kip',1,'Hoeveel ruimte heeft een kip minstens nodig in een ren?','De combien d''espace une poule a-t-elle besoin au minimum dans un enclos ?','How much space does a hen need at minimum in a run?',
 '["Ongeveer 1 tot 2 m² per kip","10 cm² per kip","Ruimte maakt niet uit","Enkel het hok telt"]',
 '["Environ 1 à 2 m² par poule","10 cm² par poule","L''espace n''a pas d''importance","Seul le poulailler compte"]',
 '["About 1 to 2 m² per hen","10 cm² per hen","Space does not matter","Only the coop counts"]',
 0,'Te weinig ruimte leidt tot verenpikken en stress in de groep.','Trop peu d''espace provoque du picage et du stress dans le groupe.','Too little space causes feather pecking and stress in the flock.'),
('kip',1,'Waarom leven kippen best niet alleen?','Pourquoi les poules ne devraient-elles pas vivre seules ?','Why should chickens not live alone?',
 '["Kippen zijn groepsdieren met een rangorde","Ze vechten altijd","Ze eten dan minder","Alleen is gezonder"]',
 '["Les poules sont des animaux grégaires avec une hiérarchie","Elles se battent toujours","Elles mangent moins","Seules, elles sont plus saines"]',
 '["Chickens are social animals with a pecking order","They always fight","They eat less","Alone is healthier"]',
 0,'De term "pikorde" komt letterlijk uit het gedrag van kippen.','Le terme « ordre de picage » vient littéralement du comportement des poules.','The term "pecking order" comes literally from chicken behaviour.'),
('kip',2,'Hoeveel water drinkt een kip ongeveer per dag?','Combien d''eau boit une poule par jour environ ?','Roughly how much water does a hen drink per day?',
 '["Ongeveer een kwart tot een halve liter","Een druppel","Vijf liter","Kippen drinken niet"]',
 '["Environ un quart à un demi-litre","Une goutte","Cinq litres","Les poules ne boivent pas"]',
 '["About a quarter to half a litre","A drop","Five litres","Hens do not drink"]',
 0,'Een ei bestaat voor ongeveer 75% uit water: vers drinkwater is dus cruciaal.','Un œuf est composé à environ 75 % d''eau : l''eau fraîche est donc essentielle.','An egg is about 75% water, so fresh drinking water is crucial.'),
('kip',2,'Welk voedsel is gevaarlijk voor kippen?','Quel aliment est dangereux pour les poules ?','Which food is dangerous for chickens?',
 '["Beschimmeld brood en zout keukenafval","Graan","Groenteresten","Gras"]',
 '["Pain moisi et déchets salés","Des céréales","Des restes de légumes","De l''herbe"]',
 '["Mouldy bread and salty kitchen waste","Grain","Vegetable scraps","Grass"]',
 0,'Schimmels maken gifstoffen die de lever van kippen zwaar beschadigen.','Les moisissures produisent des toxines qui abîment le foie des poules.','Moulds produce toxins that badly damage a chicken''s liver.'),
('kip',3,'Wat doe je bij een kip met een bleke, omgevallen kam?','Que faire si une poule a une crête pâle et tombante ?','What do you do with a hen that has a pale, floppy comb?',
 '["Apart zetten en een dierenarts raadplegen","Niets doen","Extra koud water geven","Meteen in de ren jagen"]',
 '["L''isoler et consulter un vétérinaire","Ne rien faire","Donner de l''eau très froide","La chasser dans l''enclos"]',
 '["Separate her and consult a vet","Do nothing","Give very cold water","Chase her into the run"]',
 0,'De kam is een goede gezondheidsmeter: kleur en stevigheid verraden problemen.','La crête est un bon indicateur de santé : couleur et fermeté révèlent les soucis.','The comb is a good health indicator: colour and firmness reveal problems.'),
('kip',3,'Wat gebeurt er tijdens de rui?','Que se passe-t-il pendant la mue ?','What happens during the moult?',
 '["Kippen verliezen veren en leggen tijdelijk minder","Ze worden agressief","Ze stoppen met drinken","Er gebeurt niets"]',
 '["Les poules perdent des plumes et pondent moins","Elles deviennent agressives","Elles arrêtent de boire","Rien ne se passe"]',
 '["Hens lose feathers and lay fewer eggs","They become aggressive","They stop drinking","Nothing happens"]',
 0,'Veren maken kost veel eiwit, daarom pauzeert de leg tijdens de rui.','Fabriquer des plumes coûte des protéines, la ponte s''interrompt donc.','Growing feathers costs protein, so laying pauses during the moult.'),

-- ============================ KONIJN ============================
('konijn',1,'Waarom is een konijn alleen houden geen goed idee?','Pourquoi garder un lapin seul est-il déconseillé ?','Why is keeping a rabbit alone a bad idea?',
 '["Konijnen zijn sociale dieren en hebben soortgenoten nodig","Ze vechten altijd","Ze slapen liever alleen","Twee konijnen eten te veel"]',
 '["Les lapins sont sociaux et ont besoin de congénères","Ils se battent toujours","Ils préfèrent dormir seuls","Deux lapins mangent trop"]',
 '["Rabbits are social and need company of their own kind","They always fight","They prefer sleeping alone","Two rabbits eat too much"]',
 0,'In België wordt een gecastreerd koppel als de beste combinatie gezien.','En Belgique, un couple stérilisé est considéré comme la meilleure combinaison.','A neutered pair is considered the best combination.'),
('konijn',1,'Hoe hoog moet een konijnenverblijf minstens zijn?','Quelle hauteur minimale pour un enclos à lapins ?','How high should a rabbit enclosure be at minimum?',
 '["Hoog genoeg om rechtop te staan op de achterpoten","20 cm","Zo laag mogelijk","Hoogte speelt geen rol"]',
 '["Assez haut pour se dresser sur les pattes arrière","20 cm","Le plus bas possible","La hauteur n''importe pas"]',
 '["High enough to stand up on the hind legs","20 cm","As low as possible","Height does not matter"]',
 0,'Rechtop staan hoort bij normaal konijnengedrag en houdt de rug soepel.','Se dresser fait partie du comportement normal du lapin.','Standing upright is normal rabbit behaviour.'),
('konijn',2,'Wat is het belangrijkste onderdeel van het konijnenmenu?','Quel est l''élément principal du menu du lapin ?','What is the main part of a rabbit''s diet?',
 '["Onbeperkt hooi","Brokken","Fruit","Brood"]',
 '["Du foin à volonté","Des granulés","Des fruits","Du pain"]',
 '["Unlimited hay","Pellets","Fruit","Bread"]',
 0,'Hooi slijt de tanden die levenslang doorgroeien en houdt de darm in beweging.','Le foin use les dents qui poussent en continu et fait travailler l''intestin.','Hay wears down continuously growing teeth and keeps the gut moving.'),
('konijn',2,'Wat betekent het als een konijn 24 uur niets eet?','Que signifie un lapin qui ne mange rien pendant 24 heures ?','What does it mean if a rabbit eats nothing for 24 hours?',
 '["Spoedgeval: meteen naar de dierenarts","Het dieet werkt","Het is normaal","Gewoon minder voer geven"]',
 '["Urgence : chez le vétérinaire immédiatement","Le régime fonctionne","C''est normal","Donner moins de nourriture"]',
 '["An emergency: go to the vet immediately","The diet works","It is normal","Just feed less"]',
 0,'Een stilgevallen darm (GI-stasis) kan bij konijnen op een dag dodelijk zijn.','Une stase digestive peut être mortelle en un jour chez le lapin.','Gut stasis can be fatal within a day in rabbits.'),
('konijn',3,'Waarom eten konijnen hun eigen zachte keutels?','Pourquoi les lapins mangent-ils leurs crottes molles ?','Why do rabbits eat their own soft droppings?',
 '["Om vitaminen opnieuw op te nemen (caecotrofie)","Uit verveling","Omdat ze honger lijden","Dat doen ze nooit"]',
 '["Pour réabsorber des vitamines (caecotrophie)","Par ennui","Parce qu''ils ont faim","Ils ne le font jamais"]',
 '["To reabsorb vitamins (caecotrophy)","Out of boredom","Because they are starving","They never do this"]',
 0,'Die zachte blindedarmkeutels zitten vol B-vitaminen en eiwit.','Ces crottes du caecum sont riches en vitamines B et en protéines.','These caecal pellets are full of B vitamins and protein.'),
('konijn',3,'Welke temperatuur is gevaarlijk voor konijnen?','Quelle température est dangereuse pour les lapins ?','Which temperature is dangerous for rabbits?',
 '["Boven 28 °C in de volle zon","10 °C","15 °C","Koude is het enige gevaar"]',
 '["Au-dessus de 28 °C en plein soleil","10 °C","15 °C","Le froid est le seul danger"]',
 '["Above 28 °C in full sun","10 °C","15 °C","Cold is the only danger"]',
 0,'Konijnen kunnen niet zweten en raken snel oververhit; schaduw is verplicht.','Les lapins ne transpirent pas et surchauffent vite : l''ombre est indispensable.','Rabbits cannot sweat and overheat quickly; shade is essential.'),

-- ============================ GEIT ============================
('geit',1,'Waarom klimmen geiten graag?','Pourquoi les chèvres aiment-elles grimper ?','Why do goats love to climb?',
 '["Het is natuurlijk gedrag van rotsdieren","Om te ontsnappen","Ze vervelen zich altijd","Dat doen ze nooit"]',
 '["C''est un comportement naturel d''animaux de rochers","Pour s''échapper","Elles s''ennuient toujours","Elles ne le font jamais"]',
 '["It is natural behaviour of rock-dwelling animals","To escape","They are always bored","They never do"]',
 0,'Klimobjecten in de wei voorkomen verveling en houden de hoeven gezond.','Des objets à escalader évitent l''ennui et gardent les onglons sains.','Climbing objects prevent boredom and keep hooves healthy.'),
('geit',1,'Waarom heeft een geit een droge schuilplaats nodig?','Pourquoi une chèvre a-t-elle besoin d''un abri sec ?','Why does a goat need a dry shelter?',
 '["Geiten verdragen regen en vocht slecht","Ze houden van modder","Om te verstoppen voor bezoekers","Dat is niet nodig"]',
 '["Les chèvres supportent mal la pluie et l''humidité","Elles aiment la boue","Pour se cacher des visiteurs","Ce n''est pas nécessaire"]',
 '["Goats tolerate rain and damp poorly","They love mud","To hide from visitors","It is not needed"]',
 0,'Nat blijven leidt bij geiten snel tot longontsteking en rotkreupel.','Rester mouillé mène vite à la pneumonie et au piétin.','Staying wet quickly leads to pneumonia and foot rot.'),
('geit',2,'Wat eet een geit van nature het liefst?','Que préfère manger une chèvre naturellement ?','What does a goat naturally prefer to eat?',
 '["Blad, twijgen en ruw gewas","Enkel brood","Vlees","Enkel granen"]',
 '["Feuilles, branchages et végétation grossière","Uniquement du pain","De la viande","Uniquement des céréales"]',
 '["Leaves, twigs and rough vegetation","Only bread","Meat","Only grain"]',
 0,'Geiten zijn "browsers": ze knabbelen liever aan struiken dan aan gras.','Les chèvres sont des « brouteuses de branches » plutôt que d''herbe.','Goats are browsers: they prefer shrubs over grass.'),
('geit',2,'Waarom mag je geiten geen brood voeren op bezoek?','Pourquoi ne pas donner de pain aux chèvres en visite ?','Why should visitors not feed bread to goats?',
 '["Het verstoort de pensflora en maakt ze ziek","Ze lusten het niet","Het is te duur","Het mag wel"]',
 '["Cela perturbe la flore du rumen et les rend malades","Elles n''aiment pas ça","C''est trop cher","C''est permis"]',
 '["It upsets the rumen flora and makes them ill","They dislike it","It is too expensive","It is allowed"]',
 0,'Een pens werkt op vezels; zetmeel doet de zuurtegraad gevaarlijk dalen.','Le rumen fonctionne aux fibres ; l''amidon fait chuter le pH.','A rumen runs on fibre; starch drops the pH dangerously.'),
('geit',3,'Hoe vaak moeten geitenhoeven bekapt worden?','À quelle fréquence tailler les onglons d''une chèvre ?','How often should goat hooves be trimmed?',
 '["Ongeveer om de 6 tot 10 weken","Eén keer per leven","Nooit","Elke dag"]',
 '["Environ toutes les 6 à 10 semaines","Une fois dans la vie","Jamais","Chaque jour"]',
 '["About every 6 to 10 weeks","Once in a lifetime","Never","Every day"]',
 0,'Te lange hoeven veroorzaken pijn, kreupelheid en gewrichtsproblemen.','Des onglons trop longs causent douleur et boiterie.','Overgrown hooves cause pain and lameness.'),
('geit',3,'Wat is een teken van een gezonde geit?','Quel est le signe d''une chèvre en bonne santé ?','What is a sign of a healthy goat?',
 '["Alert, herkauwend en met een glanzende vacht","Afgezonderd in een hoek","Hangende oren en hoesten","Weigert te drinken"]',
 '["Vive, ruminante et au pelage brillant","Isolée dans un coin","Oreilles tombantes et toux","Refuse de boire"]',
 '["Alert, chewing cud and with a shiny coat","Isolated in a corner","Drooping ears and coughing","Refusing to drink"]',
 0,'Herkauwen is het duidelijkste teken dat de spijsvertering goed draait.','La rumination est le signe le plus clair d''une bonne digestion.','Chewing cud is the clearest sign that digestion is working.'),

-- ============================ BIJEN ============================
('bijen',1,'Welke bij legt de eitjes in een bijenvolk?','Quelle abeille pond les œufs dans la colonie ?','Which bee lays the eggs in a colony?',
 '["De koningin","Elke werkster","De dar","Niemand"]',
 '["La reine","Chaque ouvrière","Le faux-bourdon","Personne"]',
 '["The queen","Every worker","The drone","Nobody"]',
 0,'Een koningin legt in het hoogseizoen tot 2000 eitjes per dag.','Une reine pond jusqu''à 2000 œufs par jour en pleine saison.','A queen lays up to 2,000 eggs a day in high season.'),
('bijen',1,'Wat is de taak van de darren?','Quel est le rôle des faux-bourdons ?','What is the role of drones?',
 '["De koningin bevruchten","Honing maken","De kast bewaken","Stuifmeel halen"]',
 '["Féconder la reine","Faire du miel","Garder la ruche","Récolter le pollen"]',
 '["To mate with the queen","To make honey","To guard the hive","To collect pollen"]',
 0,'Darren hebben geen angel en worden in de herfst uit de kast gezet.','Les faux-bourdons n''ont pas de dard et sont expulsés en automne.','Drones have no sting and are evicted in autumn.'),
('bijen',2,'Waarvoor dient stuifmeel in de bijenkast?','À quoi sert le pollen dans la ruche ?','What is pollen used for in the hive?',
 '["Als eiwitbron voor het broed","Als water","Als bouwmateriaal voor de kast","Nergens voor"]',
 '["Comme source de protéines pour le couvain","Comme eau","Comme matériau de construction","À rien"]',
 '["As a protein source for the brood","As water","As building material","For nothing"]',
 0,'Nectar levert energie, stuifmeel levert de eiwitten voor groeiende larven.','Le nectar fournit l''énergie, le pollen les protéines des larves.','Nectar gives energy, pollen gives protein for growing larvae.'),
('bijen',2,'Waarom laat je in de winter voldoende honing in de kast?','Pourquoi laisser assez de miel dans la ruche en hiver ?','Why leave enough honey in the hive in winter?',
 '["Het is de wintervoorraad van het volk","Voor de smaak","Om dieven te lokken","Dat hoeft niet"]',
 '["C''est la réserve hivernale de la colonie","Pour le goût","Pour attirer les voleurs","Ce n''est pas nécessaire"]',
 '["It is the colony''s winter food store","For flavour","To attract thieves","It is not needed"]',
 0,'Een volk verwarmt de tros op zo''n 20 °C en verbruikt daarvoor veel honing.','La grappe se maintient vers 20 °C, ce qui consomme beaucoup de miel.','The cluster keeps around 20 °C, which burns a lot of honey.'),
('bijen',3,'Wat doe je als een bij op je arm landt?','Que faire si une abeille se pose sur votre bras ?','What do you do if a bee lands on your arm?',
 '["Rustig blijven en ze laten wegvliegen","Slaan","Wegblazen met veel lawaai","Vastpakken"]',
 '["Rester calme et la laisser repartir","Frapper","Souffler bruyamment","L''attraper"]',
 '["Stay calm and let it fly off","Swat it","Blow at it loudly","Grab it"]',
 0,'Bijen steken enkel bij bedreiging: een steek kost een werkster het leven.','Les abeilles ne piquent que menacées : la piqûre leur coûte la vie.','Bees only sting when threatened; stinging costs a worker her life.'),
('bijen',3,'Waarom zijn bijen belangrijk voor de stad?','Pourquoi les abeilles sont-elles importantes en ville ?','Why are bees important for the city?',
 '["Ze bestuiven planten en moestuinen","Ze maken enkel lawaai","Ze verjagen vogels","Ze zijn niet nuttig"]',
 '["Elles pollinisent les plantes et les potagers","Elles font du bruit","Elles chassent les oiseaux","Elles ne servent à rien"]',
 '["They pollinate plants and vegetable gardens","They only make noise","They chase birds away","They are not useful"]',
 0,'Ook wilde bijen en hommels bestuiven mee: bloemenweides helpen hen allemaal.','Les abeilles sauvages et bourdons pollinisent aussi : les prairies fleuries les aident.','Wild bees and bumblebees pollinate too; flower meadows help them all.'),

-- ============================ HAMSTER ============================
('hamster',1,'Waarom moet een hamster alleen gehuisvest worden?','Pourquoi loger un hamster seul ?','Why should a hamster be housed alone?',
 '["Syrische hamsters zijn solitair en vechten anders","Ze zijn bang in het donker","Om plaats te sparen","Dat klopt niet"]',
 '["Les hamsters syriens sont solitaires et se battent sinon","Ils ont peur du noir","Pour gagner de la place","C''est faux"]',
 '["Syrian hamsters are solitary and will fight otherwise","They fear the dark","To save space","That is not true"]',
 0,'Samen huisvesten van Syrische hamsters eindigt bijna altijd in ernstige gevechten.','Loger deux hamsters syriens finit presque toujours en bagarre grave.','Housing two Syrian hamsters together almost always ends in serious fights.'),
('hamster',1,'Hoe diep moet de bodembedekking minstens zijn?','Quelle profondeur minimale de litière ?','How deep should the bedding be at minimum?',
 '["Minstens 20 cm om te graven","1 cm","Geen bodembedekking","Enkel krantenpapier"]',
 '["Au moins 20 cm pour creuser","1 cm","Aucune litière","Uniquement du papier journal"]',
 '["At least 20 cm so it can burrow","1 cm","No bedding","Only newspaper"]',
 0,'Graven is een basisbehoefte: te weinig bodem geeft stressgedrag zoals tralie­bijten.','Creuser est un besoin de base : trop peu de litière cause du stress.','Burrowing is a basic need; too little bedding causes stress behaviour.'),
('hamster',2,'Wanneer is een hamster het actiefst?','Quand un hamster est-il le plus actif ?','When is a hamster most active?',
 '["''s Avonds en ''s nachts","Midden op de dag","Nooit","Enkel in de winter"]',
 '["Le soir et la nuit","En pleine journée","Jamais","Seulement en hiver"]',
 '["In the evening and at night","In the middle of the day","Never","Only in winter"]',
 0,'Een hamster overdag wakker maken verstoort zijn slaapritme en maakt hem bijterig.','Réveiller un hamster en journée perturbe son sommeil et le rend mordeur.','Waking a hamster by day disrupts its sleep and makes it nippy.'),
('hamster',2,'Welk loopwiel is veilig?','Quelle roue est sûre ?','Which exercise wheel is safe?',
 '["Een dicht wiel van minstens 20-30 cm","Een wiel met spijlen","Een heel klein wiel","Geen wiel"]',
 '["Une roue pleine d''au moins 20-30 cm","Une roue à barreaux","Une très petite roue","Pas de roue"]',
 '["A solid wheel of at least 20-30 cm","A wheel with rungs","A very small wheel","No wheel"]',
 0,'Een te klein wiel dwingt de rug in een bocht en beschadigt de wervelkolom.','Une roue trop petite courbe le dos et abîme la colonne.','A wheel that is too small bends the back and damages the spine.'),
('hamster',3,'Wat betekent een uitpuilende wangzak vol voer?','Que signifient des abajoues pleines de nourriture ?','What do bulging cheek pouches full of food mean?',
 '["Normaal hamstergedrag: voorraad aanleggen","Een ziekte","Dat hij te veel eet","Dat hij dorst heeft"]',
 '["Comportement normal : faire des réserves","Une maladie","Qu''il mange trop","Qu''il a soif"]',
 '["Normal hamster behaviour: hoarding food","An illness","That it eats too much","That it is thirsty"]',
 0,'Het woord "hamsteren" komt letterlijk van dit gedrag.','Le mot « hamstérer » vient littéralement de ce comportement.','The word "hamstering" comes literally from this behaviour.'),
('hamster',3,'Wat is een teken dat een hamster ziek is?','Quel signe indique un hamster malade ?','What is a sign that a hamster is ill?',
 '["Natte staart, vermageren en apathie","Graven","Rennen in het wiel","Eten verstoppen"]',
 '["Queue humide, amaigrissement et apathie","Creuser","Courir dans la roue","Cacher la nourriture"]',
 '["Wet tail, weight loss and apathy","Digging","Running in the wheel","Hiding food"]',
 0,'"Wet tail" is een ernstige darminfectie die snel behandeling vraagt.','La « wet tail » est une infection intestinale grave à traiter vite.','"Wet tail" is a serious gut infection needing quick treatment.'),

-- ============================ STADSHOND ============================
('stadshond',1,'Wat is de regel voor hondenpoep in Brussel?','Quelle est la règle pour les crottes de chien à Bruxelles ?','What is the rule for dog poop in Brussels?',
 '["Altijd opruimen en meenemen in een zakje","Enkel in het park opruimen","Naast het pad duwen","Er is geen regel"]',
 '["Toujours ramasser et emporter dans un sachet","Ramasser seulement au parc","Pousser à côté du chemin","Il n''y a pas de règle"]',
 '["Always pick it up and take it in a bag","Only clean up in the park","Push it off the path","There is no rule"]',
 0,'Niet opruimen kan in Brussel een gemeentelijke boete opleveren.','Ne pas ramasser peut entraîner une amende communale à Bruxelles.','Not cleaning up can lead to a municipal fine in Brussels.'),
('stadshond',1,'Wanneer mag een hond los lopen in een park?','Quand un chien peut-il être en liberté dans un parc ?','When may a dog run off-leash in a park?',
 '["Alleen in een aangeduide hondenzone","Overal","Nooit met een leiband","Enkel ''s nachts"]',
 '["Uniquement dans une zone canine indiquée","Partout","Jamais avec une laisse","Seulement la nuit"]',
 '["Only in a signposted dog zone","Everywhere","Never on a lead","Only at night"]',
 0,'In het Maximiliaanpark loopt een hond aan de leiband, uit respect voor de dieren.','Au parc Maximilien, le chien reste en laisse par respect pour les animaux.','In Maximilian Park dogs stay on the lead out of respect for the animals.'),
('stadshond',2,'Hoeveel beweging heeft een gemiddelde hond per dag nodig?','De combien d''exercice un chien moyen a-t-il besoin par jour ?','How much exercise does an average dog need per day?',
 '["Minstens één tot twee uur wandelen en snuffelen","Vijf minuten","Enkel de tuin","Geen beweging"]',
 '["Au moins une à deux heures de promenade et de flair","Cinq minutes","Juste le jardin","Aucun exercice"]',
 '["At least one to two hours of walking and sniffing","Five minutes","Just the garden","No exercise"]',
 0,'Snuffelen is mentaal even vermoeiend als rennen: laat je hond ruiken.','Renifler fatigue autant que courir : laissez votre chien flairer.','Sniffing tires a dog as much as running: let them smell.'),
('stadshond',2,'Wat doe je bij warm weer met je hond in de stad?','Que faire par temps chaud avec son chien en ville ?','What do you do with your dog in hot city weather?',
 '["Wandel vroeg of laat en vermijd hete stoepen","Wandel om 14 u op asfalt","Laat hem in de auto","Geef minder water"]',
 '["Promener tôt ou tard et éviter les trottoirs brûlants","Promener à 14 h sur l''asphalte","Le laisser en voiture","Donner moins d''eau"]',
 '["Walk early or late and avoid hot pavements","Walk at 2 pm on asphalt","Leave it in the car","Give less water"]',
 0,'Asfalt kan 50 °C worden en de voetzolen van een hond verbranden.','L''asphalte peut atteindre 50 °C et brûler les coussinets.','Asphalt can reach 50 °C and burn a dog''s paw pads.'),
('stadshond',3,'Hoe benader je een onbekende hond?','Comment aborder un chien inconnu ?','How do you approach an unfamiliar dog?',
 '["Eerst aan de baasje vragen en rustig blijven","Meteen knuffelen","Van bovenaf op het hoofd grijpen","Luid roepen"]',
 '["Demander d''abord au maître et rester calme","Le câliner directement","Attraper la tête par-dessus","Crier fort"]',
 '["Ask the owner first and stay calm","Hug it immediately","Grab its head from above","Shout loudly"]',
 0,'Van bovenaf naderen voelt bedreigend; een hond leest lichaamstaal heel precies.','Approcher par le dessus est menaçant ; le chien lit le langage corporel.','Approaching from above feels threatening; dogs read body language closely.'),
('stadshond',3,'Waarom laat je je hond niet bij de boerderijdieren?','Pourquoi ne pas laisser son chien près des animaux de la ferme ?','Why keep your dog away from the farm animals?',
 '["Het stresst de dieren en kan ziektes overdragen","Honden zijn er bang","De dieren bijten altijd","Dat mag wel"]',
 '["Cela stresse les animaux et transmet des maladies","Les chiens ont peur","Les animaux mordent toujours","C''est permis"]',
 '["It stresses the animals and can spread disease","Dogs get scared","The animals always bite","It is allowed"]',
 0,'Zelfs een blaffende hond aan de omheining laat kippen en geiten in paniek slaan.','Même un chien qui aboie à la clôture panique poules et chèvres.','Even a barking dog at the fence panics chickens and goats.')

) AS v(slug, module, nl, fr, en, onl, ofr, oen, ci, wnl, wfr, wen)
JOIN public.academies a ON a.slug = v.slug
WHERE NOT EXISTS (
  SELECT 1 FROM public.academy_vragen q
   WHERE q.academy_id = a.id AND q.vraag_tekst = v.nl
);
