WITH a AS (
  INSERT INTO public.academies (diersoort_naam, diersoort_naam_fr, diersoort_naam_en, slug, badge_icon, vragen_per_test, slaag_grens, beschrijving, beschrijving_fr, beschrijving_en, categorie, prioriteit)
  VALUES ('Vogelspin','Mygale','Tarantula','vogelspin','vogelspin',12,9,'Ontdek hoe je een vogelspin op een diervriendelijke manier huisvest, voedt en observeert zonder haar te stressen.','Découvrez comment loger, nourrir et observer une mygale de façon respectueuse, sans jamais la stresser inutilement.','Learn how to house, feed and observe a tarantula responsibly, without ever stressing or handling her needlessly.','invertebraten',30)
  RETURNING id
)
INSERT INTO public.academy_vragen (academy_id, module, vraag_type, vraag_tekst, vraag_tekst_fr, vraag_tekst_en, opties, opties_fr, opties_en, correcte_optie_index, wist_je_dat, wist_je_dat_fr, wist_je_dat_en)
SELECT a.id, v.module, v.vraag_type, v.nl, v.fr, v.en, v.onl, v.ofr, v.oen, v.ci, v.wnl, v.wfr, v.wen
FROM a, (VALUES
  (1,'tekst','Hoeveel bodemsubstraat heeft een vogelspin minimaal nodig om te kunnen graven?','De combien de substrat une mygale a-t-elle besoin au minimum pour pouvoir creuser ?','How much substrate does a tarantula need at minimum to be able to burrow?',
   '["Enkele centimeters","Minstens 10-15 cm diep","Geen substraat nodig","Slechts een dun laagje zand"]'::jsonb,
   '["Quelques centimètres","Au moins 10-15 cm de profondeur","Pas de substrat nécessaire","Une fine couche de sable seulement"]'::jsonb,
   '["A few centimeters","At least 10-15 cm deep","No substrate needed","Just a thin layer of sand"]'::jsonb,
   1,'Veel soorten graven holen; te weinig substraat verhindert natuurlijk gedrag en verhoogt stress.','De nombreuses espèces creusent des terriers ; trop peu de substrat empêche ce comportement naturel et augmente le stress.','Many species burrow; too little substrate prevents natural behaviour and increases stress.'),
  (1,'tekst','Welke luchtvochtigheid hebben de meeste vogelspinsoorten in hun terrarium nodig?','Quel taux d''humidité la plupart des mygales ont-elles besoin dans leur terrarium ?','What humidity level do most tarantula species need in their enclosure?',
   '["Zo droog mogelijk","Afhankelijk van de soort, 60-80%","Altijd 100% vochtig","Vochtigheid speelt geen rol"]'::jsonb,
   '["Le plus sec possible","Selon l''espèce, 60-80%","Toujours 100% d''humidité","L''humidité n''a aucune importance"]'::jsonb,
   '["As dry as possible","Depending on species, 60-80%","Always 100% humidity","Humidity does not matter"]'::jsonb,
   1,'De juiste vochtigheid is essentieel voor een geslaagde vervelling en gezonde ademhaling.','Une humidité adaptée est essentielle pour une mue réussie et une respiration saine.','Correct humidity is essential for a successful moult and healthy breathing.'),
  (1,'tekst','Wat is een belangrijk verschil tussen een boombewonende en een grondbewonende vogelspin qua terrarium?','Quelle est une différence importante entre une mygale arboricole et terricole concernant le terrarium ?','What is an important difference between an arboreal and terrestrial tarantula regarding the enclosure?',
   '["Geen verschil","De boombewonende soort heeft meer hoogte nodig","De grondsoort heeft geen substraat nodig","Boombewonende soorten hebben geen deksel nodig"]'::jsonb,
   '["Aucune différence","L''espèce arboricole a besoin de plus de hauteur","L''espèce terricole n''a pas besoin de substrat","Les espèces arboricoles n''ont pas besoin de couvercle"]'::jsonb,
   '["No difference","The arboreal species needs more vertical space","The terrestrial species needs no substrate","Arboreal species need no lid"]'::jsonb,
   1,'Boombewonende vogelspinnen klimmen graag en hebben verticale ruimte en klimstructuren nodig.','Les mygales arboricoles aiment grimper et ont besoin d''espace vertical et de structures pour grimper.','Arboreal tarantulas like to climb and need vertical space and climbing structures.'),
  (1,'tekst','Waarom is een goed sluitend deksel op het terrarium belangrijk?','Pourquoi un couvercle bien fermé sur le terrarium est-il important ?','Why is a well-fitting lid on the enclosure important?',
   '["Om ontsnapping te voorkomen en veiligheid te garanderen","Puur decoratief","Om het terrarium zwaarder te maken","Vogelspinnen hebben geen deksel nodig"]'::jsonb,
   '["Pour éviter toute évasion et garantir la sécurité","Purement décoratif","Pour alourdir le terrarium","Les mygales n''ont pas besoin de couvercle"]'::jsonb,
   '["To prevent escape and ensure safety","Purely decorative","To make the enclosure heavier","Tarantulas do not need a lid"]'::jsonb,
   0,'Vogelspinnen zijn verrassend behendige klimmers en kunnen via kleine openingen ontsnappen.','Les mygales sont des grimpeuses étonnamment agiles et peuvent s''échapper par de petites ouvertures.','Tarantulas are surprisingly agile climbers and can escape through small gaps.'),
  (2,'tekst','Hoe vaak moet een volwassen vogelspin gemiddeld gevoerd worden?','À quelle fréquence une mygale adulte doit-elle être nourrie en moyenne ?','On average, how often should an adult tarantula be fed?',
   '["Dagelijks","Eén keer per week tot per twee weken","Elke maand slechts één keer per jaar","Nooit, ze eten vanzelf niets"]'::jsonb,
   '["Chaque jour","Une fois par semaine à toutes les deux semaines","Une seule fois par an","Jamais, elles ne mangent pas"]'::jsonb,
   '["Daily","Once a week to once every two weeks","Only once a year","Never, they do not eat"]'::jsonb,
   1,'Vogelspinnen hebben een trage stofwisseling en kunnen weken zonder voedsel overleven.','Les mygales ont un métabolisme lent et peuvent survivre des semaines sans nourriture.','Tarantulas have a slow metabolism and can survive weeks without food.'),
  (2,'tekst','Wat is een teken dat een vogelspin binnenkort gaat vervellen?','Quel est un signe indiquant qu''une mygale va bientôt muer ?','What is a sign that a tarantula is about to moult?',
   '["Ze weigert eten en ligt op haar rug","Ze wordt agressiever dan ooit","Ze verliest kleur volledig","Ze eet plots dubbel zoveel"]'::jsonb,
   '["Elle refuse de manger et se met sur le dos","Elle devient plus agressive que jamais","Elle perd complètement sa couleur","Elle mange soudain deux fois plus"]'::jsonb,
   '["She stops eating and flips onto her back","She becomes more aggressive than ever","She loses all colour","She suddenly eats twice as much"]'::jsonb,
   0,'Voor de vervelling eten vogelspinnen vaak niet meer en trekken ze zich terug.','Avant la mue, les mygales cessent souvent de manger et se retirent.','Before moulting, tarantulas often stop eating and withdraw.'),
  (2,'tekst','Waarom moet er steeds een waterschaaltje aanwezig zijn?','Pourquoi une coupelle d''eau doit-elle toujours être présente ?','Why should a water dish always be present?',
   '["Om te voorkomen dat de spin uitdroogt","Vogelspinnen drinken nooit water","Enkel voor de sier","Om de luchtvochtigheid te verlagen"]'::jsonb,
   '["Pour éviter que la mygale ne se déshydrate","Les mygales ne boivent jamais d''eau","Uniquement pour la décoration","Pour réduire l''humidité"]'::jsonb,
   '["To prevent the spider from dehydrating","Tarantulas never drink water","Purely decorative","To lower humidity"]'::jsonb,
   0,'Ondanks hun beperkte waterbehoefte moeten vogelspinnen steeds toegang hebben tot vers water.','Malgré leurs besoins limités en eau, les mygales doivent toujours avoir accès à de l''eau fraîche.','Despite limited water needs, tarantulas must always have access to fresh water.'),
  (2,'tekst','Wat moet je doen met onaangeraakte prooidieren na een tijdje?','Que faire des proies non consommées après un certain temps ?','What should you do with uneaten prey after a while?',
   '["Ze laten zitten, dat is normaal","Ze verwijderen om stress en verwondingen te vermijden","Meer prooien toevoegen","De spin dwingen te eten"]'::jsonb,
   '["Les laisser, c''est normal","Les retirer pour éviter le stress et les blessures","Ajouter plus de proies","Forcer la mygale à manger"]'::jsonb,
   '["Leave them, it is normal","Remove them to avoid stress and injury","Add more prey","Force the spider to eat"]'::jsonb,
   1,'Levende prooien kunnen een vervellende of rustende vogelspin verwonden als ze te lang blijven.','Les proies vivantes peuvent blesser une mygale en mue ou au repos si elles restent trop longtemps.','Live prey can injure a moulting or resting tarantula if left too long.'),
  (3,'tekst','Waarom is het afgeraden om een vogelspin op te pakken?','Pourquoi est-il déconseillé de manipuler une mygale ?','Why is it discouraged to handle a tarantula?',
   '["Ze zijn giftig voor mensen","Vallen kan haar verwonden en het stresst het dier","Ze houden ervan om gedragen te worden","Het is verplicht volgens de wet"]'::jsonb,
   '["Elles sont venimeuses pour l''humain","Une chute peut la blesser et cela stresse l''animal","Elles adorent être portées","C''est obligatoire par la loi"]'::jsonb,
   '["They are poisonous to humans","A fall can injure her and it stresses the animal","They enjoy being carried","It is legally required"]'::jsonb,
   1,'Een val van zelfs een geringe hoogte kan het achterlijf van een vogelspin fataal beschadigen.','Une chute, même de faible hauteur, peut endommager fatalement l''abdomen d''une mygale.','A fall from even a small height can fatally damage a tarantula''s abdomen.'),
  (3,'tekst','Wat zijn urticerende haren en waarvoor gebruikt de vogelspin ze?','Que sont les poils urticants et à quoi servent-ils à la mygale ?','What are urticating hairs and what does the tarantula use them for?',
   '["Om te horen","Verdediging tegen bedreigingen","Om te ruiken","Om warmte vast te houden"]'::jsonb,
   '["Pour entendre","Défense contre les menaces","Pour sentir","Pour retenir la chaleur"]'::jsonb,
   '["For hearing","Defence against threats","For smelling","For retaining heat"]'::jsonb,
   1,'Sommige Amerikaanse soorten schoppen prikkende haartjes van hun achterlijf als afweer tegen indringers.','Certaines espèces américaines projettent des poils urticants de leur abdomen pour se défendre.','Some American species kick urticating hairs from their abdomen to defend against intruders.'),
  (3,'tekst','Hoe reageert een vogelspin doorgaans op plotse trillingen of licht?','Comment une mygale réagit-elle généralement aux vibrations ou lumières soudaines ?','How does a tarantula typically react to sudden vibrations or light?',
   '["Ze verstijft van blijdschap","Ze schrikt en trekt zich terug of vlucht","Ze komt dichterbij nieuwsgierig","Ze reageert nooit ergens op"]'::jsonb,
   '["Elle se fige de joie","Elle sursaute et se retire ou fuit","Elle s''approche par curiosité","Elle ne réagit jamais à rien"]'::jsonb,
   '["She freezes with joy","She startles and retreats or flees","She curiously approaches","She never reacts to anything"]'::jsonb,
   1,'Vogelspinnen zijn schuwe dieren en trillingen worden vaak als bedreiging ervaren.','Les mygales sont des animaux craintifs et perçoivent souvent les vibrations comme une menace.','Tarantulas are shy animals and often perceive vibrations as a threat.'),
  (3,'tekst','Wat is de beste aanpak bij het bezoeken van vogelspinnen op de kinderboerderij?','Quelle est la meilleure approche lors de la visite des mygales à la ferme pour enfants ?','What is the best approach when visiting tarantulas at the city farm?',
   '["Tikken tegen het glas voor aandacht","Rustig kijken zonder te kloppen of te schudden","Het terrarium openen om te aaien","Luid roepen om reactie uit te lokken"]'::jsonb,
   '["Taper sur la vitre pour attirer l''attention","Observer calmement sans frapper ni secouer","Ouvrir le terrarium pour la caresser","Crier fort pour provoquer une réaction"]'::jsonb,
   '["Tap the glass to get attention","Watch calmly without knocking or shaking","Open the enclosure to pet her","Shout loudly to provoke a reaction"]'::jsonb,
   1,'Rustig observeren respecteert het welzijn van het dier en vermijdt onnodige stress.','Observer calmement respecte le bien-être de l''animal et évite un stress inutile.','Calm observation respects the animal''s welfare and avoids unnecessary stress.')
) AS v(module,vraag_type,nl,fr,en,onl,ofr,oen,ci,wnl,wfr,wen);

WITH a AS (
  INSERT INTO public.academies (diersoort_naam, diersoort_naam_fr, diersoort_naam_en, slug, badge_icon, vragen_per_test, slaag_grens, beschrijving, beschrijving_fr, beschrijving_en, categorie, prioriteit)
  VALUES ('Wandelende tak','Phasme','Stick Insect','wandelende-tak','wandelende-tak',12,9,'Leer alles over de juiste voeding, klimruimte en verzorging van wandelende takken op een kinderboerderij.','Apprenez tout sur l''alimentation, l''espace pour grimper et les soins adaptés aux phasmes dans une ferme pour enfants.','Learn all about proper feeding, climbing space and care for stick insects at a city farm.','invertebraten',31)
  RETURNING id
)
INSERT INTO public.academy_vragen (academy_id, module, vraag_type, vraag_tekst, vraag_tekst_fr, vraag_tekst_en, opties, opties_fr, opties_en, correcte_optie_index, wist_je_dat, wist_je_dat_fr, wist_je_dat_en)
SELECT a.id, v.module, v.vraag_type, v.nl, v.fr, v.en, v.onl, v.ofr, v.oen, v.ci, v.wnl, v.wfr, v.wen
FROM a, (VALUES
  (1,'tekst','Hoe hoog moet een terrarium voor wandelende takken minstens zijn?','Quelle doit être la hauteur minimale d''un terrarium pour phasmes ?','How tall should a stick insect enclosure be at minimum?',
   '["Even hoog als breed","Minstens drie keer de lichaamslengte van het dier","Precies 5 cm","Hoogte maakt niet uit"]'::jsonb,
   '["Aussi haut que large","Au moins trois fois la longueur du corps de l''animal","Exactement 5 cm","La hauteur n''a pas d''importance"]'::jsonb,
   '["As tall as it is wide","At least three times the animal''s body length","Exactly 5 cm","Height does not matter"]'::jsonb,
   1,'Voldoende hoogte is nodig zodat het dier zich veilig kan vasthouden tijdens de vervelling.','Une hauteur suffisante est nécessaire pour que l''animal puisse s''accrocher en sécurité pendant la mue.','Sufficient height is needed so the animal can safely hang during moulting.'),
  (1,'tekst','Welke luchtvochtigheid verkiezen de meeste wandelende takken?','Quel taux d''humidité la plupart des phasmes préfèrent-ils ?','What humidity level do most stick insects prefer?',
   '["Zeer droog, woestijnklimaat","Matig tot hoog, regelmatig besproeien","Nooit besproeien","Volledig onder water"]'::jsonb,
   '["Très sec, climat désertique","Modéré à élevé, vaporiser régulièrement","Ne jamais vaporiser","Complètement immergé"]'::jsonb,
   '["Very dry, desert climate","Moderate to high, spray regularly","Never spray","Fully submerged"]'::jsonb,
   1,'Regelmatig besproeien helpt niet alleen de vochtigheid, maar geeft de dieren ook water om te drinken.','Vaporiser régulièrement aide non seulement à l''humidité, mais donne aussi de l''eau à boire aux animaux.','Regular spraying not only helps humidity but also gives the animals water to drink.'),
  (1,'tekst','Wat is essentieel bodemmateriaal onderin het terrarium?','Quel matériau de fond est essentiel au fond du terrarium ?','What is essential substrate material at the bottom of the enclosure?',
   '["Scherp grind","Een zachte laag zoals aarde of vermiculiet","Niets, kale bodem volstaat","Metalen rooster"]'::jsonb,
   '["Gravier tranchant","Une couche souple comme de la terre ou du vermiculite","Rien, un fond nu suffit","Grille métallique"]'::jsonb,
   '["Sharp gravel","A soft layer such as soil or vermiculite","Nothing, a bare floor is fine","Metal grid"]'::jsonb,
   1,'Een zachte bodemlaag vangt vallende dieren op en helpt de vochtigheid te behouden.','Une couche de fond souple amortit la chute des animaux et aide à conserver l''humidité.','A soft substrate layer cushions falling animals and helps retain humidity.'),
  (1,'tekst','Waarom is voldoende ventilatie in het terrarium belangrijk?','Pourquoi une ventilation suffisante dans le terrarium est-elle importante ?','Why is sufficient ventilation in the enclosure important?',
   '["Om schimmel en te veel vocht te voorkomen","Ventilatie is niet nodig","Om het terrarium warmer te maken","Om geluid te dempen"]'::jsonb,
   '["Pour éviter les moisissures et l''excès d''humidité","La ventilation n''est pas nécessaire","Pour réchauffer le terrarium","Pour atténuer le bruit"]'::jsonb,
   '["To prevent mould and excess moisture","Ventilation is not necessary","To make the enclosure warmer","To dampen sound"]'::jsonb,
   0,'Zonder luchtcirculatie kan schimmel ontstaan op de voedselplanten, wat schadelijk is voor de dieren.','Sans circulation d''air, des moisissures peuvent apparaître sur les plantes nourricières, nuisibles aux animaux.','Without air circulation, mould can grow on food plants, which is harmful to the animals.'),
  (2,'tekst','Welke planten worden vaak als voedsel gebruikt voor wandelende takken?','Quelles plantes sont souvent utilisées comme nourriture pour les phasmes ?','Which plants are often used as food for stick insects?',
   '["Rozenblaadjes","Braamblad en klimop, afhankelijk van de soort","Enkel sla","Gras en stro"]'::jsonb,
   '["Pétales de rose","Ronce et lierre, selon l''espèce","Uniquement de la laitue","Herbe et paille"]'::jsonb,
   '["Rose petals","Bramble and ivy, depending on species","Only lettuce","Grass and straw"]'::jsonb,
   1,'Bramble en klimop zijn voor veel soorten geschikte en voedzame waardplanten.','La ronce et le lierre sont des plantes hôtes adaptées et nourrissantes pour de nombreuses espèces.','Bramble and ivy are suitable and nutritious host plants for many species.'),
  (2,'tekst','Hoe vaak moet vers voedsel ververst worden?','À quelle fréquence la nourriture fraîche doit-elle être renouvelée ?','How often should fresh food be replaced?',
   '["Om de maand","Elke twee tot drie dagen, voor het verwelkt","Nooit, verwelkt blad is prima","Elk uur"]'::jsonb,
   '["Une fois par mois","Tous les deux à trois jours, avant qu''elles ne se fanent","Jamais, les feuilles fanées conviennent","Toutes les heures"]'::jsonb,
   '["Once a month","Every two to three days, before it wilts","Never, wilted leaves are fine","Every hour"]'::jsonb,
   1,'Verse bladeren garanderen voldoende vocht en voedingsstoffen voor een gezonde spijsvertering.','Des feuilles fraîches garantissent suffisamment d''humidité et de nutriments pour une bonne digestion.','Fresh leaves ensure enough moisture and nutrients for healthy digestion.'),
  (2,'tekst','Wat kan wijzen op een gezonde vervelling bij een wandelende tak?','Qu''est-ce qui peut indiquer une mue saine chez un phasme ?','What can indicate a healthy moult in a stick insect?',
   '["Het dier verliest een poot en dat is normaal","De oude huid (exuvie) wordt volledig afgeworpen","Het dier stopt met bewegen voorgoed","Het dier verandert nooit van uiterlijk"]'::jsonb,
   '["L''animal perd une patte, c''est normal","La vieille peau (exuvie) est entièrement rejetée","L''animal arrête de bouger définitivement","L''animal ne change jamais d''apparence"]'::jsonb,
   '["The animal loses a leg and that is normal","The old skin (exuvia) is fully shed","The animal stops moving forever","The animal never changes appearance"]'::jsonb,
   1,'Een volledig afgeworpen exuvie wijst op een goed verlopen vervelling zonder complicaties.','Une exuvie entièrement rejetée indique une mue réussie sans complication.','A fully shed exuvia indicates a successful moult without complications.'),
  (2,'tekst','Waarom moet je bladeren wassen voor je ze aan wandelende takken geeft?','Pourquoi faut-il laver les feuilles avant de les donner aux phasmes ?','Why should you wash leaves before giving them to stick insects?',
   '["Om pesticiden en vervuiling te verwijderen","Om de smaak te verbeteren","Wassen is niet nodig","Om de bladeren te verkleuren"]'::jsonb,
   '["Pour éliminer les pesticides et la pollution","Pour améliorer le goût","Le lavage n''est pas nécessaire","Pour changer la couleur des feuilles"]'::jsonb,
   '["To remove pesticides and pollution","To improve the taste","Washing is not necessary","To change the leaf colour"]'::jsonb,
   0,'Pesticiden op bladeren kunnen zeer giftig zijn voor deze gevoelige insecten.','Les pesticides sur les feuilles peuvent être très toxiques pour ces insectes sensibles.','Pesticides on leaves can be highly toxic to these sensitive insects.'),
  (3,'tekst','Hoe gedragen wandelende takken zich meestal als reactie op gevaar?','Comment les phasmes réagissent-ils généralement face au danger ?','How do stick insects typically behave in response to danger?',
   '["Ze vallen stijf naar beneden of blijven roerloos staan (mimicry)","Ze bijten altijd terug","Ze vliegen onmiddellijk weg","Ze maken luid geluid"]'::jsonb,
   '["Ils se laissent tomber raides ou restent immobiles (mimétisme)","Ils mordent toujours en retour","Ils s''envolent immédiatement","Ils émettent un bruit fort"]'::jsonb,
   '["They drop stiffly or freeze motionless (mimicry)","They always bite back","They immediately fly away","They make a loud sound"]'::jsonb,
   0,'Wandelende takken vertrouwen op camouflage en verstijving als voornaamste verdediging tegen roofdieren.','Les phasmes comptent sur le camouflage et l''immobilité comme principale défense contre les prédateurs.','Stick insects rely on camouflage and freezing as their main defence against predators.'),
  (3,'tekst','Is het aangeraden om wandelende takken vaak vast te nemen?','Est-il recommandé de manipuler souvent les phasmes ?','Is it recommended to frequently handle stick insects?',
   '["Ja, dagelijks knuffelen is goed","Neen, beperk hanteren tot wat nodig is om stress te vermijden","Ja, ze houden ervan gedragen te worden","Het maakt niets uit"]'::jsonb,
   '["Oui, les câliner tous les jours est bon","Non, limiter la manipulation au strict nécessaire pour éviter le stress","Oui, ils adorent être portés","Cela n''a pas d''importance"]'::jsonb,
   '["Yes, daily cuddling is good","No, limit handling to what is necessary to avoid stress","Yes, they love being carried","It does not matter"]'::jsonb,
   1,'Fragiele pootjes kunnen makkelijk afbreken bij onvoorzichtig hanteren, dus beperk het tot een minimum.','Les pattes fragiles peuvent facilement se casser lors d''une manipulation imprudente, donc à limiter au minimum.','Fragile legs can easily break with careless handling, so it should be kept to a minimum.'),
  (3,'tekst','Wat moet je doen als je een wandelende tak toch even vastneemt?','Que faire si l''on doit tout de même manipuler un phasme un instant ?','What should you do if you do need to briefly handle a stick insect?',
   '["Aan een poot optillen","Laat het dier zelf op je hand lopen","Vastknijpen om het niet te laten ontsnappen","Aan de voelsprieten trekken"]'::jsonb,
   '["Le soulever par une patte","Laisser l''animal grimper lui-même sur la main","Le serrer pour l''empêcher de s''échapper","Tirer sur les antennes"]'::jsonb,
   '["Lift it by a leg","Let the animal walk onto your hand itself","Squeeze it so it cannot escape","Pull on the antennae"]'::jsonb,
   1,'Door het dier zelf te laten overstappen op je hand voorkom je verwondingen en stress.','En laissant l''animal grimper lui-même sur votre main, vous évitez blessures et stress.','By letting the animal walk onto your hand itself, you avoid injury and stress.'),
  (3,'tekst','Waarom worden veel wandelende takken ''s nachts actiever?','Pourquoi de nombreux phasmes sont-ils plus actifs la nuit ?','Why do many stick insects become more active at night?',
   '["Ze zijn van nature nachtdieren en vermijden zo roofdieren","Ze slapen altijd overdag door verveling","Licht doodt ze","Ze houden niet van warmte"]'::jsonb,
   '["Ils sont naturellement nocturnes et évitent ainsi les prédateurs","Ils dorment toujours le jour par ennui","La lumière les tue","Ils n''aiment pas la chaleur"]'::jsonb,
   '["They are naturally nocturnal and avoid predators this way","They always sleep during the day from boredom","Light kills them","They dislike warmth"]'::jsonb,
   0,'Nachtactiviteit vermindert de kans om overdag door vogels en andere roofdieren opgemerkt te worden.','L''activité nocturne réduit le risque d''être repéré le jour par les oiseaux et autres prédateurs.','Nocturnal activity reduces the chance of being spotted during the day by birds and other predators.')
) AS v(module,vraag_type,nl,fr,en,onl,ofr,oen,ci,wnl,wfr,wen);

WITH a AS (
  INSERT INTO public.academies (diersoort_naam, diersoort_naam_fr, diersoort_naam_en, slug, badge_icon, vragen_per_test, slaag_grens, beschrijving, beschrijving_fr, beschrijving_en, categorie, prioriteit)
  VALUES ('Reuzenslak','Escargot géant','Giant Snail','reuzenslak','reuzenslak',12,9,'Ontdek hoe je een Afrikaanse reuzenslak correct huisvest, voedt en verzorgt in een kinderboerderij-omgeving.','Découvrez comment loger, nourrir et soigner correctement un escargot géant africain dans une ferme pour enfants.','Discover how to properly house, feed and care for a giant African snail in a city farm setting.','invertebraten',32)
  RETURNING id
)
INSERT INTO public.academy_vragen (academy_id, module, vraag_type, vraag_tekst, vraag_tekst_fr, vraag_tekst_en, opties, opties_fr, opties_en, correcte_optie_index, wist_je_dat, wist_je_dat_fr, wist_je_dat_en)
SELECT a.id, v.module, v.vraag_type, v.nl, v.fr, v.en, v.onl, v.ofr, v.oen, v.ci, v.wnl, v.wfr, v.wen
FROM a, (VALUES
  (1,'tekst','Hoe dik moet de bodemlaag minstens zijn zodat een reuzenslak kan ingraven?','Quelle épaisseur minimale doit avoir la couche de fond pour qu''un escargot géant puisse s''enfouir ?','How thick should the substrate layer be at minimum so a giant snail can burrow?',
   '["1 cm volstaat","Minstens 5-8 cm diep, vochtige aarde","Geen substraat nodig","Enkel droog zand"]'::jsonb,
   '["1 cm suffit","Au moins 5-8 cm de terre humide","Pas de substrat nécessaire","Uniquement du sable sec"]'::jsonb,
   '["1 cm is enough","At least 5-8 cm deep, moist soil","No substrate needed","Only dry sand"]'::jsonb,
   1,'Reuzenslakken graven zich in om te rusten en eieren te leggen, daarvoor is diepe, vochtige aarde nodig.','Les escargots géants s''enfouissent pour se reposer et pondre, ce qui nécessite une terre profonde et humide.','Giant snails burrow to rest and lay eggs, which requires deep, moist soil.'),
  (1,'tekst','Welke luchtvochtigheid heeft een reuzenslak nodig in het terrarium?','De quel taux d''humidité un escargot géant a-t-il besoin dans le terrarium ?','What humidity level does a giant snail need in the enclosure?',
   '["Zeer laag, droog klimaat","Hoog, rond 80-90%","Er is geen vochtigheid nodig","Enkel ''s nachts vochtig"]'::jsonb,
   '["Très faible, climat sec","Élevée, autour de 80-90%","Aucune humidité n''est nécessaire","Humide uniquement la nuit"]'::jsonb,
   '["Very low, dry climate","High, around 80-90%","No humidity is needed","Only humid at night"]'::jsonb,
   1,'Een hoge luchtvochtigheid voorkomt uitdroging van de huid en houdt de slak actief en gezond.','Une humidité élevée évite le dessèchement de la peau et maintient l''escargot actif et en bonne santé.','High humidity prevents skin dehydration and keeps the snail active and healthy.'),
  (1,'tekst','Welke temperatuur is ideaal voor een Afrikaanse reuzenslak?','Quelle température est idéale pour un escargot géant africain ?','What temperature is ideal for an African giant snail?',
   '["Rond 10°C","Tussen 23-27°C","Boven 35°C","Onder 5°C"]'::jsonb,
   '["Autour de 10°C","Entre 23-27°C","Au-dessus de 35°C","En dessous de 5°C"]'::jsonb,
   '["Around 10°C","Between 23-27°C","Above 35°C","Below 5°C"]'::jsonb,
   1,'Als tropische soort heeft de reuzenslak een warme omgeving nodig om actief te blijven.','En tant qu''espèce tropicale, l''escargot géant a besoin d''un environnement chaud pour rester actif.','As a tropical species, the giant snail needs a warm environment to stay active.'),
  (1,'tekst','Waarom moet het terrarium goed afgesloten maar toch geventileerd zijn?','Pourquoi le terrarium doit-il être bien fermé mais tout de même ventilé ?','Why should the enclosure be well-sealed yet still ventilated?',
   '["Om ontsnapping te voorkomen en toch luchtcirculatie te behouden","Ventilatie is nooit nodig","Om de slak warmer te maken","Om vocht volledig te blokkeren"]'::jsonb,
   '["Pour éviter l''évasion tout en maintenant une circulation d''air","La ventilation n''est jamais nécessaire","Pour réchauffer l''escargot","Pour bloquer complètement l''humidité"]'::jsonb,
   '["To prevent escape while maintaining air circulation","Ventilation is never necessary","To make the snail warmer","To completely block moisture"]'::jsonb,
   0,'Reuzenslakken kunnen tegen glas omhoog kruipen, dus een gesloten maar geventileerd deksel is nodig.','Les escargots géants peuvent grimper le long du verre, un couvercle fermé mais ventilé est donc nécessaire.','Giant snails can crawl up glass, so a closed but ventilated lid is needed.'),
  (2,'tekst','Welke bron van calcium is essentieel voor een gezonde schelp?','Quelle source de calcium est essentielle pour une coquille saine ?','Which source of calcium is essential for a healthy shell?',
   '["Sepiaschelp of kalkblokjes","Enkel sla","Suikerwater","Zand"]'::jsonb,
   '["Os de seiche ou blocs de calcium","Uniquement de la laitue","Eau sucrée","Sable"]'::jsonb,
   '["Cuttlebone or calcium blocks","Only lettuce","Sugar water","Sand"]'::jsonb,
   0,'Zonder voldoende calcium wordt de schelp broos en kan die zelfs misvormen.','Sans calcium suffisant, la coquille devient fragile et peut même se déformer.','Without enough calcium, the shell becomes brittle and can even deform.'),
  (2,'tekst','Welk soort groenten en fruit is geschikt als hoofdvoeding?','Quel type de légumes et de fruits convient comme alimentation principale ?','What type of vegetables and fruit is suitable as staple food?',
   '["Alleen vlees","Verse sla, komkommer en fruit zoals appel","Chips en brood","Enkel droogvoer voor honden"]'::jsonb,
   '["Uniquement de la viande","Salade fraîche, concombre et fruits comme la pomme","Chips et pain","Uniquement des croquettes pour chiens"]'::jsonb,
   '["Only meat","Fresh lettuce, cucumber and fruit like apple","Chips and bread","Only dog kibble"]'::jsonb,
   1,'Verse groenten en fruit leveren de vezels en vochtigheid die reuzenslakken nodig hebben.','Les légumes et fruits frais apportent les fibres et l''humidité nécessaires aux escargots géants.','Fresh vegetables and fruit provide the fibre and moisture giant snails need.'),
  (2,'tekst','Welk voedsel moet je vermijden voor reuzenslakken?','Quel type de nourriture faut-il éviter pour les escargots géants ?','What kind of food should be avoided for giant snails?',
   '["Zout of bewerkt voedsel","Sla en komkommer","Sepiaschelp","Vochtige aarde"]'::jsonb,
   '["Nourriture salée ou transformée","Salade et concombre","Os de seiche","Terre humide"]'::jsonb,
   '["Salty or processed food","Lettuce and cucumber","Cuttlebone","Moist soil"]'::jsonb,
   0,'Zout is zeer schadelijk en kan zelfs dodelijk zijn voor slakken door uitdroging.','Le sel est très nocif et peut même être mortel pour les escargots par déshydratation.','Salt is very harmful and can even be lethal to snails due to dehydration.'),
  (2,'tekst','Hoe vaak moet het terrarium van een reuzenslak schoongemaakt worden?','À quelle fréquence le terrarium d''un escargot géant doit-il être nettoyé ?','How often should a giant snail enclosure be cleaned?',
   '["Nooit","Wekelijks, om schimmel en bacteriegroei te vermijden","Om de zes maanden","Enkel als het ruikt naar bloemen"]'::jsonb,
   '["Jamais","Chaque semaine, pour éviter moisissures et bactéries","Tous les six mois","Uniquement si cela sent la fleur"]'::jsonb,
   '["Never","Weekly, to avoid mould and bacterial growth","Every six months","Only if it smells like flowers"]'::jsonb,
   1,'Regelmatig schoonmaken houdt de leefomgeving hygiënisch en voorkomt ziektes bij de slak.','Un nettoyage régulier maintient un environnement hygiénique et prévient les maladies chez l''escargot.','Regular cleaning keeps the environment hygienic and prevents illness in the snail.'),
  (3,'tekst','Hoe moet je een reuzenslak correct oppakken?','Comment faut-il soulever correctement un escargot géant ?','How should you correctly pick up a giant snail?',
   '["Aan de schelp trekken","Voorzichtig onder het lichaam ondersteunen","Bij de voelsprieten vastnemen","Snel oppakken zonder waarschuwing"]'::jsonb,
   '["Tirer par la coquille","Soutenir délicatement sous le corps","Le saisir par les antennes","Le saisir rapidement sans prévenir"]'::jsonb,
   '["Pull by the shell","Gently support underneath the body","Grab it by the tentacles","Pick it up quickly without warning"]'::jsonb,
   1,'Voorzichtig ondersteunen voorkomt schade aan de kwetsbare voet en schelp van de slak.','Un soutien délicat évite d''endommager le pied fragile et la coquille de l''escargot.','Gentle support prevents damage to the snail''s vulnerable foot and shell.'),
  (3,'tekst','Waarom moeten handen gewassen worden na contact met een reuzenslak?','Pourquoi faut-il se laver les mains après avoir touché un escargot géant ?','Why should hands be washed after touching a giant snail?',
   '["Om hygiënische redenen, ze kunnen parasieten dragen","Slakkenslijm is giftig voor mensen","Het is niet nodig","Om de geur te verspreiden"]'::jsonb,
   '["Pour des raisons d''hygiène, ils peuvent porter des parasites","Le mucus est toxique pour l''humain","Ce n''est pas nécessaire","Pour répandre l''odeur"]'::jsonb,
   '["For hygiene reasons, they can carry parasites","Snail slime is toxic to humans","It is not necessary","To spread the scent"]'::jsonb,
   0,'Reuzenslakken kunnen drager zijn van parasieten, dus handen wassen is een belangrijke voorzorgsmaatregel.','Les escargots géants peuvent être porteurs de parasites, se laver les mains est donc une précaution importante.','Giant snails can carry parasites, so washing hands is an important precaution.'),
  (3,'tekst','Wat betekent het als een reuzenslak zich terugtrekt in zijn schelp met een vliesje (epifragma)?','Que signifie le fait qu''un escargot géant se retire dans sa coquille avec une membrane (épiphragme) ?','What does it mean when a giant snail withdraws into its shell with a membrane (epiphragm)?',
   '["Hij is ziek en gaat sterven","Hij beschermt zichzelf tegen droogte of kou (rust/aestivatie)","Hij wil spelen","Dit gebeurt nooit bij reuzenslakken"]'::jsonb,
   '["Il est malade et va mourir","Il se protège contre la sécheresse ou le froid (repos/estivation)","Il veut jouer","Cela n''arrive jamais chez les escargots géants"]'::jsonb,
   '["It is sick and will die","It protects itself from dryness or cold (rest/aestivation)","It wants to play","This never happens in giant snails"]'::jsonb,
   1,'Bij ongunstige omstandigheden vormt de slak een beschermend vliesje en gaat hij in rust.','En cas de conditions défavorables, l''escargot forme une membrane protectrice et entre en repos.','Under unfavourable conditions, the snail forms a protective membrane and goes into rest.'),
  (3,'tekst','Waarom is het belangrijk om reuzenslakken niet te lang in de hand te houden?','Pourquoi est-il important de ne pas garder un escargot géant trop longtemps dans la main ?','Why is it important not to hold a giant snail in your hand for too long?',
   '["De warmte en droogte van de hand kunnen hem stress geven","Ze bijten na een tijdje","Ze worden agressief","Er is geen enkel probleem mee"]'::jsonb,
   '["La chaleur et la sécheresse de la main peuvent lui causer du stress","Ils mordent après un moment","Ils deviennent agressifs","Il n''y a aucun problème"]'::jsonb,
   '["The warmth and dryness of the hand can cause it stress","They bite after a while","They become aggressive","There is no issue at all"]'::jsonb,
   0,'Lichaamswarmte en droge huid kunnen de vochtige huid van de slak uitdrogen en stress veroorzaken.','La chaleur corporelle et la peau sèche peuvent dessécher la peau humide de l''escargot et causer du stress.','Body heat and dry skin can dry out the snail''s moist skin and cause stress.')
) AS v(module,vraag_type,nl,fr,en,onl,ofr,oen,ci,wnl,wfr,wen);
