-- Kikker, pad & salamander
WITH a AS (
  INSERT INTO public.academies (diersoort_naam, diersoort_naam_fr, diersoort_naam_en, slug, badge_icon, vragen_per_test, slaag_grens, beschrijving, beschrijving_fr, beschrijving_en, categorie, prioriteit)
  VALUES ('Kikker, pad & salamander','Grenouille, crapaud & salamandre','Frog, toad & newt','kikker','kikker',15,12,'Leer alles over de levenscyclus van kikkers, padden en salamanders en hoe je een gezonde parkvijver onderhoudt.','Découvrez le cycle de vie des grenouilles, crapauds et salamandres et comment entretenir un étang sain.','Learn about the life cycle of frogs, toads and newts and how to maintain a healthy pond.','vijver',50)
  RETURNING id
)
INSERT INTO public.academy_vragen (academy_id, module, vraag_type, vraag_tekst, vraag_tekst_fr, vraag_tekst_en, opties, opties_fr, opties_en, correcte_optie_index, wist_je_dat, wist_je_dat_fr, wist_je_dat_en)
SELECT a.id, v.module, v.vraag_type, v.nl, v.fr, v.en, v.onl, v.ofr, v.oen, v.ci, v.wnl, v.wfr, v.wen
FROM a, (VALUES
(1,'tekst','Wat is de eerste levensfase van een kikker na het ei?','Quelle est la première phase de vie d''une grenouille après l''œuf ?','What is the first life stage of a frog after the egg?',
 '["Het dikkopje (kikkervisje)","Een volwassen kikker","Een pop zoals bij insecten","Een larve met vier poten"]'::jsonb,
 '["Le têtard","Une grenouille adulte","Une chrysalide comme chez les insectes","Une larve à quatre pattes"]'::jsonb,
 '["The tadpole","An adult frog","A pupa like an insect","A four-legged larva"]'::jsonb,
 0,'Een dikkopje ademt eerst met kieuwen en leeft volledig onder water, net als een vis.','Un têtard respire d''abord par des branchies et vit entièrement sous l''eau, comme un poisson.','A tadpole first breathes with gills and lives entirely underwater, like a fish.'),
(1,'tekst','In welke volgorde verloopt de metamorfose van een kikker?','Dans quel ordre se déroule la métamorphose d''une grenouille ?','In what order does a frog''s metamorphosis happen?',
 '["Ei, dikkopje, dikkopje met pootjes, jonge kikker","Ei, kikker, dikkopje","Dikkopje, ei, kikker","Kikker, ei, dikkopje met staart"]'::jsonb,
 '["Œuf, têtard, têtard avec pattes, jeune grenouille","Œuf, grenouille, têtard","Têtard, œuf, grenouille","Grenouille, œuf, têtard avec queue"]'::jsonb,
 '["Egg, tadpole, tadpole with legs, young frog","Egg, frog, tadpole","Tadpole, egg, frog","Frog, egg, tadpole with tail"]'::jsonb,
 0,'De staart van het dikkopje wordt tijdens de metamorfose langzaam opgenomen door het lichaam.','La queue du têtard est progressivement résorbée par le corps pendant la métamorphose.','The tadpole''s tail is gradually reabsorbed by the body during metamorphosis.'),
(1,'tekst','Wat is een duidelijk verschil tussen een kikker en een pad?','Quelle est une différence claire entre une grenouille et un crapaud ?','What is a clear difference between a frog and a toad?',
 '["Padden hebben een drogere, wrattige huid en korte poten","Kikkers leven enkel op het land","Padden kunnen niet zwemmen","Kikkers hebben geen ogen"]'::jsonb,
 '["Les crapauds ont une peau plus sèche et verruqueuse et des pattes courtes","Les grenouilles vivent uniquement sur terre","Les crapauds ne savent pas nager","Les grenouilles n''ont pas d''yeux"]'::jsonb,
 '["Toads have drier, warty skin and shorter legs","Frogs live only on land","Toads cannot swim","Frogs have no eyes"]'::jsonb,
 0,'Kikkers hebben lange achterpoten om ver te springen, padden bewegen meer kruipend.','Les grenouilles ont de longues pattes arrière pour sauter loin, les crapauds se déplacent plutôt en rampant.','Frogs have long hind legs for jumping far, while toads move more by crawling.'),
(1,'tekst','Wat is een kenmerk van een salamander tegenover een kikker?','Quelle est une caractéristique d''une salamandre par rapport à une grenouille ?','What is a feature of a salamander compared to a frog?',
 '["Salamanders behouden hun staart als volwassen dier","Salamanders hebben geen larvale fase","Salamanders leggen geen eieren","Salamanders zijn insecten"]'::jsonb,
 '["Les salamandres conservent leur queue à l''âge adulte","Les salamandres n''ont pas de phase larvaire","Les salamandres ne pondent pas d''œufs","Les salamandres sont des insectes"]'::jsonb,
 '["Salamanders keep their tail as an adult","Salamanders have no larval stage","Salamanders do not lay eggs","Salamanders are insects"]'::jsonb,
 0,'Salamanders behoren tot de staartamfibieën, kikkers en padden verliezen hun staart als volwassene.','Les salamandres appartiennent aux urodèles, alors que grenouilles et crapauds perdent leur queue à l''âge adulte.','Salamanders belong to the tailed amphibians, whereas frogs and toads lose their tail as adults.'),
(1,'tekst','Waarom mag je geen dikkopjes uit de vijver meenemen naar huis?','Pourquoi ne faut-il pas emporter des têtards de l''étang chez soi ?','Why should you not take tadpoles home from the pond?',
 '["Ze horen in hun natuurlijke leefomgeving om zich te ontwikkelen","Dikkopjes overleven overal even goed","Het is altijd toegestaan","Dikkopjes hebben geen water nodig"]'::jsonb,
 '["Ils doivent se développer dans leur habitat naturel","Les têtards survivent partout aussi bien","C''est toujours autorisé","Les têtards n''ont pas besoin d''eau"]'::jsonb,
 '["They belong in their natural habitat to develop properly","Tadpoles survive equally well anywhere","It is always allowed","Tadpoles do not need water"]'::jsonb,
 0,'Dikkopjes hebben specifieke water- en temperatuurcondities nodig die thuis moeilijk na te bootsen zijn.','Les têtards ont besoin de conditions d''eau et de température spécifiques difficiles à reproduire chez soi.','Tadpoles need specific water and temperature conditions that are hard to replicate at home.'),
(2,'tekst','Waarom worden er geen vissen gehouden in een amfibieënvijver?','Pourquoi ne garde-t-on pas de poissons dans un étang à amphibiens ?','Why are fish not kept in an amphibian pond?',
 '["Vissen eten kikkerdril en dikkopjes op","Vissen houden niet van water","Vissen maken de vijver te schoon","Amfibieën eten vissen op"]'::jsonb,
 '["Les poissons mangent le frai et les têtards","Les poissons n''aiment pas l''eau","Les poissons rendent l''étang trop propre","Les amphibiens mangent les poissons"]'::jsonb,
 '["Fish eat frogspawn and tadpoles","Fish do not like water","Fish make the pond too clean","Amphibians eat fish"]'::jsonb,
 0,'Vissen zoals goudvissen eten gretig kikkerdril, waardoor amfibieën zich moeilijk kunnen voortplanten.','Des poissons comme les poissons rouges mangent avidement le frai, ce qui empêche les amphibiens de se reproduire.','Fish such as goldfish readily eat frogspawn, making it hard for amphibians to reproduce.'),
(2,'tekst','Waarom moet een parkvijver vrij zijn van chemische bestrijdingsmiddelen?','Pourquoi un étang de parc doit-il être exempt de pesticides chimiques ?','Why must a park pond be free of chemical pesticides?',
 '["Amfibieën hebben een gevoelige, doorlaatbare huid","Pesticiden maken het water helderder","Amfibieën zijn ongevoelig voor gif","Het heeft geen invloed op de vijver"]'::jsonb,
 '["Les amphibiens ont une peau sensible et perméable","Les pesticides rendent l''eau plus claire","Les amphibiens sont insensibles au poison","Cela n''a aucun impact sur l''étang"]'::jsonb,
 '["Amphibians have sensitive, permeable skin","Pesticides make the water clearer","Amphibians are immune to poison","It has no effect on the pond"]'::jsonb,
 0,'Amfibieën ademen deels via hun huid, waardoor gifstoffen makkelijk hun lichaam binnendringen.','Les amphibiens respirent en partie par la peau, ce qui laisse facilement pénétrer les toxines.','Amphibians partly breathe through their skin, so toxins easily enter their body.'),
(2,'tekst','Wat hoort bij een gezonde, schone parkvijver voor amfibieën?','Qu''est-ce qui caractérise un étang de parc sain pour les amphibiens ?','What belongs in a healthy, clean park pond for amphibians?',
 '["Ondiepe randen, waterplanten en schaduw","Volledig betonnen, kale wanden","Enkel diep water zonder planten","Chloorwater zoals in een zwembad"]'::jsonb,
 '["Des berges peu profondes, des plantes aquatiques et de l''ombre","Des parois entièrement en béton nu","Uniquement de l''eau profonde sans plantes","De l''eau chlorée comme dans une piscine"]'::jsonb,
 '["Shallow edges, water plants and shade","Fully bare concrete walls","Only deep water without plants","Chlorinated water like a swimming pool"]'::jsonb,
 0,'Ondiepe zones laten amfibieën makkelijk in en uit het water, waterplanten bieden schuilplaats en zuurstof.','Les zones peu profondes facilitent l''entrée et la sortie des amphibiens, les plantes offrent abri et oxygène.','Shallow zones let amphibians easily enter and exit the water, plants provide shelter and oxygen.'),
(2,'tekst','Waarom moet je bladafval niet volledig uit de vijver verwijderen?','Pourquoi ne faut-il pas retirer toutes les feuilles mortes de l''étang ?','Why should you not remove all fallen leaves from the pond?',
 '["Een beetje bladafval biedt schuilplaats en voedsel voor waterleven","Bladafval is altijd giftig voor amfibieën","Het maakt het water te helder","Amfibieën houden niet van bladeren"]'::jsonb,
 '["Un peu de feuilles offre abri et nourriture à la vie aquatique","Les feuilles mortes sont toujours toxiques pour les amphibiens","Cela rend l''eau trop claire","Les amphibiens n''aiment pas les feuilles"]'::jsonb,
 '["A little leaf litter offers shelter and food for pond life","Leaf litter is always toxic to amphibians","It makes the water too clear","Amphibians dislike leaves"]'::jsonb,
 0,'Een gematigde hoeveelheid bladafval voedt kleine waterorganismen die op hun beurt amfibieën voeden.','Une quantité modérée de feuilles nourrit de petits organismes aquatiques qui nourrissent à leur tour les amphibiens.','A moderate amount of leaf litter feeds small aquatic organisms which in turn feed amphibians.'),
(2,'tekst','Wat kan je best doen om de vijver amfibievriendelijk te houden?','Que peut-on faire pour garder l''étang favorable aux amphibiens ?','What can you do to keep the pond amphibian-friendly?',
 '["Regelmatig overtollig kroos verwijderen zonder de vijver te legen","De vijver elk jaar volledig laten leeglopen","Enkel kunstplanten gebruiken","De vijver dagelijks chemisch reinigen"]'::jsonb,
 '["Retirer régulièrement l''excès de lentilles d''eau sans vider l''étang","Vider complètement l''étang chaque année","Utiliser uniquement des plantes artificielles","Nettoyer chimiquement l''étang tous les jours"]'::jsonb,
 '["Regularly remove excess duckweed without draining the pond","Fully drain the pond every year","Only use artificial plants","Clean the pond chemically every day"]'::jsonb,
 0,'Te veel kroos blokkeert licht en zuurstof, maar de vijver volledig legen verstoort het hele ecosysteem.','Trop de lentilles d''eau bloque la lumière et l''oxygène, mais vider l''étang perturbe tout l''écosystème.','Too much duckweed blocks light and oxygen, but fully draining the pond disrupts the whole ecosystem.'),
(3,'tekst','Wat is paddentrek?','Qu''est-ce que la migration des crapauds ?','What is toad migration?',
 '["De jaarlijkse trektocht van padden naar hun voortplantingsvijver","Het vervellen van de huid bij padden","Een ziekte bij padden","Het winterslaap houden onder water"]'::jsonb,
 '["La migration annuelle des crapauds vers leur étang de reproduction","La mue de la peau chez les crapauds","Une maladie des crapauds","L''hibernation sous l''eau"]'::jsonb,
 '["The yearly migration of toads to their breeding pond","The shedding of a toad''s skin","A toad disease","Hibernating underwater"]'::jsonb,
 0,'In het vroege voorjaar trekken padden vaak over dezelfde route naar de vijver waar ze zelf geboren zijn.','Au début du printemps, les crapauds empruntent souvent le même chemin vers l''étang où ils sont nés.','In early spring, toads often travel the same route to the pond where they themselves were born.'),
(3,'tekst','Waarom worden er soms tijdelijke paddenschermen langs wegen geplaatst?','Pourquoi installe-t-on parfois des barrières temporaires pour crapauds le long des routes ?','Why are temporary toad fences sometimes placed along roads?',
 '["Om padden veilig over te steken tijdens de paddentrek","Om padden weg te houden uit de natuur","Omdat padden gevaarlijk zijn voor mensen","Om verkeer te vertragen zonder reden"]'::jsonb,
 '["Pour aider les crapauds à traverser en sécurité pendant leur migration","Pour éloigner les crapauds de la nature","Parce que les crapauds sont dangereux pour l''homme","Pour ralentir le trafic sans raison"]'::jsonb,
 '["To help toads cross safely during migration","To keep toads out of nature","Because toads are dangerous to people","To slow down traffic without reason"]'::jsonb,
 0,'Vrijwilligers dragen padden vaak over in emmers om verkeersslachtoffers tijdens de trek te voorkomen.','Des bénévoles transportent souvent les crapauds dans des seaux pour éviter qu''ils ne soient écrasés.','Volunteers often carry toads across in buckets to prevent traffic casualties during migration.'),
(3,'tekst','Wat moet je doen als je een pad tegenkomt op het pad in het park?','Que faire si l''on croise un crapaud sur le sentier du parc ?','What should you do if you encounter a toad on the park path?',
 '["Hem rustig laten en niet aanraken of verstoren","Hem oppakken en meenemen naar huis","Hem wegjagen met een stok","Erover heen stappen zonder te kijken"]'::jsonb,
 '["Le laisser tranquille sans le toucher ni le déranger","Le ramasser et l''emporter chez soi","Le chasser avec un bâton","Marcher dessus sans regarder"]'::jsonb,
 '["Leave it calmly alone without touching or disturbing it","Pick it up and take it home","Chase it away with a stick","Step over it without looking"]'::jsonb,
 0,'Padden hebben een gevoelige huid, dus onnodig aanraken kan stress of huidbeschadiging veroorzaken.','La peau des crapauds est sensible, les toucher inutilement peut causer stress ou blessures cutanées.','Toads have sensitive skin, so unnecessary handling can cause stress or skin damage.'),
(3,'tekst','Waarom is het belangrijk je handen te wassen na contact met amfibieën?','Pourquoi est-il important de se laver les mains après avoir touché des amphibiens ?','Why is it important to wash your hands after touching amphibians?',
 '["Om huidsecreties te verwijderen en amfibieën te beschermen tegen onze huidbacteriën","Amfibieën zijn giftig voor mensen bij aanraking","Het is niet nodig, amfibieën zijn steriel","Enkel om je handen lekker te laten ruiken"]'::jsonb,
 '["Pour enlever les sécrétions cutanées et protéger les amphibiens de nos bactéries","Les amphibiens sont toxiques au toucher pour l''homme","Ce n''est pas nécessaire, les amphibiens sont stériles","Uniquement pour parfumer les mains"]'::jsonb,
 '["To remove skin secretions and protect amphibians from our skin bacteria","Amphibians are toxic to humans on contact","It is not necessary, amphibians are sterile","Only to make your hands smell nice"]'::jsonb,
 0,'Onze huid draagt bacteriën en lotions die schadelijk kunnen zijn voor de gevoelige huid van amfibieën.','Notre peau porte des bactéries et des lotions pouvant nuire à la peau sensible des amphibiens.','Our skin carries bacteria and lotions that can be harmful to the sensitive skin of amphibians.'),
(3,'tekst','Wat kan bezoekers helpen om amfibieën in het park te beschermen?','Qu''est-ce qui peut aider les visiteurs à protéger les amphibiens du parc ?','What can help visitors protect amphibians in the park?',
 '["Op de paden blijven en de vijverranden niet betreden","Stenen in de vijver gooien voor de lol","Dikkopjes verzamelen in potjes","Honden vrij laten zwemmen in de vijver"]'::jsonb,
 '["Rester sur les sentiers et ne pas marcher sur les berges de l''étang","Jeter des pierres dans l''étang pour s''amuser","Récolter des têtards dans des pots","Laisser les chiens nager librement dans l''étang"]'::jsonb,
 '["Staying on paths and not walking on the pond edges","Throwing stones into the pond for fun","Collecting tadpoles in jars","Letting dogs swim freely in the pond"]'::jsonb,
 0,'Vertrappelde oevers verstoren de plantengroei en schuilplaatsen die amfibieën nodig hebben.','Des berges piétinées perturbent la végétation et les abris dont les amphibiens ont besoin.','Trampled banks disturb the plant growth and shelters that amphibians need.')
) AS v(module,vraag_type,nl,fr,en,onl,ofr,oen,ci,wnl,wfr,wen);

-- Kwartel
WITH a AS (
  INSERT INTO public.academies (diersoort_naam, diersoort_naam_fr, diersoort_naam_en, slug, badge_icon, vragen_per_test, slaag_grens, beschrijving, beschrijving_fr, beschrijving_en, categorie, prioriteit)
  VALUES ('Kwartel','Caille','Quail','kwartel','kwartel',15,12,'Ontdek het gedrag van kwartels, hun kleine eitjes en hoe je hen een geschikt, laag hok geeft.','Découvrez le comportement des cailles, leurs petits œufs et comment leur offrir un enclos bas adapté.','Discover quail behaviour, their small eggs, and how to give them a suitable low enclosure.','pluimvee',50)
  RETURNING id
)
INSERT INTO public.academy_vragen (academy_id, module, vraag_type, vraag_tekst, vraag_tekst_fr, vraag_tekst_en, opties, opties_fr, opties_en, correcte_optie_index, wist_je_dat, wist_je_dat_fr, wist_je_dat_en)
SELECT a.id, v.module, v.vraag_type, v.nl, v.fr, v.en, v.onl, v.ofr, v.oen, v.ci, v.wnl, v.wfr, v.wen
FROM a, (VALUES
(1,'tekst','Hoe gedragen kwartels zich meestal ten opzichte van andere kippenachtigen?','Comment les cailles se comportent-elles généralement par rapport aux autres gallinacés ?','How do quail typically behave compared to other poultry?',
 '["Ze zijn schuw en vluchten liever weg dan te vechten","Ze zijn altijd zeer agressief","Ze klimmen graag in bomen","Ze zijn nachtactief zoals uilen"]'::jsonb,
 '["Elles sont craintives et préfèrent fuir plutôt que se battre","Elles sont toujours très agressives","Elles aiment grimper aux arbres","Elles sont nocturnes comme les hiboux"]'::jsonb,
 '["They are timid and prefer to flee rather than fight","They are always very aggressive","They enjoy climbing trees","They are nocturnal like owls"]'::jsonb,
 0,'Kwartels zijn van nature schuwe bodemvogels die snel wegrennen of laag wegvliegen bij dreiging.','Les cailles sont naturellement des oiseaux terrestres craintifs qui courent ou s''envolent bas en cas de danger.','Quail are naturally timid ground birds that quickly run or fly low away when threatened.'),
(1,'tekst','Hoe gedraagt een kwartel zich als hij schrikt in een te laag hok?','Comment se comporte une caille effrayée dans un enclos trop bas ?','How does a quail behave when startled in a too-low enclosure?',
 '["Hij vliegt recht omhoog en kan zijn kop verwonden","Hij gaat rustig zitten wachten","Hij graaft zich onmiddellijk in","Hij maakt altijd geluid om te waarschuwen"]'::jsonb,
 '["Elle s''envole tout droit vers le haut et peut se blesser la tête","Elle s''assoit calmement en attendant","Elle se met immédiatement à creuser","Elle fait toujours du bruit pour prévenir"]'::jsonb,
 '["It flies straight up and can injure its head","It sits calmly and waits","It immediately starts digging","It always makes a warning sound"]'::jsonb,
 0,'Kwartels hebben een verticale schrikreflex, daarom moet het hok een zachte, hoge afdekking hebben.','Les cailles ont un réflexe de fuite vertical, l''enclos doit donc avoir un plafond souple et suffisamment haut.','Quail have a vertical flight reflex, so the enclosure needs a soft, sufficiently tall covering.'),
(1,'tekst','Waarom leggen kwartels zulke kleine eitjes?','Pourquoi les cailles pondent-elles de si petits œufs ?','Why do quail lay such small eggs?',
 '["Omdat kwartels zelf kleine vogels zijn","Omdat ze ziek zijn","Omdat ze te weinig voer krijgen","Kwartels leggen even grote eieren als kippen"]'::jsonb,
 '["Parce que les cailles sont elles-mêmes de petits oiseaux","Parce qu''elles sont malades","Parce qu''elles reçoivent trop peu de nourriture","Les cailles pondent des œufs aussi gros que les poules"]'::jsonb,
 '["Because quail themselves are small birds","Because they are ill","Because they receive too little food","Quail lay eggs as large as chickens"]'::jsonb,
 0,'De eigrootte is evenredig met de lichaamsgrootte van de vogel, kwartels wegen maar zo''n 100 tot 150 gram.','La taille de l''œuf est proportionnelle à la taille de l''oiseau ; les cailles ne pèsent qu''environ 100 à 150 grammes.','Egg size is proportional to the bird''s body size; quail weigh only about 100 to 150 grams.'),
(1,'tekst','Wat hebben kwartels nodig om zich veilig te voelen in het hok?','De quoi les cailles ont-elles besoin pour se sentir en sécurité dans l''enclos ?','What do quail need to feel safe in their enclosure?',
 '["Voldoende schuilplaatsen zoals struiken of kastjes","Een volledig open, kaal terrein","Fel licht dag en nacht","Veel lawaai rondom hen"]'::jsonb,
 '["Suffisamment de cachettes comme des buissons ou des abris","Un terrain totalement ouvert et nu","Une lumière vive jour et nuit","Beaucoup de bruit autour d''elles"]'::jsonb,
 '["Enough hiding spots such as bushes or shelters","A fully open, bare area","Bright light day and night","A lot of noise around them"]'::jsonb,
 0,'Schuilplaatsen verminderen stress bij deze schuwe vogels en geven hen een veilig gevoel.','Les cachettes réduisent le stress de ces oiseaux craintifs et leur donnent un sentiment de sécurité.','Hiding spots reduce stress in these timid birds and give them a sense of safety.'),
(1,'tekst','Waarom is een laag hok met een zachte bovenkant aan te raden voor kwartels?','Pourquoi un enclos bas avec un plafond souple est-il conseillé pour les cailles ?','Why is a low enclosure with a soft ceiling recommended for quail?',
 '["Om verwondingen te voorkomen als ze plots opschrikken en omhoog vliegen","Omdat kwartels niet kunnen vliegen","Om het hok makkelijker te reinigen","Omdat kwartels van kleine ruimtes houden om te broeden"]'::jsonb,
 '["Pour éviter les blessures si elles s''envolent brusquement de peur","Parce que les cailles ne savent pas voler","Pour nettoyer l''enclos plus facilement","Parce que les cailles aiment les petits espaces pour couver"]'::jsonb,
 '["To prevent injury if they suddenly startle and fly upward","Because quail cannot fly","To make the enclosure easier to clean","Because quail like small spaces for nesting"]'::jsonb,
 0,'Een net of zacht doek als plafond dempt de klap wanneer een kwartel plotseling omhoog schiet.','Un filet ou un tissu souple en plafond amortit le choc quand une caille s''envole brusquement.','A net or soft cloth ceiling cushions the impact when a quail suddenly bolts upward.'),
(2,'tekst','Kunnen kwartels samenleven met kippen in hetzelfde hok?','Les cailles peuvent-elles vivre avec des poules dans le même enclos ?','Can quail live together with chickens in the same enclosure?',
 '["Meestal niet aan te raden, kippen kunnen kwartels pesten of verwonden","Altijd zonder enig probleem","Enkel als de kwartel groter is dan de kip","Kwartels en kippen mogen nooit samen buiten komen"]'::jsonb,
 '["Généralement déconseillé, les poules peuvent brutaliser les cailles","Toujours sans aucun problème","Seulement si la caille est plus grosse que la poule","Cailles et poules ne peuvent jamais sortir ensemble"]'::jsonb,
 '["Usually not advisable, chickens can bully or injure quail","Always without any problem","Only if the quail is bigger than the chicken","Quail and chickens can never go outside together"]'::jsonb,
 0,'Door hun kleinere formaat staan kwartels vaak onderaan de pikorde en kunnen ze gewond raken.','En raison de leur petite taille, les cailles sont souvent tout en bas de la hiérarchie et peuvent être blessées.','Due to their smaller size, quail are often at the bottom of the pecking order and can get hurt.'),
(2,'tekst','Waarom kiest men soms wel voor het samenhouden van kwartels met rustige, kleinere pluimveerassen?','Pourquoi choisit-on parfois de garder des cailles avec des races de volaille plus calmes et petites ?','Why is quail sometimes kept together with calm, smaller poultry breeds?',
 '["Omdat een goede match minder stress en conflict geeft","Omdat dit altijd verplicht is","Omdat kwartels dan niet meer hoeven te eten","Omdat het de kwartels agressiever maakt"]'::jsonb,
 '["Parce qu''une bonne association réduit le stress et les conflits","Parce que c''est toujours obligatoire","Parce que les cailles n''ont alors plus besoin de manger","Parce que cela rend les cailles plus agressives"]'::jsonb,
 '["Because a good match causes less stress and conflict","Because it is always mandatory","Because then quail no longer need to eat","Because it makes quail more aggressive"]'::jsonb,
 0,'Rustige, gelijkgestemde soorten verminderen de kans op onderlinge agressie in een gedeeld hok.','Des espèces calmes et compatibles réduisent le risque d''agressivité dans un enclos partagé.','Calm, compatible species reduce the chance of mutual aggression in a shared enclosure.'),
(2,'tekst','Waarop moet je letten als kwartels toch samen met ander pluimvee leven?','À quoi faut-il faire attention si les cailles vivent quand même avec d''autres volailles ?','What should you watch for if quail do live with other poultry?',
 '["Voldoende ruimte en schuilplaatsen om vluchten mogelijk te maken","Alleen op de kleur van de veren","Enkel op het aantal eieren per dag","Niets, dit vraagt geen extra aandacht"]'::jsonb,
 '["Suffisamment d''espace et de cachettes pour permettre la fuite","Uniquement la couleur des plumes","Uniquement le nombre d''œufs par jour","Rien, cela ne demande aucune attention particulière"]'::jsonb,
 '["Enough space and hiding spots to allow escape","Only the colour of the feathers","Only the number of eggs per day","Nothing, this needs no special attention"]'::jsonb,
 0,'Voldoende ruimte laat kwartels ontsnappen aan opdringerig gedrag van ander pluimvee.','Un espace suffisant permet aux cailles d''échapper au comportement envahissant d''autres volailles.','Enough space lets quail escape from pushy behaviour by other poultry.'),
(2,'tekst','Waarom moeten kwartels apart gevoerd kunnen worden in een gemengd hok?','Pourquoi les cailles doivent-elles pouvoir être nourries séparément dans un enclos mixte ?','Why should quail be able to feed separately in a mixed enclosure?',
 '["Grotere pluimveesoorten kunnen hen wegjagen bij het voer","Kwartels eten nooit graag samen met andere dieren","Het is wettelijk verplicht","Kwartels hebben geen voer nodig"]'::jsonb,
 '["Les espèces de volaille plus grandes peuvent les chasser de la mangeoire","Les cailles n''aiment jamais manger avec d''autres animaux","C''est une obligation légale","Les cailles n''ont pas besoin de nourriture"]'::jsonb,
 '["Larger poultry species can chase them away from the feed","Quail never like eating with other animals","It is a legal requirement","Quail do not need feed"]'::jsonb,
 0,'Een aparte, lage voederplek zorgt dat kwartels voldoende te eten krijgen zonder verdrongen te worden.','Un point de nourrissage séparé et bas garantit que les cailles mangent suffisamment sans être écartées.','A separate, low feeding spot ensures quail get enough food without being pushed out.'),
(2,'tekst','Wat is een teken dat kwartels zich niet goed voelen bij ander pluimvee?','Quel est un signe que les cailles ne se sentent pas bien avec d''autres volailles ?','What is a sign that quail are not comfortable with other poultry?',
 '["Ze blijven voortdurend verstopt en eten weinig","Ze lopen vrolijk rond met de kippen","Ze leggen extra veel eieren","Ze maken luide, vrolijke geluiden"]'::jsonb,
 '["Elles restent constamment cachées et mangent peu","Elles se promènent joyeusement avec les poules","Elles pondent beaucoup plus d''œufs","Elles font des bruits joyeux et forts"]'::jsonb,
 '["They stay constantly hidden and eat little","They walk around happily with the chickens","They lay extra many eggs","They make loud, cheerful sounds"]'::jsonb,
 0,'Aanhoudend verstopgedrag en verminderde eetlust wijzen op chronische stress bij kwartels.','Un comportement de cachette constant et une baisse d''appétit indiquent un stress chronique chez la caille.','Persistent hiding behaviour and reduced appetite indicate chronic stress in quail.'),
(3,'tekst','Waarom houden kwartels van zandbaden?','Pourquoi les cailles aiment-elles les bains de sable ?','Why do quail enjoy dust baths?',
 '["Om hun veren schoon te houden en parasieten te verwijderen","Om af te koelen in de zomer","Om hun snavel te slijpen","Om te oefenen met graven van nesten"]'::jsonb,
 '["Pour garder leurs plumes propres et éliminer les parasites","Pour se rafraîchir en été","Pour aiguiser leur bec","Pour s''entraîner à creuser des nids"]'::jsonb,
 '["To keep their feathers clean and remove parasites","To cool down in summer","To sharpen their beak","To practise digging nests"]'::jsonb,
 0,'Net als kippen gebruiken kwartels stof en zand om overtollig vet en parasieten uit hun veren te halen.','Comme les poules, les cailles utilisent poussière et sable pour éliminer graisse excédentaire et parasites de leurs plumes.','Like chickens, quail use dust and sand to remove excess oil and parasites from their feathers.'),
(3,'tekst','Wat moet er aanwezig zijn in het hok om zandbaden mogelijk te maken?','Que doit-on prévoir dans l''enclos pour permettre les bains de sable ?','What must be present in the enclosure to allow dust bathing?',
 '["Een bak met droog zand of fijne aarde","Enkel een waterbad","Een betonnen vloer zonder toevoegingen","Een dikke laag stro zonder zand"]'::jsonb,
 '["Un bac avec du sable sec ou de la terre fine","Uniquement un bain d''eau","Un sol en béton sans rien d''autre","Une épaisse couche de paille sans sable"]'::jsonb,
 '["A tray with dry sand or fine soil","Only a water bath","A concrete floor with nothing added","A thick layer of straw without sand"]'::jsonb,
 0,'Een droge zandbak nodigt kwartels uit tot natuurlijk stofbadgedrag, essentieel voor hun verenverzorging.','Un bac de sable sec invite les cailles à un comportement naturel de bain de poussière, essentiel à l''entretien de leurs plumes.','A dry sand tray invites quail to natural dust-bathing behaviour, essential for feather care.'),
(3,'tekst','Hoe vaak baden kwartels normaal gezien in zand of stof?','À quelle fréquence les cailles prennent-elles normalement un bain de sable ?','How often do quail normally take a dust bath?',
 '["Regelmatig, meerdere keren per week als het mogelijk is","Slechts één keer per jaar","Nooit, kwartels wassen zich niet","Enkel wanneer het regent"]'::jsonb,
 '["Régulièrement, plusieurs fois par semaine si possible","Seulement une fois par an","Jamais, les cailles ne se lavent pas","Uniquement quand il pleut"]'::jsonb,
 '["Regularly, several times a week if possible","Only once a year","Never, quail do not wash themselves","Only when it rains"]'::jsonb,
 0,'Kwartels nemen graag geregeld een stofbad, vooral op warme, droge dagen.','Les cailles aiment prendre régulièrement un bain de poussière, surtout par temps chaud et sec.','Quail like to take dust baths regularly, especially on warm, dry days.'),
(3,'tekst','Wat gebeurt er als kwartels geen mogelijkheid hebben om te zandbaden?','Que se passe-t-il si les cailles n''ont pas la possibilité de prendre un bain de sable ?','What happens if quail have no opportunity to dust bathe?',
 '["Hun veren kunnen vet en vervuild raken en parasieten toenemen","Ze groeien sneller","Ze leggen meer eieren","Er verandert helemaal niets"]'::jsonb,
 '["Leurs plumes peuvent devenir grasses et sales, avec plus de parasites","Elles grandissent plus vite","Elles pondent plus d''œufs","Rien ne change du tout"]'::jsonb,
 '["Their feathers can become greasy and dirty, with more parasites","They grow faster","They lay more eggs","Nothing changes at all"]'::jsonb,
 0,'Zonder stofbaden hopen vet en parasieten zich op in de veren, wat het welzijn van kwartels schaadt.','Sans bain de poussière, graisse et parasites s''accumulent dans les plumes, nuisant au bien-être des cailles.','Without dust baths, oil and parasites build up in the feathers, harming the welfare of quail.'),
(3,'tekst','Waarom is het zandbad ook belangrijk voor het sociale gedrag van kwartels?','Pourquoi le bain de sable est-il aussi important pour le comportement social des cailles ?','Why is the dust bath also important for quail social behaviour?',
 '["Kwartels baden vaak samen, wat de groepsband versterkt","Kwartels vechten altijd bij het zandbad","Het zandbad heeft geen sociale functie","Kwartels mijden elkaar bij het baden"]'::jsonb,
 '["Les cailles se baignent souvent ensemble, ce qui renforce le lien de groupe","Les cailles se battent toujours au bain de sable","Le bain de sable n''a aucune fonction sociale","Les cailles s''évitent pendant le bain"]'::jsonb,
 '["Quail often bathe together, which strengthens the group bond","Quail always fight at the dust bath","The dust bath has no social function","Quail avoid each other while bathing"]'::jsonb,
 0,'Gezamenlijk baden is een vorm van sociaal gedrag dat de band tussen kwartels in de groep versterkt.','Le bain collectif est une forme de comportement social qui renforce le lien entre les cailles du groupe.','Bathing together is a form of social behaviour that strengthens the bond between quail in the group.')
) AS v(module,vraag_type,nl,fr,en,onl,ofr,oen,ci,wnl,wfr,wen);

-- Tuinvogels & nestkasten
WITH a AS (
  INSERT INTO public.academies (diersoort_naam, diersoort_naam_fr, diersoort_naam_en, slug, badge_icon, vragen_per_test, slaag_grens, beschrijving, beschrijving_fr, beschrijving_en, categorie, prioriteit)
  VALUES ('Tuinvogels & nestkasten','Oiseaux de jardin & nichoirs','Garden birds & nest boxes','tuinvogels','tuinvogels',15,12,'Leer tuinvogels herkennen en ontdek hoe je hen het hele jaar door helpt met de juiste voeding en nestkasten.','Apprenez à reconnaître les oiseaux de jardin et découvrez comment les aider toute l''année avec la bonne nourriture et les bons nichoirs.','Learn to recognise garden birds and discover how to help them year-round with the right food and nest boxes.','pluimvee',50)
  RETURNING id
)
INSERT INTO public.academy_vragen (academy_id, module, vraag_type, vraag_tekst, vraag_tekst_fr, vraag_tekst_en, opties, opties_fr, opties_en, correcte_optie_index, wist_je_dat, wist_je_dat_fr, wist_je_dat_en)
SELECT a.id, v.module, v.vraag_type, v.nl, v.fr, v.en, v.onl, v.ofr, v.oen, v.ci, v.wnl, v.wfr, v.wen
FROM a, (VALUES
(1,'tekst','Waaraan herken je een roodborst het makkelijkst?','Comment reconnaît-on le plus facilement un rouge-gorge ?','What is the easiest way to recognise a robin?',
 '["Aan de opvallende oranjerode borst en keel","Aan een lange, blauwe staart","Aan een gele buik en zwarte kop","Aan witte strepen over de vleugels"]'::jsonb,
 '["À sa poitrine et sa gorge orange-rouge caractéristiques","À sa longue queue bleue","À son ventre jaune et sa tête noire","À des rayures blanches sur les ailes"]'::jsonb,
 '["By its striking orange-red breast and throat","By a long blue tail","By a yellow belly and black head","By white stripes across the wings"]'::jsonb,
 0,'De felle oranjerode borst van de roodborst is bij beide geslachten aanwezig, in tegenstelling tot bij veel andere vogels.','La poitrine orange-rouge vive du rouge-gorge est présente chez les deux sexes, contrairement à de nombreux autres oiseaux.','The bright orange-red breast of a robin is present in both sexes, unlike many other birds.'),
(1,'tekst','Wat is een kenmerk van de koolmees?','Quelle est une caractéristique de la mésange charbonnière ?','What is a feature of the great tit?',
 '["Een gele buik met een zwarte streep in het midden","Een volledig witte vacht","Een lange, kromme snavel","Rode vleugels en een grijze kop"]'::jsonb,
 '["Un ventre jaune avec une bande noire au milieu","Un plumage entièrement blanc","Un long bec courbé","Des ailes rouges et une tête grise"]'::jsonb,
 '["A yellow belly with a black stripe down the middle","An entirely white plumage","A long, curved beak","Red wings and a grey head"]'::jsonb,
 0,'Bij de koolmees is de zwarte buikstreep bij mannetjes breder dan bij vrouwtjes.','Chez la mésange charbonnière, la bande noire ventrale est plus large chez le mâle que chez la femelle.','In great tits, the black belly stripe is wider in males than in females.'),
(1,'tekst','Hoe herken je een huismus?','Comment reconnaît-on un moineau domestique ?','How do you recognise a house sparrow?',
 '["Bruingrijs verenkleed en bij mannetjes een zwarte bef","Een felgroen verenkleed","Een lange staart zoals een ekster","Volledig zwart met een gele snavel"]'::jsonb,
 '["Un plumage brun-gris et une bavette noire chez le mâle","Un plumage vert vif","Une longue queue comme une pie","Entièrement noir avec un bec jaune"]'::jsonb,
 '["Brown-grey plumage and a black bib on males","A bright green plumage","A long tail like a magpie","Entirely black with a yellow beak"]'::jsonb,
 0,'Mannelijke huismussen hebben een opvallende zwarte bef op de borst, vrouwtjes zijn egaler bruin.','Les moineaux mâles ont une bavette noire distincte sur la poitrine, les femelles sont plus uniformément brunes.','Male house sparrows have a distinctive black bib on the chest, females are more uniformly brown.'),
(1,'tekst','Wat is een goede manier om vogels te leren herkennen in het park?','Quelle est une bonne façon d''apprendre à reconnaître les oiseaux du parc ?','What is a good way to learn to recognise birds in the park?',
 '["Letten op kleur, grootte, geluid en gedrag","Enkel naar de kleur van de poten kijken","Vogels vangen om ze van dichtbij te bekijken","Alleen ''s nachts vogels observeren"]'::jsonb,
 '["Observer la couleur, la taille, le chant et le comportement","Regarder uniquement la couleur des pattes","Attraper les oiseaux pour les observer de près","Observer les oiseaux uniquement la nuit"]'::jsonb,
 '["Paying attention to colour, size, sound and behaviour","Only looking at the colour of the legs","Catching birds to look at them closely","Only observing birds at night"]'::jsonb,
 0,'Een combinatie van uiterlijke kenmerken, geluid en gedrag helpt om vogelsoorten betrouwbaar te herkennen.','Combiner apparence, chant et comportement aide à identifier les espèces d''oiseaux de manière fiable.','Combining appearance, sound and behaviour helps reliably identify bird species.'),
(1,'tekst','Welke vogel zie je vaak dicht bij de grond scharrelen op zoek naar wormen?','Quel oiseau voit-on souvent fouiller près du sol à la recherche de vers ?','Which bird do you often see foraging close to the ground for worms?',
 '["De roodborst","De buizerd","De ijsvogel","De ooievaar"]'::jsonb,
 '["Le rouge-gorge","La buse","Le martin-pêcheur","La cigogne"]'::jsonb,
 '["The robin","The buzzard","The kingfisher","The stork"]'::jsonb,
 0,'Roodborstjes volgen vaak tuiniers om insecten en wormen te vinden die worden blootgelegd bij het spitten.','Les rouges-gorges suivent souvent les jardiniers pour trouver insectes et vers mis à jour lors du bêchage.','Robins often follow gardeners to find insects and worms exposed while digging.'),
(2,'tekst','Wanneer is bijvoeren van tuinvogels het nuttigst?','Quand le nourrissage des oiseaux de jardin est-il le plus utile ?','When is supplementary feeding of garden birds most useful?',
 '["Tijdens de koude wintermaanden","Enkel in de zomer","Nooit, bijvoeren is altijd slecht","Alleen tijdens het broedseizoen"]'::jsonb,
 '["Pendant les mois froids d''hiver","Uniquement en été","Jamais, le nourrissage est toujours mauvais","Uniquement pendant la saison de reproduction"]'::jsonb,
 '["During the cold winter months","Only in summer","Never, feeding is always bad","Only during the breeding season"]'::jsonb,
 0,'In de winter is natuurlijk voedsel schaars, waardoor bijvoeren vogels helpt de kou te overleven.','En hiver, la nourriture naturelle est rare, le nourrissage aide donc les oiseaux à survivre au froid.','In winter, natural food is scarce, so supplementary feeding helps birds survive the cold.'),
(2,'tekst','Waarom mag je tuinvogels geen brood geven?','Pourquoi ne faut-il pas donner de pain aux oiseaux de jardin ?','Why should you not give bread to garden birds?',
 '["Brood heeft weinig voedingswaarde en kan de spijsvertering verstoren","Brood is het beste voedsel voor vogels","Vogels lusten geen brood","Brood maakt vogels sterker in de winter"]'::jsonb,
 '["Le pain a peu de valeur nutritive et peut perturber la digestion","Le pain est la meilleure nourriture pour les oiseaux","Les oiseaux n''aiment pas le pain","Le pain rend les oiseaux plus forts en hiver"]'::jsonb,
 '["Bread has little nutritional value and can upset digestion","Bread is the best food for birds","Birds do not like bread","Bread makes birds stronger in winter"]'::jsonb,
 0,'Brood vult de maag zonder de nodige vetten en eiwitten te leveren die vogels in de winter nodig hebben.','Le pain remplit l''estomac sans apporter les graisses et protéines nécessaires en hiver.','Bread fills the stomach without providing the fats and proteins birds need in winter.'),
(2,'tekst','Waarom is gezouten voer schadelijk voor vogels?','Pourquoi la nourriture salée est-elle nocive pour les oiseaux ?','Why is salted food harmful to birds?',
 '["Zout kan bij vogels de nier- en vochtbalans ernstig verstoren","Zout is net heel gezond voor vogels","Vogels proeven geen zout","Gezouten voer is enkel duurder"]'::jsonb,
 '["Le sel peut gravement perturber le bilan rénal et hydrique des oiseaux","Le sel est en fait très sain pour les oiseaux","Les oiseaux ne perçoivent pas le sel","La nourriture salée est juste plus chère"]'::jsonb,
 '["Salt can seriously disrupt birds'' kidney and fluid balance","Salt is actually very healthy for birds","Birds cannot taste salt","Salted food is just more expensive"]'::jsonb,
 0,'Vogels kunnen overtollig zout veel slechter verwerken dan mensen, wat tot uitdroging en orgaanschade leidt.','Les oiseaux traitent beaucoup moins bien l''excès de sel que les humains, ce qui provoque déshydratation et lésions organiques.','Birds process excess salt much worse than humans, leading to dehydration and organ damage.'),
(2,'tekst','Wat is geschikt winters vogelvoer?','Qu''est-ce qu''une nourriture d''hiver adaptée pour les oiseaux ?','What is suitable winter bird food?',
 '["Vetbollen, zonnebloempitten en ongezouten noten","Chips en koekjes","Gezouten spek","Chocolade"]'::jsonb,
 '["Boules de graisse, graines de tournesol et noix non salées","Chips et biscuits","Lard salé","Chocolat"]'::jsonb,
 '["Fat balls, sunflower seeds and unsalted nuts","Chips and cookies","Salted bacon","Chocolate"]'::jsonb,
 0,'Vetrijk voer zoals vetbollen geeft vogels snel energie om koude winternachten te doorstaan.','Une nourriture riche en graisse comme les boules de graisse donne rapidement de l''énergie pour survivre aux nuits froides.','Fat-rich food like fat balls gives birds quick energy to survive cold winter nights.'),
(2,'tekst','Waarom is water ook belangrijk om aan te bieden aan vogels in de zomer?','Pourquoi est-il aussi important d''offrir de l''eau aux oiseaux en été ?','Why is it also important to provide water for birds in summer?',
 '["Vogels hebben water nodig om te drinken en te baden, vooral bij hitte","Vogels drinken nooit water","Water trekt enkel ongewenste dieren aan","Het is enkel nodig in de winter"]'::jsonb,
 '["Les oiseaux ont besoin d''eau pour boire et se baigner, surtout par forte chaleur","Les oiseaux ne boivent jamais d''eau","L''eau n''attire que des animaux indésirables","Ce n''est nécessaire qu''en hiver"]'::jsonb,
 '["Birds need water to drink and bathe, especially in heat","Birds never drink water","Water only attracts unwanted animals","It is only needed in winter"]'::jsonb,
 0,'Een schoon vogelbadje helpt vogels tijdens hete zomerdagen om af te koelen en hun veren te onderhouden.','Un bain d''oiseau propre aide les oiseaux à se rafraîchir et à entretenir leurs plumes lors des chaudes journées d''été.','A clean bird bath helps birds cool down and maintain their feathers during hot summer days.'),
(3,'tekst','Waarom hebben verschillende vogelsoorten een andere nestkast nodig?','Pourquoi différentes espèces d''oiseaux ont-elles besoin de nichoirs différents ?','Why do different bird species need different nest boxes?',
 '["De grootte van het invlieggat en de kast moet passen bij de soort","Alle vogels gebruiken exact dezelfde nestkast","Nestkasten zijn enkel decoratief","Vogelsoorten bouwen nooit een nest in een kast"]'::jsonb,
 '["La taille du trou d''envol et du nichoir doit correspondre à l''espèce","Tous les oiseaux utilisent exactement le même nichoir","Les nichoirs sont uniquement décoratifs","Les espèces ne font jamais de nid dans un nichoir"]'::jsonb,
 '["The size of the entry hole and box must match the species","All birds use exactly the same nest box","Nest boxes are purely decorative","Bird species never build a nest in a box"]'::jsonb,
 0,'Een te groot invlieggat laat roofdieren of grotere concurrenten toe, een te klein gat weert de doelsoort zelf.','Un trou trop grand laisse entrer prédateurs ou concurrents plus gros, un trou trop petit exclut l''espèce visée elle-même.','A too-large entry hole lets in predators or bigger competitors, while a too-small hole excludes the target species itself.'),
(3,'tekst','Welk type nestkast is geschikt voor een koolmees?','Quel type de nichoir convient à une mésange charbonnière ?','What type of nest box suits a great tit?',
 '["Een gesloten kastje met een rond invlieggat van ongeveer 32 mm","Een volledig open plankje zonder wanden","Een kast met een gat van 10 cm breed","Enkel een holle boomstronk zonder opening"]'::jsonb,
 '["Un nichoir fermé avec un trou d''envol rond d''environ 32 mm","Une simple planche ouverte sans parois","Un nichoir avec un trou de 10 cm de large","Uniquement une souche creuse sans ouverture"]'::jsonb,
 '["A closed box with a round entry hole of about 32 mm","A fully open plank with no walls","A box with a 10 cm wide hole","Only a hollow tree stump without an opening"]'::jsonb,
 0,'Een invlieggat van ongeveer 32 mm past bij koolmezen en weert grotere vogels zoals spreeuwen.','Un trou d''envol d''environ 32 mm convient aux mésanges charbonnières et empêche l''entrée d''oiseaux plus grands comme les étourneaux.','An entry hole of about 32 mm suits great tits and keeps out larger birds like starlings.'),
(3,'tekst','Welk type nestplek verkiest een roodborst vaak?','Quel type d''emplacement de nid le rouge-gorge préfère-t-il souvent ?','What type of nesting spot does a robin often prefer?',
 '["Een open of halfopen nestkastje laag bij de grond in dichte begroeiing","Een gesloten kastje hoog in een kale boom","Enkel een nestkast op het water","Een nestkast met een gat van 6 cm"]'::jsonb,
 '["Un nichoir ouvert ou semi-ouvert, bas dans une végétation dense","Un nichoir fermé haut dans un arbre nu","Uniquement un nichoir sur l''eau","Un nichoir avec un trou de 6 cm"]'::jsonb,
 '["An open or half-open nest box low in dense vegetation","A closed box high in a bare tree","Only a nest box on the water","A nest box with a 6 cm hole"]'::jsonb,
 0,'Roodborstjes nestelen van nature vaak laag bij de grond, verscholen tussen struiken of klimop.','Les rouges-gorges nichent naturellement souvent bas, cachés dans des buissons ou du lierre.','Robins naturally often nest low to the ground, hidden among bushes or ivy.'),
(3,'tekst','Wanneer is de beste periode om nestkasten op te hangen of schoon te maken?','Quelle est la meilleure période pour installer ou nettoyer les nichoirs ?','What is the best time to hang or clean nest boxes?',
 '["Buiten het broedseizoen, bijvoorbeeld in de late herfst of winter","Midden in het broedseizoen","Enkel op een warme zomerdag","Het maakt niet uit wanneer"]'::jsonb,
 '["En dehors de la saison de reproduction, par exemple en automne ou hiver","En plein milieu de la saison de reproduction","Uniquement une chaude journée d''été","Peu importe le moment"]'::jsonb,
 '["Outside the breeding season, e.g. late autumn or winter","In the middle of the breeding season","Only on a warm summer day","It does not matter when"]'::jsonb,
 0,'Nestkasten schoonmaken buiten het broedseizoen voorkomt verstoring van broedende vogels en hun eieren.','Nettoyer les nichoirs hors saison de reproduction évite de déranger les oiseaux couveurs et leurs œufs.','Cleaning nest boxes outside the breeding season avoids disturbing nesting birds and their eggs.')
) AS v(module,vraag_type,nl,fr,en,onl,ofr,oen,ci,wnl,wfr,wen);

-- Hond op de boerderij
WITH a AS (
  INSERT INTO public.academies (diersoort_naam, diersoort_naam_fr, diersoort_naam_en, slug, badge_icon, vragen_per_test, slaag_grens, beschrijving, beschrijving_fr, beschrijving_en, categorie, prioriteit)
  VALUES ('Hond op de boerderij','Chien à la ferme','Dog at the farm','hond-boerderij','hond-boerderij',15,12,'Leer hoe je veilig en respectvol met je hond de kinderboerderij bezoekt, zonder de dieren of andere bezoekers te storen.','Apprenez à visiter la ferme urbaine avec votre chien en toute sécurité et respect, sans déranger les animaux ou les autres visiteurs.','Learn how to visit the city farm safely and respectfully with your dog, without disturbing the animals or other visitors.','etiquette',50)
  RETURNING id
)
INSERT INTO public.academy_vragen (academy_id, module, vraag_type, vraag_tekst, vraag_tekst_fr, vraag_tekst_en, opties, opties_fr, opties_en, correcte_optie_index, wist_je_dat, wist_je_dat_fr, wist_je_dat_en)
SELECT a.id, v.module, v.vraag_type, v.nl, v.fr, v.en, v.onl, v.ofr, v.oen, v.ci, v.wnl, v.wfr, v.wen
FROM a, (VALUES
(1,'tekst','Waarom geldt er meestal een lijnplicht voor honden op de kinderboerderij?','Pourquoi la laisse est-elle généralement obligatoire pour les chiens à la ferme urbaine ?','Why is a leash usually mandatory for dogs at the city farm?',
 '["Om de veiligheid van dieren en bezoekers te garanderen","Omdat honden niet mogen lopen","Om de hond trager te maken","Lijnplicht bestaat niet op boerderijen"]'::jsonb,
 '["Pour garantir la sécurité des animaux et des visiteurs","Parce que les chiens ne doivent pas marcher","Pour ralentir le chien","La laisse obligatoire n''existe pas dans les fermes"]'::jsonb,
 '["To ensure the safety of animals and visitors","Because dogs are not allowed to walk","To slow the dog down","Leash rules do not exist at farms"]'::jsonb,
 0,'Een losse hond kan boerderijdieren onbedoeld opjagen, zelfs als hij enkel wil spelen.','Un chien en liberté peut effrayer les animaux de la ferme sans le vouloir, même en voulant simplement jouer.','A loose dog can unintentionally chase farm animals, even if it only wants to play.'),
(1,'tekst','Hoe lang mag de lijn best zijn op een drukke kinderboerderij?','Quelle doit être la longueur idéale de la laisse dans une ferme urbaine fréquentée ?','How long should the leash ideally be at a busy city farm?',
 '["Kort, zodat je de hond snel onder controle hebt","Zo lang mogelijk, minstens tien meter","De lijn mag losgemaakt worden","Lengte maakt niets uit"]'::jsonb,
 '["Courte, pour garder rapidement le contrôle du chien","Aussi longue que possible, au moins dix mètres","La laisse peut être détachée","La longueur n''a aucune importance"]'::jsonb,
 '["Short, so you can quickly control the dog","As long as possible, at least ten metres","The leash can be unclipped","The length does not matter"]'::jsonb,
 0,'Een korte lijn geeft je meer controle in drukke ruimtes met kinderen en dieren dichtbij.','Une laisse courte offre plus de contrôle dans des espaces fréquentés avec enfants et animaux à proximité.','A short leash gives you more control in busy spaces with children and animals nearby.'),
(1,'tekst','Wat moet je doen als je hond plots naar een dier wil toe trekken?','Que faire si votre chien tire soudainement vers un animal ?','What should you do if your dog suddenly pulls toward an animal?',
 '["Stevig de lijn vasthouden en de hond rustig terugroepen","De lijn loslaten zodat de hond kan gaan kijken","De hond aanmoedigen om dichterbij te komen","Niets doen, dit lost zichzelf op"]'::jsonb,
 '["Tenir fermement la laisse et rappeler calmement le chien","Lâcher la laisse pour qu''il puisse aller voir","Encourager le chien à s''approcher","Ne rien faire, cela se résout tout seul"]'::jsonb,
 '["Hold the leash firmly and calmly call the dog back","Release the leash so it can go look","Encourage the dog to come closer","Do nothing, it will resolve itself"]'::jsonb,
 0,'Stevig vasthouden en rustig commanderen voorkomt dat je hond een dier laat schrikken of verwondt.','Tenir fermement et donner un ordre calme évite que votre chien n''effraie ou ne blesse un animal.','Holding firmly and calmly commanding prevents your dog from startling or injuring an animal.'),
(1,'tekst','Waarom is het slim om je hond al thuis wat te laten wandelen voor het bezoek?','Pourquoi est-il judicieux de faire marcher son chien avant la visite ?','Why is it wise to walk your dog before the visit?',
 '["Een uitgeruste hond is doorgaans rustiger tussen de dieren","Dit heeft geen enkel effect","Het maakt de hond juist onrustiger","Het is verplicht volgens de wet"]'::jsonb,
 '["Un chien qui a pu se dépenser est généralement plus calme parmi les animaux","Cela n''a aucun effet","Cela rend le chien plus agité","C''est une obligation légale"]'::jsonb,
 '["A dog that has had exercise is usually calmer around the animals","This has no effect at all","It actually makes the dog more restless","It is a legal requirement"]'::jsonb,
 0,'Een hond met opgekropte energie reageert vaak heftiger op prikkels zoals loslopend pluimvee.','Un chien avec un excès d''énergie réagit souvent plus vivement aux stimuli comme la volaille en liberté.','A dog with pent-up energy often reacts more strongly to stimuli like free-roaming poultry.'),
(2,'tekst','Wat is een teken van stress bij boerderijdieren wanneer een hond nadert?','Quel est un signe de stress chez les animaux de ferme quand un chien approche ?','What is a sign of stress in farm animals when a dog approaches?',
 '["Ze klitten samen, drukken hun oren plat of proberen weg te vluchten","Ze komen rustig dichterbij om te spelen","Ze gaan onmiddellijk slapen","Ze eten net iets meer"]'::jsonb,
 '["Ils se serrent, plaquent les oreilles ou tentent de fuir","Ils s''approchent calmement pour jouer","Ils s''endorment immédiatement","Ils mangent juste un peu plus"]'::jsonb,
 '["They huddle together, flatten their ears or try to flee","They calmly approach to play","They immediately fall asleep","They eat just a bit more"]'::jsonb,
 0,'Samendrommen, platte oren en vluchtgedrag zijn duidelijke signalen van angst bij boerderijdieren.','Se regrouper, plaquer les oreilles et fuir sont des signes clairs de peur chez les animaux de ferme.','Huddling together, flattened ears and flight behaviour are clear signs of fear in farm animals.'),
(2,'tekst','Hoe reageert een geit vaak wanneer die gestrest raakt door een hond?','Comment une chèvre réagit-elle souvent au stress causé par un chien ?','How does a goat often react when stressed by a dog?',
 '["Ze stampt met de poten, blaat luid of vlucht weg","Ze gaat rustig liggen slapen","Ze wordt onmiddellijk vriendelijk met de hond","Ze reageert nooit op honden"]'::jsonb,
 '["Elle tape du pied, bêle fort ou s''enfuit","Elle se couche calmement pour dormir","Elle devient immédiatement amicale avec le chien","Elle ne réagit jamais aux chiens"]'::jsonb,
 '["It stamps its feet, bleats loudly or runs away","It calmly lies down to sleep","It immediately becomes friendly with the dog","It never reacts to dogs"]'::jsonb,
 0,'Stampen en luid blaten zijn waarschuwingssignalen die aangeven dat een geit zich bedreigd voelt.','Taper du pied et bêler fort sont des signaux d''avertissement indiquant que la chèvre se sent menacée.','Stamping and loud bleating are warning signals indicating a goat feels threatened.'),
(2,'tekst','Wat moet je doen als je merkt dat dieren gestrest raken door je hond?','Que faire si vous remarquez que les animaux sont stressés par votre chien ?','What should you do if you notice animals becoming stressed by your dog?',
 '["Direct afstand nemen en de hond wegleiden van het dier","Dichterbij gaan om te helpen kalmeren","De hond loslaten zodat hij zich kan aanpassen","Niets doen, dieren wennen vanzelf"]'::jsonb,
 '["Prendre immédiatement de la distance et éloigner le chien de l''animal","S''approcher pour aider à calmer","Détacher le chien pour qu''il s''adapte","Ne rien faire, les animaux s''habituent tout seuls"]'::jsonb,
 '["Immediately create distance and lead the dog away from the animal","Get closer to help calm things down","Release the dog so it can adjust","Do nothing, animals get used to it on their own"]'::jsonb,
 0,'Afstand nemen bij de eerste tekenen van stress voorkomt paniek en mogelijke verwondingen bij het dier.','Prendre ses distances dès les premiers signes de stress évite panique et blessures possibles chez l''animal.','Creating distance at the first signs of stress prevents panic and possible injury to the animal.'),
(2,'tekst','Waarom kan zelfs een vriendelijke hond stress veroorzaken bij prooidieren zoals konijnen of schapen?','Pourquoi même un chien amical peut-il stresser des proies comme les lapins ou moutons ?','Why can even a friendly dog cause stress in prey animals like rabbits or sheep?',
 '["Deze dieren herkennen honden instinctief als mogelijke roofdieren","Konijnen en schapen zien honden nooit als gevaar","Enkel agressieve honden veroorzaken stress","Dit gebeurt enkel bij grote honden"]'::jsonb,
 '["Ces animaux reconnaissent instinctivement les chiens comme des prédateurs potentiels","Lapins et moutons ne voient jamais les chiens comme un danger","Seuls les chiens agressifs causent du stress","Cela n''arrive qu''avec de grands chiens"]'::jsonb,
 '["These animals instinctively recognise dogs as potential predators","Rabbits and sheep never see dogs as a threat","Only aggressive dogs cause stress","This only happens with large dogs"]'::jsonb,
 0,'Prooidieren reageren op de vorm en het gedrag van een hond, ongeacht diens vriendelijke bedoelingen.','Les proies réagissent à la forme et au comportement du chien, indépendamment de ses intentions amicales.','Prey animals react to a dog''s shape and behaviour, regardless of its friendly intentions.'),
(3,'tekst','Waarom moet je hondenpoep altijd meteen opruimen op de boerderij?','Pourquoi faut-il toujours ramasser immédiatement les excréments de son chien à la ferme ?','Why should you always immediately clean up dog faeces at the farm?',
 '["Om verspreiding van ziektekiemen naar mens en dier te voorkomen","Omdat het verboden is om een hond mee te nemen","Hondenpoep is compleet onschadelijk","Enkel om esthetische redenen"]'::jsonb,
 '["Pour éviter la propagation de germes aux humains et aux animaux","Parce qu''il est interdit d''emmener un chien","Les excréments de chien sont totalement inoffensifs","Uniquement pour des raisons esthétiques"]'::jsonb,
 '["To prevent the spread of germs to humans and animals","Because bringing a dog is forbidden","Dog faeces are completely harmless","Only for aesthetic reasons"]'::jsonb,
 0,'Hondenpoep kan parasieten en bacteriën bevatten die schadelijk zijn voor mens en boerderijdier.','Les excréments de chien peuvent contenir parasites et bactéries nocifs pour l''homme et les animaux de ferme.','Dog faeces can contain parasites and bacteria harmful to humans and farm animals.'),
(3,'tekst','Wat is neospora en waarom is dit relevant bij hondenpoep op de boerderij?','Qu''est-ce que la néosporose et pourquoi est-ce pertinent avec les excréments de chien à la ferme ?','What is neospora and why is it relevant regarding dog faeces at the farm?',
 '["Een parasiet uit hondenpoep die abortus bij herkauwers zoals runderen kan veroorzaken","Een vitamine die goed is voor koeien","Een onschuldige bacterie zonder gevolgen","Een ziekte die enkel honden treft"]'::jsonb,
 '["Un parasite des excréments de chien pouvant causer l''avortement chez les ruminants comme les bovins","Une vitamine bénéfique pour les vaches","Une bactérie inoffensive sans conséquence","Une maladie qui touche uniquement les chiens"]'::jsonb,
 '["A parasite from dog faeces that can cause abortion in ruminants like cattle","A vitamin that is good for cows","A harmless bacterium with no consequences","A disease that only affects dogs"]'::jsonb,
 0,'Neospora caninum is een parasiet die via hondenpoep in veevoer of weiland terecht kan komen en drachtige koeien kan schaden.','Neospora caninum est un parasite pouvant contaminer fourrage ou pâturage via les excréments de chien et nuire aux vaches gestantes.','Neospora caninum is a parasite that can contaminate feed or pasture via dog faeces and harm pregnant cows.'),
(3,'tekst','Hoe voorkom je het risico van neospora-besmetting het best op de boerderij?','Comment prévenir au mieux le risque de contamination par la néosporose à la ferme ?','How do you best prevent the risk of neospora contamination at the farm?',
 '["Altijd hondenpoep direct opruimen en weg van veevoer en weides houden","Honden altijd los laten lopen bij het vee","Poep gewoon laten liggen, het lost vanzelf op","Enkel opruimen als er iemand toekijkt"]'::jsonb,
 '["Toujours ramasser immédiatement les excréments et les tenir loin du fourrage et des pâturages","Toujours laisser les chiens en liberté près du bétail","Laisser simplement les excréments, ils se dégraderont seuls","Ramasser uniquement si quelqu''un regarde"]'::jsonb,
 '["Always immediately clean up faeces and keep them away from feed and pastures","Always let dogs roam freely near livestock","Just leave the faeces, it will break down on its own","Only clean up when someone is watching"]'::jsonb,
 0,'Snel en consequent opruimen van hondenpoep, weg van veevoer, vermindert het besmettingsrisico aanzienlijk.','Ramasser rapidement et systématiquement les excréments, loin du fourrage, réduit considérablement le risque de contamination.','Quickly and consistently cleaning up dog faeces, away from feed, significantly reduces the risk of contamination.'),
(3,'tekst','Hoe gedraag je je best met je hond bij hekken waar dieren achter staan?','Comment se comporter avec son chien près des clôtures où se trouvent des animaux ?','How should you behave with your dog near fences where animals are kept?',
 '["Rustig voorbijlopen op een korte lijn zonder de hond te laten opspringen","De hond tegen het hek laten springen om te kijken","De hond loslaten om te snuffelen bij het hek","Je hond aanmoedigen om te blaffen naar de dieren"]'::jsonb,
 '["Passer calmement avec une laisse courte sans laisser le chien sauter","Laisser le chien sauter contre la clôture pour regarder","Détacher le chien pour qu''il renifle près de la clôture","Encourager le chien à aboyer sur les animaux"]'::jsonb,
 '["Walking past calmly on a short leash without letting the dog jump up","Letting the dog jump against the fence to look","Releasing the dog to sniff at the fence","Encouraging the dog to bark at the animals"]'::jsonb,
 0,'Springen of blaffen tegen een hek kan dieren erg laten schrikken en het hek beschadigen.','Sauter ou aboyer contre une clôture peut effrayer fortement les animaux et endommager la clôture.','Jumping or barking at a fence can severely frighten animals and damage the fence.'),
(3,'tekst','Wat is belangrijk om te doen als een kind zonder begeleiding je hond wil aaien bij de dierenweide?','Que faire si un enfant sans surveillance veut caresser votre chien près de l''enclos ?','What is important to do if an unsupervised child wants to pet your dog near the animal paddock?',
 '["Rustig vragen om een volwassene erbij te halen en het contact begeleiden","Het kind zomaar laten doen zonder toezicht","Het kind wegduwen zonder uitleg","Negeren en snel weglopen met de hond"]'::jsonb,
 '["Demander calmement qu''un adulte accompagne et superviser le contact","Laisser l''enfant faire sans aucune surveillance","Repousser l''enfant sans explication","Ignorer et s''éloigner rapidement avec le chien"]'::jsonb,
 '["Calmly ask for an adult to accompany and supervise the contact","Let the child do it unsupervised","Push the child away without explanation","Ignore it and quickly walk away with the dog"]'::jsonb,
 0,'Begeleid contact tussen kinderen en honden voorkomt ongelukken doordat een volwassene het gedrag van beide kan inschatten.','Un contact encadré entre enfants et chiens évite les accidents, un adulte pouvant évaluer le comportement des deux.','Supervised contact between children and dogs prevents accidents since an adult can assess both parties'' behaviour.')
) AS v(module,vraag_type,nl,fr,en,onl,ofr,oen,ci,wnl,wfr,wen);
