-- Regenworm
WITH a AS (
  INSERT INTO public.academies (diersoort_naam, diersoort_naam_fr, diersoort_naam_en, slug, badge_icon, vragen_per_test, slaag_grens, beschrijving, beschrijving_fr, beschrijving_en, categorie, prioriteit)
  VALUES ('Regenworm & compost','Ver de terre & compost','Earthworm & compost','regenworm','regenworm',15,12,'Leer hoe regenwormen de bodem verrijken, hoe je een wormenbak beheert, wat wel en niet in de compost mag en waarom gangen zorgen voor waterinfiltratie.','Découvrez comment les vers de terre enrichissent le sol, comment gérer un lombricomposteur, ce qui peut ou non aller au compost et pourquoi les galeries favorisent l''infiltration de l''eau.','Learn how earthworms enrich the soil, how to manage a worm bin, what can and cannot go in the compost, and why tunnels help water infiltration.','moestuin',50)
  RETURNING id
)
INSERT INTO public.academy_vragen (academy_id, module, vraag_type, vraag_tekst, vraag_tekst_fr, vraag_tekst_en, opties, opties_fr, opties_en, correcte_optie_index, wist_je_dat, wist_je_dat_fr, wist_je_dat_en)
SELECT a.id, v.module, v.vraag_type, v.nl, v.fr, v.en, v.onl, v.ofr, v.oen, v.ci, v.wnl, v.wfr, v.wen
FROM a, (VALUES
(1,'tekst','Wat is de belangrijkste rol van regenwormen in de bodem?','Quel est le rôle principal des vers de terre dans le sol ?','What is the main role of earthworms in the soil?',
 '["Ze verteren organisch materiaal en verrijken de bodem met voedingsstoffen","Ze eten enkel levende plantenwortels","Ze verspreiden onkruidzaden","Ze verdringen andere bodemdieren"]'::jsonb,
 '["Ils décomposent la matière organique et enrichissent le sol en nutriments","Ils ne mangent que des racines vivantes","Ils dispersent les graines de mauvaises herbes","Ils chassent les autres organismes du sol"]'::jsonb,
 '["They break down organic matter and enrich the soil with nutrients","They only eat living plant roots","They spread weed seeds","They displace other soil organisms"]'::jsonb,
 0,'Regenwormen kunnen tot wel hun eigen lichaamsgewicht aan organisch materiaal per dag verteren.','Les vers de terre peuvent digérer jusqu''à l''équivalent de leur propre poids en matière organique par jour.','Earthworms can digest up to their own body weight in organic matter per day.'),
(1,'tekst','Wat produceren regenwormen dat de bodemvruchtbaarheid verhoogt?','Que produisent les vers de terre qui augmente la fertilité du sol ?','What do earthworms produce that increases soil fertility?',
 '["Wormenpoep, ook wel castings genoemd","Zuurstofbellen","Suikerkristallen","Zaadpluis"]'::jsonb,
 '["Des excréments, appelés turricules","Des bulles d''oxygène","Des cristaux de sucre","Des aigrettes de graines"]'::jsonb,
 '["Worm castings, their excrement","Oxygen bubbles","Sugar crystals","Seed fluff"]'::jsonb,
 0,'Wormencastings zitten boordevol stikstof, fosfor en kalium en vormen een natuurlijke meststof.','Les turricules de vers regorgent d''azote, de phosphore et de potassium et forment un engrais naturel.','Worm castings are packed with nitrogen, phosphorus and potassium and form a natural fertiliser.'),
(1,'tekst','Wat mag je zeker in een wormenbak stoppen?','Que peut-on certainement mettre dans un lombricomposteur ?','What can you definitely put in a worm bin?',
 '["Groente- en fruitresten en koffiedik","Vlees en vis","Zure citrusvruchten in grote hoeveelheden","Plastic verpakkingen"]'::jsonb,
 '["Épluchures de légumes et fruits et marc de café","De la viande et du poisson","De grandes quantités d''agrumes acides","Des emballages en plastique"]'::jsonb,
 '["Vegetable and fruit scraps and coffee grounds","Meat and fish","Large amounts of acidic citrus fruit","Plastic packaging"]'::jsonb,
 0,'Koffiedik trekt regenwormen aan en levert waardevolle stikstof voor de wormenbak.','Le marc de café attire les vers de terre et apporte de l''azote précieux au lombricomposteur.','Coffee grounds attract earthworms and provide valuable nitrogen for the worm bin.'),
(1,'tekst','Waarom vermijd je vlees en zuivel in de compost?','Pourquoi éviter la viande et les produits laitiers dans le compost ?','Why avoid meat and dairy in the compost?',
 '["Ze trekken ongedierte aan en veroorzaken nare geurtjes","Ze zijn juist ideaal voor wormen","Ze bevatten geen voedingsstoffen","Ze versnellen het composteringsproces te snel"]'::jsonb,
 '["Ils attirent les nuisibles et provoquent de mauvaises odeurs","Ils sont en fait idéaux pour les vers","Ils ne contiennent aucun nutriment","Ils accélèrent trop le processus de compostage"]'::jsonb,
 '["They attract pests and cause bad odours","They are actually ideal for worms","They contain no nutrients","They speed up composting too much"]'::jsonb,
 0,'Vlees en zuivel rotten anders dan plantaardig afval en trekken ratten en vliegen aan.','La viande et les produits laitiers pourrissent différemment des déchets végétaux et attirent rats et mouches.','Meat and dairy rot differently from plant waste and attract rats and flies.'),
(1,'tekst','Wat is een goede verhouding voor een gezonde compost?','Quel est un bon équilibre pour un compost sain ?','What is a good ratio for healthy compost?',
 '["Een mix van bruin materiaal (droog) en groen materiaal (nat)","Enkel groen keukenafval","Enkel droge bladeren","Zoveel mogelijk water zonder vast materiaal"]'::jsonb,
 '["Un mélange de matière brune (sèche) et de matière verte (humide)","Uniquement des déchets de cuisine verts","Uniquement des feuilles sèches","Le plus d''eau possible sans matière solide"]'::jsonb,
 '["A mix of brown material (dry) and green material (wet)","Only green kitchen waste","Only dry leaves","As much water as possible without solid material"]'::jsonb,
 0,'Een goede balans tussen bruin (koolstofrijk) en groen (stikstofrijk) materiaal voorkomt geurhinder en versnelt afbraak.','Un bon équilibre entre matière brune (riche en carbone) et verte (riche en azote) évite les odeurs et accélère la décomposition.','A good balance between brown (carbon-rich) and green (nitrogen-rich) material prevents odours and speeds decomposition.'),
(2,'tekst','Hoe helpen de gangen van regenwormen bij waterinfiltratie?','Comment les galeries des vers de terre aident-elles l''infiltration de l''eau ?','How do earthworm tunnels help water infiltration?',
 '["Ze creëren kanalen waardoor regenwater dieper in de bodem kan dringen","Ze houden water juist tegen aan het oppervlak","Ze maken de bodem waterdicht","Ze hebben geen invloed op waterinfiltratie"]'::jsonb,
 '["Elles créent des canaux permettant à l''eau de pluie de pénétrer plus profondément dans le sol","Elles retiennent l''eau à la surface","Elles rendent le sol imperméable","Elles n''ont aucun effet sur l''infiltration de l''eau"]'::jsonb,
 '["They create channels allowing rainwater to penetrate deeper into the soil","They keep water at the surface","They make the soil waterproof","They have no effect on water infiltration"]'::jsonb,
 0,'Wormengangen kunnen tot wel 2 meter diep gaan en verbeteren de waterinfiltratie en beluchting van de bodem.','Les galeries de vers peuvent atteindre 2 mètres de profondeur et améliorent l''infiltration de l''eau et l''aération du sol.','Worm tunnels can reach up to 2 metres deep and improve water infiltration and soil aeration.'),
(2,'tekst','Wat gebeurt er met de bodemstructuur dankzij regenwormen?','Que se passe-t-il avec la structure du sol grâce aux vers de terre ?','What happens to soil structure thanks to earthworms?',
 '["De bodem wordt losser en beter belucht","De bodem wordt harder en compacter","De bodem verzuurt sterk","Er verandert niets aan de structuur"]'::jsonb,
 '["Le sol devient plus meuble et mieux aéré","Le sol devient plus dur et compact","Le sol s''acidifie fortement","Rien ne change dans la structure"]'::jsonb,
 '["The soil becomes looser and better aerated","The soil becomes harder and more compact","The soil becomes strongly acidic","Nothing changes in the structure"]'::jsonb,
 0,'Regenwormen mengen organisch materiaal door de bodem en verbeteren zo de kruimelstructuur.','Les vers de terre mélangent la matière organique dans le sol, améliorant ainsi sa structure grumeleuse.','Earthworms mix organic matter through the soil, improving its crumbly structure.'),
(2,'tekst','Wat is een teken van een gezonde, wormrijke tuinbodem?','Quel est un signe d''un sol de jardin sain et riche en vers ?','What is a sign of a healthy, worm-rich garden soil?',
 '["Kleine wormenhoopjes (castings) op het oppervlak","Een keiharde, dichtgeslagen bodem","Volledige afwezigheid van leven","Een grijze, kleiige laag zonder structuur"]'::jsonb,
 '["De petits tas d''excréments (turricules) en surface","Un sol très dur et compacté","Une absence totale de vie","Une couche grise et argileuse sans structure"]'::jsonb,
 '["Small casting mounds on the surface","A rock-hard, compacted soil","A complete absence of life","A grey, clayey layer with no structure"]'::jsonb,
 0,'Zichtbare castings op het oppervlak wijzen op een actieve, gezonde wormenpopulatie in de bodem.','Des turricules visibles en surface indiquent une population de vers active et saine dans le sol.','Visible castings on the surface indicate an active, healthy worm population in the soil.'),
(2,'tekst','Waarom is mulchen goed voor regenwormen?','Pourquoi le paillage est-il bon pour les vers de terre ?','Why is mulching good for earthworms?',
 '["Het houdt de bodem vochtig en levert voedsel voor de wormen","Het droogt de bodem sneller uit","Het verhindert wormen om aan het oppervlak te komen","Het heeft geen enkel effect"]'::jsonb,
 '["Il maintient le sol humide et fournit de la nourriture aux vers","Il assèche le sol plus rapidement","Il empêche les vers de remonter à la surface","Il n''a aucun effet"]'::jsonb,
 '["It keeps the soil moist and provides food for the worms","It dries out the soil faster","It stops worms from reaching the surface","It has no effect at all"]'::jsonb,
 0,'Een mulchlaag houdt vocht vast en biedt regenwormen een constante voedselbron van afbrekend materiaal.','Une couche de paillis retient l''humidité et offre aux vers de terre une source constante de matière en décomposition.','A mulch layer retains moisture and gives earthworms a constant food source of decaying material.'),
(2,'tekst','Waarom verschijnen regenwormen na een zware regenbui aan het oppervlak?','Pourquoi les vers de terre remontent-ils à la surface après une forte pluie ?','Why do earthworms come to the surface after heavy rain?',
 '["Verzadigde grond bevat te weinig zuurstof voor hen","Ze willen dan juist meer zonlicht opzoeken","Ze komen naar boven om te paren met vogels","Regen heeft geen invloed op hun gedrag"]'::jsonb,
 '["Le sol saturé contient trop peu d''oxygène pour eux","Ils cherchent alors plus de lumière du soleil","Ils remontent pour s''accoupler avec des oiseaux","La pluie n''a aucune influence sur leur comportement"]'::jsonb,
 '["Waterlogged soil contains too little oxygen for them","They seek more sunlight","They surface to mate with birds","Rain has no effect on their behaviour"]'::jsonb,
 0,'Bij verzadigde grond raakt de zuurstof op in de gangen, waardoor wormen naar het oppervlak vluchten.','Dans un sol saturé, l''oxygène des galeries s''épuise, ce qui pousse les vers à fuir vers la surface.','In waterlogged soil, oxygen in the tunnels runs out, causing worms to flee to the surface.'),
(3,'tekst','Hoe onderhoud je een wormenbak correct?','Comment entretenir correctement un lombricomposteur ?','How do you properly maintain a worm bin?',
 '["Regelmatig kleine hoeveelheden voedsel toevoegen en vochtigheid controleren","Eenmalig alle etensresten van een maand ineens toevoegen","Nooit water toevoegen","De bak in de volle zon plaatsen"]'::jsonb,
 '["Ajouter régulièrement de petites quantités de nourriture et vérifier l''humidité","Ajouter en une fois tous les déchets d''un mois","Ne jamais ajouter d''eau","Placer le bac en plein soleil"]'::jsonb,
 '["Regularly add small amounts of food and check moisture","Add a whole month of scraps at once","Never add water","Place the bin in full sun"]'::jsonb,
 0,'Te veel voedsel ineens kan gaan rotten voor de wormen het kunnen verwerken, wat geurhinder veroorzaakt.','Trop de nourriture d''un coup peut pourrir avant que les vers ne puissent la traiter, causant des odeurs.','Too much food at once can rot before the worms can process it, causing odours.'),
(3,'tekst','Welke wormensoort wordt meestal gebruikt in een wormenbak?','Quelle espèce de ver est généralement utilisée dans un lombricomposteur ?','Which worm species is usually used in a worm bin?',
 '["De compostworm (Eisenia fetida)","De gewone regenworm uit de tuin","De aardworm (Lumbricus terrestris) alleen","Elke wormensoort werkt even goed"]'::jsonb,
 '["Le ver de compost (Eisenia fetida)","Le ver de terre ordinaire du jardin","Le ver de terre commun (Lumbricus terrestris) uniquement","N''importe quelle espèce de ver fonctionne aussi bien"]'::jsonb,
 '["The compost worm (Eisenia fetida)","The ordinary garden earthworm","The common earthworm (Lumbricus terrestris) only","Any worm species works equally well"]'::jsonb,
 0,'Eisenia fetida, ook wel tijgerworm genoemd, verwerkt organisch afval veel sneller dan gewone regenwormen.','Eisenia fetida, aussi appelé ver tigré, décompose les déchets organiques bien plus vite que les vers de terre ordinaires.','Eisenia fetida, also called the tiger worm, breaks down organic waste much faster than ordinary earthworms.'),
(3,'tekst','Wat doe je best als je wormenbak te nat en te zuur ruikt?','Que faire si le lombricomposteur sent trop l''humidité et l''acidité ?','What should you do if your worm bin smells too wet and sour?',
 '["Meer droog, bruin materiaal zoals karton toevoegen","Meer keukenafval toevoegen","De bak volledig afsluiten van lucht","Extra water toevoegen"]'::jsonb,
 '["Ajouter plus de matière brune sèche comme du carton","Ajouter plus de déchets de cuisine","Fermer complètement le bac à l''air","Ajouter plus d''eau"]'::jsonb,
 '["Add more dry, brown material such as cardboard","Add more kitchen scraps","Seal the bin off completely from air","Add extra water"]'::jsonb,
 0,'Droog materiaal zoals gescheurd karton absorbeert overtollig vocht en herstelt de balans in de wormenbak.','Une matière sèche comme du carton déchiré absorbe l''excès d''humidité et rétablit l''équilibre du lombricomposteur.','Dry material like shredded cardboard absorbs excess moisture and restores balance in the worm bin.'),
(3,'tekst','Hoe oogst je de compost uit een wormenbak?','Comment récolter le compost d''un lombricomposteur ?','How do you harvest compost from a worm bin?',
 '["Aan de zijkant verse voeding toevoegen zodat wormen migreren en de rijpe compost apart kan","Alles ineens weggooien inclusief de wormen","De bak nooit legen","Enkel water uit de bak gebruiken"]'::jsonb,
 '["Ajouter de la nourriture fraîche sur le côté pour que les vers migrent et récolter le compost mûr séparément","Tout jeter d''un coup, y compris les vers","Ne jamais vider le bac","N''utiliser que l''eau du bac"]'::jsonb,
 '["Add fresh food to one side so worms migrate, allowing you to harvest the mature compost separately","Throw everything away at once, including the worms","Never empty the bin","Only use the liquid from the bin"]'::jsonb,
 0,'Door voeding aan één kant te concentreren, migreren de wormen daarheen zodat je de rijpe compost elders kan oogsten.','En concentrant la nourriture d''un côté, les vers y migrent, permettant de récolter le compost mûr ailleurs.','By concentrating food on one side, the worms migrate there, allowing you to harvest the mature compost elsewhere.'),
(3,'tekst','Wat is "wormenthee" en waarvoor gebruik je het?','Qu''est-ce que le "thé de vers" et à quoi sert-il ?','What is "worm tea" and what is it used for?',
 '["Het vloeibare afvalproduct van de wormenbak, gebruikt als vloeibare meststof","Een drank gemaakt van gedroogde wormen","Een middel om wormen te doden","Water dat wormen moeten drinken"]'::jsonb,
 '["Le liquide résiduel du lombricomposteur, utilisé comme engrais liquide","Une boisson faite de vers séchés","Un produit pour tuer les vers","De l''eau que les vers doivent boire"]'::jsonb,
 '["The liquid runoff from the worm bin, used as a liquid fertiliser","A drink made from dried worms","A product to kill worms","Water that worms need to drink"]'::jsonb,
 0,'Wormenthee is rijk aan voedingsstoffen en wordt verdund gebruikt om planten te bemesten.','Le thé de vers est riche en nutriments et est utilisé dilué pour fertiliser les plantes.','Worm tea is rich in nutrients and is used diluted to fertilise plants.')
) AS v(module,vraag_type,nl,fr,en,onl,ofr,oen,ci,wnl,wfr,wen);

-- Lieveheersbeestje
WITH a AS (
  INSERT INTO public.academies (diersoort_naam, diersoort_naam_fr, diersoort_naam_en, slug, badge_icon, vragen_per_test, slaag_grens, beschrijving, beschrijving_fr, beschrijving_en, categorie, prioriteit)
  VALUES ('Lieveheersbeestje','Coccinelle','Ladybird','lieveheersbeestje','lieveheersbeestje',15,12,'Ontdek hoe lieveheersbeestjes bladluizen bestrijden, hoe je biologisch tuiniert zonder gif, een insectenhotel bouwt en de larven en overwintering herkent.','Découvrez comment les coccinelles luttent contre les pucerons, comment jardiner bio sans pesticides, construire un hôtel à insectes et reconnaître les larves et l''hivernage.','Discover how ladybirds control aphids, how to garden organically without pesticides, build an insect hotel, and recognise larvae and overwintering.','moestuin',50)
  RETURNING id
)
INSERT INTO public.academy_vragen (academy_id, module, vraag_type, vraag_tekst, vraag_tekst_fr, vraag_tekst_en, opties, opties_fr, opties_en, correcte_optie_index, wist_je_dat, wist_je_dat_fr, wist_je_dat_en)
SELECT a.id, v.module, v.vraag_type, v.nl, v.fr, v.en, v.onl, v.ofr, v.oen, v.ci, v.wnl, v.wfr, v.wen
FROM a, (VALUES
(1,'tekst','Wat eten lieveheersbeestjes en hun larven het liefst?','Que mangent le plus les coccinelles et leurs larves ?','What do ladybirds and their larvae mostly eat?',
 '["Bladluizen","Rozenblaadjes","Sla en kool","Houtsnippers"]'::jsonb,
 '["Des pucerons","Des pétales de rose","De la salade et du chou","Des copeaux de bois"]'::jsonb,
 '["Aphids","Rose petals","Lettuce and cabbage","Wood chips"]'::jsonb,
 0,'Eén lieveheersbeestjeslarve kan tijdens haar ontwikkeling honderden bladluizen verorberen.','Une larve de coccinelle peut dévorer des centaines de pucerons durant son développement.','A single ladybird larva can devour hundreds of aphids during its development.'),
(1,'tekst','Waarom worden lieveheersbeestjes gezien als natuurlijke plaagbestrijders?','Pourquoi les coccinelles sont-elles considérées comme des auxiliaires naturels ?','Why are ladybirds seen as natural pest controllers?',
 '["Ze verminderen bladluispopulaties zonder chemische middelen","Ze bestuiven bloemen zoals bijen","Ze verjagen vogels uit de tuin","Ze verspreiden ziektes bij insecten"]'::jsonb,
 '["Elles réduisent les populations de pucerons sans produits chimiques","Elles pollinisent les fleurs comme les abeilles","Elles chassent les oiseaux du jardin","Elles propagent des maladies chez les insectes"]'::jsonb,
 '["They reduce aphid populations without chemicals","They pollinate flowers like bees","They scare birds away from the garden","They spread diseases among insects"]'::jsonb,
 0,'Door lieveheersbeestjes aan te trekken kan je bladluisplagen bestrijden zonder pesticiden te gebruiken.','En attirant les coccinelles, on peut lutter contre les invasions de pucerons sans utiliser de pesticides.','By attracting ladybirds you can control aphid outbreaks without using pesticides.'),
(1,'tekst','Welke planten trekken lieveheersbeestjes aan in de moestuin?','Quelles plantes attirent les coccinelles dans le potager ?','Which plants attract ladybirds in the vegetable garden?',
 '["Dille, venkel en goudsbloem","Enkel naaldbomen","Uitsluitend grasplanten","Enkel varens"]'::jsonb,
 '["L''aneth, le fenouil et le souci","Uniquement les conifères","Exclusivement des graminées","Uniquement des fougères"]'::jsonb,
 '["Dill, fennel and marigold","Only conifers","Exclusively grasses","Only ferns"]'::jsonb,
 0,'Bloeiende kruiden zoals dille en venkel bieden lieveheersbeestjes nectar en stuifmeel als aanvullend voedsel.','Les herbes en fleurs comme l''aneth et le fenouil offrent aux coccinelles nectar et pollen en complément.','Flowering herbs like dill and fennel provide ladybirds with nectar and pollen as supplementary food.'),
(1,'tekst','Hoeveel bladluizen kan een volwassen lieveheersbeestje ongeveer per dag eten?','Combien de pucerons une coccinelle adulte peut-elle manger environ par jour ?','How many aphids can an adult ladybird eat roughly per day?',
 '["Tot ongeveer 50 bladluizen","Slechts 1 bladluis","Meer dan 5000 bladluizen","Ze eten geen bladluizen als volwassene"]'::jsonb,
 '["Jusqu''à environ 50 pucerons","Seulement 1 puceron","Plus de 5000 pucerons","Elles ne mangent pas de pucerons à l''âge adulte"]'::jsonb,
 '["Up to about 50 aphids","Only 1 aphid","More than 5000 aphids","They do not eat aphids as adults"]'::jsonb,
 0,'Een volwassen lieveheersbeestje kan tot 50 bladluizen per dag eten, wat het een uitstekende bondgenoot maakt.','Une coccinelle adulte peut manger jusqu''à 50 pucerons par jour, ce qui en fait un allié précieux.','An adult ladybird can eat up to 50 aphids a day, making it an excellent ally.'),
(1,'tekst','Waarom is het gebruik van pesticiden schadelijk voor lieveheersbeestjes?','Pourquoi l''utilisation de pesticides est-elle nuisible aux coccinelles ?','Why is pesticide use harmful to ladybirds?',
 '["Pesticiden doden ook nuttige insecten zoals lieveheersbeestjes","Pesticiden maken lieveheersbeestjes juist sterker","Lieveheersbeestjes zijn immuun voor alle pesticiden","Pesticiden trekken meer lieveheersbeestjes aan"]'::jsonb,
 '["Les pesticides tuent aussi les insectes utiles comme les coccinelles","Les pesticides rendent les coccinelles plus fortes","Les coccinelles sont immunisées contre tous les pesticides","Les pesticides attirent davantage de coccinelles"]'::jsonb,
 '["Pesticides also kill beneficial insects like ladybirds","Pesticides actually make ladybirds stronger","Ladybirds are immune to all pesticides","Pesticides attract more ladybirds"]'::jsonb,
 0,'Breedwerkende pesticiden maken geen onderscheid tussen plaaginsecten en nuttige insecten zoals lieveheersbeestjes.','Les pesticides à large spectre ne distinguent pas les nuisibles des insectes utiles comme les coccinelles.','Broad-spectrum pesticides do not distinguish between pest insects and beneficial insects like ladybirds.'),
(2,'tekst','Hoe herken je de larve van een lieveheersbeestje?','Comment reconnaître la larve d''une coccinelle ?','How do you recognise a ladybird larva?',
 '["Langwerpig, zwart met oranje vlekken en kleine pootjes","Rond en rood met zwarte stippen","Wit en pluizig zonder pootjes","Groen met vleugels"]'::jsonb,
 '["Allongée, noire avec des taches orange et de petites pattes","Ronde et rouge avec des points noirs","Blanche et duveteuse sans pattes","Verte avec des ailes"]'::jsonb,
 '["Elongated, black with orange spots and small legs","Round and red with black spots","White and fluffy without legs","Green with wings"]'::jsonb,
 0,'Larven van lieveheersbeestjes lijken op kleine krokodilletjes en worden vaak per ongeluk als plaag verward.','Les larves de coccinelles ressemblent à de petits crocodiles et sont souvent confondues avec des nuisibles.','Ladybird larvae resemble tiny crocodiles and are often mistakenly confused with pests.'),
(2,'tekst','Waarom moet je larven van lieveheersbeestjes niet verwijderen uit de tuin?','Pourquoi ne faut-il pas retirer les larves de coccinelles du jardin ?','Why should you not remove ladybird larvae from the garden?',
 '["Ze eten net zoveel of meer bladluizen dan de volwassen kevers","Ze zijn giftig voor planten","Ze veroorzaken schade aan groenten","Ze trekken ongewenste vogels aan"]'::jsonb,
 '["Elles mangent autant, voire plus, de pucerons que les coccinelles adultes","Elles sont toxiques pour les plantes","Elles endommagent les légumes","Elles attirent des oiseaux indésirables"]'::jsonb,
 '["They eat as much or more aphids than the adult beetles","They are toxic to plants","They damage vegetables","They attract unwanted birds"]'::jsonb,
 0,'De larvefase is vaak de meest vraatzuchtige periode in het leven van een lieveheersbeestje.','Le stade larvaire est souvent la période la plus vorace de la vie d''une coccinelle.','The larval stage is often the most voracious period in a ladybird''s life.'),
(2,'tekst','Wat is een goede manier om zonder gif bladluizen te bestrijden naast lieveheersbeestjes inzetten?','Quelle est une bonne façon de lutter contre les pucerons sans pesticide, en plus des coccinelles ?','What is a good way to control aphids without poison, besides using ladybirds?',
 '["Een krachtige waterstraal gebruiken om bladluizen weg te spoelen","Chemische insecticiden op alle planten spuiten","Alle bloeiende planten verwijderen","De volledige plant verbranden"]'::jsonb,
 '["Utiliser un jet d''eau puissant pour rincer les pucerons","Pulvériser des insecticides chimiques sur toutes les plantes","Retirer toutes les plantes en fleurs","Brûler la plante entière"]'::jsonb,
 '["Using a strong jet of water to wash aphids away","Spraying chemical insecticides on all plants","Removing all flowering plants","Burning the entire plant"]'::jsonb,
 0,'Een sterke waterstraal verwijdert bladluizen mechanisch zonder nuttige insecten zoals lieveheersbeestjes te schaden.','Un jet d''eau puissant élimine mécaniquement les pucerons sans nuire aux insectes utiles comme les coccinelles.','A strong water jet mechanically removes aphids without harming beneficial insects like ladybirds.'),
(2,'tekst','Wat is companion planting in relatie tot bladluisbestrijding?','Qu''est-ce que le compagnonnage végétal en lien avec la lutte contre les pucerons ?','What is companion planting in relation to aphid control?',
 '["Planten combineren die nuttige insecten aantrekken of plagen afweren","Enkel één plantensoort per moestuin telen","Planten willekeurig door elkaar zaaien zonder doel","Alleen bloemen planten en geen groenten"]'::jsonb,
 '["Combiner des plantes qui attirent des insectes utiles ou repoussent les nuisibles","Cultiver une seule espèce de plante par potager","Semer les plantes au hasard sans but précis","Ne planter que des fleurs et aucun légume"]'::jsonb,
 '["Combining plants that attract beneficial insects or repel pests","Growing only one plant species per vegetable garden","Sowing plants randomly with no purpose","Only planting flowers and no vegetables"]'::jsonb,
 0,'Companion planting met bijvoorbeeld goudsbloemen kan lieveheersbeestjes aantrekken en plagen natuurlijk beperken.','Le compagnonnage, par exemple avec des soucis, peut attirer les coccinelles et limiter naturellement les nuisibles.','Companion planting, for example with marigolds, can attract ladybirds and naturally limit pests.'),
(2,'tekst','Waarom is biologisch tuinieren zonder gif belangrijk voor het ecosysteem van de moestuin?','Pourquoi le jardinage bio sans pesticide est-il important pour l''écosystème du potager ?','Why is pesticide-free organic gardening important for the vegetable garden ecosystem?',
 '["Het behoudt een gezond evenwicht tussen plagen en hun natuurlijke vijanden","Het zorgt voor snellere groei van onkruid","Het heeft geen effect op insectenpopulaties","Het is enkel belangrijk voor de smaak van groenten"]'::jsonb,
 '["Cela préserve un équilibre sain entre nuisibles et leurs ennemis naturels","Cela accélère la croissance des mauvaises herbes","Cela n''a aucun effet sur les populations d''insectes","C''est important uniquement pour le goût des légumes"]'::jsonb,
 '["It maintains a healthy balance between pests and their natural enemies","It causes weeds to grow faster","It has no effect on insect populations","It is only important for the taste of vegetables"]'::jsonb,
 0,'Zonder gif kunnen natuurlijke vijanden zoals lieveheersbeestjes zich vestigen en plagen op lange termijn beheersen.','Sans pesticides, les ennemis naturels comme les coccinelles peuvent s''installer et réguler les nuisibles à long terme.','Without poison, natural enemies like ladybirds can establish themselves and control pests in the long term.'),
(3,'tekst','Wat is een insectenhotel en waarvoor dient het?','Qu''est-ce qu''un hôtel à insectes et à quoi sert-il ?','What is an insect hotel and what is it for?',
 '["Een constructie met holtes die schuilplaats biedt aan nuttige insecten zoals lieveheersbeestjes","Een val om plaaginsecten te doden","Een broeikas voor groenten","Een voederbakje voor vogels"]'::jsonb,
 '["Une structure avec des cavités offrant un abri aux insectes utiles comme les coccinelles","Un piège pour tuer les insectes nuisibles","Une serre pour légumes","Une mangeoire pour oiseaux"]'::jsonb,
 '["A structure with cavities offering shelter to beneficial insects like ladybirds","A trap to kill pest insects","A greenhouse for vegetables","A bird feeder"]'::jsonb,
 0,'Een insectenhotel met holle stengels en dennenappels biedt lieveheersbeestjes een veilige overwinteringsplek.','Un hôtel à insectes avec tiges creuses et pommes de pin offre aux coccinelles un abri sûr pour hiverner.','An insect hotel with hollow stems and pine cones offers ladybirds a safe place to overwinter.'),
(3,'tekst','Waar overwinteren lieveheersbeestjes doorgaans?','Où les coccinelles hivernent-elles généralement ?','Where do ladybirds typically overwinter?',
 '["In beschutte plekken zoals bladhopen, schors of holtes","Ondergedompeld in vijverwater","Op het open, kale gazon","In de lucht tijdens hun vlucht"]'::jsonb,
 '["Dans des endroits abrités comme des tas de feuilles, l''écorce ou des cavités","Immergées dans l''eau d''un bassin","Sur la pelouse ouverte et nue","En vol dans les airs"]'::jsonb,
 '["In sheltered spots such as leaf piles, bark or crevices","Submerged in pond water","On open, bare lawn","In the air during flight"]'::jsonb,
 0,'Lieveheersbeestjes groeperen zich vaak met honderden soortgenoten om samen te overwinteren en warmte te delen.','Les coccinelles se regroupent souvent par centaines pour hiverner ensemble et partager la chaleur.','Ladybirds often gather in groups of hundreds to overwinter together and share warmth.'),
(3,'tekst','Wat kan je in de tuin laten liggen om overwinterende lieveheersbeestjes te beschermen?','Que peut-on laisser dans le jardin pour protéger les coccinelles hivernantes ?','What can you leave in the garden to protect overwintering ladybirds?',
 '["Dode plantenstengels en bladafval tot in het voorjaar","Alle plantenresten meteen verwijderen in de herfst","Enkel vers gemaaid gras","Plastic folie over de border"]'::jsonb,
 '["Des tiges mortes et des feuilles mortes jusqu''au printemps","Retirer immédiatement tous les résidus de plantes en automne","Uniquement de l''herbe fraîchement tondue","Une bâche en plastique sur la bordure"]'::jsonb,
 '["Dead plant stems and leaf litter until spring","Removing all plant debris immediately in autumn","Only freshly mown grass","Plastic sheeting over the border"]'::jsonb,
 0,'Door de tuin pas in het voorjaar op te ruimen, geef je overwinterende lieveheersbeestjes de kans om veilig te ontwaken.','En ne rangeant le jardin qu''au printemps, on laisse aux coccinelles hivernantes le temps de se réveiller en sécurité.','By only tidying the garden in spring, you give overwintering ladybirds a chance to safely wake up.'),
(3,'tekst','Hoeveel eitjes kan een vrouwelijk lieveheersbeestje ongeveer leggen in haar leven?','Combien d''œufs une coccinelle femelle peut-elle pondre environ dans sa vie ?','How many eggs can a female ladybird lay roughly in her lifetime?',
 '["Tot ongeveer 1000 eitjes","Slechts 2 tot 3 eitjes","Meer dan 1 miljoen eitjes","Lieveheersbeestjes leggen geen eitjes"]'::jsonb,
 '["Jusqu''à environ 1000 œufs","Seulement 2 à 3 œufs","Plus d''1 million d''œufs","Les coccinelles ne pondent pas d''œufs"]'::jsonb,
 '["Up to about 1000 eggs","Only 2 to 3 eggs","More than 1 million eggs","Ladybirds do not lay eggs"]'::jsonb,
 0,'Vrouwtjes leggen hun eitjes vaak dicht bij bladluiskolonies zodat de larven meteen voedsel hebben.','Les femelles pondent souvent leurs œufs près des colonies de pucerons pour que les larves aient immédiatement de la nourriture.','Females often lay their eggs close to aphid colonies so the larvae have food right away.'),
(3,'tekst','Wat gebeurt er als een lieveheersbeestje zich bedreigd voelt?','Que se passe-t-il quand une coccinelle se sent menacée ?','What happens when a ladybird feels threatened?',
 '["Het scheidt een geel, bitter vocht af als afweer","Het spuwt vuur","Het verandert onmiddellijk van kleur naar groen","Het graaft zich onder de grond"]'::jsonb,
 '["Elle sécrète un liquide jaune et amer pour se défendre","Elle crache du feu","Elle change immédiatement de couleur pour devenir verte","Elle s''enterre sous le sol"]'::jsonb,
 '["It secretes a yellow, bitter fluid as a defence","It spits fire","It immediately changes colour to green","It burrows underground"]'::jsonb,
 0,'Dit gele vocht heet reflexbloeding en heeft een bittere smaak die roofdieren afschrikt.','Ce liquide jaune s''appelle un saignement réflexe et a un goût amer qui repousse les prédateurs.','This yellow fluid is called reflex bleeding and has a bitter taste that deters predators.')
) AS v(module,vraag_type,nl,fr,en,onl,ofr,oen,ci,wnl,wfr,wen);
