UPDATE public.academies SET diersoort_naam_fr='Lapin', diersoort_naam_en='Rabbit', beschrijving_fr='Tout ce qu''il faut savoir avant d''adopter un lapin.', beschrijving_en='Everything you need to know before adopting a rabbit.' WHERE slug='konijn';
UPDATE public.academies SET diersoort_naam_fr='Poule', diersoort_naam_en='Chicken', beschrijving_fr='Devenez expert des poules et de leur environnement de vie.', beschrijving_en='Become an expert on chickens and their living environment.' WHERE slug='kip';
UPDATE public.academies SET diersoort_naam_fr='Chèvre', diersoort_naam_en='Goat', beschrijving_fr='Les bases des soins aux chèvres à la ferme urbaine.', beschrijving_en='The basics of goat care at the city farm.' WHERE slug='geit';

UPDATE public.academy_vragen SET vraag_tekst_fr='Les chèvres sont par nature...', vraag_tekst_en='Goats are by nature...', opties_fr='["Des animaux solitaires","Des animaux de troupeau","Des animaux nocturnes","Des prédateurs"]'::jsonb, opties_en='["Solitary animals","Herd animals","Nocturnal animals","Predators"]'::jsonb WHERE id='0ad1bf52-b428-4392-9f0c-8f73226fbb13';
UPDATE public.academy_vragen SET vraag_tekst_fr='Quelle plante est toxique pour les chèvres ?', vraag_tekst_en='Which plant is toxic to goats?', opties_fr='["Ronce","If","Trèfle","Saule"]'::jsonb, opties_en='["Bramble","Yew","Clover","Willow"]'::jsonb WHERE id='5f566ed8-8df4-4a53-97ed-dd2e444bf743';
UPDATE public.academy_vragen SET vraag_tekst_fr='À quelle fréquence faut-il parer les onglons des chèvres ?', vraag_tekst_en='How often should goat hooves be trimmed?', opties_fr='["Jamais","Chaque semaine","Toutes les 6 à 8 semaines","Une fois par an"]'::jsonb, opties_en='["Never","Every week","Every 6 to 8 weeks","Once a year"]'::jsonb WHERE id='18c5a4b9-161a-466d-a9dd-f64778b6e80b';
UPDATE public.academy_vragen SET vraag_tekst_fr='Qu''est-ce qui est essentiel dans l''abri d''une chèvre ?', vraag_tekst_en='What is essential in a goat''s shelter?', opties_fr='["Une étable entièrement fermée","Un couchage sec et un abri","Un aquarium","Un bac à litière"]'::jsonb, opties_en='["A fully closed barn","A dry resting place and shelter","An aquarium","A litter box"]'::jsonb WHERE id='8df74551-f14c-42df-98cb-7ab3f45e53de';
UPDATE public.academy_vragen SET vraag_tekst_fr='Combien d''estomacs a une chèvre ?', vraag_tekst_en='How many stomachs does a goat have?', opties_fr='["1","2","4","6"]'::jsonb, opties_en='["1","2","4","6"]'::jsonb WHERE id='20457ce4-ef16-49b4-9f19-8b690b627abb';
UPDATE public.academy_vragen SET vraag_tekst_fr='Que mangent principalement les chèvres ?', vraag_tekst_en='What do goats mainly eat?', opties_fr='["De la viande","Du fourrage comme le foin et les feuilles","Uniquement des céréales","Des fruits"]'::jsonb, opties_en='["Meat","Roughage such as hay and leaves","Only grains","Fruit"]'::jsonb WHERE id='5226b5ae-f8e8-48b6-a1bf-4f154d8b1cc9';

UPDATE public.academy_vragen SET vraag_tekst_fr='Pourquoi les poules ont-elles besoin de grit ?', vraag_tekst_en='Why do chickens need grit?', opties_fr='["Pour le goût","Pour broyer la nourriture dans le gésier","Comme jouet","Comme litière"]'::jsonb, opties_en='["For the taste","To grind food in the gizzard","As a toy","As bedding"]'::jsonb WHERE id='e41c60d5-86eb-44d0-be9f-27daf1bd9453';
UPDATE public.academy_vragen SET vraag_tekst_fr='Combien de poules faut-il garder ensemble au minimum ?', vraag_tekst_en='What is the minimum number of chickens to keep together?', opties_fr='["Une","Deux ou plus","Dix","Vingt"]'::jsonb, opties_en='["One","Two or more","Ten","Twenty"]'::jsonb WHERE id='a0cfe73c-9cd6-4225-832b-5cb2b7f04f35';
UPDATE public.academy_vragen SET vraag_tekst_fr='Que ne peuvent PAS manger les poules ?', vraag_tekst_en='What must chickens NOT eat?', opties_fr='["Des céréales","Des restes de légumes","Des épluchures de pommes de terre crues","Des vers"]'::jsonb, opties_en='["Grain","Vegetable scraps","Raw potato peels","Worms"]'::jsonb WHERE id='8431f0cf-2e9e-44cc-9211-c69832769dc0';
UPDATE public.academy_vragen SET vraag_tekst_fr='Qu''est-ce qu''un bain de poussière pour les poules ?', vraag_tekst_en='What is a dust bath for chickens?', opties_fr='["Une décoration","Un moyen de repousser les parasites","De la boisson","Un jouet"]'::jsonb, opties_en='["A decoration","A way to keep parasites away","Drinking water","A toy"]'::jsonb WHERE id='e9ff2e4e-d7e4-4b17-acf2-e08a3e78fb22';
UPDATE public.academy_vragen SET vraag_tekst_fr='Combien d''œufs pond environ une poule pondeuse en bonne santé par an ?', vraag_tekst_en='About how many eggs does a healthy laying hen produce per year?', opties_fr='["10","50","200 à 300","1000"]'::jsonb, opties_en='["10","50","200 to 300","1000"]'::jsonb WHERE id='d371ce15-15fd-419c-b819-2c49aa4f99f3';
UPDATE public.academy_vragen SET vraag_tekst_fr='Quel élément est essentiel dans le poulailler ?', vraag_tekst_en='What is an essential part of the coop?', opties_fr='["Une télévision","Un perchoir","Un escalier","Une piscine"]'::jsonb, opties_en='["A TV","A perch","A staircase","A swimming pool"]'::jsonb WHERE id='afe5fbdb-a811-4528-b5ce-dacdc92cb251';

UPDATE public.academy_vragen SET vraag_tekst_fr='Combien d''heures par jour un lapin doit-il au minimum pouvoir bouger en dehors de son enclos ?', vraag_tekst_en='How many hours a day should a rabbit at least be able to move outside its hutch?', opties_fr='["Moins d''1 heure","1 à 2 heures","Au moins 4 heures","Les lapins n''ont pas besoin de bouger"]'::jsonb, opties_en='["Less than 1 hour","1 to 2 hours","At least 4 hours","Rabbits do not need exercise"]'::jsonb WHERE id='097f76f2-f921-4fdc-b207-6080c4eee9b3';
UPDATE public.academy_vragen SET vraag_tekst_fr='Quel légume est toxique pour les lapins ?', vraag_tekst_en='Which vegetable is toxic to rabbits?', opties_fr='["La carotte","Le persil","L''avocat","La chicorée frisée"]'::jsonb, opties_en='["Carrot","Parsley","Avocado","Endive"]'::jsonb WHERE id='eabad219-fbe6-4a43-9655-f10d949e77a0';
UPDATE public.academy_vragen SET vraag_tekst_fr='Pourquoi les lapins doivent-ils ronger régulièrement ?', vraag_tekst_en='Why do rabbits need to gnaw regularly?', opties_fr='["Pour le goût","Leurs dents poussent toute leur vie","Ils s''ennuient","C''est un jeu"]'::jsonb, opties_en='["For the taste","Their teeth grow throughout life","They are bored","It is a game"]'::jsonb WHERE id='211529e6-bc55-4264-95ca-adc2b2f49e33';
UPDATE public.academy_vragen SET vraag_tekst_fr='Quel âge peut atteindre un lapin bien soigné ?', vraag_tekst_en='How old can a well-cared-for rabbit get?', opties_fr='["2 ans","5 ans","8 à 12 ans","20 ans"]'::jsonb, opties_en='["2 years","5 years","8 to 12 years","20 years"]'::jsonb WHERE id='9983467b-db0b-4a2e-8f64-23a992a1e468';
UPDATE public.academy_vragen SET vraag_tekst_fr='Les lapins vivent le mieux...', vraag_tekst_en='Rabbits live best...', opties_fr='["Seuls","Avec au moins un autre lapin","Avec un cochon d''Inde","Avec un chat"]'::jsonb, opties_en='["Alone","With at least one other rabbit","With a guinea pig","With a cat"]'::jsonb WHERE id='b41d6789-17d9-4d87-9cc6-44941383ef64';
UPDATE public.academy_vragen SET vraag_tekst_fr='Quel est le principal composant d''une alimentation saine pour lapin ?', vraag_tekst_en='What is the main component of a healthy rabbit diet?', opties_fr='["Des granulés","Du foin","Du pain","Uniquement des légumes"]'::jsonb, opties_en='["Pellets","Hay","Bread","Vegetables only"]'::jsonb WHERE id='7689afe1-d755-4d57-a6e6-960d137758c7';